### PR TITLE
gr-digital: The usage of 'and', 'or' and 'not' logical statements breaks compilation under MSVC

### PR DESCRIPTION
**Pull request by ptrkrysik**
i.e. with Geof Nieboer's scripts.

Replacing them with '&&', '||' and '!' respectively.

### CODE REVIEW

**Comment by noc0lour** [comment]
Testing failures are due to other bugs not related to this change.

**Comment by ptrkrysik** [comment]
Not supporting them is MSCV's 'feature'. Even more weird, as someone
pointed on the #gnuradio IRC channel, is that after disabling MS
"language extensions"
(https://msdn.microsoft.com/en-us/library/0k0w269d.aspx) MSVC compiles
these constructs just fine. I don't know if it compiles whole GNU Radio
correctly with this option though because I didn't try it.

**Comment by mbr0wn** [comment]
In any case this change is harmless and I see no harm merging.

**Comment by marcusmueller** [comment]
We're merging this, changing the commit msg on the way to be action-describing.

**Comment by marcusmueller** [comment]
in there as a212beb816781416d24d1c2b7ea31265ad702f33

**Pull request closed without merging**
