### PR TITLE
Remove redundant DPSK blocks (Feature 625)

### PR DESCRIPTION
**Pull request by sbmueller**
Since the PSK blocks are able to (de)mod differential signals, the DPSK blocks are redundant. I removed them. Also see https://gnuradio.org/redmine/issues/625

### CODE REVIEW

**Comment by jmcorgan** [comment]
Since this is an API change, it would only be considered for merging into the next branch as part of the 3.8.x release series.

Also, @trondeau is currently working in a related area to clean up some of the cruft/redundancy in gr-digital.

**Comment by trondeau** [comment]
@sbmueller thanks for taking the initiative here! As @jmcorgan pointed out, this changes currently available code/API so it can't be done until the next version. In fact, there's quite a lot of cleanup to be done with the gr-digital space and set of available blocks. This is definitely one of them, but I think we should probably remove both the PSK and DPSK versions and focus on using the constellation object concept.

**Comment by sbmueller** [comment]
Alright, thanks for the explanation. Feel free to close this pull request then.

**Comment by jmcorgan** [comment]
Won't close it yet.  Would you like to help me and @trondeau plan out the changes and work on this together?

**Comment by sbmueller** [comment]
Sure, maybe you can contact me under gsenpo@gmail.com and give me some information about the current state and outstanding tasks?

**Comment by n-west** [comment]
Piling on to the list:

* https://github.com/gnuradio/gnuradio/blob/master/gr-digital/python/digital/gfsk.py
* https://github.com/gnuradio/gnuradio/blob/master/gr-digital/python/digital/gmsk.py
* https://github.com/gnuradio/gnuradio/blob/master/gr-analog/lib/cpfsk_bc_impl.cc

**Comment by jmcorgan** [comment]
@nwest You're hired.

**Comment by jmcorgan** [comment]
So this sort of turned into a mix of things...I'd rather see a written plan for a before and after look at what blocks would be in gr-digital/analog for the 3.7/3.8 transition, then we can check off the boxes on that plan.  @nwest, would you like to work this out?

**Comment by nwest** [comment]
I think you meant to tag @n-west.

**Comment by jmcorgan** [comment]
Heh, thanks @nwest, I bet that happens a lot. @n-west can you do the above?

**Comment by n-west** [comment]
Hmmm, I can start with the duplications I know of, but it'll get hairy since I consider the million bit/acces code correlators to be part of this.

**Comment by jmcorgan** [comment]
We've started an internal review of the 3.8 cleanup for gr-digital, it is a fairly significant amount of work. @n-west is currently shepherding this along; @sbmueller if you'd like to participate, please contact him.

I'm going to close this here.

**Pull request closed without merging**
