### PR TITLE
doxygen: Resolve broken references with Wiki links.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Comment by ValZapod** [comment]
Can you also fix (https://github.com/gnuradio/gnuradio/issues/3071 and https://ci.gnuradio.org/buildbot/#/builders/59/builds/454)
 ```
 /cache/workdir/Centos_7_6_0/build_Centos_7_6/src/gr-utils/python/modtool/templates/gr-newmod/docs/doxygen/other/group_defs.dox:2: warning: group block: ignoring title "GNU Radio HOWTO C++ Signal Processing Blocks" that does not match old title "GNU Radio C++ Signal Processing Blocks"
/cache/workdir/Centos_7_6_0/build_Centos_7_6/src/gr-utils/python/modtool/templates/gr-newmod/docs/doxygen/other/main_page.dox:1: warning: found more than one \mainpage comment block! Skipping this block.
```

In particular please also revert my commit https://github.com/gnuradio/gnuradio/commit/2bfec163015d0b695f5ebb970ad30ead0ad4ca08 it did not work. 💩

**Comment by drmpeg** [comment]
@ValZapod I wish I knew how to fix those remaining warnings. The ctrlport and uhd warnings still produce good links in the HTML documentation, so I have no idea what's going on there. So this PR only includes what I was able to figure out with my essentially zero knowledge of Doxygen.

**Comment by ValZapod** [comment]
@drmpeg Look here https://github.com/gnuradio/gnuradio/commit/73b074f121b0ab2ac38336916a60891c4d88d2cb

**Comment by drmpeg** [comment]
@ValZapod The ctrlport and uhd warnings are inherited from 3.7 and have been around for a long time (years).

**Comment by ValZapod** [comment]
I reopened it to restart CI. /sigh

**Pull request merged**
