### PR TITLE
analog: new test for agc3

### PR DESCRIPTION
**Pull request by cmrincon**
I added a new test for agc3 block.

## Related Issue
[Issue #6356](https://github.com/gnuradio/gnuradio/issues/6356)

## Which blocks/areas does this affect?
AGC tests.

- [ x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ x] I have squashed my commits to have one significant change per commit. 
- [ x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

PD -> Is master the correct branch to pr?

### CODE REVIEW

**Comment by willcode** [comment]
@cmrincon There is a formatter in the tree: `tools/autoformat_python.sh`. You can also use `tools/check_pep8.sh` to see what the formatting complaints are.

**Comment by willcode** [comment]
@cmrincon Maybe you reformatted a couple too many files! We might do another grand reformat some day, but not here.

**Comment by willcode** [comment]
Oh - PRs should be against `main`, not `master`. Maybe that's what is causing all the strange things.

**Comment by willcode** [comment]
I changed the base to `main`, and that picked up one other stray file. You're going to have to close this one and put in another one against `main`. I did try re-running the Python Formatting job after changing the base. Did not help. We'll see what a new PR does for you.

**Comment by cmrincon** [comment]
@willcode I'm closing this pr and changed some code of the test to understand easily whats going on.

**Pull request closed without merging**
