### PR TITLE
gnuradio: Regenerating bindings in place and a fresh build in one step fail

### PR DESCRIPTION
**Pull request by dl1ksv**
---

# Pull Request Details

Trying to regenerate the bindings for agc2_cc.h together with a fresh build
fails with
    from gnuradio.bindtool import BindingGenerator
ModuleNotFoundError: No module named 'gnuradio'

## Description

This is an example to discuss a build problem.
Set 
BINDTOOL_GEN_AUTOMATIC(1)
BINDTOOL_USE_PYGCCXML(1)
and delete one digit of the hash
in agc2_cc_python.cc

and do a fresh build of gnuradio.

The CMake run shows:

-- Configuring gr-analog support...
--   Dependency ENABLE_GNURADIO_RUNTIME = ON
--   Dependency ENABLE_GR_BLOCKS = ON
--   Dependency ENABLE_GR_FFT = ON
--   Dependency ENABLE_GR_FILTER = ON
--   Enabling gr-analog support.
--   Override with -DENABLE_GR_ANALOG=ON/OFF
-- Regenerating Bindings in-place for agc2_cc.h

But make leads to 

[ 54%] Built target pygen_gr_analog_python_analog_8d44d
[ 54%] /home/schroer/gnuradiocomponents/gnuradio-volker/gr-analog/python/analog/bindings/../../../include/gnuradio/analog/agc2_cc.h
Traceback (most recent call last):
  File "/home/schroer/gnuradiocomponents/gnuradio-volker/gr-utils/bindtool/scripts/bind_intree_file.py", line 3, in <module>
    from gnuradio.bindtool import BindingGenerator
ModuleNotFoundError: No module named 'gnuradio'
make[2]: *** [gr-analog/python/analog/bindings/CMakeFiles/agc2_cc_python.cc_regen_bindings.dir/build.make:73: ../gr-analog/python/analog/bindings}/agc2_cc_python.cc] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:5638: gr-analog/python/analog/bindings/CMakeFiles/agc2_cc_python.cc_regen_bindings.dir/all] Fehler 2
make: *** [Makefile:146: all] Fehler 2

The module 'gnuradio' is not part of the build tree and will be first setup on install.
That is: You must first install gnuradio before you can regenerate bindings.

Question: Is this an accepted behavior or a should it be treated as a bug and fixed in the long run
## Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ ] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by dl1ksv** [comment]
After installing gnuradio make in build/gr-analog leads to

Writing binding code to /home/schroer/gnuradiocomponents/gnuradio-volker/gr-analog/python/analog/bindings/../bindings/agc2_cc_python.cc
Writing binding code to /home/schroer/gnuradiocomponents/gnuradio-volker/gr-analog/python/analog/bindings/../bindings/docstrings/agc2_cc_pydoc_template.h

and the build succeeds without errors

**Comment by willcode** [comment]
Few of the blocks are set up this way. I'm just going to make this PR a draft, since it's meant to create discussion.

**Comment by dl1ksv** [comment]
Either pygccxml or pybind11 is missing, so no build can show the expected error.

**Comment by dl1ksv** [comment]
Meanwhile I found a way to regenerate the bindings together with a fresh build. But this requires pygccxml to be installed.
So how do I force pygccxml to be included in the testsystems?

**Comment by dl1ksv** [comment]
@ryanvolz could you please give me advice how to get pygccxml into the conda package?

**Comment by ryanvolz** [comment]
Unfortunately, `pygccxml` is not packaged for conda-forge. The best solution would be to avoid needing it, but that's not looking likely. The next best solution would be for someone to make that package, but I don't know how tricky that is. The last resort would be to add something like `$PYTHON -m pip install pygccxml` to the conda recipe build scripts to get it from PyPI through `pip`. It would then be good to do a similar `uninstall` at the end of the build scripts so that the `pygccxml` files are not included in the `gnuradio` package, but that only really matters outside this testing context.

**Comment by mormj** [comment]
Closing this as I don't think we are well situated to bringing pygccxml into the build process.  In 4.0 with code generation, we skip the need for scraping the compiled code to infer the bindings, so this gets much easier

**Pull request closed without merging**
