### PR TITLE
blocks: re-enable benchmarking tests

### PR DESCRIPTION
**Pull request by marcusmueller**
Were probably disabled since they don't compile with current GR.

Signed-off-by: Marcus Müller <mmueller@gnuradio.org>

## Description

These are non-unit tests, but benchmarks. They still serve the purpose of compile-checking, and take very little time to build.

While we're at it, remove the now defunct vco test, replace it with a polynomial sine approximation. 

Takeaway: approximation through a float polynomial that has less than 3.5e-6 of absolute error over the whole [-pi, pi] range is faster than our fxpt implementation.

## Related Issue

#6800 inspired me to look into the in-tree benchmarks

## Which blocks/areas does this affect?

nöthing

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
How do we use the information from the polynomial vco benchmark if this method isn't used anywhere?

**Comment by marcusmueller** [comment]
> How do we use the information from the polynomial vco benchmark if this method isn't used anywhere?

:D That's the thing, someone might be willing to triage "oscillators broken" as fixable mistake once they know there's a viable alternatives.

**Comment by willcode** [comment]
> > How do we use the information from the polynomial vco benchmark if this method isn't used anywhere?
> 
> :D That's the thing, someone might be willing to triage "oscillators broken" as fixable mistake once they know there's a viable alternatives.

OK, maybe someone will stumble across this and make changes that improve performance and fix 6800.

**Comment by marcusmueller** [comment]
No seriously, I'm getting started doing the triage issues job, and #6800 is kind of severe for an SDR framework. I had this polynomial code lying around, so and I needed to compare it to what GNU Radio does otherwise, so I was kind of happy to find `benchmark_.co` here. Didn't build, so I fixed it. This obviously really isn't useful getting #6800 sorted out itself, but it's kind of infrastructure desirable to test the qualities of these implementations; `qa_fxpt_vco` isn't as good as it should be, so I do plan on migrating code to that once I get around to fixing the issue.

**Comment by willcode** [comment]
As long as this is self-contained, go ahead and merge when you're done. Any chance of dependency or compile problems for unwitting users?

**Comment by marcusmueller** [comment]
Don't think so, but as you noticed, for a change that does little to actual functionality, this must be the one where I had to do the most changes for nothing but windows (and thankfully so, these were real issues that MSVC detected)

**Pull request merged**
