### PR TITLE
peak_detector2: bug fix and add a test case

### LINKED ISSUE #3345: peak_detector2: The average might not be correct
I think I found a problem using the Peak Detector2 block.
The debug output, which should output the moving average of the input signal, is outputting something slightly different.
An input sample making `d_found` switch from `false` to `true` might be counted twice in the average, resulting in a wrong average.

### PR DESCRIPTION
**Pull request by Callyan**
Fixes #3345 and adds a test case for the debug output.

### CODE REVIEW

**Comment by marcusmueller** [comment]
hey, @Callyan, this looks very nice, and correct. Um, now, I really want to merge this, but: do you happen to have a CLA for GNU Radio already? (or maybe your organisation, if any?) If not, please hit up @bhilburn under bhilburn (at) gnuradio (dot) org and say "I need a CLA"

**Comment by rear1019** [comment]
With all due respect, but this fix is flawed just as mine :smile:. See [1].

[1] https://github.com/gnuradio/gnuradio/pull/3356#issuecomment-612977923

**Comment by Callyan** [comment]
So the mail about the CLA has been sent, guess I have to wait now.

@rear1019 I guess you won this "comptetition" between pull requests 😂. Also, there might be the same issue with Peak Detector (when the work function doesn't return the whole batch of items), but changing the way Peak Detector works would make it very close to Peak Detector2 so I don't know what to do here.

**Comment by mormj** [comment]
@Callyan - were you able to get the CLA in place?

**Comment by Callyan** [comment]
After having left this aside for some time, I am now working on getting it. I hope I will have it soon.

**Comment by Callyan** [comment]
I have now my CLA

**Review by mormj — APPROVED** [review]

**Review by willcode — COMMENTED** [review]
I think the fix is not necessary, and is incorrect. The index from the threshold detection pass is saved off, and could possibly be used as the peak index into the input to the _next_ work() call. The referenced issue was that a sample could be counted twice in the average. This could be fixed by putting the d_avg calculation at the bottom of the threshold detection loop so it is not hit before the return.

**Comment by rear1019** [comment]
> I think the fix is not necessary, and is incorrect.

The fix here is incorrect indeed; see [1]

[1] https://github.com/gnuradio/gnuradio/pull/3356#issuecomment-612977923

**Comment by mbr0wn** [comment]
Since we have two people in agreement that this is incorrect, and no further activity, closing now.

**Pull request closed without merging**
