### PR TITLE
digital: split swig (a la, blocks/swig) into 3 parts

### PR DESCRIPTION
**Pull request by michaelld**
Allows for building on "low memory" systems (e.g., RPi). Passes "make test", and my GRC test flowgraphs all work.

### CODE REVIEW

**Comment by jmcorgan** [comment]
Concept ACK.  I'll have to test this on different swig versions and can actually set the RAM size in the test setup.  What memory level did you test this at?

**Comment by michaelld** [comment]
RPi with 1 GB DRAM. Can't use anything more than "-j2" until it runs out of memory, then back down to just "make" until it gets over the SWIG files; than back to "-j2" until it runs out of memory (etc). Eventually the build works. OR: Start the build ("make"), go to bed, should be done 8 hours later.

**Comment by jmcorgan** [comment]
Got it.  I should be testing low-memory compiles anyway.

**Comment by michaelld** [comment]
Looks like there's 1 GB total, so really only about 948 KiB available for compiling (according to 'top').

**Comment by michaelld** [comment]
I'm impressed that I can even build GR in whole on a RPi, no matter how slow it is. With this change, it does build & passes "make test" too ... I did of course test this change on my macOS box, and it works nicely there too.

**Comment by jmcorgan** [comment]
Heh, make -j on the 64GB/48 core box used to take 53GB before some of the cmake optimizations.

**Comment by michaelld** [comment]
LOL I do "-j4" on my macOS box ... usually doesn't hang the system.

**Comment by mbr0wn** [comment]
"64 GB ought to be enough for anybody"

**Comment by mbr0wn** [comment]
Unrelated, but we really need to teach the RPi crowd how to crosscompile.

**Comment by jmcorgan** [comment]
This branch has passed on my local setup, but I haven't done any low-memory testing yet.

**Comment by michaelld** [comment]
I'll do a build from scratch on my PRi tonight & verify (just "make" ... no "-j2" or whatever). I think this was the only build issue on that device.

**Comment by michaelld** [comment]
@mbr0wn : I'd -love- to know how to do a cross compile. Any docs reference you prefer? Easier is better.

**Comment by mbr0wn** [comment]
Cross compiling on RPi seems more difficult than other devices, but I don't know why. There's no toolchain file. You can take a look at Phil's docs on the GNU Radio wiki if you want a general intro.

**Comment by michaelld** [comment]
Hmm ... I'm trying building on the RPi right now, and it looks like I have to split trellis/swig too. I'll do that & push it to this PR when it works on both my macOS box & the RPi.

**Comment by mbr0wn** [comment]
I'm not opposing this or anything, but waiting 8 hours instead of 4 on the RPi doesn't seem like a major issue.

**Comment by jmcorgan** [comment]
We do occasionally get the support issue from people struck by the OOM killer when native compiling on these low mem architectures.

**Comment by jmcorgan** [comment]
These splits also tend to slightly speed up compilation on "regular" machines, as swig compiles tend to be single-core operations, and the splits can be done in parallel.

**Comment by michaelld** [comment]
I've split the trellis/swig files into 2 parts; seems to work on my Mac both as "-j1" and "-j4". Still building on the RPi (gonna be a few hours on the RPi before I can say if this is the final change for building in low memory or not).

**Comment by michaelld** [comment]
Looks like the build works now, with these 2 changes in place. I'm running "make test" now ... back in a few hours ...

**Comment by michaelld** [comment]
"make test" passed/failed as expected. I'm doing a fresh configure/build overnight just to make sure. I'll report back tomorrow morning sometime.

**Comment by michaelld** [comment]
OK. After much ado I confirm that this branch allow for building on a memory-limited RPi. The output of "time make" from a clean build directory (just created by cmake): "real 562m44.924s  user 541m28.180s  sys 15m54.570s" ... so a little over 9 hours to build! But, it now works, which is better than what we had before -- if anybody really cares (beyond me).

**Pull request merged**
