### PR TITLE
Modtool: use cmake-format in newmod

### PR DESCRIPTION
**Pull request by marcusmueller**
- cmake-format: include necessary tooling in config Py
- modtool: fix passing of filename instead of filenames iterable
- newmod: Format template CMakeLists.txt according to our cmake-format
- cmake-format: install to data directory, use in new modules

## Description

People's `gr_modtool` breaks when they format their OOT's CMakeLists.txt with cmake-format defaults.

Include .cmake-format.py from our source to fix that.

Also, fix the bugs in `gr_modtool add --scm-mode yes`  that went unnoticed.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Will also pull 297a26b out to a separate bugfix PR

**Comment by willcode** [comment]
@marcusmueller Saw the other PR, are you going to remove 297a26b30838e1036f991770965373471594f7e1 from this PR?

**Comment by marcusmueller** [comment]
@willcode since things don't work without, I'd be hesitant to – the rebase on HEAD would get rid of that commit, anyways.

**Comment by willcode** [comment]
OK, all good.

**Comment by willcode** [comment]
Since there aren't many modtool updates, I'll just keep them together and close the other PR.

**Pull request merged**
