### PR TITLE
Misc warnings fixes

### PR DESCRIPTION
**Pull request by michaelld**
Per GR issue #776: I've been playing around with building GNU Radio using various compilers and hardware architecture settings on OSX -- meaning: Apple GCC 4.2, vanilla (MacPorts) GCC 4.8, Apple Clang 5.1 (llvm 3.4), and vanilla (MacPorts) Clang 3.6 (llvm 3.6); 32-bit and 64-bit for as many of these as I can. I've found some interesting bugs. This PR contains all of the fixes for those warnings. Some of these are (I think) critical (programming errors), while others are mundane (making the compiler happy). I tried to keep volk changes separate from the others, and then combining similar changes into a single commit.

### CODE REVIEW

**Comment by trondeau** [comment]
Michael,

Good stuff. Just a few points to discuss:

1. Why prefer memcpy over bcopy? My gut says bcopy was used here to avoid issues of potentially overlapping memory; memcpy will error out if src and dst overlap at all.

2. In osx_impl, a call like "char var[other_var]" isn't legal for all compilers. This may be something that I haven't kept up on, so it might be in the newer C++ standards. To be safe, though, can we call new and delete instead?

3. I think the glfsr issue is discussed here: http://gnuradio.org/redmine/issues/540

I definitely like the other changes. I'm going to wait on this until @jmcorgan can also take a look to give his opinion.

**Comment by trondeau** [comment]
Also, we'll want to make sure those volk patches get migrated over to the volk stand alone repo (attn @n-west).

**Comment by michaelld** [comment]
1) memcpy is what's used throughout GR. Every one of these bcopy calls copies between disparate buffers, so there's no overlap issue.

2) the "char format_id[sizeof(asbd.mFormatID)+1]" works for all of the compilers I tried. I'd guess that this is partly due to "sizeof" being a compiler pre-processor directive, and then the result being a constant -- no actual variable being used within the []'s.

3) Could be; doesn't look the same though.

**Comment by trondeau** [comment]
@michaelld I'm satisfied on 1 and 2; I'd still need to review 3 but it's likely ok as you say. Still want @jmcorgan to have a quick glance over these to see if there might be anything else.

Meantime, this is a PR against master, but some or all of these likely belong on maint. Can you look into that and maybe separate PRs for maint and master if that's the case?

**Comment by michaelld** [comment]
Yes, I can split them into 2 PRs. What's your general guideline for what going on maint versus master?

3) OK; yes, I see what you mean upon more specific review of those patches. I like those patches better; mine assumed the continued use of "int" type, while theirs move to using "unsigned int", which should avoid the issue the compiler found: some compilers interpret numbers starting with "0x" as being unsigned, and so the one starting with "0x8XXXXXXX" may nor not be correctly converted to the "int" type. I'll remove this patch from the split PR.

**Comment by n-west** [comment]
Probably not the answer you're looking for, but I can't pass up the opportunity.

guidelines

**Comment by michaelld** [comment]
Haha! Well, none of these changes are "new development"; they are really all bug fixes of various sorts. So, everything on maint?

**Comment by jmcorgan** [comment]
Comments:

* The volk commits should be on their own, to facilitate redoing them on the separate volk repository,
* The gr-fcd ones can be ignored, as this component is deprecated and will be removed for 3.8,
* The remainder should be on a branch off maint

**Comment by michaelld** [comment]
OK; will do; hopefully Monday. Thanks for the clarification. I'm closing this PR since it's not going to be used.

**Pull request closed without merging**
