### PR TITLE
digital:added new constellations objects naturally mapped 8PSK and 16QAM

### PR DESCRIPTION
**Pull request by fengzhe29888**
Dear @jmcorgan ,

I've made a clean new branch with only the constellation commit. Could you check and merge it?

Thanks!
Best,
Zhe

### CODE REVIEW

**Comment by jmcorgan** [comment]
Ok, now do the same for the accessor commit.

**Comment by jmcorgan** [comment]
Sorry, I somehow missed the second commit when I merged.  I'll get that now.

**Comment by fengzhe29888** [comment]
It was my mistake. I should have updated it earlier.

I'm ready for the trellis pull request.

Thanks!

**Comment by jmcorgan** [comment]
Please make each of these a new pull request, and if possible, have them on separately named branches.

**Comment by fengzhe29888** [comment]
Sure. I'll do that! The next pull is ready.

Thanks!

**Pull request closed without merging**
