### PR TITLE
coc: Update to contributor covenant 2.0

### PR DESCRIPTION
**Pull request by mbr0wn**
The text is unmodified, with the exception of our coc email put in.

### CODE REVIEW

**Comment by duggabe** [comment]
In our GRCon21 Indico website we have "coc@gnuradio.org"

**Comment by dkozel** [comment]
The Wiki will need updating as well as it is a canonical source for many web links.
https://wiki.gnuradio.org/index.php/Code_of_Conduct

**Review by 777arc — APPROVED** [review]

**Comment by 777arc** [comment]
> The Wiki will need updating as well as it is a canonical source for many web links.
> https://wiki.gnuradio.org/index.php/Code_of_Conduct

I always prefer having stuff live in 1 place whenever possible, any chance we can just leave that wiki page with the link and not the actual CoC?

**Comment by duggabe** [comment]
I agree with the "one place" objective! Currently there are three:
https://github.com/gnuradio/gr-governance/blob/main/CODE_OF_CONDUCT.md email: conduct@gnuradio.org
https://wiki.gnuradio.org/index.php/Code_of_Conduct email: conduct@gnuradio.org
https://events.gnuradio.org/event/8/page/2-code-of-conduct email: coc@gnuradio.org
I recommend that the one, authoritative source be in gr-governance, with the other two having only a brief statement and a link.

**Pull request merged**
