### PR TITLE
Add new Symbol Synchronizer blocks

### PR DESCRIPTION
**Pull request by awalls-cx18**
Add new symbol synchronizer blocks to gr-digital and their required supporting classes to gr-digital and gr-filter.

These blocks are a superset of the Clock Recovery M&M blocks, MSK Timing Recovery Block, and PFB Clock Synch blocks.

These blocks address many bugs found in those existing GNU Radio blocks.  These blocks also propagate tags correctly and will resync their tracking on time_est and clock_est tags.

The user can select the timing error detector to use.  Decision directed TEDs (like M&M) require the user to specify a slicer constellation (usually digital.constellation_bpsk.base() or digital.constellation_qpsk.base()).

The user can select which interpolating resampler to use.  The "PFB with MF" interpolating resampler requires the user to provide taps for matched filtering.

The user can also set, within reason, an arbitrary number of output samples per symbol (1, 2, 3, 4, 5,...).

-Andy

### CODE REVIEW

**Comment by awalls-cx18** [comment]
The build-bot's giving my last commit, that fixes an example flowgraph, a bum rap:

```
The following tests FAILED:
	 80 - qa_hier_block2 (Failed)
Errors while running CTest
```

**Comment by marcusmueller** [comment]
[Specifically:](https://ci.gnuradio.org/buildbot/#/builders/6/builds/19/steps/5/logs/stdio)

```
 80/210 Test  #80: qa_hier_block2 .......................***Failed    3.32 sec
......................................Segmentation fault (core dumped)
```

**Comment by awalls-cx18** [comment]
A hand drawn block diagram of the symbol synchronizer block's design is attached.  Hopefully it helps you review the DSP.  Let me know if you have questions.

-Andy
[Symbol_Synchronizer_block_diagram.pdf](https://github.com/gnuradio/gnuradio/files/950045/Symbol_Synchronizer_block_diagram.pdf)

**Comment by noc0lour** [comment]
@marcusmueller the `qa_hier_block2` is one of the broken test cases. I probably just exclude that one and put it on the "tests to investigate" list.

**Comment by jmcorgan** [comment]
The qa_hier_block2 is a known troublemaker.

**Comment by jmcorgan** [comment]
@awalls-cx18  :-1: for not using an actual napkin for that diagram.

**Comment by awalls-cx18** [comment]
@jmcorgan:  LOL!

I should also point to this PDF about the clock tracking loop (P-I loop filter) transfer function derivation:
https://github.com/awalls-cx18/gr-nwr/blob/master/docs/clock_loop.pdf
to demystify some of the math performed when updating the alpha and beta gains of the loop filter.

**Comment by marcusmueller** [comment]
:+1: for the tikz usage :) I'll probably tikz down your non-napkin figure Thursday, if you'd like me to, and we can look how we'll get that into the docs. 

Am 24. April 2017 00:13:11 MESZ schrieb Andy Walls <notifications@github.com>:
>@jmcorgan:  LOL!
>
>I should also point to this PDF about the clock tracking loop (P-I loop
>filter) transfer function derivation:
>https://github.com/awalls-cx18/gr-nwr/blob/master/docs/clock_loop.pdf
>to demystify some of the math performed when updating the alpha and
>beta gains of the loop filter.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gnuradio/gnuradio/pull/1294#issuecomment-296492623

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by awalls-cx18** [comment]
@marcusmueller : Feel free to tikz my hand drawn picture, I didn't have time myself (I barely know tikz and LaTex).  That picture is also applicable to the existing GNU Radio M&M clock recovery blocks, MSK timing recovery block, and the PFB clock sync blocks.

Note that that picture shows all the components whether they exist or not in the current configuration.  I.e., not all TEDs need a slicer constellation; not all TEDs need derivative input samples; if using the PFB MF interpolating resampler, one doesn't need the external matched filter.  The decimators are always there, but in some configurations they are doing nothing (decimating by a factor of 1).

Another subtle point is that the MMSE interpolation filter in GNU Radio is actually implemented as a polyphase filter bank, even though it's not called that explicitly.

-Andy

**Comment by awalls-cx18** [comment]
Come 15 May 2017, I will be too busy to address any comments on this PR until 15 June 2017.  Please try to get comments to me by, let's say, 8 May 2017, if you would like me to work them sooner rather than later.

**Comment by jmcorgan** [comment]
@awalls-cx18 I have some structural issues with the code organization and placement of header files, but this is all non-DSP and mechanical.  I'll be doing deeper review this week, and of course, anyone else is free to review and critique.

**Comment by awalls-cx18** [comment]
Made the following changes at the request of @jmcorgan : 

- Rebase on master then force push commit.  Done.
- TED class must be removed from API.  Split the enum ted_type to its own small API visible definition. Done.
- Clock tracking loop class must be removed from API.  Done.
- Interp_differentiator_taps.h must be removed from API.  Done.
- Move interpolating resampler class to gr-digital and it must be removed from API. Split the enum ir_type to its own small API visible definition. Done.
- The mmse_interpolating_differentiator class could move to gr-digital, since only gr-digital uses it. Or maybe it could be left in gr-filter, and use GR_FILTER_INCLUDE.  Done, left in gr-filter.

Remaining to be done of @jmcorgan's requested items:

- Reformat source code to be consistent with GNURadio coding style: no tabs, 2 space indents, lines end at 70 characters.   Anything else? (That's all I could glean from the gnuradio wiki on coding style and Emacs C++ is not a clearly defined specification to work to for a Vim user: I could find no definition of its behavior/parameters.)

Regards,
Andy

**Comment by jmcorgan** [comment]
@awalls-cx18 Thanks for taking the time to clean up the code organization. As I said, these were the mechanical changes needed to conform to our API principles. I'll review this now for any showstoppers for merging, and since this is a new block, we can merge it in even if we need to make internal changes to the actual DSP functionality after the fact.

**Comment by noc0lour** [comment]
@jmcorgan we could try to agree on a astyle configuration and make that a test (:

**Comment by jmcorgan** [comment]
This is going in as one squashed commit.

**Pull request closed without merging**
