### PR TITLE
Change rounding method to `std::lround`

### LINKED ISSUE #2822: use right rounding method for floating point rounding
```
/home/marcus/src/gnuradio/gnuradio-runtime/lib/block_executor.cc:146:38: warning: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings]
                    new_tag.offset = ((double)new_tag.offset * rrate) + 0.5;

```

for large offsets, +0.5 can silently round to 0 ('doh).

might be more than related to #2055

### PR DESCRIPTION
**Pull request by mathiasvr**
Fixes #2822

### CODE REVIEW

**Comment by mathiasvr** [comment]
@michaelld Thanks, from the issue it wasn't even clear to me that `0.5` was part of the rounding, so your comment cleared things up for me. I have updated PR accordingly.

I believe using the `lround` function instead of the `+0.5` trick is preferable since it reads more clearly the intent. Also, it is supposedly faster and more correct in some cases, see https://clang.llvm.org/extra/clang-tidy/checks/bugprone-incorrect-roundings.html

**Comment by michaelld** [comment]
> @michaelld Thanks, from the issue it wasn't even clear to me that `0.5` was part of the rounding, so your comment cleared things up for me. I have updated PR accordingly.

OK. Thanks for that change. I can agree now that the code is roughly equivalent to what it was doing before.

> I believe using the `lround` function instead of the `+0.5` trick is preferable since it reads more clearly the intent. Also, it is supposedly faster and more correct in some cases, see https://clang.llvm.org/extra/clang-tidy/checks/bugprone-incorrect-roundings.html

Interesting. Makes sense, sort of. Makes me sad that my "old school" go to for float to integer conversion isn't guaranteed to be as fast or accurate as I thought it was! :(

**Comment by michaelld** [comment]
I've tagged @marcusmueller for a 2nd review, just for the sake of 1 more set of eyes here.

**Comment by ValZapod** [comment]
Mmm... What is the point of changing only one place?

**Comment by willcode** [comment]
Using llround() for clarity is good, and this looks correct here. I don't think it improves accuracy or performance in this case (rrate/offset are positive doubles). Also in tagged_stream_block.cc.

**Comment by michaelld** [comment]
I think with the change to line 195, I'm happy with this PR. I'd wish for a review from @marcusmueller  ... but if he's too busy I'm OK with moving this along as it's simple and makes sense.

**Comment by mathiasvr** [comment]
I went ahead and fixed every line reported as `bugprone-incorrect-roundings` by `clang-tidy`.

**Comment by michaelld** [comment]
@mathiasv do you have a CLA (commit agreement) with the GNU Project? If you don't or you don't know, then you don't & we need to get you one for this many changes.

**Comment by mathiasvr** [comment]
@michaelld I see, how do I get one?

**Comment by michaelld** [comment]
@bhilburn would you please get @mathiasvr started with the CLA process?

**Comment by bhilburn** [comment]
@mathiasvr - Just send me an email, `bhilburn@gnuradio.org` =)

**Comment by mathiasvr** [comment]
I signed the CLA a while ago, am I supposed to do something or did you already receive it?

**Comment by bhilburn** [comment]
Hi Mathias - Nope, you are all set! All your contributions are clear for
merge.

**Comment by michaelld** [comment]
All CI passes. Multiple positive reviews. CLA. -> merging

**Pull request merged**
