### PR TITLE
runtime: top_block: Add precondition to Python version of wait()

### PR DESCRIPTION
**Pull request by mbr0wn**

### CODE REVIEW

**Review by marcusmueller — APPROVED** [review]
It is a bit of a hack (why not wait to call `wait()` in the test?), but it seems to be sensible functionality in the right place, and it doesn't actually cost anything.

**Comment by marcusmueller** [comment]
(this, btw, would be the kind of change that'd make sense to have in the CHANGELOG)

**Comment by mbr0wn** [comment]
lulz-- I must have fat-fingered this PR. I wasn't going to put it up yet. But glad you still approve :)

**Comment by mbr0wn** [comment]
> It is a bit of a hack (why not wait to call `wait()` in the test?), but it seems to be sensible functionality in the right place, and it doesn't actually cost anything.

BTW, I totally agree this is a hack. But in principle, I think it is the right idea to give the flowgraph some more info about what's going on externally.

**Comment by mbr0wn** [comment]
Well I'll be damned -- this didn't actually fix the underlying issue. Huh?

**Comment by willcode** [comment]
Is there a way to put this in gr_unittest.py? Or are you thinking that it might be of wider use?

A wrapper would be nice, just because wait() has a fairly well known meaning. Could it be wrapped or patched in just for qa?

**Comment by mormj** [comment]
Yeah - I'm on the fence about this one because it creates a diversion between the python and c++ versions of `wait`

Wrap wait with this functionality as `wait_until`?

**Comment by mbr0wn** [comment]
I'm actually having second thoughts about this entire approach. How about we close this and think about it. It didn't even fix the thing I was trying to fix (qa_agc).

**Pull request closed without merging**
