### PR TITLE
qtgui: make sure QSS style is applied to Qt gui even when no plotter …

### PR DESCRIPTION
**Pull request by osh**
…is attached

### CODE REVIEW

**Comment by jmcorgan** [comment]
FYI, the build is breaking with this; I'm looking into why:

**Comment by jmcorgan** [comment]
Looks like util.py wasn't checked in, please fix.

**Comment by osh** [comment]
thnx, now very pushed

**Comment by jmcorgan** [comment]
FYI, this is merged, but there were fixups needed to integrate the changes into the QT4/QT5 conditionalization on the next branch, and they aren't quite right, so next is broken for QT until that gets straightened out.

**Pull request merged**
