### PR TITLE
modtool: Switched over to mako template engine

### PR DESCRIPTION
**Pull request by mbr0wn**

### CODE REVIEW

**Comment by jmcorgan** [comment]
Needs rebase.

**Comment by mbr0wn** [comment]
Rebased.

**Comment by jmcorgan** [comment]
Would it make sense to merge this into 'next' now?

**Comment by mbr0wn** [comment]
Should pull in @skoslowski and probably @trondeau:

As soon as we merge, we add mako as a dependency. In previous discussions, we already discussed having both Cheetah and Mako as deps, so that would be OK. It would mean another commit to update the docs and the CMake, and I would volunteer to do those, too.

However, we still need to move Cheetah out of GRC and I'm not sure what the plans are on that. If it's not going to happen for 3.8, that would be reason not to merge this. Otherwise, we're good.

**Comment by jmcorgan** [comment]
It will be essential to pull out Cheetah from GRC for 3.8; we won't have time to do it otherwise for a very long time, and we're facing Python 3 issues in six months or so.

**Comment by mbr0wn** [comment]
OK, in that case, merge it, and I'll add another PR today for Mako.

**Comment by trondeau** [comment]
I agree with @jmcorgan; we'll need Mako support in GRC for 3.8.

**Comment by jmcorgan** [comment]
@mbr0wn Can you just add the new commits on top of this PR?

**Comment by mbr0wn** [comment]
Will do!

**Comment by mbr0wn** [comment]
Updated.

**Comment by mbr0wn** [comment]
Note I didn't remove Cheetah or even touch anything GRC-related.

**Pull request merged**
