### PR TITLE
Update README.md to provide instructions for building GR with support of python3.x

### PR DESCRIPTION
**Pull request by aru31**
Request PR review for issue #2328

### CODE REVIEW

**Comment by michaelld** [comment]
Nice work! I'm of mixed mind as to whether this change should be here or in the REAME.md for PyBOMBS: https://github.com/gnuradio/pybombs/blob/master/README.md . Thinking @mbr0wn will have an opinion here!

**Comment by michaelld** [comment]
Also: @bhilburn do we require a CLA for tweaking a README file?

**Comment by michaelld** [comment]
Reviewing GR's README.md, I think it would be appropriate to have this tweak in it, since the README already covers PyBOMBS and this change is GR-specific.

**Comment by dkozel** [comment]
If this does get merged it should be generic to any supported Python 3.x version, not just 3.6.

**Comment by 777arc** [comment]
I support this change, but it's kind of silly to not just fix PyBOMBS and make a gnuradio3.8 recipe

**Comment by aru31** [comment]
@dkozel, I guess it is definitely generic for python3.x version because actually, it is an apache-thrift issue, which has been dealt with in this issue.

**Comment by noc0lour** [comment]
Manually fixed up the commit message and merged in 3864d35f53a79bd201a1d1da4e7c30533793a6c9.

**Pull request closed without merging**
