### PR TITLE
gr-dtv: Vastly improved OFDM symbol acquisition for DVB-T receiver.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Comment by jmcorgan** [comment]
Will need copyright assignment from @git-artes

**Comment by git-artes** [comment]
Hi, 
As I said by mail, we are more than glad to help with GNU Radio. Regarding the copyright assignment, I suppose it is some documents which we should sign and send you? Will I get them by mail or is there a URL where I may download them?
best
Federico

**Comment by trondeau** [comment]
@git-artes please send me an email (tom AT trondeau.com) and I'll forward you the documents you need to start the process.

**Comment by git-artes** [comment]
Hi, 
Just to let you know we've sent the documents Tom sent us. 
best

**Comment by git-artes** [comment]
Hello (again), 
We've just snailed the documentation required by the FSF. 
best, 
Federico

**Pull request closed without merging**
