### PR TITLE
grc: Fix generation of QT hier blocks

### PR DESCRIPTION
**Pull request by haakov**
Mostly just code left over from before Mako.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Hey @haakov, I think @dl1ksv is right here. Can you fix that?

**Comment by haakov** [comment]
Oops, I thought I fixed that before I left!
I can fix it, but not until Tuesday.

**Comment by haakov** [comment]
Okay, fixed. 

@dl1ksv Did I interpret your correction correctly?

**Comment by mbr0wn** [comment]
How can I test this?

**Comment by mbr0wn** [comment]
Actually it was quite easy to test. Merged manually, had to fix the commit messge formatting.

**Pull request closed without merging**
