### PR TITLE
gr-fft: add locking mechanism to fftw_wisdom

### PR DESCRIPTION
**Pull request by noc0lour**
Add a lockfile for access to the fftw wisdom. 
Unfortunately in Linux the lockfile will be locked for all threads in one process so there has to be a mutex to lock other threads out as well.

I didn't test running `all` GR tests with a high job number.

### CODE REVIEW

**Comment by jmcorgan** [comment]
I haven't looked through the code yet, but a quick trial merge and parallel ctest resulted in the below:

```
$ ctest -j214 --output-on-failure

94% tests passed, 12 tests failed out of 214

Total Test time (real) =  24.85 sec

The following tests FAILED:
	 97 - qa_fft (Failed)
	100 - qa_fft_filter (Failed)
	104 - qa_freq_xlating_fft_filter (Failed)
	107 - qa_pfb_synthesizer (Failed)
	117 - qa_pfb_channelizer (Failed)
	119 - qa_pfb_interpolator (Failed)
	120 - qa_pfb_decimator (Failed)
	144 - qa_ofdm_txrx (Failed)
	150 - qa_correlate_and_sync (Failed)
	152 - qa_ofdm_sync_sc_cfb (Failed)
	165 - qa_ofdm_serializer_vcc (Failed)
	197 - qa_qtgui (Failed)
Errors while running CTest
```
I think this is every test for something that uses gr::fft inside. All of the failures look like this:
```
1/214 Test  #97: qa_fft ...............................***Failed    7.85 sec
fftw: planner.c:891: assertion failed: flags.u == u
Aborted (core dumped)
```
Full log: [ctest.txt](https://github.com/gnuradio/gnuradio/files/967926/ctest.txt)

**Comment by jmcorgan** [comment]
This may have been a result of a corrupted fft_wisdom file from previous testing, rechecking now.

**Comment by jmcorgan** [comment]
Unfortunately, even with this PR, the wisdom file is getting corrupted by parallel tests.  However, setting .gr_fftw_wisdom to a 0 byte read-only file results in all tests passing ctest -j214, ten times in a row.

**Comment by noc0lour** [comment]
hm, that's strange, probably there is still something wrong in the code,I can put some debug prints in sometime this week and run parallel tests somewhere.

**Comment by jmcorgan** [comment]
@darek-kawamoto wrote an interface class to allow better coordination between GNU Radio and OOT modules for managing FFTW wisdom/planner sharing. I collected his commits and made a branch off current maint [here](https://github.com/jmcorgan/gnuradio/commit/743063e5cc4ff5477cd74f61aae66a5270798bf8).

While this might be overkill for what we need, within it is a similar locking mechanism to what you wrote in the PR.

@darek-kawamoto Can you do a quick summary of the changes and how they might be applicable here?

**Comment by darek-kawamoto** [comment]
boost::interprocess::file_lock attempts interprocess-synchronization of wisdom file access.

The other problem is that currently, every gr-fft block creation results in a hit to the wisdom file (a read and a write).  A cached wisdom file manager only reads the wisdom file once, and is only allowed to write once every 100 ms.

A cached-concurrent manager combines both of the above.

At library load, an initializer in the anonymous namespace sets up the basic manager and queues up the teardown using std::atexit().

**Comment by jmcorgan** [comment]
@noc0lour Given that the lock/unlock wisdom calls are only ever paired with calls to import/export wisdom, it would be simpler to just add the lock/unlock logic to the import/export functions themselves.

**Comment by noc0lour** [comment]
Putting the locking and unlocking in the import/export is possible as well. I thought putting it in the top level function is clearer for other uses of the fftw-wisdom.

**Comment by jmcorgan** [comment]
I've done some more testing and I'll go ahead and merge this as-is.  It may not be the complete solution but it's clear it is part of it.

**Comment by gnieboer** [comment]
FYI, on an MSVC build this is hanging on the test_multithreaded test, it appears that lock is being called on the thread_mutex locked twice and never unlocked.  It'll take a bit more time to set up a specific test scenario to step into.  All I can say for the moment is that the second lock attempt happens during the make() call.

**Comment by gnieboer** [comment]
OK, found the problem.  A new wisdom_lock object is being created in the wisdom_unlock() routine, which then throws an exception when unlock() is called because the new object isn't locked.  This then aborts the make() routine without unlocking the original object.  Then when wisdom_lock() gets called in the next test, it's already locked and the application hangs.  To fix just create a single wisdom_lock object and reuse it for both calls.  Pull request forthcoming.

**Comment by noc0lour** [comment]
@gnieboer thanks for debugging (: I was sure there is still some flaw hidden somwhere ;)

**Comment by gnieboer** [comment]
#1332 is the pull request.  No problems!

**Pull request merged**
