### PR TITLE
filter: add cpp export for iir filter

### PR DESCRIPTION
**Pull request by martynvdijke**
Hi all,

This is my first pull request hope everything is owkey/ up to standards.

I noticed not all filter components have direct cpp export and i needed this to debug my system much easier, so based #2343 I edited the fir interp block to also directly output cpp.

### CODE REVIEW

**Comment by mormj** [comment]
@martynvdijke - Thank you for the contribution - it is good to have more coverage with the cpp templates.  Haven't tested this out, but on the surface looks good.

One small thing - would you mind rewording the commit message to indicate the module that the commit pertains to, in this case something like `filter: add cpp export for iir filter`.  This makes it easier to sift through the commit log later on.

**Comment by marcusmueller** [comment]
Hi @martynvdijke! You changed the pull request title, not the commit message :)

**Comment by martynvdijke** [comment]
> Hi @martynvdijke! You changed the pull request title, not the commit message :)

Yeah I know, I was figuring out how to do it.
But then it was Friday afternoon :)

It should be fixed now.

**Comment by haakov** [comment]
I'll have a look later today.

**Comment by mormj** [comment]
@haakov - any chance to take a look?  If not, I can test it out, but certainly don't have as much insight into this feature

**Review by haakov — CHANGES_REQUESTED** [review]
Tested, looks good! But I'd change the commit message to `filter: Add C++ templates for Interpolating FIR filter`

**Comment by martynvdijke** [comment]
Fixed the commit message

**Pull request merged**
