### PR TITLE
docs: Fix definition of hilbert transformer in hilbert_fc.h

### PR DESCRIPTION
**Pull request by valdaarhun**
## Description

In [hilbert_fc.h](https://github.com/gnuradio/gnuradio/blob/main/gr-filter/include/gnuradio/filter/hilbert_fc.h), the description given is that of an analytic signal rather than the hilbert transformer.

## Related Issue

Related to #5437 

## Which blocks/areas does this affect?

The change is related to the hilbert transformer block. There shouldn't be a change in performance whatsoever.

## Testing Done

Documentation-related change, so no testing is required.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Review by mbr0wn — CHANGES_REQUESTED** [review]
The output of this block is in fact the analytic signal to its input (see https://github.com/gnuradio/gnuradio/blob/463c3477549b26b32d9b73eef30044e97c4eee64/gr-filter/lib/hilbert_fc_impl.cc#L44-L56). That means the original documentation is, in fact, accurate.

In practice, a single block that simply phase-shifts can be implemented by other means and would not be super useful by itself. Hence this block that generates an analytic signal to its real input.

I'm guessing that you're thrown off by the name of the block. Given that, I agree though that the documentation could be improved. Please either find a better description of this block, or consider closing the PR again.

**Comment by valdaarhun** [comment]
Hi. I understand the issue here. The description and implementation both point to the generation of an analytic signal. But the name implies that this is a hilbert transformer. Simply changing the name of the file to something more appropriate might have unfavourable project-wide consequences.

According to [this description](https://github.com/gnuradio/gnuradio/issues/5437#issue-1091620730):

> it would seem to be nice to have "Hilbert transformer taps" as separate block, just as we have "low pass filter taps", etc, especially since chances are you'd want your discrete HT to be of significant length, i.e. use an FFT filter.

How do you find the idea of moving the current implementation to a new file that is appropriately named and changing the implementation in `hilbert_fc.h` to something based on the above comment?

**Comment by mbr0wn** [comment]
> > it would seem to be nice to have "Hilbert transformer taps" as separate block, just as we have "low pass filter taps", etc, especially since chances are you'd want your discrete HT to be of significant length, i.e. use an FFT filter.

I think this assessment by @marcusmueller is a bit overkill. How often do people actually use Hilbert transfomers in practice? All SDR hardware generates complex I/Q. If you are using this block in a simulation, then there's no need to optimize this for the last few percentages. And are you really going to create a Hilbert transformer with so many taps that the FFT filter is going to be significantly faster? I doubt many people who run this in real-time applications have ever changed the default number of taps, which is 65. And which does not require an FFT filter.

> How do you find the idea of moving the current implementation to a new file that is appropriately named and changing the implementation in `hilbert_fc.h` to something based on the above comment?

Like I said, I don't agree with @marcusmueller on this being a major issue. I would suggest going back to improving the documentation, maybe adding a better explanation what exactly it is that this block does, maybe a reference or two. You can reference textbooks or wikipedia, and you can certainly reference `firdes::hilbert()` which is used internally. IMO, that would be sufficient to close the associated bug.

Thanks for taking a look at this, @valdaarhun!

**Comment by mbr0wn** [comment]
Thank you!

**Comment by mbr0wn** [comment]
@valdaarhun I'll close this PR until you have a better documentation suggestion. Then, please either re-open the PR or create a new one. This is so the PR queue on github doesn't become too cluttered. We look forward to your contribution!

**Comment by valdaarhun** [comment]
Hi. Sorry for the delay. I have got a new patch ready. I am not sure how one re-opens a PR. I think I'll just open a new PR.

**Pull request closed without merging**
