### PR TITLE
Qt5 next

### PR DESCRIPTION
**Pull request by trondeau**
Fixes examples; based off @pcercuei qt5 branch.

Supersedes #651.

### CODE REVIEW

**Comment by jmcorgan** [comment]
I'm having trouble getting the qwt5 dependencies found during cmake.  Will have to spend a little more time to see if it is a local issue.

**Comment by jmcorgan** [comment]
CMake Warning at gr-qtgui/CMakeLists.txt:25 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


-- QWT Version: 5.2.3
-- 
-- Python checking for PyQt5
-- Python checking for PyQt5 - not found

**Comment by jmcorgan** [comment]
The only python related package I can find on Ubuntu 14.04 is python3-pyqt5; it appears this isn't packaged for python2 here, unless I'm completely mistaken.

**Comment by pcercuei** [comment]
Debian stable has python-pyqt5, so it'd be surprising if Ubuntu didn't have it.
There is also libqwt-qt5-6 in Debian experimental.

Do you think it's too early to merge this then?

**Comment by jmcorgan** [comment]
Possibly.  I'm out of the office at the moment but will look into it further later today.  In general, yes, we try to synchronize our dependencies with their availability on long-term support or stable releases of distributions.

**Comment by jmcorgan** [comment]
So, I've confirmed that Ubuntu only packages python3-pyqt5 on 14.04 LTS release.  Our plan is to go to python3 with the 3.8 release, so this will be okay, but there is major work to be done on next branch in preparation for that.  I'm going to put this pull request on hold pending that.

**Comment by jmcorgan** [comment]
This has been merged into a new next-qt5 branch, untested (by me).

**Pull request closed without merging**
