### PR TITLE
modtool: replace OptionParser by ArgumentParser

### PR DESCRIPTION
**Pull request by pinkavaj**
This is almost rework of argument passing for modtool. Lot of thinks are now right in ArgParser by default. There are some changes in behaviour namely:
  * all commands aliases removed
  * remove of duplicit arguments
  * better help

Command aliases are mostly confusing (in mi opinion), so I would prefer to remove them anyway. This tool is not used so often to be worth of spare 4 letters typing and define both 'rename' and 'mv', is it?

Some commands have had both optional and positional argument for something (eg. --block-name, --module-name), they are now only positional arguments, sinc this seems to be most natural.

Each command was tested and works.

PS: It is pain to test this tool, because each time I want to test it I need to reinstall GnuRadio, mey be there is something I missed (please let my now!), but the primary cause is that structure of Python code in GnuRadio breaks the rules for Python modules. ("from gnuradio.modtool import *", but the modtool modules are in directory "gr-utils/python/modtool/" not for example "gr-utils/python/gnuradio/modtool/"). I can open separate thread for this, if desired.

### CODE REVIEW

**Comment by jmcorgan** [comment]
@mbr0wn

**Comment by mbr0wn** [comment]
@pinkavaj Thanks for doing this!

**Comment by mbr0wn** [comment]
@jmcorgan Still reviewing.

**Comment by mbr0wn** [comment]
OK, we can merge this. :+1: 

But let me say this: @pinkavaj, you took a lot of liberties here to make this happen and I would recommend you get some feedback before doing that in the future. You removed the aliases, but who knows what people's favourite alias was? Also, removing the help module is a bit of a shame (and I'm curious why you consider that 'better help'). You're making assumptions about people's preferences without backing that up with some research.

**Comment by pinkavaj** [comment]
This patch is just proposal, I would expect some discussion now.

No trouble in adding help module again, should I do that?.

About the alias and peoples preference, change the command names is trivial, just make some voting or something. Reducing multiple aliases to single command was design goal.

Where to discus it, on malinglist/bug tracker?

**Comment by mbr0wn** [comment]
@pinkavaj Thanks for taking the feedback seriously! As for the help module, we can add that back later. A quick survey on the mailing list would be fantastic.

**Comment by mbr0wn** [comment]
@pinkavaj Looks like there's no one who cares a lot. I suggest we proceed in that case.

**Comment by pinkavaj** [comment]
I think the same.

**Comment by mbr0wn** [comment]
Then let's do it! :+1:

**Pull request merged**
