### PR TITLE
blocks: peak_detector2 is updated with a bug fixed, two additional parameters and optional avg output

### PR DESCRIPTION
**Pull request by fengzhe29888**
Dear all, 

We found a bug in peak_detector2 when we were using it previously, so we tried to fix it. To make the peak_detector2 more functional, we added two more parameters. Besides, we made an optional output of the average for debugging. 

Bug description: 
In the previous block, the stall problem always happens at the end of the noutput_items buffer. When the time "work" function is called, the threshold is passed and a peak is found in the term "i" which "d_peak_ind" is set to. When the input index is close to noutput_items, the for loop may end after setting tmp = d_peak_ind and return tmp-1. Since only tmp-1 is returned, it's possible that tmp -1 is less than noutput_items. So the next time the scheduler may set a very small noutput_items. For example, 2, and the d_found is still true. So the next time the work function is called, it directly goes to the peak finding mode and search for the peak. For noutput_items =2, it will end shortly and it's highly possible that the very first input is detected as the peak, so tmp is set to 0. In that case, what we return now will be tmp-1 = -1 which is impossible. That's why the system stalls. 

You can also check the post below and run the example attached in the post to see the bug.
http://gnuradio.4.n7.nabble.com/Peak-Detector2-stalls-simulation-td51761.html

Bug Fixing:
To avoid such a circumstance, we rewrite the peak_detector2 block in the state machine way that only one state is active everytime "work" is called. We made sure that we'll wait for enough output buffers before we start to locate the peak within the look_ahead. 

Additional parameters:

The additional parameter is the average type. This parameter gives the user two options, to calculate the auto-regressive average all the time or to calculate the average only when the value of input signal is below threshold_factor_rise*average. The first option is more accurate but requires more computational resource, while the second option is more computational friendly but less accurate. The user can decide by the character of their application. 

We were about to add another parameter to enable the "sliding window" option. But it seems there is an unsolved bug. So we decided to drop it for now.

Optional avg output:
When we want to debug the peak_detector2 by adding the average_output port, we have to edit the xml file and rebuild the gnuradio which is inconvenient. So we make the average_out port an optional output by adding one parameter "Debug" in xml file. When "Debug" is enabled, the block will have an additional output port avg_out. When "Debug" is disabled, the avg_out port will be hiden.

QA TEST:

We also modified the qa_test to make the test work for the new peak_detector2 but fails for the old peak_detector2. I think you can also see the bug by running the qa_test with the original peak_detector2. 
 
This is our update to the peak_detector2 which makes it robuster and more functional. Could you check and merge it? 

Best regards,
Zhe

### CODE REVIEW

**Comment by trondeau** [comment]
Looking over the commit, things look fine. I'd like to build and test it out, which I might not get to until next week.

One thing to ask before I get to this, can you help generate more instructive QA code? qa_peak_detector2.py has a single, trivial test case. Any chance you can add more tests for more complex situations? And tests that exercise the difference arguments. If at all possible, a test that might fail on the current implementation but succeed with your fixes. Anything to expand this set of tests would be helpful.

**Comment by fengzhe29888** [comment]
Hi Tom, 

Sure, I'll try to add the QA code with more tests on the features. 

Best regards,
Zhe

**Comment by fengzhe29888** [comment]
Dear  @trondeau 

I attached the qa_test which the original peak_detector2 fails and the new peak_detector2 works. We decided to add only one additional parameter which works nicely and review the other one for future update.  I updated the description above.

Could you check it?

Thanks!
best regards,
Zhe

**Comment by trondeau** [comment]
Zhe,

I have other examples where this new peak detector doesn't work. Just putting in a sine wave against it shows bad results.

The main problem is that peak detectors are really only developed for specific scenarios, so we write them for those scenarios, but they don't generalize well. We probably should not have a block named "peak_detector" (and notice that there are two of them for different purposes). These should be specific blocks written and named to solve their specific problem. I think we should rename these in 3.8 to avoid further confusion about what they do and can do.

For your version, I suggest you keep that one in an OOT module of your own so you can use the functionality yourself where you need it.

**Pull request closed without merging**
