### PR TITLE
Add ATSC transmitter block definitions and flow graph.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Comment by jmcorgan** [comment]
Ron, this is great, but gr-atsc has been deprecated in favor of the new component, gr-dtv.  It would be very useful to not only see the corresponding patch for gr-dtv, but also, the optimized transmitter flowgraph you've come up with.  That may required changes to the blocks themselves.  If you do this, please break it up into small, successive commits.

Thanks again.

**Comment by drmpeg** [comment]
Would you like the TX blocks to be cleaned up a little to match what's in gr-dtv, or just copied over from gr-atsc?

**Comment by jmcorgan** [comment]
Ideally they'd be converted over to the new 3.7 code layout, etc., and "look" like they are an integral set with the RX blocks.  But more important is any actual performance optimizations you've might have made when you were using the gr-atsc blocks.

I had planned to return to this fairly soon, getting you involved, so I think we can see what you come up with and iterate, any, if needed.  Thanks.

**Comment by drmpeg** [comment]
Okay, I'll volunteer for this effort. You can close this pull request if you want.

**Comment by jmcorgan** [comment]
I forgot to mention that the whole purpose of the gr-atsc -> gr-dtv transition was to be able to make changes as needed without breaking user code.  So a mechanical conversion from gr-atsc, while useful, would miss out on any opportunities to improve things.  Most of the fairly major changes to the receive pipeline were based on reimplementing things when possible using blocks in gr-analog or gr-filter, and rethinking the signal flow based on modern I/Q SDRs.

**Pull request closed without merging**
