### PR TITLE
Finally merging next into master

### PR DESCRIPTION
**Pull request by marcusmueller**

### CODE REVIEW

**Comment by noc0lour** [comment]
Looking at the errors in the `F28` builder: somehow QT5_WRAP_CPP generates wrong `*.cpp_parameters` files which are fed to `moc`. Specifically it inserts an additional slash in front of the path to the source files which apparently is commenting out the line `//`.

Qt5 version: 5.10.1
cmake version: 3.11.2

I actually couldn't find the QT5_WRAP_CPP definitions.

**Comment by noc0lour** [comment]
Update: It looks like this is just a problem of `moc` stalling on the first build and depending builds failing after that. cmake modules and generated files seem to be good enough now. Just a matter of `moc` not working in this particular case ...

**Comment by noc0lour** [comment]
So, something is strange: testing with same (or greater version) on my local hardware does not impact the build: 
```
╭─ /mnt/compile/gnuradio2/build   merge_next  
╰─ moc --version                                                                         ✔  23:25:16 
moc 5.11.1
╭─ /mnt/compile/gnuradio2/build   merge_next  
╰─ cmake --version                                                                       ✔  23:28:55 
cmake version 3.12.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
I'd say this is a "bad" version in F28 and will resolve after an update (╯°□°)╯︵ ┻━┻.

**Comment by noc0lour** [comment]
Can't say what, but something is :fish:y with Fedora and Qt5....

**Comment by noc0lour** [comment]
@marcusmueller CI is again up to building F28 & F29, only failing `qa_constellation` due to timeout requirements now.

**Comment by marcusmueller** [comment]
Awesome!

On 8 September 2018 02:41:39 GMT+02:00, Andrej Rode <notifications@github.com> wrote:
>@marcusmueller CI is again up to building F28 & F29, only failing
>`qa_constellation` due to timeout requirements now.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gnuradio/gnuradio/pull/2001#issuecomment-419599413

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by smunaut** [comment]
Just merge it already ... then we'll be forced to fix all the problems.

**Comment by noc0lour** [comment]
Agree with @smunaut , this PR is actually stalling fixing outstanding bugs etc.

**Comment by 777arc** [comment]
Plus then we can spend the rest of grcon fixing issues :grin:

**Comment by michaelld** [comment]
Builds on OSX (with a slight patch for the new MP code)! +1 for me to merge & we'll work out any not-already-discovered issues post-merge.

**Comment by marcusmueller** [comment]
So... there's simply too much state in `next` that's broken, and although I *really* wanted to rebase next onto master, this is not humanly possible for someone with an occasional demand for sleep, nor for someone up to the end of the coolest conference on the face of the earth.

So, after inspecting the commits added since we've last talked, I've decided to just perform a non-ff merge.

Let us never, ever, ever, ever have a development branch diverge from master for 4+ years. Thank you.

**Comment by michaelld** [comment]
Amen, brother Marcus!

**Comment by noc0lour** [comment]
:tada:

**Comment by smunaut** [comment]
Well it's not merged yet right ?

**Pull request merged**
