### PR TITLE
Change vlen variables to unsigned datatype. Fixes #1459

### LINKED ISSUE #1459: integrate has `int vlen` parameter; should be `unsigned`; check other block's
There's a lot of blocks that take `vlen` parameters. This is a reminder to myself (please assign to me) to go through the tree and identify all places where we should've used unsigned int instead of int.

This might look cosmetic (it's unlikely someone would want a vector half of MAX_INT in size, and the scheduler and buffer allocator might reasonably break on that), but it actually gives compiler warnings when trying to parameterize a block with a signed vlen, so it's actually a code quality issue.

### PR DESCRIPTION
**Pull request by sbmueller**
Hi, I had a look at an issue from last year's hacktoberfest which did not seem to be resolved so far. In accordance with GREP 11 I did some code cleanup on the files I touched.

### CODE REVIEW

**Comment by noc0lour** [comment]
@sbmueller Hi, thanks for the effort. Unfortunately The first (and most important part) of GREP 11 hasn't been implemented: Reformatting the full source tree. Thus mixing formatting & bug fixes is undesirable. Sorry for not having been able to have the reformatting rampage done. According to @marcusmueller the reformatting may take place once 3.8 is released.

**Comment by sbmueller** [comment]
@noc0lour 
> Thus mixing formatting & bug fixes is undesirable.

So does that mean I should split formatting and bug fixing commits or do no formatting changes at all?

@michaelld I tried to solve #1459 here. Don't know what happened to the whitespaces. It should be spaces, of course. I will follow up soon.

**Comment by noc0lour** [comment]
Personally I'm fine with separate commits with the formatting in place. We shouldn't clutter history with a lot of formatting commits though. The idea is to have a big formatting commit which everyone could skip.

**Comment by marcusmueller** [comment]
Very nice indeed. Note, however, that this **intentionally** introduces a lot of new warnings to our build. 

We'll need to fix those sooner or later; these are exactly the reason I wanted this to happen. Now, we're notified of any place where we might be doing something stupid.

**Pull request merged**
