### PR TITLE
fec: fix ber_test.grc flowgraph

### PR DESCRIPTION
**Pull request by jdemel**
This flowgraph ('ber_test.grc' in gr-fec/examples) was broken.
1. a variable 'puncpat' was missing. Thus, the flowgraph didn't run out-of-the-box.
2. Even with very high SNR it had quite some bit errors. (replaced unpacked-to-packed by pack-k-bits)

Now it should run and work without errors. So others can just use it as a reference.

### CODE REVIEW

**Comment by trondeau** [comment]
Looks good. Should be applied against maint, though.

**Comment by jdemel** [comment]
So this pull request should be reopened to be pulled against maint?

**Comment by trondeau** [comment]
You certainly can do that, and it would make it easier for us during the merge process, but you don't really have to. @jmcorgan or I would just cherry-pick this, anyways.

**Comment by trondeau** [comment]
cherry-picked onto maint.

**Pull request closed without merging**
