### PR TITLE
grc: add missing tags to metainfo file

### PR DESCRIPTION
**Pull request by AsciiWolf**
## Description
- Add developer name tag
- Add OARS metadata tag

Both are now required by many AppStream parsers.

## Which blocks/areas does this affect?
None.

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
We literally talked about this: https://github.com/gnuradio/gnuradio/pull/5615#issuecomment-1073785815 and will not merge this.

**Comment by marcusmueller** [comment]
Also, claiming that GNU Radio was constructed by a homogeneous community is a bit of a statement you're making there without having asked the project itself. 

Personal remark: Note that I really don't like your project's attitude that metadata needs to fit the ideas of the metadata-consuming application on how the world ought to work, instead of using the metadata to allow projects to represent their reality and then make the consuming applications, whose whole purpose is exactly that, reflect that reality to their users.

**Comment by AsciiWolf** [comment]
Oops, I forgot about the OARS metadata discussion under previous PR. Sorry! Fair points, I agree with you. And OARS is currently compulsory only for Flatpak apps on Flathub. I have added it only to make the metadata more future-proof.

However, I would still like to add the developer_name tag if possible, because that one is a de facto standard thing (although not compulsory yet) for AppStream metadata nowadays. It helps categorize and search the software in GUI software centres and it makes the overall app details page look good and complete.

I was not sure who the developer of GNU Radio actually is. The "GNU Radio Community" is stated on the GNU Radio [Wikipedia page](https://en.wikipedia.org/wiki/GNU_Radio) while on the GNU Radio [homepage](https://www.gnuradio.org), there is a "Radio project" copyright.

Therefore, I would like to ask you (@marcusmueller) to consider re-opening this ticket. I will remove the OARS tag and fill the developer_name tag with the actual correct developer name provided by you.

Thanks!

**Comment by AsciiWolf** [comment]
I have made a [new PR](url) (without the OARS metadata). Feel free to review it. Thanks!

**Comment by AsciiWolf** [comment]
I have made a [new PR](https://github.com/gnuradio/gnuradio/pull/7479) (without the OARS metadata). Feel free to review it. Thanks!

**Pull request closed without merging**
