### PR TITLE
Band pass filter validates low/high frequency and transition width

### LINKED ISSUE #2777: GRC38 Band pass filter does not validate parameter
When low/high frequency or transition width is not fill in (left blank), GRC does not detect the missing parameters and generates invalid Python code such as:

      self.band_pass_filter_0 = filter.fir_filter_ccf(
            1,
            firdes.band_pass(
                1,
                samp_rate,
                ,
                ,
                1000,
                firdes.WIN_HAMMING,
                6.76))

*i.e.* several comma separator in a row.

### PR DESCRIPTION
**Pull request by cbdonohue**
Added some minimal parameter validation for band pass filter
fixes #2777

### CODE REVIEW

**Comment by drmpeg** [comment]
Sorry, but this doesn't work for a complex band pass filter with negative frequencies.

An example of band pass filter with negative frequencies usage is an SSB transmitter. The lower sideband (LSB) mode is generated with a negative frequency band pass filter.

image

**Comment by cbdonohue** [comment]
Thanks for the feedback!
I just pushed another change to my branch that allows for complex band pass filters. cbdonohue/gnuradio@2ba39c14f026ff22362ae905143be1b361e60e3e

**Comment by primercuervo** [comment]
@mormj based on your feedback, would you mind checking if this check is now valid?

**Comment by drmpeg** [comment]
@primercuervo I guess you meant me instead of @mormj. I've tested the patch, and it mostly works. Unfortunately, the two asserts that are trying to make sure something is entered:
```
-   ${ low_cutoff_freq }
-   ${ high_cutoff_freq }
```
also disallow having the value 0, which is valid.

**Comment by primercuervo** [comment]
@drmpeg you are absolutely right that I meant you! I'm sorry for the spam this might have caused. Thanks for checking that.

@cbdonohue mind having a look at the assert of 0?

**Comment by cbdonohue** [comment]
> @drmpeg you are absolutely right that I meant you! I'm sorry for the spam this might have caused. Thanks for checking that.
> 
> @cbdonohue mind having a look at the assert of 0?

I'll check it out

**Comment by cbdonohue** [comment]
The assert statements are eventually sent to the builtin **eval()** method. I think what is happening is that it returns **False** if it is evaluating **0**. 

The solution for now might be to remove:
```
-   ${ low_cutoff_freq }
-   ${ high_cutoff_freq }
```

 add default values to the **low_cutoff_freq** and **high_cutoff_freq**. 
```
-   id: low_cutoff_freq
    label: Low Cutoff Freq
    dtype: real
    default: '0'
-   id: high_cutoff_freq
    label: High Cutoff Freq
    dtype: real
    default: '1'
```

Another possible solution is to modify the template python code. We could check for empty values when populating the lower level filter function parameters.

**Comment by mbr0wn** [comment]
Looks like all the comments have been addressed; merging manually (commit message needed cleanup).

**Pull request closed without merging**
