### PR TITLE
BUGFIX: Removed persistent logging to console present in correlate_access_code_bb_impl.cc

### PR DESCRIPTION
**Pull request by LaughingCabbage**
Removed persistent logging to console present in packet decode as a result of new_flag calls in correlate_access_code_bb_impl.cc. Test flow: File source -> packet encoder -> dpsk mod -> dpsk demod -> packet decoder -> time sink.

### CODE REVIEW

**Comment by LaughingCabbage** [comment]
@jmcorgan would you like me to repull this into maint? Really, the packet decode block is pretty useless without removing the logging.

**Comment by jmcorgan** [comment]
I'm trying to understand why this is a problem now and not before.

**Comment by LaughingCabbage** [comment]
@jmcorgan So I've just retested running a build off maint and I have no issue. However, looking at the main branch again, it appears that the 'if #VERBOSE' directive is missing from the main branch.

**Comment by jmcorgan** [comment]
Can you highlight the two areas of code on each branch?

**Comment by LaughingCabbage** [comment]
@jmcorgan [The line from the master branch](https://github.com/gnuradio/gnuradio/blob/master/gr-digital/lib/correlate_access_code_bb_impl.cc#L111) and [the line from the maint branch](https://github.com/gnuradio/gnuradio/blob/maint/gr-digital/lib/correlate_access_code_bb_impl.cc#L112)

**Comment by jmcorgan** [comment]
Ok, that's strange as master is usually a strict superset of maint. I'll look into it.

**Comment by jmcorgan** [comment]
Ok, this was a result of #1292. I'm merging this, but actually snipping out the code altogether.

**Pull request merged**
