### PR TITLE
uhd: Updates to UHDApp and siggen apps

### PR DESCRIPTION
**Pull request by mbr0wn**
- Added time source option
- Fixed bug where sources where not applied to all motherboards
- Various formatting cleanups (better Pylint score)

### CODE REVIEW

**Comment by mbr0wn** [comment]
One sec, seems like I may have missed a bug there.

**Comment by mbr0wn** [comment]
OK, fixed that.

**Comment by jmcorgan** [comment]
You've mixed new features and bug fixes here.

**Comment by jmcorgan** [comment]
This was cherry-picked onto master.

**Pull request closed without merging**
