### PR TITLE
 modtool: added gr_modtool help command that should work exactly like gr_modtool --help

### LINKED ISSUE #7310: `gr_modtool help` should consistently output what `gr_modtool --help` does
### Feature Description

s. title.

### Feature Urgency

low (just an idea)

### More Information
This would be a nice first modification for someone who wants  to get into improving the devops and user-facing Python tooling that GNU Radio comes with.

### PR DESCRIPTION
**Pull request by Mindslayer001**
## Description

This pull request introduces a new `gr_modtool help` command that functions equivalently to `gr_modtool --help`. This addition improves consistency and user experience by integrating the help functionality into the `gr_modtool` CLI in a more intuitive way. The implementation uses the `click` library and the `subprocess` module to execute the existing `gr_modtool --help` command and display its output.

This change resolves issue #7310.

---

## Related Issue

Fixes #7310.

---

## Which blocks/areas does this affect?

This change affects the `gr-modtool` CLI utility, specifically by adding a new command (`gr_modtool help`). It does not impact core functionality but enhances the usability of the CLI.

---

## Testing Done
- Automated tests were executed during the build process from the modified source code, and all test cases passed successfully.
- Manual testing was performed to ensure the following:
  1. The `gr_modtool help` command outputs the same content as `gr_modtool --help`.
  2. Errors are correctly handled, and appropriate error messages are displayed when the `gr_modtool --help` command fails.
  3. The `help.py` script integrates seamlessly with the `gr-modtool` build system.

- Testing Environment:
  - Operating System: Linux (Ubuntu 22.04)
  - Python Version: Python 3.x
  - GNU Radio version: Main branch, built from source.

---

## Checklist

- [x] I have read the [[CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md)](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit.  
- [ ] I [[have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed).  
- [x] My code follows the code style of this project. See [[GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md)](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).  
- [x] I have updated [[the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation)](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.  
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by Mindslayer001** [comment]
Sure! Here's a more natural and conversational version of the message:

Hi @marcusmueller,

I’ve made some updates to the PR based on your feedback. When you get a chance, could you please take another look? Thanks for your help!

**Comment by Mindslayer001** [comment]
hey @marcusmueller , It has been 4 days since my pr. I have been wondering is there any wrong in my work? Hope you have spare some time to guide me to complete my pr.

**Comment by marcusmueller** [comment]
What happened: Volunteers on Christmas break. Please understand that we don't do maintenance for a living and hence need some time to review code.

**Comment by Mindslayer001** [comment]
My bad @marcusmueller , I totally forgot about Christmas. The place I live don't celebrate much on Christmas. 

Merry Christmas btw

**Comment by marcusmueller** [comment]
No problem! Just be aware that we try to be as responsive as possible, but even without holidays, this is a pure volunteer project – us not being able to review things for a couple of days is sadly not rare. There's only so much time we can throw around!

**Comment by willcode** [comment]
@Mindslayer001 the MinGW error is not due to your PR. Nothing you need to do. The error was fixed on `main` earlier today, but your PR is still based on the version of `main` before the fix.

**Comment by Mindslayer001** [comment]
@willcode  I changed my pr version to fixed main version. Please run  the tests again.

**Pull request merged**
