### PR TITLE
Use C++11 for range loops, and some more const

### PR DESCRIPTION
**Pull request by ThomasHabets**

### CODE REVIEW

**Comment by michaelld** [comment]
Holy moly ... this is awesome! Thank you for expanding the scope of that prior PR!

The code reads very nicely ... I really like the auto C++11 style iterators!

You've had at least a PR merged into GR before, from a quick search of the GIT commit history. Do you hopefully have a CLA (code license assignment) in place already?

**Comment by michaelld** [comment]
There are enough changes it'll take a bit to test & review everything here. Thanks for your patience!

**Comment by ThomasHabets** [comment]
Oh, you have one of those. :-(

I don't think I have a CLA already. Where can I find the form? I need to run this past the Google opensource people.

**Comment by michaelld** [comment]
> Oh, you have one of those. :-(
> 
> I don't think I have a CLA already. Where can I find the form? I need to run this past the Google opensource people.

Yes, we have one of those :(  Send an email to Ben Hilburn bhilburn@gnuradio.org ... tagging him here so he knows @bhilburn

**Comment by ThomasHabets** [comment]
Google has a corporate-level CLA with FSF that covers this. I'm contributing as a Google employee (they owning everything I do by default. This is me contributing on my own time but with their blessing).

**Comment by bhilburn** [comment]
Confirmed, clear to merge

**Comment by michaelld** [comment]
Excellent! CI testing looks good & the code reads nicely. Let us do some testing on our local host computers.

**Comment by ThomasHabets** [comment]
I realise code review takes a while (I do it myself). But is there an ETA on this?

I'd prefer not to pipeline my changes, so while I'm not promising a flood of changes, getting this merged is kinda holding me back looking for the next thing.

**Comment by michaelld** [comment]
@ThomasHabets Sorry for the delay ... clearly this PR slipped through the cracks!

**Comment by michaelld** [comment]
MLD summary: code changes look good; CLA in place; CI all passes; 1 review and plenty of time for others to review (so, a "timeout" of sorts given the other positive conditions). Merging.

**Pull request merged**
