### PR TITLE
grcqt: Add double click to add block and simplify tests

### PR DESCRIPTION
**Pull request by cafeclimber**
## Description
This PR adds the ability to double-click on a block to add it to a flowgraph. With this, it simplifies many of the qt-specific tests, focusing on making them standalone, and easier to read.

## Related Issue
None

## Which blocks/areas does this affect?
GRC (Qt)

## Testing Done
The `tests/test_qtbot.py` tests were run and passed, and individual testing was done to ensure double click works

## Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
@cafeclimber did you mean for your email address in the signoff to be "gmaill" 
`Signed-off-by: Bailey Campbell <baileycampbell1990@gmaill.com>`

**Comment by cafeclimber** [comment]
> @cafeclimber did you mean for your email address in the signoff to be "gmaill" `Signed-off-by: Bailey Campbell <baileycampbell1990@gmaill.com>`

I did not...wow that has been my git config for a while too...oof.

**Comment by willcode** [comment]
Not that we use it for anything. Sometimes it ends up in a list of contributors.

**Comment by cafeclimber** [comment]
@willcode Do I need to amend the commit or anything?

**Comment by willcode** [comment]
No - just pointing it out.

**Review by haakov — CHANGES_REQUESTED** [review]
This is great! I had to increase some wait times to get it to run. Apart from that, I approve :)

**Comment by cafeclimber** [comment]
Sweet :) I'll make those quick edits. I'm the future might try to do more direct signal sending instead of clicks to avoid this issue but that's a later problem

**Pull request merged**
