### PR TITLE
cmake: Error out if Log4Cpp is not found

### PR DESCRIPTION
**Pull request by noc0lour**

### CODE REVIEW

**Comment by michaelld** [comment]
Why not just make the FindPackage REQUIRED? The end result is the same & the code is simpler ...

**Comment by noc0lour** [comment]
@michaelld True, can you test that?

**Comment by michaelld** [comment]
@noc0lour sure NP

**Comment by michaelld** [comment]
+1 from me; let's merge this!

**Comment by mbr0wn** [comment]
@michaelld approves.

**Pull request merged**
