### PR TITLE
Key filter zmq

### LINKED ISSUE #2236: gr-zeromq  subscriber block does not support filtering by key
The gr-zeromq subscriber block does not support subscribing to a specific key in a multi-part message. 
This is useful if different messages are transmitted to the same port.

### PR DESCRIPTION
**Pull request by talih0**
Fixes #2236

### CODE REVIEW

**Comment by talih0** [comment]
I just realized this will break tag propagation when the key is enabled. I need to fix and update the pr

**Comment by marcusmueller** [comment]
@talih0 following your last comment, I tagged this "Don't merge" for now. Is that correct? Is there something you need help with?

**Comment by talih0** [comment]
@marcusmueller, 
I pushed the updated the version that should fix the problem. But, I'd like to add a qa test for the new commit. 

For the qa test, I want to create the following zmq multi-part message:
["key",  serialized_tag + payload1, payload2, payload3, ...]

Could you advise on the best way to serialize a tag? I saw you use the function gen_tag_header in the cpp code, but I don't think it's built with swig. Should I add I try to add it to the swig build or would you recommend another approach?

**Comment by talih0** [comment]
Hi @marcusmueller, 
I put together a publish/subscribe qa test with both keys and tags enabled. Everything is working on my end.

**Comment by talih0** [comment]
@marcusmueller, it would also be interesting to support a proxy for the publish nodes (see Fig. 13 http://zguide.zeromq.org/page:all )
Let me know your thoughts. I can work on this if you feel it would be useful for the community.

**Comment by devnulling** [comment]
@talih0 Can you rebase this onto the current master? 

Also, IMO having support for a proxy would be useful, but it should go into a separate issue/PR.

**Comment by talih0** [comment]
@devnulling I'll have a look what's been done recently and rebase

**Comment by mbr0wn** [comment]
@talih0 do we have a CLA from you?

**Comment by mbr0wn** [comment]
@talih0 Thanks for this PR and sorry there hasn't been a lot of action on it recently. Two things need to happen before we can review and finalize:
- We need to figure out if you have a CLA with us, and
- You need to rebase this. Likely we have issues with formatting. If that's the case, run clang-format over your commits to easily rebase them.

I'll close this PR for now, until those two issues are resolved. If you have already submittted a CLA with us, just let us know. If not, please reach out to ben at gnuradio dot org to get that going.

A first scan of this PR was positive. Looks like it's going in the right direction, code looks sensible.

**Comment by talih0** [comment]
@mbr0wn, yes, I did a CLA in the past

**Comment by mbr0wn** [comment]
Thank you! That's great. Can you please rebase this onto master? If you do that and force-push your branch, you can reopen the PR. Many thanks!

**Comment by talih0** [comment]
@mbr0wn I've rebased to master, could you re-open the PR pls

**Comment by talih0** [comment]
I created a new pull request

**Comment by mbr0wn** [comment]
Thanks a lot!

**Comment by mbr0wn** [comment]
Continued here:
https://github.com/gnuradio/gnuradio/pull/3068

**Pull request closed without merging**
