### PR TITLE
prefs reader misparses '#' anywhere but start-of-line -> rm inline comments

### PR DESCRIPTION
**Pull request by marcusmueller**

### CODE REVIEW

**Comment by marcusmueller** [comment]
@jmcorgan no, this is not a New Feature, this is a bugfix-only patch

**Comment by jmcorgan** [comment]
Right, but it has to go on master so I tagged it that way.

**Comment by marcusmueller** [comment]
Well, current release is broken because of these files; why has this to
go on master?

**Comment by jmcorgan** [comment]
Ah, was confused by the PR off master instead of maint.  Cherry-picked.

**Pull request closed without merging**
