### PR TITLE
Fixes for YAML files

### PR DESCRIPTION
**Pull request by haakov**
- [x]  `if not label` causes an error in several widgets
- [x]  Message edit box, Chooser and Tab Widget are creating errors
- [x]  QT Sink: `QObject.connect()` is not implemented in PyQt5
- [x] GRC saves corrupted .grc files (`n\nconnections`)
- [x] Some filter blocks have invalid `make` strings
- [ ]  Some QT sinks have callbacks with undefined variables (what's `${which}` ?)
- [ ] Error evaluating value of variable blocks

### CODE REVIEW

**Comment by jmcorgan** [comment]
@skoslowski when you work on this can you collapse the final version to a single commit?

@haakov thanks!

**Comment by skoslowski** [comment]
@haakov Thanks for seeing this through. Like Johnathan suggested we will probably squash this down to one or two commits. Ideally I'd like to have one, that contains all the auto-generated ones, and one that holds the ones you had to manually add in stuff. You can either do it directly here in the PR or I'll squash it when merging. I suspect qtgui and usrp as well as GRC's "own" blocks needed manual editing?

**Comment by haakov** [comment]
Alright, done :)

**Comment by skoslowski** [comment]
Perfect

**Comment by skoslowski** [comment]
status: merged this locally and removed the auto-converter. Will hunt down some minor issues before I push the merge

**Comment by skoslowski** [comment]
fixups done, implemented to json-based cache from the converter. pushed to my staging branches.

One minor issue with the yaml files: Do we want to keep that awkward syntax for the top-level category, e.g. [module]/cat1/cat2, or should this be split-off into a separate setting? (I tend to the later)

**Comment by noc0lour** [comment]
Testing with https://github.com/noc0lour/gnuradio/tree/next3 locally shows issues with most of the qtgui blocks.  @haakov Did you generate some skeleton code for the qtgui blocks?

**Comment by haakov** [comment]
I think I used the same procedure for all of the qtgui blocks: I removed the "make" code from the block, passed the rest of the block through the auto-converter and manually edited and added the missing make code. Can't remember any problems with them, though. What issues exactly are you seeing with the blocks?

**Comment by noc0lour** [comment]
Since GitHub can't handle this PR at all I pulled this from the Waterfall YML:
```
-   id: alpha1
    label: Line 1 Alpha
    category: Config
    dtype: float
    default: '1.0'
    hide: ${ ('part' if int(nconnections) >= 1 else 'all') }
-   id: label2
    label: Line 2 Label
    dtype: ''
    hide: ${ ('part' if int(nconnections) >= 2 else 'all') }
-   id: color2
    label: Line 2 Color
    dtype: ''
    hide: ${ ('part' if int(nconnections) >= 2 else 'all') }
```

Instead of `dtype: ''` it should contain the correct dtype and a sensible default value.
Otherwise this:
```
        labels = [${label1}, ${label2}, ${label3}, ${label4}, ${label5},
                  ${label6}, ${label7}, ${label8}, ${label9}, ${label10}]
        colors = [${color1}, ${color2}, ${color3}, ${color4}, ${color5},
                  ${color6}, ${color7}, ${color8}, ${color9}, ${color10}]
        alphas = [${alpha1}, ${alpha2}, ${alpha3}, ${alpha4}, ${alpha5},
                  ${alpha6}, ${alpha7}, ${alpha8}, ${alpha9}, ${alpha10}]
```

will render to:

```
        labels = ['', , , , ,
                  , , , , ]
        colors = [0, , , , ,
                  , , , , ]
        alphas = [1.0, , , , ,
                  , , , , ]
```

Furthermore the `import sip` is swallowed by the generator along the way, thus `import sip` missing in the generated Python file.

**Comment by noc0lour** [comment]
Qt Time Sink had even more erros when I just drag & dropped it into GRC.

**Comment by haakov** [comment]
Right! This is undoubtedly caused by the auto-converter not converting <base_key> from the XMLs :smile: The time sink has styles and markers and such as well, so that makes sense. I'll look into it.

**Comment by noc0lour** [comment]
Awesome! Thanks a lot :) I'll keep testing and probably will fix bugs in GRC along the way.

**Comment by haakov** [comment]
Okay, so I have fixed the other issues you pointed out (and fixed a couple additional typos), but I still find the `set_color()` and `set_title()` callbacks a bit puzzling. They are present in the Waterfall, Histogram, Time, Time Raster and Constellation sinks. I can't quite get my head around their purpose and how they have worked earlier. 

Is the `set_title()` callback supposed to be `set_line_label()`?

**Comment by noc0lour** [comment]
I have rebased the remaining commits locally and could force push them on this PR if you don't mind @haakov ?

**Comment by marcusmueller** [comment]
@haakov is this now already part of `next`?

**Comment by haakov** [comment]
@noc0lour I don't mind at all, go ahead :)

**Comment by marcusmueller** [comment]
Ah OK, I see :)

**Comment by noc0lour** [comment]
I rebased & force pushed & changed the base branch: https://ci.gnuradio.org/buildbot/#/builders/4/builds/692

Apparently BuildBot still thinks python3 is the base branch

**Comment by haakov** [comment]
- [x]  `if not label` causes an error in several widgets
- [ ]  Some sinks have callbacks with undefined variables (what's `${which}` ?)
- [ ]  QT Sink: `QObject.connect()` is not implemented in PyQt5
- [ ]  Message edit box, Chooser and Tab Widget are creating errors

**Comment by marcusmueller** [comment]
Closed by merging superset #1915

**Pull request closed without merging**
