### PR TITLE
swig block.i: add void set_output_multiple(int multiple)

### PR DESCRIPTION
**Pull request by willcode**
Resolve https://github.com/gnuradio/gnuradio/issues/1757

### CODE REVIEW

**Comment by dkozel** [comment]
Hi @willcode Sorry for the delay here. I've just triggered a rebuild of the CI system. Did you have a test or application which used this function in Python?

**Comment by willcode** [comment]
@dkozel - no application, this is just a missing Python wrapper pointed out/requested by a user.

**Comment by marcusmueller** [comment]
Nice! Thanks.

**Comment by marcusmueller** [comment]
Still, if you'd have a separate test case for this, and be it really minimal, I'd like to have that, too!

**Pull request merged**
