### PR TITLE
Go back to 3.7 port naming scheme.

### PR DESCRIPTION
**Pull request by dl1ksv**
See discussion in #2540

### CODE REVIEW

**Comment by michaelld** [comment]
Hmmm ... does this change the default label to -always- be just "in" or "out", regardless of how many I or O message ports there are? I'm no expert in how message ports are named in GRC ...

**Comment by dl1ksv** [comment]
As far as I understand : 
In the yaml description ports can be named by id or use an automatic generated name by grc. 
In 3.7 automatic generated stream input  ports are named in0, in1, in2, ... while in 3.8  they are named in00, in01, in02 ... . As long as there are no port named in10, in11, in12 I see no advantage in this naming scheme. But there are no problems to do connections as there are referenced by the number of the port.

Message ports are differently handled.The ports are addressed by name, which is hardcoded in the block code.( As far as I can see).   Here again yaml description can use id or generate the port name by grc.

In 3.7 the generated name (input ) port name is in while in 3.8 the name is in0. I could not detect any block that contained more than one automated named port.

Summary:
I don't no why there is a new port naming in 3.8 and I can't any advantages in the moment.

So before proposing further fixes I need a decision how (automatic) port names should be generated in the future:

message: in / out or in0 / out0 

streams: in0,in1,in2, ../out0,out1,out2,..    or in00, in01, in02.... /out00 , out01,out02,......

I'd prefer message in/out and streams in0,.. /out0 ..

which would be handled by this pr.

**Comment by mbr0wn** [comment]
I'm in favour of this PR. Will merge if there are no complaints.

**Comment by michaelld** [comment]
+1 from me

**Comment by mormj** [comment]
Tested out this PR - will require many of the example grc files to be fixed up, but it works and appears to generally fix the problem.

**Comment by mbr0wn** [comment]
Merging manually.

**Comment by mbr0wn** [comment]
@dl1ksv Can you go through your issues and PRs and see which ones are still required after this change?

**Comment by dl1ksv** [comment]
@mbr0wn All port related issues I know are fixed. #2494 and #2557 still remain.

**Pull request closed without merging**
