### PR TITLE
WIP: QT: Convert the gr_plot_qt application to use pyqtgraph

### PR DESCRIPTION
**Pull request by btashton**
Right now this is using a mixture of QwtPlot and pyqtgraph.  The time plot is using pyqtgraph and the other plots have been left using QwtPlot.  I would like some feedback on the time plot before converting the other two.

### CODE REVIEW

**Comment by btashton** [comment]
I think the main missing feature is rectangle zoom instead of panning.
http://www.pyqtgraph.org/documentation/graphicsItems/viewbox.html#pyqtgraph.ViewBox.setMouseMode

**Comment by mbr0wn** [comment]
Can you post some screenshots here? And can anyone just run the current version?

**Comment by btashton** [comment]
select
sinplot
white_background

Here are a few showing some of the functionality.  Something is a little funky with the symbol syle (circle, triangle, etc...)

**Comment by btashton** [comment]
I thought the spectrogram was going to be a little harder, but it looks trivial via ImageItem.

**Comment by btashton** [comment]
Here are some of the old version, looks like I'm missing the legend 
old_select
sin_old

On the new one we get some cool features with right click like exporting the plot as images or csv data.
new_rightclick

**Comment by btashton** [comment]
Yeah, Python 3 won't work because it still has PyQwt code in it. Tomorrow I'll try and get the rest of it converted over.  As for the matplotlib bit I think that's for the other plotting utilities.  The with the pyqtgraph plot if you right click it you can export matplotlib code. I would say if we do that we should just put all that functionality into this tool so there is a single plotting tool and not the 15 we have now in mixed States of function

**Comment by noc0lour** [comment]
If I see this correctly this PR is supersed by https://github.com/btashton/grplot and we might merge the utility back in-tree?

**Comment by noc0lour** [comment]
Or keep it in a separate project but maybe keep in in the `GR` org?

**Comment by btashton** [comment]
I was going to get back to this after the new year. But yeah I'm open to whatever, if we move it in tree I'll need to change the tests from pytest and do the cmake stuff.

**Comment by noc0lour** [comment]
I'm open for any. Basically I'm mainly concerned on how to get people to use & embrace it.

**Comment by mbr0wn** [comment]
Please, please can we merge your tools into GNU Radio and replace all the crap we have!

**Comment by btashton** [comment]
I have not forgotten.  Just trying to wrap up an FPGA project that I was working on over the holidays that is taking longer than expected (shocking I know).  I probably could get a MR together this weekend.

**Comment by noc0lour** [comment]
Fixes another part of #1634.
@btashton how are things?

**Pull request closed without merging**
