### PR TITLE
Style and indentation cleanup for YAML blocks (WIP)

### PR DESCRIPTION
**Pull request by haakov**
Contains fixes from recent GitHub issues. Also contains some further cleanup of YAML files, mostly getting rid of `\n` and `\t` from the `make` field.

### CODE REVIEW

**Comment by haakov** [comment]
Haha well said!

So, about 2/3 of these 68 (as of Aug 16) changed files are cosmetic/style changes, while the rest are actual functional fixes.

**Comment by marcusmueller** [comment]
I've review cherry-picked the explicitly mentioned commits in #1962. You can (but don't have to) remove them here. There's been a bit of selective picking  `${}` changes from the larger cleanup commit, just act as if these don't happen – they shouldn't be leading to merge conflicts, in any case.

**Comment by marcusmueller** [comment]
The idea was that I separate out the bugfixes, so that this can in the end be squashed into one "fixed style, indentation, whitespace, whatevs of YAML files" commit, which doesn't hide bug fixes.

**Comment by haakov** [comment]
Okay great! Thanks, I probably should have separated them to begin with :+1:

**Comment by marcusmueller** [comment]
manually rebased and merged. Thank you!!

**Pull request closed without merging**
