### PR TITLE
modtool: Use c++17 in template to match top level CMakeLists.txt.

### PR DESCRIPTION
**Pull request by drmpeg**
Signed-off-by: Ron Economos <w6rz@comcast.net>

### CODE REVIEW

**Review by mormj — APPROVED** [review]
This is a good change regardless of std::any (but necessitated by that change).

**Comment by drmpeg** [comment]
Should I change the commit message? Something like "gr_modtool template should match top-level CMakeLists.txt".

**Comment by mormj** [comment]
Up to you - would probably be more accurate since std::any might get deferred.

**Comment by drmpeg** [comment]
I think reverting std::any is a good idea. It's clearly more pain to users than usefulness in the tree.

**Comment by mormj** [comment]
My bad on that one - premature merge before realizing all the ramifications

**Comment by drmpeg** [comment]
No worries. It's pretty difficult to be prescient. Maybe some sort of quick gr_modtool test in the CI? Perhaps just newmod, add, bind. I'm not sure that's even possible.

**Pull request merged**
