### PR TITLE
modtool: Fix bug where gr_modtool rm messes up the C++ QA section

### PR DESCRIPTION
**Pull request by mbr0wn**
This bug was originally reported by chenzhubattg. Previously, C++
QA files weren't properly removed from lib/CMakeLists.txt, such
that the path to the file was left in the CMake file, making it
invalid.
This fixes a bug in the cmake_editor.py module, which previously
had a too lenient regex.

### CODE REVIEW

**Comment by jmcorgan** [comment]
Was #537

**Comment by jmcorgan** [comment]
Maint or master?

**Comment by mbr0wn** [comment]
Dang should have been maint. It was based off of maint, but clicked wrong branch in creating PR.

**Comment by jmcorgan** [comment]
I'll take care of it.

**Comment by jmcorgan** [comment]
Cherry-picked onto maint.

**Pull request closed without merging**
