### PR TITLE
gr-qtgui: Repair qtgui examples for pybind11.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Comment by drmpeg** [comment]
QT GUI Message Edit Box is still broken.

**Comment by mormj** [comment]
LGTM.  Tagging a few other developers to get another set of eyes on the changes

**Comment by duggabe** [comment]
Using @drmpeg fork I have tested ~/gnuradio/gr-qtgui/examples/qtgui_message_inputs.grc works confirming the Time Raster Sink works..
I also tested ~/gnuradio/gr-qtgui/examples/pyqt_eye_sink.grc which works as well.

**Comment by ghostop14** [comment]
Hi @mormj, sorry was on vacation the past week and just got back today.  Let me know if you need any additional tests.

**Pull request merged**
