### PR TITLE
Fixes for mingw-w64

### PR DESCRIPTION
**Pull request by pcercuei**
This set of patches fix the build of various components of GNU Radio when compiled under mingw-w64 on Linux.

### CODE REVIEW

**Comment by jmcorgan** [comment]
Have you verified this using a native compile with MSVC?

**Comment by jmcorgan** [comment]
Also, why next branch?

**Comment by pcercuei** [comment]
I didn't test it under MSVC, because log4cpp is a requirement now for the 'next', and I never got that to compile under Visual Studio. But the changes shouldn't affect MSVC.

I thought it made sense to send the PR to 'next', do you want it for 'master' instead?

**Comment by jmcorgan** [comment]
@gnieboer Can you do a test of this branch?

@pcercuei It seems like a bug fix for maint, actually, but I'm not sure if it is based on any recent changes that would be only in master/next.

**Comment by gnieboer** [comment]
Sure, shouldn't be a problem.

**Comment by gnieboer** [comment]
Tested against master using MSVC 2015, no issues building, ran a sample graph with a fast noise source, no issues running.

**Comment by pcercuei** [comment]
@jmcorgan: Those fixes apply cleanly on master, too, so maybe apply them to master (and they'll be in "next" the next time you'll merge anyway).

**Comment by jmcorgan** [comment]
I'm going to try this on maint as they qualify as bug fixes and will then make it into the pending 3.7.10.2.

**Comment by jmcorgan** [comment]
This was cherry-picked onto the maint branch.

**Comment by jmcorgan** [comment]
Also, I'd be interested in your mingw compile setup; I hope to add it as another one of the build configurations in the build farm.

**Comment by pcercuei** [comment]
I used MSYS2 (on Windows) to download the dependencies, then cross-compiled GNU Radio on Linux with that setup, since GNU Radio does not build under MSYS2. Something related to the command lines being too long.

**Comment by jmcorgan** [comment]
Ah ok.  What I had originally hoped to do was to cross-compile all the deps from scratch and form a mingw prefix of all those artifacts, then cross build GR against that.

**Comment by pcercuei** [comment]
Well you can certainly create a ZIP containing the .lib and .dll files picked from a MSYS2, and then cross-compile against that. As long as you're using the same GCC version it should work fine.

**Pull request closed without merging**
