### PR TITLE
grc: Add window icon for main window

### PR DESCRIPTION
**Pull request by pwicks86**
The main grc icon gets set to the default question mark (at least on linux). GNU Radio has a nice icon, so it seems like it would be nice if it used it. I've used the icon png from the official gnu radio logo repository on github here. 

This is my first PR for gnuradio, so if I've missed anything in the process, please let me know. Thanks.

### CODE REVIEW

**Comment by drmpeg** [comment]
Just FYI, there's a way to install an icon already. See:

https://wiki.gnuradio.org/index.php/GNURadioCompanion#Installing_Icons.2C_Mime_Type.2C_and_Menu_Items

**Comment by pwicks86** [comment]
Dang, missed that somehow. 

Would it make sense to integrate ``grc_setup_freedesktop`` into the standard ``make install``?

**Comment by skoslowski** [comment]
I would, I suppose. This has been around longer than I have. @jmcorgan , any reason for this script not to run at install time?

**Comment by jmcorgan** [comment]
Well, it's specific to a particular desktop manager, which the user might not have in their OS.  Typically, these things are run in a postinst script by a package manager on systems that support it.

**Comment by jmcorgan** [comment]
If we want to have this automated at the application level, we could do it the way it is implemented here, but the the [FHS](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html) location for the icon file would be under $PREFIX/share/icons/gnuradio.

**Comment by jmcorgan** [comment]
Please let me know if there will be further movement on this, or if it should be closed out.

**Comment by skoslowski** [comment]
I'll formally review this soon, but it looks good

**Pull request merged**
