### PR TITLE
grc :  connection line bug fix for Windows

### PR DESCRIPTION
**Pull request by fasthyun**
(I am sorry I can't speak English well ....) 

This bug only occurs in Windows XP/7/8/?

This fix works for Linux too...

Please look at the following images

**1. the bug**  connection-bug

**2. fixed**  connection-fix

### CODE REVIEW

**Comment by jmcorgan** [comment]
@skoslowski

**Comment by skoslowski** [comment]
The linestyle is correct and can't be changed. We need double dashed lines for interdomain connections!

We can switch to solid lines for intra domain connections, but it will only mask the original problem.

Instead we should double check that the colors of double dashed lines are set correctly. Looks like for some reason either the sink or source domain color is white instead of both black for the stream domain.

**Comment by jmcorgan** [comment]
@skoslowski Not quite following this.  Is there an actual bug here that needs fixing?

**Comment by skoslowski** [comment]
There is a bug - on Windows only. This PR is not a fix. It only masks the problem. Introducing other bugs.

The pointers I gave above are for @fasthyun in case he is willing to work on thid some more. Else it can be closed.

**Comment by jmcorgan** [comment]
@fasthyun If you pursue this, please open a new pull request.

**Pull request closed without merging**
