### PR TITLE
grc: add python snippets to GRC - 3.8 backport

### PR DESCRIPTION
**Pull request by mormj**
3.8 backport of the python snippets

https://github.com/gnuradio/gnuradio/pull/3169

### CODE REVIEW

**Comment by mormj** [comment]
I'm going back through and doing more thorough testing of other grc files because this feature impacts the mako templates that generate all of the grc output, even when there is no snippet defined.  @nickoe - if you get a chance to test other grc files with this change please let us know how it goes.  Also, I haven't figured out how to control the whitespace in the mako templates that well, but for auto-generated code it hopefully doesn't matter too much.

**Comment by mormj** [comment]
ran a bunch of other flowgraphs, seems to have no impact

**Comment by michaelld** [comment]
@mormj so ... you approve of this backport?

**Comment by mormj** [comment]
Yes, I approve of it, as in I think it has minimal impact on any other grc functionality

**Comment by michaelld** [comment]
Desirable addition to the GRC API. Multiple approvals. CI still passes. Merging.

**Pull request merged**
