### PR TITLE
codec2: fix support for codec2 version < 0.8

### PR DESCRIPTION
**Pull request by ra1nb0w**
codec2 version < 0.8 doesn't provide codec2/version.h header
therefore cmake discovers if it is available.

fix gr-vocoder build on ubuntu < 19.04 and debian < 10

Closes: https://github.com/gnuradio/gnuradio/pull/2858#issuecomment-549391165

### CODE REVIEW

**Comment by ra1nb0w** [comment]
if it works, should be also merged to `maint-3.8`

**Comment by michaelld** [comment]
> if it works, should be also merged to `maint-3.8` (with the previous one)

Yes. maint-3.7 also if it is applicable.

**Comment by mormj** [comment]
This fixes the build (master) on ubuntu 18 for me

**Comment by michaelld** [comment]
All tests have passed, which is a positive sign. 2 of us approve. I'm merging as this is a critical fix.

**Comment by michaelld** [comment]
@ra1nb0w can you make PRs for maint-3.8 and, if appropriate, maint-3.7?

**Comment by ra1nb0w** [comment]
Ok for maint-3.8
GR 3.7 uses internal codec2 code so not needed.

**Comment by ra1nb0w** [comment]
thank you ;-)

**Pull request merged**
