### PR TITLE
SOCIS polar code work

### PR DESCRIPTION
**Pull request by jdemel**
This is the planned pull request for my polar code work.

I know that there's still a pending pull request for VOLK which has to be merged first. I consider it to be useful to get comments on this rather big pull request now. So I can fix any issues sooner than later.

### CODE REVIEW

**Comment by jdemel** [comment]
Nathan just merged polar kernels into VOLK master. Should I update my volk commit pointer and push it on github on this branch?

**Comment by jdemel** [comment]
Updated VOLK pointer. Kernels are merged into VOLK/master.

**Comment by jmcorgan** [comment]
@trondeau I'lll leave this for you to work into your overall FEC stuff.

**Comment by jdemel** [comment]
Found a few bugs that would pop up in some cases. They're fixed now.
Had to remove hide feature in GRC representation of configurator block. Cheetah doesn't let me compare variables with strings. It produces useless code.

**Comment by jmcorgan** [comment]
Please rebase this off a current master branch.

**Comment by jdemel** [comment]
I moved all commits. So they should be based off of current master. Hope that helps.

**Comment by trondeau** [comment]
@jdemel I've started to look through this, but I'm not having much luck with making examples out of it. Can you make a series of examples that show off how to use this more than just the QA code? Look at the examples dir and make similar ones, like:

fecapi_async_polar_encoders
fecapd_polar_decoders

And possibly any others that make sense. I like to be able to compare results between different methods of use (like streaming versus async messages) and performance between different codes.

Also, you've a good start on the documentation, but it still needs work. I'd prefer to have the parameters marked up properly using the "\param" key so they format properly in the html page. You should do this for each function, including the 'make' function -- don't put the is_packed in the main docs for the block but specifically for the make function itself. I think you should try to explain better what the block is doing and what the parameters really mean. It's unclear what block_size really means other than it's a power of two. What relationship does num_info_bits mean to the block? Relative to the block_size?

I think making the examples work and thinking about how to set up the parameters in a GRC flowgraph might help you understand how better to document the behavior.

**Comment by jdemel** [comment]
There should be 5 flowgraphs which show polar codes in different scenarios. They're compared among themselves and with a few other decoders.

Also documentation got an update. I hope things are more straightforward now.

**Comment by trondeau** [comment]
Ok, better. The examples look good. I've updated the polar_code_example.grc file to also show what happens in an uncoded situation, so you can see how much faster the BER starts when not using FEC.

Two things. First, the QA code is failing. Second, when you open up an example, the encoder and decoder blocks don't necessarily recognize polar_config. I think this is a problem with defining variables and when variable objects get instantiated. We might need @skoslowski to help with this.

I've made some commits onto my github repo under the socis/master branch. Please work off that so we don't have conflicting merges.

**Comment by jdemel** [comment]
Could I just merge your branch? Or would that brake the commit history here on github? 

I had to fix how rate was calculated for decoders. But I did update the tests too. So I'm a bit surprised. What fails exactly?

**Comment by trondeau** [comment]
Yes, just merge my branch. I can cherry-pick or merge, depending, your changes later.

I have to recompile my build dir for this (not sure why) to run the tests again. But both qa_polar_decoder test suites fail. Something about 2 != 0.5, if I recall.

**Comment by jdemel** [comment]
@trondeau your branch is merged. I just ran all tests in gr-fec and they pass. The issue with 2 != 0.5 arose after I had to change how decoder->rate() calculated its return value. But everything should be up-to-date now.

There is a file 'polar/testbed.py' which was intended to make it easier to play around with Python code but it's mainly a code dump file now. Should I remove it or could it still be of any use for others?

It already happened to me in a few situations that flowgraphs report errors after I opened them. This seems to be the case since @skoslowski disabled constant flowgraph evaluation. But opening and closing a parameter window fixes that. It's annoying but I assume it's a GRC issue.

**Comment by trondeau** [comment]
Ok, QA passing now. Thanks.

And I agree that this is a GRC issue, not anything you can do about it. We'll see if we can get @skoslowski to fix it once we merge this in and provide him with a test case.

I'd like to keep the "polar" Python code around since it seems like a bunch of useful utilities for working with them. I appreciate that there is a Readme.md file there, but it provides very little description of what's going on in this directory, and none of the functions that I saw are documented. I think it's fine that they are there in the source code, but we won't install them.

I've made one more commit that I will push soon to install the rest of the FEC examples properly. Otherwise, I think this is probably good enough to merge.

**Comment by trondeau** [comment]
Closing. Replaced with PR #641.

**Pull request closed without merging**
