### PR TITLE
Github Issue Tracker: Show links to docs, for asking questions

### PR DESCRIPTION
**Pull request by marcusmueller**
## Description

Lately, a wave of usage questions has hit the issue tracker. You can provide links to off-tracker resources, so that people aren't tempted to ignore what the issue template says and still open an issue to ask a question.

## Related Issue

#7259
#7258
#7257
…

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Example of such a thing in action: 
https://github.com/highlightjs/highlight.js/issues/new/choose

Screenshot 2024-04-08 at 11-44-48 New Issue · highlightjs_highlight js

**Comment by willcode** [comment]
Sounds good. Is there a way to see what this would look like on our github, or do we have to merge to see it?

**Comment by marcusmueller** [comment]
@willcode https://github.com/marcusmueller/github-feature-playground/issues/new/choose

**Comment by marcusmueller** [comment]
narf. Just the second after you've merged I realized github ate half of the `about:` of the Matrix link

**Pull request merged**
