### PR TITLE
pmt: use memcpy in uniform vector initializer for speed increase

### PR DESCRIPTION
**Pull request by osh**

### CODE REVIEW

**Comment by trondeau** [comment]
This is almost a bug fix... It could go into maint.

**Comment by douggeiger** [comment]
Don't tell @balister that we're *adding* memcpy's to gnuradio!

**Comment by jmcorgan** [comment]
Too late.

**Comment by osh** [comment]
everybody loves a little memcpy

**Comment by jmcorgan** [comment]
This was cherry-picked onto maint.

**Pull request closed without merging**
