### PR TITLE
Update README.pdu

### PR DESCRIPTION
**Pull request by jasonuher**
I think this is right - @mormj did I misunderstand something or was this a c/p error?

### CODE REVIEW

**Comment by jasonuher** [comment]
LOL can't DCO when you make the change in the github cli.... guess I'll get to this later....

**Review by jacobagilbert — APPROVED** [review]
This was overlooked. Good fix.

`git commit --amend --no-edit -s` and it's good to go.

Thanks!

**Comment by mormj** [comment]
Looks like a c/p error

**Comment by jasonuher** [comment]
signed.  That's what I get for trying to 'code' from a phone :p

**Pull request merged**
