### PR TITLE
Add `override` for common virtual function overrides

### PR DESCRIPTION
**Pull request by ThomasHabets**
Mostly done with:

```
find -name "*_impl.h" | xargs sed -i -r '/(void forecast|int work|int general_work|bool check_topology)\(/{:back /\)/b nxt;N;b back;:nxt s/\)$|\)(;)/) override\1/g}'
```

Then I removed an incorrect `work` that this found.

It may seem like a silly change, but it did find some confusing code I deleted.

### CODE REVIEW

**Review by mormj — APPROVED** [review]

**Comment by marcusmueller** [comment]
Ha! Sorry for letting this ripen for so long. Generally, nice work! (would have done it through a `clang-tidy` pass, though :))

Let me go through this real quickly.

**Comment by marcusmueller** [comment]
huh, this introduces failing unit tests, which is surprising, but probably a positive side effect...

**Comment by ThomasHabets** [comment]
True, but clang-tidy would not have found the incorrect `work` declaration. :-)

**Comment by marcusmueller** [comment]
@ThomasHabets I'm still throwing in the whole-tree clang-tidy rework. My compiler otherwise becomes *very* verbose about inconsistent `override` usage...

**Comment by marcusmueller** [comment]
Man, I'm not doing this nice and tidy today...

**Review by marcusmueller — APPROVED** [review]

**Comment by marcusmueller** [comment]
@ThomasHabets as soon as these checks pass, could I ask you to review this?

**Comment by ThomasHabets** [comment]
@marcusmueller looks good

**Pull request merged**
