### PR TITLE
Corr only

### PR DESCRIPTION
**Pull request by bistromath**
This branch separates out my and Andy Walls's work on modifying the correlate and sync block from the MSK branch on which it was based, and rebases the work on master.

My work allows the user to modulate a candidate (preamble) vector with the modulator of their choice using the modulate_vector block, allowing the correlate_and_sync block to therefore be modulation independent. I've updated the test_corr_and_sync example in gr-digital/examples to show the operation of the new block.

Andy's work fixed a lot of bugs in the block, adjusted phase_est and time_est calculations, Volkified the work function, and generally cleaned things up.

### CODE REVIEW

**Comment by jmcorgan** [comment]
Ultimately, this will be up to @trondeau to review and merge, but one thing I noticed--there is a public API visible change in correlate_and_sync_cc::make, which would force this as-is to go into the 3.8 branch.

**Comment by bistromath** [comment]
Oh, I thought API breakage was OK for master (but not for maint). The API
necessarily changes as the utility of the block is now significantly
different. This is not intended for maint.

**Comment by jmcorgan** [comment]
'maint' is for bug fixes only; 'master' is for new stuff within the 3.7 API, 'next' is for API changes to be released in 3.8.

Since the features are significantly different, I recommend making this a new block and deprecating the old one (leaving it unchanged.)

**Comment by bistromath** [comment]
I don't much like that for two reasons:

1. The new behavior is a superset of the old behavior, generalizing the
block to any modulation
2. The new block does what it says on the box: correlate and sync. The old
block's functionality, if it is to be preserved, should be renamed
"psk_correlate_and_sync_cc" to reflect more accurately what it is intended
to do.

Rebasing on next is of course a good idea and easy to accomplish.

**Comment by bistromath** [comment]
Also, to the best of my knowledge, the only users of the correlate_and_sync
block are me and Andy, and we're breaking it to fix it. ;)

**Comment by jmcorgan** [comment]
gr-digital is Tom's area of responsibility...I'll leave it to him.

**Comment by bistromath** [comment]
OK. Should I close this PR and create a new one, or push --force the rebased branch?

**Comment by bistromath** [comment]
Nevermind. Closing this PR as the source and target branches are fixed.

**Comment by jmcorgan** [comment]
This could still end up being on master branch as part of 3.7.x, with appropriate changes, let's leave it open.

**Comment by trondeau** [comment]
Yes, keep this one open. I might not get to this for another week, but I'm interested in the work that's been done here and have been following the discussions on it. I would like to get as much of this on master as possible.

**Comment by bistromath** [comment]
Ping! =) Any progress on this?

**Comment by trondeau** [comment]
Many other things taking my attention right now. Once some of these start to get wrapped up, I'll get to this.

**Comment by trondeau** [comment]
Began looking at this. There are changes to the make function of the correlate_and_sync. I like what you're doing here, but we need to treat this a bit more carefully.

I'm going to try to change this to a second make function (make_raw or something) and reintroduce the original make that will do the symbol conversion that you're now handling externally.

I like where I see other things going there, though.

**Comment by bistromath** [comment]
Cool. It would make more sense to reintroduce the prior functionality
(putting the symbol mapping in the constructor) in a new, more specific
constructor -- say, make_psk -- rather than putting the more general case
in a new make function.

--n

**Comment by trondeau** [comment]
Except that that changes the API :)

Moving over will be part of the 3.8 API change.

**Comment by jmcorgan** [comment]
We can't change the current make function and stay within the 3.7API.
However, we can introduce the more general function as something else, as
Tom suggests, then in 3.8, make it the default.

On Fri, Feb 27, 2015 at 3:38 PM, bistromath <notifications@github.com>
wrote:

> Cool. It would make more sense to reintroduce the prior functionality
> (putting the symbol mapping in the constructor) in a new, more specific
> constructor -- say, make_psk -- rather than putting the more general case
> in a new make function.
>
> --n
>
> On Fri, Feb 27, 2015 at 2:46 PM, Tom Rondeau <notifications@github.com>
> wrote:
>
> > Began looking at this. There are changes to the make function of the
> > correlate_and_sync. I like what you're doing here, but we need to treat
> > this a bit more carefully.
> >
> > I'm going to try to change this to a second make function (make_raw or
> > something) and reintroduce the original make that will do the symbol
> > conversion that you're now handling externally.
> >
> > I like where I see other things going there, though.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gnuradio/gnuradio/pull/376#issuecomment-76487072>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gnuradio/gnuradio/pull/376#issuecomment-76493310>.
>



-- 
Johnathan Corgan
Corgan Labs - SDR Training and Development Services
http://corganlabs.com

**Comment by bistromath** [comment]
Love it.

**Comment by jmcorgan** [comment]
I assume we'll go with a master/3.7.x merge for this, and so we can close #378, correct?

**Comment by jmcorgan** [comment]
I'm going to review this.  It won't go into 3.7.7, but I'm trying to get a bunch of packet handling stuff into the master branch and this would be a good candidate.  I may end up renaming the block to something new to avoid the whole API breakage issue.

**Comment by jmcorgan** [comment]
Superseded by #473.  The commits have been squashed to a single commit, then the final files have been copied over and renamed to work as digital::corr_est_cc.  This will allow inclusion in master branch without conflict, and the existing digital::correlate_and_sync_cc will be removed in 3.8.

**Pull request closed without merging**
