### PR TITLE
Update README to prepare for GR4.0 incorporation

### PR DESCRIPTION
**Pull request by cafeclimber**
## Description
Updating the README to prepare for the upcoming incorporation of FAIR's work into the GNU Radio Organization.

## Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Review by duggabe — APPROVED** [review]
Looks good!

**Comment by cafeclimber** [comment]
I fully forgot to sign my commit 😖 @willcode can you remind the steps to force a commit to fix?

And if they look good I'll go ahead and make they PR not a draft 😊

**Comment by willcode** [comment]
`git commit --amend --no-edit -S`
`git push -f origin HEAD`

**Comment by willcode** [comment]
@cafeclimber This point users to FAIR for bug reports on the `main` branch. That should still point to our repo.

**Pull request merged**
