### PR TITLE
pmt.cc: Adding mutex for thread-safety to handle simultaneous pmt_sym…

### PR DESCRIPTION
**Pull request by darek-kawamoto**
…bol insertions.

Background: When two threads simultaneously tried to call pmt::dict_add using the same key, the first pmt in would fail all dict_has_key() subsequent checks, while the second pmt would be fine.  This is because the global pmt_symbol table would insert two pmt_symbols for the same key string but only uses one moving forward.

The code in this pull request ensures only one pmt_symbol is inserted into the table, and also ensures that a new symbol was not inserted before the mutex is acquired.  The additional costs of mutex locking is only present when inserting new pmt_symbols.

### CODE REVIEW

**Comment by osh** [comment]
much danger here

**Comment by jmcorgan** [comment]
@osh please spell this out

**Comment by osh** [comment]
Danger in the underlying issue not in the pr to fix :)

**Comment by darek-kawamoto** [comment]
This issue should not come up often, but when it does it's not fun.

**Comment by jmcorgan** [comment]
This is being cherry-picked onto the maint branch as a bug-fix.

**Pull request closed without merging**
