### PR TITLE
Adding LDPC functionality to gr-fec

### PR DESCRIPTION
**Pull request by tracierenea**
Same features described in pull request #521, with the addition of: 

- Doxygen documentation and tags added to public header files
- alist files moved to more public location ($prefix/share/gnuradio/fec/ldpc/) and example and documentation updated accordingly
- Example LDPC GRC file updated to use exact paths to alist files. I used the approach of gr-trellis where the paths to the installed alist files are set by cmake.

### CODE REVIEW

**Comment by jmcorgan** [comment]
@trondeau This will be up to you, but I wonder if it would be better to clean up the history on this one, by rebasing on current master and cherry-picking each commit from the various merged branches.  There is even a commit where .gitmodules is added, and that shouldn't have been necessary.

**Comment by trondeau** [comment]
Yes, I noticed the .gitmodules issue as well, and I agree that we can clean this up a bit. I'll go ahead and do this myself, though, since I think it'll help me to work through the code and make sure it all looks good otherwise. I have it on my list to work on tomorrow.

**Comment by tracierenea** [comment]
I didn't think about my commit history being a little... uh.. long and hairy, and I realize that the project needs to have clear & concise logs. If it is better, I can refork gnuradio and add all of this in just a few clean commits. My changes are adding new files to gr-fec and then updating the Makefiles/swig instructions, so I think it would be straightforward for me to do this, if it's helpful.

I think the .gitmodules issue was when I accidentally deleted the volk submodule and didn't know how to gracefully recover from that... (mentioned on #521 ).

Thanks for your patience and help on my first pull request!

**Comment by jmcorgan** [comment]
Tracie--no worries at all.  Tom has already done it and we're likely to merge in the next day or two.  Thanks again for all your work!

**Comment by trondeau** [comment]
No problem, Tracie. Check out my new branch:
https://github.com/trondeau/gnuradio/tree/fec/ldpc_methods

It cleans up your commit history a bit. Not a whole lot -- there were a lot of fixes between files and commits that were hard to squash easily. But this is a case where the commits are logical in what they do and show a few lessons in the development of the system. I think in this case it's better than starting fresh, dumping it all into a new branch and making a commit that says it's all there and working.

You'll see a few extra commits on my side that fixed up a few build and install issues, some of which are general fixes and trying to smooth out both LDPC capabilities now in there.

**Comment by tracierenea** [comment]
Awesome! It is really helpful for me to hear both of your insights and to see these details in Tom's branch. Good lessons learned for next time. Thanks again!

**Comment by trondeau** [comment]
Tracie,

One thing you can do to really help is document the differences between the LDPC encoder/decoder that are in there already (based on Manu T-S's work) and your new encoders and decoder.

The decoder is fairly obvious what the differences are, though I wish that we had named the other better than "ldpc_decoder". For the encoders, what's the main difference between what's in ldpc_encoder (actually done using the class cldpc in clpdc.cc) and your ldpc_R_U_encoder and ldpc_gen_mtrx_encoder.

I started to add some of this into the fec.dox file by going through the GSoC presentations, but you can hopefully whip this together much faster than I can.

Thanks!

**Comment by trondeau** [comment]
Tracie,

One more thing, feel free to just send me an email with either the new fec.dox or a diff of your new one versus the old one.

**Comment by tracierenea** [comment]
Sure! I'll send it by this evening.

**Comment by trondeau** [comment]
Replaced by #660

**Pull request closed without merging**
