### PR TITLE
gr-qtgui: Switch to Qt5

### PR DESCRIPTION
**Pull request by pcercuei**
This pull request switches the gr-qtgui blocks to use Qt5 instead of Qt4.
Same as https://github.com/gnuradio/gnuradio/pull/649 but rebased on the "next" branch instead of "master".

### CODE REVIEW

**Comment by pcercuei** [comment]
Please also pay attention to this important note: https://github.com/gnuradio/gnuradio/pull/649#issuecomment-144043968

**Comment by pcercuei** [comment]
The support of Qt5 was only finalized in 2.8.12: http://doc.qt.io/qt-5/cmake-manual.html
The minimum version required to use Qt5 is CMake 2.8.3 anyway, so 2.8.0 won't work.

**Comment by jmcorgan** [comment]
Got it, thanks for the details.  It's likely then we'll have to make cmake 2.8.12 our target for releases 3.8.x; we'll have to check what OS versions that might exclude.

**Comment by jmcorgan** [comment]
Also, github is indicating the branch will no longer merge without conflicts.  Can you rebase this on current next and make whatever changes are needed for a clean merge?  I need to speak with @trondeau about the 2.8.12 issue, but no need to let divergences pile up until then.

**Comment by pcercuei** [comment]
Done.

**Pull request closed without merging**
