### PR TITLE
trellis: bug fixed:adding a missing callback function set_K in trellis_encoder

### PR DESCRIPTION
**Pull request by fengzhe29888**
Dear @jmcorgan 

The trellis fix is ready.

Thanks!
Best,
Zhe

### CODE REVIEW

**Comment by jmcorgan** [comment]
Since this is a bug fix, please rebase it off the maint branch, and please make your branch names something descriptive.

**Comment by fengzhe29888** [comment]
Hi Johnathan, 

I didn't get you quite well, could you describe it a little more? 
Thanks!

**Comment by jmcorgan** [comment]
Actually, this pull request combines both a bug fix and a new feature.  The bug fix commit should be in a different branch, base of the 'maint' branch, and have a descriptive branch name.

**Comment by fengzhe29888** [comment]
Dear Johnathan,

I got what you meant and I just opened another pull request from my maint
branch.
Could you check it?

Thanks!
best,
Zhe

**Pull request closed without merging**
