### PR TITLE
Update conda recipes and CI scripts

### PR DESCRIPTION
**Pull request by ryanvolz**
## Description

This updates the the OOT modtool template conda recipe, `gnuradio-dev` in-tree conda recipe used for CI builds, and the generated CI scripts to stay up to date with the conda-forge package ecosystem.

## Which blocks/areas does this affect?

CI, modtool template

## Testing Done

I've manually put into place the template recipe changes in the recent rebuilds I did of various OOT modules for GR 3.10.8.0, and those are working fine. The remaining changes will be tested by the CI builds themselves.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
All set?

**Comment by ryanvolz** [comment]
Yes!

**Comment by willcode** [comment]
Any other PRs that need to be backported before this one? I'll backport all the RFNoC stuff first, since there's a reference to  it here.

**Comment by ryanvolz** [comment]
I think the last commit fixing the RFNOC F15 build on Windows is the only thing that will care about order.

**Pull request merged**
