### PR TITLE
Tags and rate changing blocks

### PR DESCRIPTION
**Pull request by trondeau**
It's a bug fix, technically, but it's a pretty significant change in the internal behavior of the blocks with how they handle the tags. It will also add overhead in how the tags are managed, and I'm not sure by how much exactly.

### CODE REVIEW

**Comment by trondeau** [comment]
Seeing some other issues elsewhere when I'm using this. Need to verify the tag placement.

**Comment by jmcorgan** [comment]
Any update on this?

**Comment by trondeau** [comment]
Negative. Haven't found time to follow through with the tests that I need to run.

**Comment by trondeau** [comment]
Going to close this because I have a better solution on my [packet2](https://github.com/trondeau/gnuradio/tree/packet2) branch. See

https://github.com/trondeau/gnuradio/commit/dc9b165b9c173223802348a098e411f79361b790

This would need to be applied (and tested) for both complex and float versions of the PFB and M&M clock sync blocks.

**Pull request closed without merging**
