### PR TITLE
C++20: Fix logging, set std to C++20

### PR DESCRIPTION
**Pull request by marcusmueller**
# Pull Request Details

## Description

In prep for C++20ification, overhauled the logging header: we should actually be doing perfect forwarding. Don't remember why I didn't do that on main – might need to backport.

## Related Issue

#6035 

I hoped this would solve the "spdlog fails with C++20", alas it didn't. However, this is still cleaner, and cleans up the API by removing levels that we were dragging along from 3.7 that are in basically no use.

## Which blocks/areas does this affect?

Lögging.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
ah we need modern fmt, so ubuntu 20.04 fails.

@mormj should I include spdlog/fmtlib as subproject (whatever of the two suffices to make Ubuntu 20.04 build)? What's the oldest distro we need to support?

**Comment by mormj** [comment]
We can probably bump up to 22.04 for simplicity. There are some c++20 features that are not supported by the gcc in 20.04. 

But as far as subprojects thats the path i took for cppzmq. For header libs it seems to work fine.

**Comment by mormj** [comment]
Re-ran the CI because failures were because of some PMT changes.  I'm ok ignoring the Ubuntu 20.04 failure and removing 20.04 as a worker if we are going to run into more of these issues.  Some other c++20 changes I'd like to do will exacerbate this and there is no real reason to stick with 20.04 as a minimum for a future release

**Review by mormj — APPROVED** [review]
I'll remove the Ubuntu 20 worker in a separate commit (and upgrade Ubuntu on my dev machine lol)

**Review by mormj — APPROVED** [review]
With Ubuntu 20.04 out of the way, is this one good to go?

**Comment by marcusmueller** [comment]
Hey sorry to keep you hanging there (in the middle of moving flats), yes, it is.

**Pull request merged**
