### PR TITLE
Changed numpy to scipy since fftpack is in scipy

### PR DESCRIPTION
**Pull request by shanejohnpaul**
fftpack is present in scipy not numpy

### CODE REVIEW

**Comment by mbr0wn** [comment]
Did you get an error with the original code? `from numpy.fft import fftpack` works fine for me, and unlike scipy, numpy is an actual dependency of GNU Radio.

**Comment by shanejohnpaul** [comment]
Yeah. It said that it cannot import fftpack from numpy.fft. But with the scipy version, everything works fine. Does gnuradio require a specific numpy version?

**Comment by velichkov** [comment]
@mbr0wn,

It turns out the numpy's `fftpack` was replaced with `pocketfft` in https://github.com/numpy/numpy/pull/11888, https://github.com/numpy/numpy/commit/062dc8f831e695c2c179482da35affcc6045b4f3 so no `fftpack` in versions >  v1.17.0rc1 

The `scipy` is actually used in few places although there are no checks in cmake's files.

https://github.com/gnuradio/gnuradio/blob/96a5e82123ddc8a3ea6ced7bb903cafacd5113fb/gr-filter/python/filter/design/filter_design.py#L53
https://github.com/gnuradio/gnuradio/blob/96a5e82123ddc8a3ea6ced7bb903cafacd5113fb/gr-filter/python/filter/design/fir_design.py#L23
https://github.com/gnuradio/gnuradio/blob/96a5e82123ddc8a3ea6ced7bb903cafacd5113fb/gr-trellis/python/trellis/fsm_utils.py#L33

**Comment by mbr0wn** [comment]
Yeah scipy is one of those optional dependencies. Scripts using scipy are supposed to check for its existence and print a useful error on ImportError.

**Comment by velichkov** [comment]
The same problem in `gr-filter/python/filter/design/filter_design.py` was fixed in https://github.com/gnuradio/gnuradio/pull/2755 by importing `pocketfft` in case importing of `fftpack` fails.

The `fftpack` is being used in:
- gr-utils/python/utils/plot_fft_base.py
- gr-dtv/examples/atsc_ctrlport_monitor.py
- gr-digital/examples/example_timing.py

**Comment by devnulling** [comment]
@shanejohnpaul Would you want to update this PR to behave the same as what the solution was in https://github.com/gnuradio/gnuradio/pull/2755/files ? 

Also we will need a CLA from you, not specifically for this minor change, but it will streamline PRs that may have more LOC in the future. Please email bhilburn at gnuradio.org to get the CLA started.

**Comment by shanejohnpaul** [comment]
@devnulling Yes, it should behave the same. The `fftpack` is in `scipy` and not `numpy.fft`, and that is all I have changed.

I'm new to PRs, so I have no idea about CLAs.

**Comment by drmpeg** [comment]
It should also be noted that the polar code QA tests fail during "make test" without scipy.

**Comment by marcusmueller** [comment]
I'm really no fan of depending on `scipy` just because numpy's naming changed...

**Comment by michaelld** [comment]
I made an issue #3235  for this topic. Agreed we don't want to promote SciPy to being a configure requirement. There are better ways ...

**Comment by mbr0wn** [comment]
@shanejohnpaul based on our discussions in #3280 and #3290, it turns out this is the wrong fix. We need to call straight into numpy.fft. I'll close this PR, but still many thanks for submitting

**Pull request closed without merging**
