### PR TITLE
Cmake fixes

### PR DESCRIPTION
**Pull request by bastibl**
Some cmake cleanup. I recently had a look into the build process since GNU Radio doesn't compile on my mac for quite a while. I think there are some fundamental problems with the build process, which I quickly outlined in Issue #1045.

However, according to my understanding this is already being addressed somewhere else, so this PR covers only some minor things.

The patch "cmake: remove duplicate swig includes" makes the swig commands a bit more readable. For example, the swig command to compile the bindings for the blocks components includes 226 directories on my machine (out of which 16 are actual unique directories).

### CODE REVIEW

**Comment by marcusmueller** [comment]
* 2da961c :Very fond of that! kill all the manual -I, remove duplicates.
* e19ce20: confuses me a bit, doesn't FindLog4cpp.cmake set `LOG4CPP_INCLUDE_DIRS`; why do the scripts in the pre-patch version even use `LOG4CXX_INCLUDE_DIRS` (notice: `CPP` set, vs `CXX` used)? shouldn't that be a `sed -i 's/LOG4CXX_/LOG4CPP_/g` instead of a complete removal of these lines?
* a9640d1: ah suddenly the above commit makes sense. How could that slip us? If anything, you *could* squash these two (but seriously, matter of taste)
* 3df7c1b: yeah! Wanted to do that for years. Seriously, also, we can basically disable testing if we don't rely on `gr-blocks`; we test very little in `gnuradio-runtime`'s tests and do most in `gr-blocks`' tests.
* d3ef758: ... No-brainer. Same: 5367ce1,  		9742868,  		9a9cdd0,  		df9f9b3,  	cb463db,  	faa6c9d,  	5d85eb9
* 582e047: `gr-fec` works without it?
* ef6be72: Is that how it is? Because then, we can essentially let the whole of GR depend on VOLK. Which I'd personally don't object to.

**Comment by bastibl** [comment]
> e19ce20: confuses me a bit, doesn't FindLog4cpp.cmake set LOG4CPP_INCLUDE_DIRS; why do the scripts in the pre-patch version even use LOG4CXX_INCLUDE_DIRS (notice: CPP set, vs CXX used)? shouldn't that be a sed -i 's/LOG4CXX_/LOG4CPP_/g instead of a complete removal of these lines?

I though since all these variables were void, they can just as well be removed, and regarded this as one step. The next commit adds the `LOG4CPP_INCLDUDE_DIRS` to `GNURADIO_RUNTIME_INCLUDES` to avoid the need to add it to every component.

> 582e047: gr-fec works without it?

Dunno, but at least the module thinks it does. It's full of `if(GSL_FOUND)` switches

```
basti@flinn (next*):~/src/gnuradio/gr-fec >> grep -i GSL **/CMakeLists.txt
apps/CMakeLists.txt:#  ${GSL_INCLUDE_DIRS}
apps/CMakeLists.txt:#  ${GSL_LIBRARIES}
CMakeLists.txt:find_package(GSL)
include/gnuradio/fec/CMakeLists.txt:if(GSL_FOUND)
include/gnuradio/fec/CMakeLists.txt:endif(GSL_FOUND)
lib/CMakeLists.txt:# Only include the LDPC work if we have GSL installed
lib/CMakeLists.txt:if(GSL_FOUND)
lib/CMakeLists.txt:  include_directories(${GSL_INCLUDE_DIRS})
lib/CMakeLists.txt:  link_directories(${GSL_LIBRARY_DIRS})
lib/CMakeLists.txt:  list(APPEND gnuradio_fec_libs ${GSL_LIBRARIES})
lib/CMakeLists.txt:endif(GSL_FOUND)
python/fec/CMakeLists.txt:# Without GSL, we don't build some of the LDPC work, so we can't test
python/fec/CMakeLists.txt:if(NOT GSL_FOUND)
python/fec/CMakeLists.txt:endif(NOT GSL_FOUND)
swig/CMakeLists.txt:if(GSL_FOUND)
swig/CMakeLists.txt:  list(APPEND GR_SWIG_FLAGS "-DGSL_FOUND")
swig/CMakeLists.txt:endif(GSL_FOUND)
swig/CMakeLists.txt:set(GR_SWIG_LIBRARIES gnuradio-fec ${GSL_LDFLAGS})
```

According to my understanding, the current implementation voids all these switches since it requires GSL. I could also remove all the switches and just require GSL.

> ef6be72: Is that how it is? Because then, we can essentially let the whole of GR depend on VOLK. Which I'd personally don't object to.

Yes, volk is used very heavily in gr-blocks:
```
basti@flinn (next*):~/src/gnuradio/gr-blocks >> grep -R volk *
include/gnuradio/blocks/rotator.h:#include <volk/volk.h>
include/gnuradio/blocks/rotator.h:        volk_32fc_s32fc_x2_rotator_32fc(out, in, d_phase_incr, &d_phase, n);
include/gnuradio/blocks/control_loop.h:     * volk_32f_tanh_32f.
lib/divide_cc_impl.cc:#include <volk/volk.h>
lib/divide_cc_impl.cc:        volk_32fc_x2_divide_32fc(optr, numerator, (gr_complex*) input_items[inp], noutput_items * d_vlen);
lib/complex_to_float_impl.cc:#include <volk/volk.h>
lib/complex_to_float_impl.cc:	volk_get_alignment() / sizeof(float);
lib/complex_to_float_impl.cc:        volk_32fc_deinterleave_real_32f(out0, in, noi);
lib/complex_to_float_impl.cc:        volk_32fc_deinterleave_32f_x2(out0, out1, in, noi);
[and on and on]
```

**Comment by marcusmueller** [comment]
Thanks, that clears all my confusion!

**Comment by jmcorgan** [comment]
@bastibl After the release I'll go over this in detail.  We'll probably want to do some of the obvious ones right away and break out the ones that need more discussion into separate PRs.

**Comment by jmcorgan** [comment]
@bastibl I need to verify the gr-fec related commit 582e047, but the rest of these look good to go.

However, it also looks like a significant chunk of them would also apply on current master. It would be useful if you could create a new PR off master that cherry picks those commits that apply cleanly and are appropriate there.  This could then merge up to next, and form a second PR with the remaining commits cherry-picked on top of that.

**Comment by bastibl** [comment]
I cherry-picked the relevant commits and squashed some of them. Regarding GSL, I uninstalled it, recompiled, and ran the unit tests.

**Comment by jmcorgan** [comment]
Thanks for getting to this.  I should be able to get these merged up today.

**Comment by bastibl** [comment]
Thanks, I'm not 100% sure about the last one. Can `LD_FLAGS` be required for shared libraries that are referenced indirectly?

In this case gr-dtv uses gr-fec, which might be linked against GSL. Is there something special with GSL that gr-dtv could need the `LD_FLAGS` of GSL?

**Comment by jmcorgan** [comment]
If I recall correctly, the linker behavior here is different between GNU ld and MSVC, and these were added to correct that. @gnieboer @guruofquality can comment.  Also, this may have to do with rpath behavior.

Come to think of it, I'll defer this last commit until we're confident about this. Can you push the branch with out it?

**Comment by bastibl** [comment]
It was introduced with this pull request https://github.com/gnuradio/gnuradio/pull/1066 and, AFAIK, is only required if one didn't set the install_name of the GSL library on macOS. (Then, this change might help to compile, but will lead to problems during run time, as it would still require the `DYLD_LIBRARY_PATH` to be set).
@horvathp do you have any thoughts on that?

**Comment by jmcorgan** [comment]
Let's leave off the GSL-related commit(s) here so I can get in the rest of these, then please open a new PR for the GSL change.  We can continue the discussion there.

**Comment by bastibl** [comment]
OK.

**Comment by guruofquality** [comment]
> If I recall correctly, the linker behavior here is different between GNU ld and MSVC, and these were added to correct that. @gnieboer @guruofquality can comment. Also, this may have to do with rpath behavior.

In general, if the public headers for the dependency library reference GSL in any way, when its a good idea to link GSL for any subsequent library that also includes those same headers. Headers can drag in library dependencies by means of inline functions that call symbols in the library, or even pragmas that specifically try to link the library.

If the GSL includes are all nicely hidden inside the PIMPL classes in the dependency library, then you should be able to get away with **not** linking GSL in the subsequent client library that uses those blocks. But otherwise, you have to do the linking. Sometimes you can get away with the implicit linking through the dependency, but its not something that's very consistent across platforms.

**Comment by bastibl** [comment]
Thanks for your input. AFAIS, gr-fec doesn't reference GSL in its  public headers in `gr-fec/include`. So, I think, the patch should be OK.

I didn't know that headers can drag in library references. Actually, that means that the current way of linking log4cpp is wrong. All components depend on runtime, which references log4cpp in its [public includes](https://github.com/gnuradio/gnuradio/blob/next/gnuradio-runtime/include/gnuradio/logger.h#L46). It would mean that all components should also link against log4cpp.

**Pull request merged**
