### PR TITLE
build: remove clang warnings

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Comment by drmpeg** [comment]
@ThomasHabets The warning(s) for polyphase_filterbank.h was:
```
In file included from /home/ubuntu/xfer/gnuradio/gr-filter/lib/pfb_decimator_ccf_impl.cc:15:
In file included from /home/ubuntu/xfer/gnuradio/gr-filter/lib/pfb_decimator_ccf_impl.h:16:
/home/ubuntu/xfer/gnuradio/gr-filter/lib/../include/gnuradio/filter/polyphase_filterbank.h:111:5: warning: explicitly defaulted move constructor is implicitly deleted [-Wdefaulted-function-deleted]
    polyphase_filterbank(polyphase_filterbank&&) = default;
    ^
/home/ubuntu/xfer/gnuradio/gr-filter/lib/../include/gnuradio/filter/polyphase_filterbank.h:99:26: note: move constructor of 'polyphase_filterbank' is implicitly deleted because field 'd_fft' has a deleted move constructor
    fft::fft_complex_rev d_fft;
                         ^
/home/ubuntu/xfer/gnuradio/gr-fft/lib/../include/gnuradio/fft/fft.h:83:5: note: 'fft' has been explicitly marked deleted here
    fft(const fft&) = delete;
    ^
1 warning generated.
```

**Comment by ThomasHabets** [comment]
Declaring a default move constructor implies that there's a definition, and could risk a link error for users of this public header, right?

The current state is similarly deceptive to the code reader though, but is at least a compile time error. Maybe just delete the line?

**Comment by mbr0wn** [comment]
> Declaring a default move constructor implies that there's a definition, and could risk a link error for users of this public header, right?
> 
> The current state is similarly deceptive to the code reader though, but is at least a compile time error. Maybe just delete the line?

Agree with deleting.

**Comment by ThomasHabets** [comment]
Oh, while I don't disagree, I forgot to say that if `d_fft` is ever changed to be move constructible, then if we fix this warning we *won't* automatically make the polyphase filterbank movable. As-is it would be. So that's the only downside.

**Review by ThomasHabets — APPROVED** [review]

**Review by marcusmueller — APPROVED** [review]

**Pull request merged**
