### PR TITLE
gr-uhd enable/disable issue stream cmd on start

### PR DESCRIPTION
**Pull request by iohannez**
Please cross-check with Martin Braun

### CODE REVIEW

**Comment by mbr0wn** [comment]
This is OK. @iohannez and I discussed this beforehand. Note it'll probably break ABI because public factory function arguments change.

**Comment by mbr0wn** [comment]
...for this reason suggest putting into 3.8 (master).

**Comment by jmcorgan** [comment]
This needs rebasing off the next branch; there is a conflict there.

**Comment by trondeau** [comment]
This is not an API change. We've never considered adding a final argument with a default such in the past. This is fine to go onto master.

**Comment by mbr0wn** [comment]
Yeah, you're right -- I said 3.8, but what I meant was master.

**Comment by jmcorgan** [comment]
Ok, there is still an issue that this will not cleanly merge up into next.

**Comment by mbr0wn** [comment]
#709 will resolve the merge conflicts for you.

**Pull request merged**
