### PR TITLE
add missing includes to fix build with newer versions of GCC

### PR DESCRIPTION
**Pull request by danielnachun**
---
name: Pull Request Template
about: A template to help contributors submit clear pull-requests.
title: ''
labels: ''
assignees: ''

---

# Pull Request Details

## Description
On newer versions of GCC, `cmath` is not included by default and must be explicitly added with `include`.  If it is missing the build will fail because of undefined variables.

## Related Issue
Fixes the failure we saw in Homebrew CI on Linux: https://github.com/Homebrew/homebrew-core/pull/105154

## Which blocks/areas does this affect?
This has no runtime effects - it only fixes a compilation error.

## Testing Done
A patch with the same fix was run in https://github.com/Homebrew/homebrew-core/pull/105154 and the build now succeeds.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Hey @danielnachun! Thank you for working on the homebrew package, that is much appreciated.

I don't think this should have influence on the issue, as I consider the fix "include cmath if you use cmath functions" correct, but: what's the GCC version homebrew is currently using, where this happened?

**Comment by danielnachun** [comment]
We are using GCC 11.  I believe a lot of changes to default includes happened in GCC 10 as I’ve seen similar patches in other software that were needed after GCC 10 was released.

**Comment by danielnachun** [comment]
Yes we do use parallel builds with GCC, so there could be build order differences.  And we are using Ubuntu, which may handle the C++ stdlib a little differently.  In fact I wouldn't be surprised if Fedora even does some patching of `libstdc++` to maintain backwards compatibility with code written for older GCC that assumes more headers are included by default.  Interestingly, Clang + libc++ on macOS doesn't have any of these issues with missing `#include` statements even for very old code, which I suspect is because they wanted to maintain backwards compatibility as well.

**Comment by l29ah** [comment]
Same issue on Gentoo on gcc-12.

**Review by mormj — APPROVED** [review]

**Pull request merged**
