### PR TITLE
grc: generating a simple cpp qt-gui flowgraph fails

### PR DESCRIPTION
**Pull request by dl1ksv**
Generating cpp code for the simple flowgraph described in #2688 fails as
an include statement and a required link lib is missing.

This pr fixes this issue. More complex flowgraphs will still fail.

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>

### CODE REVIEW

**Comment by willcode** [comment]
Wow, painful but simple! How do we test that all those work and they don't have additional link deps?

**Comment by dl1ksv** [comment]
We do not have to care about link dependencies. They are handled by cmake. For example the audio sink depends on ALSA and OSS, but there is no entry in the corresponding yml file.
These dependencies are handled in gnuradio-audioConfig.cmake. 

I can't test if  you can valid cpp code for all referenced blocks, but at the moment no block can be used in cpp as linking fails for all of them.

**Comment by dl1ksv** [comment]
Next step: make gui_hint work!

**Comment by haakov** [comment]
I'm not quite sure about these changes. The `test_cpp` flowgraph in https://github.com/gnuradio/gnuradio/issues/2688 works for me on latest master after applying https://github.com/gnuradio/gnuradio/pull/4427

**Comment by dl1ksv** [comment]
@haakov I'm using a fresh build of the master branch on fedora 34. Sorry, I was not aware of your #4427 .
You are right , it's sufficient to add Qt5::Widgets to the target link libraries but including gnuradio::gnuradio-qtgui work ,too, as it has Qt5::Widgets  as dependency.

But if I replace in test_cpp the null sink by a waterfall sink ( your second commit already applied) , building fails with:

Scanning dependencies of target horn1
[ 50%] Building CXX object CMakeFiles/horn1.dir/horn1.cpp.o
[ 75%] Linking CXX executable horn1
/usr/bin/ld: cannot find -lgnuradio-qtgui
collect2: Fehler: ld gab 1 als Ende-Status zurück

Or just another example:

Replace  the null source by an analog signal source and try to build:
You get:

[100%] Linking CXX executable horn1
/usr/bin/ld: cannot find -lgnuradio-analog
collect2: Fehler: ld gab 1 als Ende-Status zurück
gmake[2]: *** [CMakeFiles/horn1.dir/build.make:136: horn1] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/horn1.dir/all] Fehler 2
gmake: *** [Makefile:103: all] Fehler 2

That is why my second commit is necessary.

**Comment by haakov** [comment]
Interesting! I'm travelling these days, but it'd be great if someone could try it out on an Ubuntu platform.

Are you compiling with LD_LIBRARY_PATH correctly set?

Relevant PR: https://github.com/gnuradio/gnuradio/pull/4263

**Comment by dl1ksv** [comment]
Yes,  LD_LIBRARY_PATH is correctly set, otherwise grc would not start. 
And in one of your comments to #4263 you propose the prefix in the yaml file.
That's just what my second commit does.
And in
https://github.com/gnuradio/gnuradio/blob/d84df80edaf1e8491a1b4fc208b407b7e5c5198c/grc/core/generator/cpp_templates/CMakeLists.txt.mako#L55

The lib is explicitly prefixed. So I think this is the right way to handle the links. And all the examples I tested work with this change.

**Comment by dl1ksv** [comment]
@haakov Meanwhile I have setup ubuntu 20.04 and testet against. There is no difference between ubuntu and fedora 33/34

To avoid the problems with the qtgui I set up a block without gui, just an analog source connected to a null sink. See attached flowgraph

[analog_source.grc.gz](https://github.com/gnuradio/gnuradio/files/6671398/analog_source.grc.gz)

If the link entry looks like 
link: ['gnuradio-analog']
in analog_sig_source_x.block.yml

linking fails with 

[ 50%] Building CXX object CMakeFiles/signal_source.dir/signal_source.cpp.o
[100%] Linking CXX executable signal_source
/usr/bin/ld: cannot find -lgnuradio-analog
collect2: Fehler: ld gab 1 als Ende-Status zurück
gmake[2]: *** [CMakeFiles/signal_source.dir/build.make:118: signal_source] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/signal_source.dir/all] Fehler 2
gmake: *** [Makefile:103: all] Fehler 2

but setting it to

link: ['gnuradio::gnuradio-analog']
the build succeeds without any error and you can run the executable.

**Comment by dl1ksv** [comment]
@haakov Meanwhile I have setup ubuntu 20.04 and testet against. There is no difference between ubuntu and fedora 33/34

To avoid the problems with the qtgui I set up a block without gui, just an analog source connected to a null sink. See attached flowgraph

[analog_source.grc.gz](https://github.com/gnuradio/gnuradio/files/6671398/analog_source.grc.gz)

If the link entry looks like 
link: ['gnuradio-analog']
in analog_sig_source_x.block.yml

linking fails with 

[ 50%] Building CXX object CMakeFiles/signal_source.dir/signal_source.cpp.o
[100%] Linking CXX executable signal_source
/usr/bin/ld: cannot find -lgnuradio-analog
collect2: Fehler: ld gab 1 als Ende-Status zurück
gmake[2]: *** [CMakeFiles/signal_source.dir/build.make:118: signal_source] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/signal_source.dir/all] Fehler 2
gmake: *** [Makefile:103: all] Fehler 2

but setting it to

link: ['gnuradio::gnuradio-analog']
the build succeeds without any error and you can run the executable.

**Comment by haakov** [comment]
Okay great! That convinces me that the `gnuradio::` prefix should be added.

**Pull request merged**
