### PR TITLE
Fix the 'dllexport' decoration

### PR DESCRIPTION
**Pull request by gvanem**

### CODE REVIEW

**Review by nickoe — APPROVED** [review]

**Comment by mbr0wn** [comment]
@gvanem Again, we need that Signed-off-by line.

**Comment by nickoe** [comment]
Ah this was the one with the dll export. This should be an easy one to amend the sign off on.

**Comment by nickoe** [comment]
@gvanem mmm, now you messed up your remote branch "patch-2" that did only contain the dllexport patch before.

**Comment by gvanem** [comment]
@nickoe I on the brink of deleting my GnuRadio fork and hence the PRs. After updating GitHubCLI just now and running
`gh.exe pr checkout 4013`, it bitches about tokens:
```
GraphQL error: Your token has not been granted the required scopes to execute this query. The 'name' field requires one
of the following scopes: ['read:org', 'read:discussion'], but your token has only been granted the: ['repo'] scopes. Ple
ase modify your token's scopes at: https://github.com/settings/tokens.
```
I've done that; no help.

**Comment by gvanem** [comment]
Well now the DCO has a green check-mark. OK now?

**Comment by nickoe** [comment]
@gvanem Sure, but the correct commit is not included in this pull request any longer. I don't know about the error you mention, I don't use GitHubCLI. I just use git directly.

**Comment by mbr0wn** [comment]
I *think* this was fixed by https://github.com/gnuradio/gnuradio/pull/4056. @gvanem, if that's untrue, sorry, and please reopen this.

**Comment by nickoe** [comment]
@mbr0wn That is correct.

**Pull request closed without merging**
