### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
---
name: Pull Request Template
about: A template to help contributors submit clear pull-requests.
title: ''
labels: ''
assignees: ''

---

## Description

Fix various user and non-user facing typos

## Related Issue

n/a

## Which blocks/areas does this affect?

n/a

## Testing Done

none

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by drmpeg** [comment]
For the include/*.h files you've changed, you have to update the hash in the corresponding pybind11 bind file.

For example, with fft_filter.h, you have to change gr-filter/python/filter/bindings/fft_filter_python.cc.

Just take the md5sum of the new .h file and edit the hash. For fft_filter_python.cc, dad8d136a3842f0e989324232efb2949 would change to 209a90728e0accc2186c762cf484e0ad.

**Comment by luzpaz** [comment]
Is there a script i can run to address the whitespace issue in https://github.com/gnuradio/gnuradio/runs/7772304164?check_suite_focus=true ?

**Comment by drmpeg** [comment]
That's been fixed with https://github.com/gnuradio/gnuradio/commit/bdd49943b6eda1004d5bf20e294639ee047ab40a

You do need to sign-off your last commit. When you take care of that, the CI will be triggered and all the tests should pass this time.

**Comment by luzpaz** [comment]
All tests have passed.

**Review by mormj — APPROVED** [review]

**Pull request merged**
