### PR TITLE
gnuradio-companion: add Meta modifier key for macOS

### PR DESCRIPTION
**Pull request by ra1nb0w**
implements support for the Meta key on macOS.
Others platforms continue to use Ctrl.

if you like, I also have the patch for maint-3.8

### CODE REVIEW

**Comment by ra1nb0w** [comment]
@michaelld what do you think?

**Comment by japm48** [comment]
For readability, I would suggest leaving `<Ctrl>` as it is in the shortcut table and use a `replace` as "post-processing" (i.e. [right here](https://github.com/gnuradio/gnuradio/blob/8e777117e10a70a57e138ddbe2144732a3469cfc/grc/gui/Actions.py#L128)).

I mean, something like: 
```self.keypresses = keypresses.replace("<Ctrl>", Utils.get_modifier_key(True))```

Also append: `markup = markup.replace(...)`
Just after markup assignment.

**Comment by ra1nb0w** [comment]
Can be optimized (I did in that way the first time) setting the `if platform == "darwin":` per file seen that `Actions.py` use `<Ctrl>` and `Dialogs.py` use `Ctrl`

**Comment by ra1nb0w** [comment]
@japm48 good idea unfortunately
```
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gnuradio/grc/gui/Actions.py", line 141, in __init__
    self.keypresses = self.keypresses.replace("<Ctrl>", Utils.get_modifier_key(True))
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by japm48** [comment]
Oh, OK; what about this?
```python
if keypresses:
    self.keypresses = [kp.replace("<Ctrl>", Utils.get_modifier_key(True)) for kp in keypresses]
else:
    self.keypresses = None
```

**Comment by ra1nb0w** [comment]
Done. thank you @japm48

**Comment by michaelld** [comment]
Tagging a couple other GR developers to look at this, just in case.

**Comment by michaelld** [comment]
Once this is done, I'd love to see a backport to maint-3.8

**Comment by ra1nb0w** [comment]
> Once this is done, I'd love to see a backport to maint-3.8

sure :)

**Comment by michaelld** [comment]
All CI passes. Changes just for OSX, and the primary maintainer (me) approves. Timeout for other reviews. Merging.

**Comment by ra1nb0w** [comment]
thank you! the backport https://github.com/gnuradio/gnuradio/pull/3390

**Pull request merged**
