### PR TITLE
filter_design: Update to pyqtgraph

### PR DESCRIPTION
**Pull request by noc0lour**
Based on the work of @ekigwana a draft PR for someone who is interested to pick it up.

### CODE REVIEW

**Comment by noc0lour** [comment]
Fixes part of #1634

**Comment by noc0lour** [comment]
@marcusmueller is eager to merge a not yet working state so someonelse can pick it up.

**Comment by marcusmueller** [comment]
rebased and pushed to retrigger QA; will have a look at code Mon or Tue

**Comment by noc0lour** [comment]
afaik no QA on filter_design or similar is run.

**Comment by mormj** [comment]
This is continued in #2495 which picks up from this point and includes the work of @ekigwana

**Comment by noc0lour** [comment]
Thank you @mormj !

**Pull request closed without merging**
