### PR TITLE
GRC: add Documentation URLs

### PR DESCRIPTION
**Pull request by marcusmueller**
GRC: enable setting of documentation URLs, relative or absolute in yaml

## Description

This allows OOT module developers to link to online or offline documentation, and allows us to disambiguate in-tree blocks with the same label, as currently, only the label is used to form the URL.

## Which blocks/areas does this affect?

GRC: Optional block field

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
This also properly aligns the link, and adds a tooltip that shows the URL:
Untitled

**Comment by marcusmueller** [comment]
And here with the custom URL in action:
Untitled2

**Comment by marcusmueller** [comment]
Note that we need to update the wiki on what to put into block yaml should we merge this.

**Comment by duggabe** [comment]
That looks good!

**Comment by marcusmueller** [comment]
The :globe_with_meridians: symbol only appears for URLs that aren't local (so, paths or starting with "file:")

**Comment by mbr0wn** [comment]
This is nice! I wonder if we should introduce namespaces for OOTs? Let's say a popular OOT (like gr-satellites) would like to use the wiki. What if all blocks that link from there have a "gr_satellites" prefix in the URL, without having to specify that for every block?

**Comment by mbr0wn** [comment]
In-tree blocks could maybe specify their own namespace somehow. These "FPGA" blocks have been abandoned, but we do plan to spruce them up. However, they have a special use case (building RFNoC images through GRC), so they're pretty special-case. They would warrant their own namespace.

**Comment by cafeclimber** [comment]
Imo if we were to open up the wiki to OOT modules, we should establish a documentation standard. E.g. all blocks must be documented including all parameters and functionality, etc

**Comment by marcusmueller** [comment]
I'd argue in line with @cafeclimber here; letting OOTs onto our wiki is akin to committing to co-maintaining their documentation. We'd put limits on that, especially because it limits what we can do to the wiki in the future without breaking whole ecosystems :) 

But! I don't think that was your main point, @mbr0wn; it was more whether modules should be able to define their own URL prefix. 

I think they shouldn't! (I was surprised to come to that conclusion, hence the exclamation mark.)

**Scenario**: an OOT with HTML files in docs/ ; or pages on a webserver with commonprefix

The overhead for adding the full URL vs the relative path to a URL prefix is probably negligible. The argument "making the prefix configurable for local installability" is a great one, and it's something that should be done at install time, statically string-replacing a relative path to a HTML file with the full installation path of the HTML file; installation of is the only time we know where the files end up. 

**Proposed solution**: have an 

```cmake
install_block_docs([DOWNLOAD]
                   File1… )
```
CMake command, which 

1. downloads the files from the specified URL when asked (`DOWNLOAD`) for it, 
3. installs the specified files to that target `${CMAKE_INSTALL_PREFIX}/${CMAKE_DATA_DIR}/docs/${CMAKE_PROJECT_NAME}/blocks/`

and amend our GRC block Yaml installation to respect a `[REMOVE_PREFIX prefix]` optional argument, to remove an URL prefix and replace it with `${CMAKE_INSTALL_PREFIX}/${CMAKE_DATA_DIR}/docs/${CMAKE_PROJECT_NAME}/blocks/`.

That way, the OOT maintainer can have absolute URLs pointing at whatever wiki/CMS/BTX page they want to. And it takes a flip of switch to download, install and correctly link to them.

**Side benefit**: same mechanism can be extended to download the in-tree block docs wiki pages.

**Pull request merged**
