### PR TITLE
Added parent (aka 'transient for') references to dialogs

### PR DESCRIPTION
**Pull request by courtarro**
First attempt at fixing #1494. For most dialogs, the `parent` window will be the `MainWindow`, but for dialogs opened by other dialogs, the `parent` will be the dialog that opened them. The deepest example of this is the Python Block's "Open in Editor" choice dialog, which itself triggers a file selection dialog.

Please test if possible. Not sure how to do any kind of automated testing on this.

### CODE REVIEW

**Comment by courtarro** [comment]
I'll be honest - I'm pretty confused by the testing results. I don't need to write code that works in both master _and_ next, do I?

**Comment by courtarro** [comment]
Fixed one goof in the missing XTerm warning dialog

**Comment by noc0lour** [comment]
@courtarro We still have issues with random test failures, if they are not related to your changes ignore them for now

**Comment by skoslowski** [comment]
(ignoring the tests)

This looks good to me. Thanks, @courtarro 

@jmcorgan this was already implemented as part of the GTK3 port and will produce conflicts. I will handle the merge on my repo

**Comment by marcusmueller** [comment]
As I'm not aware of the GTK3 development structure right now, can't merge this, although it looks very reasonable. Waiting for feedback from @skoslowski: Shouldn't we still be doing this on master right now?

**Pull request merged**
