### PR TITLE
Extend dot-graph generator to draw hierarchical blocks

### PR DESCRIPTION
**Pull request by iohannez**
Changed the implementation to use a stringstream pointer in flatten_aux that defaults to NULL.

### CODE REVIEW

**Comment by trondeau** [comment]
I feel like this is really intrusive just to support this feature. I don't like seeing us pull in flowgraph.h into hier_block2 code just for this purpose. Seems to add confusing if/else statements to what's already complicated enough code.

Also, I'm pretty sure that we already talked about not changing the block names for usrp_sink and usrp_source blocks, and this applies to the sub_ff block as well. These changes affect how the blocks are referenced and potentially called by other systems through the global registry. We will fix these in 3.8 API release, but we cannot change them on 3.7. We had an issue open on our issue tracker, but I cannot find it.

**Comment by iohannez** [comment]
Let's put the renaming of blocks aside then, we can do this separately in a future release as you said, I just didn't think about that again and it's not really that important.

However, for the feature of creating the hierarchical dot-graphs I am not sure what else to do then? I removed the separate flatten_aux function as you suggested here:
https://github.com/gnuradio/gnuradio/pull/370#issuecomment-73022920
so now that you don't like this either I have no idea how else we could solve this problem.

**Comment by trondeau** [comment]
Part of my reasoning is that you're basically the only one (or team) that really wants this. So it's hard to justify this kind of intrusion into the core code to support it.

As an alternative, could you use the top_block.edge_list() function and reformat it into the dot format? We use this model in gr-perf-monitorx to redraw the flowgraph in the client application. The minor downside to this is that the edge_list is empty until /after/ start is called. So you'd have something like:

tb = print_dot_graph()
print tb.dot_graph()
tb.start()
print tb.edge_list()
raw_input('Press Enter to quit: ')

The output for this (random graph I threw together) in the dot format is:
digraph flowgraph {
subgraph cluster0{ label="Print Dot Graph"
1 [ label="fir_filter_ccc" ]
2 [ label="fir_filter_ccc" ]
subgraph cluster3{ label="channel_model"
4 [ label="fractional_resampler_cc" ]
5 [ label="fir_filter_ccc" ]
6 [ label="add_cc" ]
7 [ label="fastnoise_source_c" ]
8 [ label="sig_source_c" ]
9 [ label="multiply_cc" ]
}
10 [ label="throttle" ]
11 [ label="null_sink" ]
12 [ label="null_sink" ]
13 [ label="delay" ]
14 [ label="sig_source_c" ]
}
14 -> 10
10 -> 13
13 -> 2
2 -> 12
10 -> 4
6 -> 1
1 -> 11
4 -> 5
5 -> 9
8 -> 9
9 -> 6
7 -> 6
}


And the edges list is:
sig_source_c1:0->throttle0:0
throttle0:0->delay0:0
delay0:0->fir_filter_ccc1:0
fir_filter_ccc1:0->null_sink1:0
throttle0:0->fractional_resampler_cc0:0
add_cc0:0->fir_filter_ccc0:0
fir_filter_ccc0:0->null_sink0:0
fractional_resampler_cc0:0->fir_filter_ccc2:0
fir_filter_ccc2:0->multiply_cc0:0
sig_source_c0:0->multiply_cc0:1
multiply_cc0:0->add_cc0:1
fastnoise_source_c0:0->add_cc0:0

It doesn't offer you the same subgraph grouping that you wanted, though.

**Comment by iohannez** [comment]
> Part of my reasoning is that you're basically the only one (or team) that
> really wants this. So it's hard to justify this kind of intrusion into the
> core code to support it.

Personally I would suggest that this kind of argument could also be more like a
self-fulfilling prophecy. Maybe the absence of such sophisticated debugging
tools (I could name some others but that would lead to an off-topic discussion)
causes the people to believe that GNU Radio should be only used in conjunction
with the companion and is not meant for any other "serious" work.
Also how do you come to the conclusion that nobody other than us wants this, if
it didn't exist so far? No offense but that doesn't sound perfectly valid. Or
are you talking about the dot-graph features that we had until now?

I can find a discussion on the mailing list suggesting to extend the
dot-graph features:
https://lists.gnu.org/archive/html/discuss-gnuradio/2014-10/msg00015.html
I find this a good idea as well. Maybe that could be done in a next step.

Actually it's a fact that if you build a flowgraph from pure python and C++
code then there is no way to obtain the information about it's hierarchical
structure in an automatic way. This can become very bothersome as your
flowgraph grows bigger and bigger and you really need to introduce hierarchy.

Probably the fact that the dot-graph feature is badly documented is the actual
reason why not many people are using it. So we should maybe rather discuss
about extending the documentation (which I would be willing to do if you would
let me know where exactly you would like to have a page written about this)
than if this is a useful feature.

What could be further done is to enable GNU Radio itself to generate the final
PDF(, PNG, JPG) of the flowgraph using the graphviz library in order to make
the feature more accessible.  At the moment we are doing this manually from the
command-line.  I imagine there could also be a button in the companion that
generates the PDF with a single click. Wouldn't that be great for all kinds of
documentation tasks?

So I actually believe that what we are talking about here is a very basic
feature and not something totally obscure that nobody would ever like to use.
I would agree though that it's probably not enough integrated and exposed to 
the user.

I don't understand this one:

> It doesn't offer you the same subgraph grouping that you wanted, though.

Do you mean that we can not get the hier blocks drawn with what you suggest?

**Comment by iohannez** [comment]
> #include <stdio.h>
> #include <gnuradio/flowgraph.h>
in hier_block2.cc was a mistake.
Obviously neither my student nor me did clean up properly after trying out the different ways to implement the feature.
I removed it and compiled again.
Those two lines are a left over and NOT necessary, so maybe that helps.

If you prefer, the if/else statements in flatten_aux could also be removed and we could always write the string(stream) into a dummy variable/stream if the pointer is NULL in the first recursion. I just prefered some checks instead of the dummy variable.

**Comment by trondeau** [comment]
I'm not going to argue with you about the popularity or demand for this feature. Neither of us have the numbers, but I have some perspective from where I sit on the project.

As for the feature request, you have conflated your argument. We started talking about this very specific feature -- representing the flowgraph and grouping the hier_blocks together in a dot format. You are now talking about the general usefulness of being able to get a general representation of the flowgraph. I agree with the latter proposition. Having the ability to ask the top_block for it's structure is a useful thing on many levels. I've known many people and projects (some of mine included) that would benefit from this. But we'd want that in some other data structure, probably with the ability to select if hier_blocks should be flattened or shown as single blocks. That structure could then be converted to any other format people might want for representation, including the dot format.

However, I was mistaken in the inclusion of flowgraph.h. That's already included in the file; it simply caught my eye and came up as a red flag. I don't particular like the if/elses in this case, but I'd rather them here than not -- seems to provide a better separation from the existing code.

I'll cherry-pick this in and fix up the extra include line. I'd still much rather see us restructure things that we can get a better, generic representation of the flowgraph than just the dot format, but that won't happen until at least v3.8.

**Comment by iohannez** [comment]
I agree to what you are saying.
Also having a flattened datastructure for the flowgraph that still includes the hierarchy sounds like a good thing.
However, I guess a discussion and an agreement among more people having enough insight into the GNU Radio core (I am not quite sure if that includes myself) would be necessary before beginning to hack around because I have to agree to your point of view that changes as we are doing here should be handled with care.
I am surely open to a more general and or nicer solution of my problem but meanwhile I believe that it is not too bad.

**Comment by trondeau** [comment]
Just waiting for copyright disclaimer.

**Comment by iohannez** [comment]
We are (still) waiting for a response from FSF.

**Pull request closed without merging**
