### PR TITLE
Remove MSVC shim header cruft, reduce CMake overhead

### LINKED ISSUE #1674: CMake: Be sure we still need all checks we do in 3.8

### LINKED ISSUE #1680: msvc: remove cmake/msvc/config.h
For more standard conformance we should strive to remove `cmake/msvc/config.h` as soon as possible.

Most of the things in there should be easy fixable.
 - inline -> __inline typedef for `C89`  We can check for C-Code and define in there, otherwise it's not needed in C++
 - `ptrdiff_t` -> `ssize_t` typedef can be removed if all `ssize_t` references are replaced with `std::ptrdiff_t` Edit: this is mostly used by code that can be written in a portable fashion.
 - MSVC < 1800 shouldn't be necessary if we use `C++11` since `C++11` and MSVC only play well together for MSVC >= 1800
 - random()/srandom() calls should be replaced with C++11 `<random>` library instead.

If we fix these things this header will be unecessary.

### PR DESCRIPTION
**Pull request by marcusmueller**
closes #1680, closes #1674

### CODE REVIEW

**Review by ryanvolz — CHANGES_REQUESTED** [review]
This looks good to my eye, with the caveat that additionally you'll need to remove `add_definitions(-DHAVE_CONFIG_H)` from `CMakeLists.txt` to get it compiling! A [conda build using these changes](https://github.com/conda-forge/gnuradio-feedstock/pull/36) compiles successfully with MSVC (and on Linux and macOS).

**Comment by marcusmueller** [comment]
I've removed the CMake Check cleanup, which is a separate issue (and now in #4256), and added in -DHAVE_CONFIG_H

**Comment by mbr0wn** [comment]
Introduces new warnings:
```
/__w/gnuradio/gnuradio/gr-blocks/lib/udp_sink_impl.cc: In member function 'virtual int gr::blocks::udp_sink_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)':
/__w/gnuradio/gnuradio/gr-blocks/lib/udp_sink_impl.cc:110:23: error: comparison of integer expressions of different signedness: 'std::ptrdiff_t' {aka 'long int'} and 'const size_t' {aka 'const long unsigned int'} [-Werror=sign-compare]
  110 |     while (bytes_sent < total_size) {
      |            ~~~~~~~~~~~^~~~~~~~~~~~
/__w/gnuradio/gnuradio/gr-blocks/lib/udp_sink_impl.cc:111:23: error: operation on 'bytes_to_send' may be undefined [-Werror=sequence-point]
  111 |         bytes_to_send = bytes_to_send =
      |         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  112 |             std::min(static_cast<std::ptrdiff_t>(d_payload_size),
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  113 |                      static_cast<std::ptrdiff_t>(total_size - bytes_sent));
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 36%] Building CXX object gr-zeromq/python/zeromq/bindings/CMakeFiles/zeromq_python.dir/pull_msg_source_python.cc.o
cc1plus: all warnings being treated as errors
```

**Review by mbr0wn — CHANGES_REQUESTED** [review]
Can you please fix the compiler warnings -- we no do `-Werror` where applicable.

**Review by mbr0wn — APPROVED** [review]

**Comment by mbr0wn** [comment]
Maybe merge the fixup UDP commit with the first one?

**Comment by mbr0wn** [comment]
Merged manually + squashed.

**Pull request closed without merging**
