### PR TITLE
doc: cleaning misc stuff

### PR DESCRIPTION
**Pull request by 777arc**

### CODE REVIEW

**Comment by 777arc** [comment]
Is that something I can do without making a new PR?

**Comment by mbr0wn** [comment]
Sure, just `rebase -i` and force push to the  branch. The PR auto-updates.

**Comment by 777arc** [comment]
Hmm didn't work >.<

**Comment by mbr0wn** [comment]
You changed the base branch. All you need to do is update your local branch accordingly (using rebase -i), force-push to the same remote you're using for the PR, and that's it.

**Comment by 777arc** [comment]
I accidentally removed the commits which auto-closed the PR it looks like, so I made a new one

**Pull request closed without merging**
