### PR TITLE
add and revise flowgraphs for qt_gui examples

### PR DESCRIPTION
**Pull request by duggabe**
resolves https://github.com/gnuradio/gnuradio/issues/1971
resolves https://github.com/gnuradio/gnuradio/issues/3411

### CODE REVIEW

**Comment by mrjacobagilbert** [comment]
@duggabe thank you for doing this, i think its great to have a complete set of examples. I looked at the FG from #3411 I had commented on, and I would suggest:

1) put the throttle between the source and freq_xlating_fir block and get rid of the null sinks

2) put a note or comment in the FG about what the freq_xlating_fir block is emulating (e.g.: a hardware device such as a USRP that is being tuned by a message). you and I understand that, but I don't necessarily think it is obvious to the users these examples are intended for

**Comment by mrjacobagilbert** [comment]
@duggabe message updates look good. not sure if you saw it or not, but the block comments on by default was addressed in #3432

**Comment by 777arc** [comment]
Looks good to me, the reference to an example in a different module is something we have never done before, but seems better than nothing

**Comment by 777arc** [comment]
Thanks for updating the example flowgraphs!  Merging

**Pull request merged**
