### PR TITLE
Replace SWIG with pybind11

### PR DESCRIPTION
**Pull request by mormj**
This is the collection of changes to replace SWIG with pybind11.  There will be many implications to the workflow and the API, and OOTs will have to be changed to be compatible with the pybind11 branch.

Things that are *known* to not be working at this point:
- ctrlport
- modtool disable
- qa tests: uncaught_exception, header_payload_demux, qa_uhd

Information on usage and workflow here:
https://github.com/gnuradio/gnuradio/blob/pybind/docs/PYBIND11.md
and detailed information about OOT porting is/will be here:
https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide

### CODE REVIEW

**Comment by mormj** [comment]
So the buildbots don't have pybind11 :(  Will have to figure out how to get that included since we have not vendorized at this point.

**Comment by noc0lour** [comment]
@mormj I kicked the PR runner and now they build (minus the forseen test failures)

**Comment by drmpeg** [comment]
Commit https://github.com/gnuradio/gnuradio/pull/3562/commits/3c302ef4c1655ff27c3f66a924d897a6fdd07060 fixes the issue of all bindings in a component being rebuilt when a module changes.

However, I believe the fix goes too far. When a docstring in a .h file is changed, the binding is not rebuilt.

**Comment by marcusmueller** [comment]
@drmpeg good point, will have to check that. I've merged nevertheless, because otherwise this gets stale and Josh ends up in an endless rebase loop...

**Comment by mormj** [comment]
@marcusmueller thank you for merging and adding issue #3578 has been added.
@drmpeg - this is a good catch, still I think the current state is better than the constant rebuilding of all modules, but I will look into how to get the docstring scraping run appropriately on individual files being changed.  Probably some better cmake magic than is currently implemented

**Comment by noc0lour** [comment]
Yeah, if you set up the depndencies correctly (not sure this is even possible) it should be able to run this automatically.

**Pull request merged**
