### PR TITLE
qtgui: removed imported firdes from yml files

### PR DESCRIPTION
**Pull request by Kurtle250**
## Description

Removed unused imported firdes modules that seem to be copied in from the python yaml template genarator file.

## Related Issue

Fixes https://github.com/gnuradio/gnuradio/issues/6507

## Which blocks/areas does this affect?

gr-qtgui/grc/qtgui_eye_sink_x.block.yml
gr-qtgui/grc/qtgui_freq_sink_x.block.yml
gr-qtgui/grc/qtgui_sink_x.block.yml
gr-qtgui/grc/qtgui_time_sink_x.block.yml
gr-qtgui/grc/qtgui_waterfall_sink_x.block.yml
gr-qtgui/grc/qtgui_time_sink_x.block.yml.py

## Testing Done

Tested all yaml files in validator to ensure no syntax errors and also reviewed all the files to make sure the libraries that were removed were not being used.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
@Kurtle250 thanks for the PR. You'll need to add a `Signed-off-by` line to your commit. The easiest way to do that is
`git commit --amend --signoff`, assuming your user and email are set up in your git client. Or you can add it manually to your commit message, with a blank line above it.

Have you tested code generation in Python and C++ after making these changes?

**Comment by Kurtle250** [comment]
@willcode No worries.  I am trying to learn so I can contribute more, so any feedback would be great. I believe I signed off the commit as you suggusted. Do you mean recompiling the whole package and doing the make tests?

**Comment by willcode** [comment]
Signoff - I don't see any updates here, so it's still not signed off.

Testing - since this PR changes code generation, we should be sure that the code GRC generates from flowgraphs using these blocks works correctly. Since there aren't any automated tests in this area, that would involve making minimal flowgraphs for each modified block to make sure it still operates, inspecting generated code, etc.

See the checklist, above. Make sure you can check off at least the first 4 boxes.

**Comment by Kurtle250** [comment]
# signed off
Okay I have amended my previous commit with the signed off, but should I force push the amended commit or should I make a new commit with the signed off added?

# Testing
For the testing I rebuild everything and tested the GUI's using two of the example flowgraphs, so I had a baseline for testing.
Example files used:
grc_qt_example.grc
qtgui_eye_sink_example.grc

All the graphs generated and seem to have full working functionality and the graphs, which use the FFT to generate the frequency response also are working.

**Comment by willcode** [comment]
Do a force push to replace the existing commit. Adding a new commit won't sign your original one, and we try to have a single commit per PR unless there's a reason to subdivide.

**Pull request merged**
