### PR TITLE
fix deadlock in unlock() when called from Python - #594 (resend)

### PR DESCRIPTION
**Pull request by pinkavaj**
Resend for pull request #416

### CODE REVIEW

**Comment by jmcorgan** [comment]
I had requested that you issue this pull request against the maint branch; also, you did not remove the do {} until(false); construct.

**Comment by jmcorgan** [comment]
The branch itself actually needs to be reimplemented as a branch off maint, of course.

**Comment by pinkavaj** [comment]
oops maint not main, fix latter thx.

**Comment by pinkavaj** [comment]
Ok, pushed corrected fix rebased on correct branch. Hope this one is OK.

**Pull request merged**
