### PR TITLE
RangeWidget: avoid double-changes

### PR DESCRIPTION
**Pull request by Sec42**
Small fix to the CounterSlider widget to avoid double change notifications.

### CODE REVIEW

**Comment by Sec42** [comment]
Assuming that CLA means Contributor Licence Agreement or something similar, please direct me to the appropriate place. "gnuradio cla" does not turn up any hits.

**Comment by devnulling** [comment]
@Sec42 please email bhilburn at gnuradio dot org to get the CLA process started. Thanks!

**Comment by ValZapod** [comment]
@Sec42 It will ask you to sign the contract with Free Software Foundation, you can use sign&Fill by Adobe (free on google play and iOS) to put a signature in a pdf. FSF does the same. No need to scan anything.

**Comment by dkozel** [comment]
CLA Done! Thanks!

**Comment by nickoe** [comment]
@Sec42 Should this be backported to maint-3.8?

**Comment by michaelld** [comment]
> @Sec42 Should this be backported to maint-3.8?

yes please let's do, if not already in the process of ...

**Pull request merged**
