### PR TITLE
gr-dtv: added GRC C++ generation

### PR DESCRIPTION
**Pull request by ncorgan**

### CODE REVIEW

**Comment by michaelld** [comment]
I've requested reviews from a couple more GR devs ... a few more eyes to confirm that this all looks good.

**Comment by drmpeg** [comment]
I would love to test this, but I need some help. How do I resolve the following error?
```
<<< Welcome to GNU Radio Companion 3.9.0.0-git >>>

Block paths:
	/opt/gnuradio-3.7.12git/share/gnuradio/grc/blocks

Loading: "/home/re/xfer/gnuradio/vv009-4kfftcpp.grc"
>>> Done

Generating: '/home/re/xfer/gnuradio/vv009_4kfft'

Executing: cmake .. && make &&  /usr/bin/gnome-terminal -e /home/re/xfer/gnuradio/vv009_4kfft/build/vv009_4kfft

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/re/xfer/gnuradio/vv009_4kfft/build
Scanning dependencies of target vv009_4kfft_autogen
[ 25%] Automatic MOC for target vv009_4kfft
[ 25%] Built target vv009_4kfft_autogen
Scanning dependencies of target vv009_4kfft
[ 50%] Building CXX object CMakeFiles/vv009_4kfft.dir/vv009_4kfft.cpp.o
In file included from /home/re/xfer/gnuradio/vv009_4kfft/vv009_4kfft.cpp:8:0:
/home/re/xfer/gnuradio/vv009_4kfft/vv009_4kfft.hpp:13:10: fatal error: gnuradio/top_block.h: No such file or directory
 #include <gnuradio/top_block.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/vv009_4kfft.dir/build.make:62: recipe for target 'CMakeFiles/vv009_4kfft.dir/vv009_4kfft.cpp.o' failed
make[2]: *** [CMakeFiles/vv009_4kfft.dir/vv009_4kfft.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/vv009_4kfft.dir/all' failed
make[1]: *** [CMakeFiles/vv009_4kfft.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

>>> Done (return code 2)
```

**Comment by mbr0wn** [comment]
@drmpeg Do you have some unusual installation path of GNU Radio? This is probably a bug, but it's also weird that CMake seems to find GNU Radio (or maybe it doesn't actually look?) and then gcc doesn't.

**Comment by drmpeg** [comment]
Yes, my install path is /opt/gnuradio-3.7.12git

Ignore the old name, just too lazy to update it.

**Comment by haakov** [comment]
I haven't seen that error recently, but I have a WIP branch called cppgen_modern_cmake that might fix it. However, I was able to build the vv009-4kfft example (without cppgen_modern_cmake) after 2-3 small changes to the resulting header and source file. 

I would also recommend using No GUI mode until gr-qtgui gets C++ generation support in master.

**Comment by haakov** [comment]
A few notes about said branch:

It hasn't been debased in a while. 

If you are using blocks from gr-X in your flowgraph and gr-X depends on gr-Y, you will have to add gr-Y to target_link_libraries manually.

**Comment by drmpeg** [comment]
At this point, I'm just going to wait for an update to C++ generation and revisit gr-dtv at that time. For now, I'm going to approve this PR.

**Pull request merged**
