### PR TITLE
soapy: completed API related to block's current functionality

### PR DESCRIPTION
**Pull request by ncorgan**
* Consistency in validate_channel() calls

Signed-off-by: Nicholas Corgan <n.corgan@gmail.com>

### CODE REVIEW

**Comment by willcode** [comment]
Looks good. I'll take a closer look tomorrow, try it out, and merge.

Do you have any idea about testing the whole interface? Does the dummy driver get built in, and can it be used?

**Comment by ncorgan** [comment]
The only testing to really be done would be making sure the right Soapy function is called for each function. Anything beyond that would turn into testing the underlying driver itself.

**Comment by willcode** [comment]
The null driver would allow for a couple of tests. It has no channels, so it would throw on most calls.

**Comment by willcode** [comment]
The SoapySDR types are in the SoapySDR namespace, where we've wrapped everything else into the `gr::soapy` namespace. Something seems a little asymmetric here. Ideas? The original, minimal wrapping was just enough to make things work. Now that it's full-featured, we could potentially have provided more direct access to the SoapySDR functions.

I think I still like the full wrapping, to make everything have a GNU Radio feel. Should we just `using` the types into `gr::soapy`?

**Comment by ncorgan** [comment]
The enum would become `gr::soapy::arginfo_t::Type`. Not ideal. How about `argtype_t`? I've already been using `argtype` as a parameter name.

**Comment by willcode** [comment]
I like that. It seems like a pain to have to rename/rewrap everything, but it keeps the API more consistent across gnuradio.

Minor thing: is there a way to make `SOAPY_SDR_ARG_INFO_BOOL` into just `ARGINFO_BOOL`, or really `gr::soapy::ARGINFO_BOOL`?

**Comment by ncorgan** [comment]
With this, we have `gr::soapy::BOOL`. If we want `gr::soapy::ARGINFO_BOOL`, we'd need a new enum, which means casting for each access.

**Comment by willcode** [comment]
Got it, thanks. I was looking in `Types.h` instead of `Types.hpp`.

I think this is all good.

**Pull request merged**
