### PR TITLE
GRC: enable displaying of variable IDs

### LINKED ISSUE #2235: Block ID's missing
Block ID's for Variable blocks are missing from 3.8. Seems like a useful feature to me.

New:

image

Old:

image

### PR DESCRIPTION
**Pull request by marcusmueller**
This was a regression from GRC 3.7: Variable IDs were no longer
displayed.

This restores that functionality for any block with the flag "variable".

This tags the Variable, Variable Config, Variable Struct, Parameter, and
Function Probe blocks with that particular flag.

Closes #2235.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Does that look OK, @drmpeg?

**Comment by haakov** [comment]
There are some variable blocks in gr-qtgui, should probably display their IDs too :)

**Comment by marcusmueller** [comment]
@haakov done

**Comment by haakov** [comment]
Wait, doesn't this break compatibility with older .grc files?  Removing the ID prefix, I mean?

**Comment by marcusmueller** [comment]
@haakov good point. Wish we had a "block alias" field that I could use to do this without breaking stuff, but you're right, we shouldn't be unnecessarily breaking .grc files. Let me rework that.

**Comment by mbr0wn** [comment]
@marcusmueller Is this still WIP?

**Comment by marcusmueller** [comment]
@mbr0wn oh! I have a version on my laptop that I simply forgot to push here.

**Comment by nickoe** [comment]
@marcusmueller Any update?

**Comment by noc0lour** [comment]
@marcusmueller push it (:

**Comment by noc0lour** [comment]
Apparently the commit is still missing.

**Comment by bastibl** [comment]
I think it's a good idea to introduce a flag to show the id of the block, but I'm not sure if we should tie it to variables. My understanding is that in some parts of the code a variable is something that has a `variable` flag (which actually just means that the id is shown). In other parts of the code a variable is something that has a `value` (and the semantics between the two are not differentiated). How about a `show_id` flag to show the id?

**Comment by drmpeg** [comment]
This PR can be closed. Superseded by https://github.com/gnuradio/gnuradio/pull/2568

**Pull request closed without merging**
