### PR TITLE
blocks: swig: split #2

### PR DESCRIPTION
**Pull request by michaelld**
blocks: swig: increase split from 5 to 10, to do a native build on low memory systems (e.g., RPi). Amazingly, the single new block added in b49f52f9 broke native build, so the prior split was fragile. This new spit leaves a significant margin for adding new blocks here and there without breaking native builds on low memory systems.

### CODE REVIEW

**Comment by michaelld** [comment]
WTF about all the other non-swig stuff? Not my fault I hope; I've no idea how that stuff got in here! @jmcorgan : can you make this PR work, or do I need to do a different one?

**Comment by jmcorgan** [comment]
Just guessing but it looks like you made the branch off master and then pull requested into maint.  This sort of thing would go into master anyway, so you might just try changing the base branch you're requesting in the PR to master.  You can do that that now in github without closing the PR.

**Comment by michaelld** [comment]
Hmm ... I don't see an obvious way to get GitHub to change the "merge into" branch. Thoughts?

**Comment by michaelld** [comment]
I'm closing this one & redoing from master. GitHub won't let me change the merge into branch once the PR is created.

**Pull request closed without merging**
