### PR TITLE
grcqt: Improve logging

### PR DESCRIPTION
**Pull request by dl1ksv**
## Description

grc has the comman line option --log, which can be set to debug. Doing so enables the debug log in Application.py but not in the depending classes.
For debugging the output of the called classes  would be important,too.

In gtk-grc we have  similar problem. See #4628.

I ported the solution proposed in #4628 to the gui_qt part and it works well for these classes.
## Related Issue

#4628

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by haakov** [comment]
I haven't tried this yet, but won't this mean that window.py becomes `grc.application.gnuradio.grc.gui_qt.components.window` if you run `gnuradio-companion --qt` ? (please correct me if I'm wrong :)

If so, maybe it's better to set the name explicitly, like we do here:
 https://github.com/gnuradio/gnuradio/blob/1e538fce67f3bf9e0ff450d97af15afe3b5d0093/grc/gui_qt/grc.py#L33C1-L33C43

**Comment by dl1ksv** [comment]
Yes, this is an short excerpt from the log:

2024-01-31 12:50:50,680 [DEBUG] Using QSettings from /home/schroer/.gnuradio/grc.conf (grc.application:50)
2024-01-31 12:50:50,680 [DEBUG] Creating QApplication instance (grc.application:53)
2024-01-31 12:50:50,770 [DEBUG] ARGV - ['/usr/local/gnuradio/bin/gnuradio-companion', '--qt', '--log', 'debug'] (grc.application:66)
2024-01-31 12:50:50,770 [DEBUG] INSTALL_DIR - /usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc (grc.application:67)
2024-01-31 12:50:50,770 [DEBUG] Creating main application window (grc.application:73)
2024-01-31 12:50:50,776 [DEBUG] Initializing MainWindow (grc.application.gnuradio.grc.gui_qt.base:43)
2024-01-31 12:50:50,776 [DEBUG] Connecting signals (grc.application.gnuradio.grc.gui_qt.base:60)
2024-01-31 12:50:50,776 [DEBUG] Setting the main window (grc.application.gnuradio.grc.gui_qt.components.window:66)
...............
2024-01-31 12:50:51,017 [DEBUG] Registering widget (Console, 8) (grc.application:128)

At the moment we get

2024-02-01 17:38:53,215 [DEBUG] Using QSettings from /home/schroer/.gnuradio/grc.conf (grc.application:50)
2024-02-01 17:38:53,215 [DEBUG] Creating QApplication instance (grc.application:53)
2024-02-01 17:38:53,315 [DEBUG] ARGV - ['/usr/local/gnuradio/bin/gnuradio-companion', '--qt', '--log', 'debug'] (grc.application:66)
2024-02-01 17:38:53,315 [DEBUG] INSTALL_DIR - /usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc (grc.application:67)
2024-02-01 17:38:53,315 [DEBUG] Creating main application window (grc.application:73)
2024-02-01 17:38:53,547 [DEBUG] Registering widget (Console, 8) (grc.application:128)

I think, seeing the whole module path in the log is OK.

**Comment by haakov** [comment]
@dl1ksv Hmm okay. I still think it's unnecessary to have such a long module path. Maybe we should get rid of "application" at some point, at the very least. 

But this is still an improvement! Merging once the merge conflict has been resolved.

**Review by haakov — APPROVED** [review]

**Comment by dl1ksv** [comment]
I resolved the merge conflict. Sorry for the delay.

**Review by marcusmueller — APPROVED** [review]

**Pull request merged**
