### PR TITLE
Make file_source accept a user-specified offset and read length

### PR DESCRIPTION
**Pull request by ckuethe**
http://gnuradio.org/redmine/issues/738

I'd like to be able to peek at small intervals from large recordings. I propose adding two parameters to file_source: offset and readlen...

I'd rather do this with a source block than by slicing up my source file with dd so that i can change the part of the file I'm reading at runtime, and so that I don't accidentally split and interesting signal in the middle.

### CODE REVIEW

**Comment by trondeau** [comment]
@ckuethe ping. Please respond or we will have to close this issue due to inactivity.

**Comment by garverp** [comment]
I'm really interested in this feature as well - I'd be willing to give this a push if needed.

**Comment by ckuethe** [comment]
Thanks for the wake-up call, I've been tinkering with other projects. Context-switching now :)

**Comment by jmcorgan** [comment]
ping

**Comment by jmcorgan** [comment]
Closing due to inactivity.  If you pick this up again, please submit a new pull request.

**Pull request closed without merging**
