### PR TITLE
gr-blocks: Fix file source block large file handling for Windows.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Review by ThomasHabets — COMMENTED** [review]
I don't think I have anything to say about this. Yes, [`_fstatd64` exists](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fstat-fstat32-fstat64-fstati64-fstat32i64-fstat64i32?view=msvc-160), and it seems that this brings `fstat` in line with the other calls here.  But that's about all I can say not knowing Windows.

**Comment by drmpeg** [comment]
This has been tested. See https://github.com/gnuradio/gnuradio/issues/3971 Also approved elsewhere https://github.com/gnuradio/gnuradio/pull/3976

**Comment by ThomasHabets** [comment]
I didn't mean to imply it's not been tested, just that I was added as a reviewer but am not competent in windows so I can't review aside from "sure, I don't see why not". In any case I don't have merging powers.

**Review by ryanvolz — APPROVED** [review]
I can confirm that this builds. I haven't personally verified that it fixes the large file problem but @MountainLogic says it does and that's good enough for me.

**Comment by mbr0wn** [comment]
I didn't test, but trust @ryanvolz and @mountainlogic's testing.

**Pull request merged**
