### PR TITLE
Remove CppUnit dependency

### PR DESCRIPTION
**Pull request by mbr0wn**

### CODE REVIEW

**Comment by mbr0wn** [comment]
And now for the killing blow! CppUnit is now gone.

**Comment by mbr0wn** [comment]
@marcusmueller I've also removed the hack that enabled C++11 for master when we have a newer CppUnit. However, I would suggest that we start enabling C++11 on master all the time.

**Comment by marcusmueller** [comment]
Fully Agreed. We shall have C++11 on master.

**Comment by marcusmueller** [comment]
heyyyy you smuggled a bugfix in there, didn't you ;) ! Would the missing FindPkgConfig Cmake statements be something I'd want to cherry-pick onto maint-3.7?

**Comment by mbr0wn** [comment]
@marcusmueller Good question, I think on maint the bug will never occur because the `find_package()` call for CppUnit always includes the other module. It's up to you, it's definitely more accurate with the bugfix.

**Pull request merged**
