### PR TITLE
Include cstdint in gr-fec's alist.h

### PR DESCRIPTION
**Pull request by chris-pcguy**
## Description

GCC 13 will error out otherwise.

## Which blocks/areas does this affect?

gr-fec

## Checklist

- [X] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [X] I have squashed my commits to have one significant change per commit. 
- [X] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [X] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Review by marcusmueller — APPROVED** [review]
Fair enough – this uses a `uint8_t`, and should include that header.

**Comment by marcusmueller** [comment]
@willcode  probably a candidate for backporting (potentially even to pre-3.10?); I don't think including that header has any expectable detrimental side-effects.

**Comment by willcode** [comment]
Is this causing compile problems for someone? As far as pre-3.10, it would only help people who pull from maint-3.9, since there won't be any more 3.9.X releases.

**Comment by marcusmueller** [comment]
True – older builds with modern GCC will be rare.

**Pull request merged**
