### PR TITLE
digital: Use little-endian for CRC32 regardless of platform

### PR DESCRIPTION
**Pull request by argilo**
## Description
Various CRC32 test cases fail on big-endian platforms. This occurs because they expect the CRC to be little-endian, while the blocks write the CRC in machine order.

I think it's justified to expect that these blocks behave the same on all platforms, so I've rewritten them to always use little-endian. This is technically a breaking change on big-endian platforms, but these platforms are very rare. I'd be surprised if anyone depends on the CRC32 blocks producing big-endian output there.

The failing tests are:

```
======================================================================
FAIL: test_crc32 (__main__.qa_crc32_async_bb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/gr-digital/python/digital/qa_crc32_async_bb.py", line 46, in test_crc32
    self.assertEqual(out_append, data + [0x88, 0xe2, 0xce, 0xce])
AssertionError: Lists differ: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 206, 206, 226, 136] != [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 136, 226, 206, 206]

First differing element 16:
206
136

- [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 206, 206, 226, 136]
?                                                                ----------

+ [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 136, 226, 206, 206]
?                                                       ++++++++++


----------------------------------------------------------------------
```

```
======================================================================
FAIL: test_002_crc_equal_unpacked (__main__.qa_crc32_bb)
Test unpacked operation with packed operation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/gr-digital/python/digital/qa_crc32_bb.py", line 193, in test_002_crc_equal_unpacked
    self.assertEqual(sink1.data(), sink2.data())
AssertionError: Lists differ: [[0, [211 chars], 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,[47 chars], 0]] != [[0, [211 chars], 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,[47 chars], 1]]

First differing element 0:
[0, 0[210 chars], 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,[46 chars]0, 0]
[0, 0[210 chars], 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,[46 chars]0, 1]

Diff is 898 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_003_crc_equal_unpacked (__main__.qa_crc32_bb)
Test unpacked operation with packed operation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/gr-digital/python/digital/qa_crc32_bb.py", line 218, in test_003_crc_equal_unpacked
    self.assertEqual(sink1.data(), sink2.data())
AssertionError: Lists differ: [[0, [835 chars], 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,[47 chars], 1]] != [[0, [835 chars], 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,[47 chars], 0]]

First differing element 0:
[0, 0[834 chars], 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,[46 chars]0, 1]
[0, 0[834 chars], 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,[46 chars]0, 0]

Diff is 2599 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_005_tag_propagation (__main__.qa_crc32_bb)
Make sure tags on the CRC aren't lost.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/gr-digital/python/digital/qa_crc32_bb.py", line 131, in test_005_tag_propagation
    self.assertEqual([len(data) - 5, ], [
AssertionError: Lists differ: [8] != []

First list contains 1 additional elements.
First extra element 0:
8

- [8]
?  -

+ []

----------------------------------------------------------------------
```
## Related Issue
* #6300 

## Which blocks/areas does this affect?
* Async CRC32
* Stream CRC32

## Testing Done
I verified that the tests pass on both amd64 (little-endian) and s390x (big-endian).

## Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] ~~I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.~~
- [x] ~~I have added tests to cover my changes~~, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Agree that there should be some standard endian. Do we want to make some across-the-board declaration that packet fields are in network order, instead of having it case-by-case what order things are in?

**Comment by willcode** [comment]
Sometimes CRCs are bit-reversed, so it could be that that is the intent here.

**Comment by argilo** [comment]
> Do we want to make some across-the-board declaration that packet fields are in network order

It's definitely worth considering that, since we already did it for CRC16 in #6096. The only reason I didn't take take that approach is that CRC32 has been in GNU Radio for a decade or so, so there's a greater chance of breaking someone's application.

**Comment by argilo** [comment]
The docs say very little about the CRC format. The Async block just says that the generator is 0x04C11DB7, and the Stream block says nothing at all.

**Comment by argilo** [comment]
It's also worth noting that the Async CRC16 and Async CRC32 blocks were deprecated in #6128. It might not make sense to change the behaviour of a deprecated block, since we want people to use the new CRC blocks anyway.

For Stream CRC32, we should probably just make a flexible replacement like what @daniestevez built in #5619 to replace the Async blocks.

**Comment by argilo** [comment]
> I verified that the tests pass on both amd64 (little-endian) and s390x (big-endian).

Oops! I hit the submit button on this before the 390x build was finished, and it turns out there are still some failures there. :facepalm:. Let me see what's going on.

**Comment by argilo** [comment]
Well of course they're broken, I fixed the generation but not the verification. Fixing now...

**Comment by argilo** [comment]
All fixed, and the tests now pass on s390x. For real! :smile:

**Review by daniestevez — APPROVED** [review]
Hi, I've taken a look at the code and it looks good to me.

I'll keep in mind the idea of extending the CRC implementation I did for PDUs to tagged streams so that it can be used to replace Stream CRC32. If I have time, I might implement this within the next few weeks.

**Pull request merged**
