### PR TITLE
CI/conda: convert conda logging groups to github logging groups

### PR DESCRIPTION
**Pull request by marcusmueller**
## Description

Conda logs for a single run on Linux are 23 MB (!), which makes them impossible to inspect on the web.

But, a lot of CI failures are found exactly that way, so we should make these logs accessible, if we're already spending so much work and CI time on generating them.

## Related Issue

Tried to figure out what went wrong on a CI build, needed to download the log archive, because githubs web UI was helpless.

## Which blocks/areas does this affect?

CI / conda

## Testing Done

this PR.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Definitely an improvement.

**Review by ryanvolz — APPROVED** [review]
This won't persist through a re-rendering of the conda CI scripts with `conda smithy rerender`, but since I'm the one who does that I can put in a little effort to merge those changes in instead of completely overwriting `.github/workflows/conda-build.yml`.

If you think this would also be useful to other people who might be using conda-smithy-provided CI on Github Actions (which the conda-forge feedstocks themselves don't use, instead using Azure), and you feel up for submitting upstream, then the place to do that would be https://github.com/conda-forge/conda-smithy/blob/main/conda_smithy/templates/github-actions.yml.tmpl.

**Comment by marcusmueller** [comment]
admittedly, was a bit of a hotfix!

**Comment by marcusmueller** [comment]
@ryanvolz looked through that template and then realized that merging this is still a good idea

**Pull request merged**
