### PR TITLE
grc: fix to allow loading flowgraphs with missing blocks

### PR DESCRIPTION
**Pull request by seeAppRun**
After a recent merge fixing some C++ code generation issues (merge request #2797), GRC now fails to load a flowgraph if it has any missing blocks.

### CODE REVIEW

**Comment by mormj** [comment]
This appears to fix a pretty ugly bug.  Just ran into it - let's get it merged quickly.

@seeAppRun - can you please rebase your commits down to 1?

**Comment by seeAppRun** [comment]
> Simple change, and makes sense. Please update the Copyright date and either rebase or squash all of the commits.

Sounds good. Just trying to figure out the git rebase syntax (haven't done this before and want to be sure before committing). I think I would need to `git rebase -i HEAD~6` and then `git push`?

**Comment by mormj** [comment]
Once you do rebase -i, you'll have to go in and put "s" for all but the first of your commits, then clean up the commit message.  After that you'll have to force push

**Comment by seeAppRun** [comment]
> Once you do rebase -i, you'll have to go in and put "s" for all but the first of your commits, then clean up the commit message. After that you'll have to force While push

While working through git rebase, somehow the merge request was closed. Not sure if it's possible to re-open or I should create a new one? (Sorry for the headaches. I don't mean to be learning git during commits.)

**Comment by mormj** [comment]
No worries at all.  Since this was a 1 line change, might be easier just to re-checkout master, create a new branch, then make a new pull request.

**Comment by seeAppRun** [comment]
> No worries at all. Since this was a 1 line change, might be easier just to re-checkout master, create a new branch, then make a new pull request.

Good deal! The new merge request is #3255.

**Pull request closed without merging**
