### PR TITLE
digital/chunks to symbols: be less inefficient (backport to maint-3.9)

### PR DESCRIPTION
**Pull request by marcusmueller**
This is essentially an exact replication of the patchset from #4901, but does not change the exported signature in the public header.

### CODE REVIEW

**Comment by willcode** [comment]
@marcusmueller Could you do the clang-format and let me know if this looks good, since the master version merged.

**Comment by willcode** [comment]
@marcusmueller Would you like me to update this one?

**Comment by mbr0wn** [comment]
@willcode Probably too late for the release, but I gave this one a push.

**Comment by willcode** [comment]
I'll put it in. It's been on master for a while.

**Pull request merged**
