### PR TITLE
README: fix indentation and formatting

### PR DESCRIPTION
**Pull request by michaelfm1211**
Currently, the README contains inconsistent indentation that makes the example commands look awkward. Different sections are also wrapped at different line widths. This commit fixes that.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Thanks for the doc update. Are you familiar enough with GNU Radio to review the content of the README, too?

A dev hint: create a git branch, for example `readme-work`, from `main` and create PRs from the new branch. No need to do this now. This allows you to work on multiple changes at once without running into rebasing issues.

**Comment by michaelfm1211** [comment]
Oops, sorry for creating a PR from main. I'm kind of new to contributing to open source, so thanks for the tip!

I don't think I know enough about GNU Radio and its development to scrutinize the README's content in depth. I did read through it but I didn't see anything that I thought was out of place, so I just submitted these formatting fixes.

**Comment by willcode** [comment]
@michaelfm1211 We'll hold this PR open for now. Someone may work on updating the information on this page and fix the indent in the process. Marking it "draft" in the mean time.

**Comment by willcode** [comment]
Replaced by #6747, which updates the content of the README.

**Pull request closed without merging**
