### PR TITLE
Eye sink

### PR DESCRIPTION
**Pull request by ChristopheSeguinot**
Hi 
As explained in the mailing list , I propose aQTGUI eye_sink GRC block. this PR comprise a GRC example to see it in action. 
I hope this can be included in GNURadio (at present, I was not able to construct this eye_sink as an OOT module)

Regards, Christophe

### CODE REVIEW

**Comment by michaelld** [comment]
Thanks for the submission, @ChristopheSeguinot ! You'll need to have a copyright assignment (CLA) in place for this level of code addition / change. We do this by email and postal mail, for better or for worse. I'll email you to get the process started.

**Comment by devnulling** [comment]
@ChristopheSeguinot Can you please squash all the commits for this branch into a single commit? 

A loose suggestion for the commit message would be something like:

`qtgui: Add Eye sink widget`

**Comment by devnulling** [comment]
@ChristopheSeguinot thanks for completing the CLA. We will need to fixup this git commit history/branch before we can merge it though. I'll try to put together some instructions to help out on this.

**Comment by marcusmueller** [comment]
Hi @ChristopheSeguinot,

I really tried to bring this changeset into a form that would it make it even technically possible to merge into master; sadly, it seems, that's impossible.

I'll need you to checkout current `master`, branch off a clean branch from that, and really pick over the files in the state you want them to appear in GNU Radio – I'd do that for you, really, but I've spent more than an hour trying to, and conflicts due to you partially reverting commits from the master branch really stood in way of any progress.

I very, very, very much apologize for this, but I see no chance of merging the current state of this eye_sink branch into master, and so I sadly have to close this PR :( Please don't feel set back by that! I'm really looking forward to merging your new, clean PR :) If in doubt, a `git fetch origin; git rebase origin/master` should go through on your branch without any issue, then it's ready to be merged by us.

**Pull request closed without merging**
