### PR TITLE
removed several readmes

### PR DESCRIPTION
**Pull request by 777arc**
either had no useful info, or outdated info that isn't worth keeping up to date

### CODE REVIEW

**Comment by mbr0wn** [comment]
Base branch is maint, though. Why is this even a branch?

**Comment by 777arc** [comment]
Oh I just made the changes like I am use to doing, using a separate branch and merging into maint.  What is the proper way?

**Comment by mbr0wn** [comment]
Everything goes into master. Stable branch maintainers can backport. However, the actual `maint` branch was superseded by `maint-3.7` and shouldn't even exist any more (that was more of a comment to @marcusmueller ).

**Comment by marcusmueller** [comment]
@mbr0wn we can't simply delete branches. There might be folks with build scripts that pull these, and there's definitely people that have their own branches based off maint, and those need to be able to correlate what they did in the past with the current state, no matter how dead maint is!

Deleting a branch changing history, so it'll never happen :( as much as I'd like to clean up this mess. I might want to change the README on that branch and add a big CMake warning, good catch.

**Comment by marcusmueller** [comment]
In the meantime, let me recreate this commit on master.

**Comment by marcusmueller** [comment]
manually cherry-picked per dea45c14abb5c4a76a507376198f954d01a74f9c

**Pull request closed without merging**
