### PR TITLE
[RFC] gr-pager: Add split message support

### PR DESCRIPTION
**Pull request by amboar**
Hi,

My aim in this series is to support sensible emission of split messages. FLEX is in active use in the SAGRN (South Australian Government Radio Network) for use by their emergency services, and at least in that deployment, messages can be split across more than one FLEX frame. As it stands gnuradio emits truncated messages for this case.

Some benefits of the series:

* The first patch adds test cases to capture behaviour for simple frame cases
* The third patch adds support for emitting complete pages when the content is split across frames

Now, some caveats (hence RFC):

* This is the first time I've written C++ let alone hacked gnuradio, so no doubt there is room for improvement
* The second patch rewrites `flex_parse_impl.{cc,h}`
* The memory management is more complex in the re-write (for a start, it uses the heap)

Now the re-write was well intentioned: The existing implementation is compact but does a lot to hide the relationships between elements of the FLEX frame; untangling the frame structure from the code was quite an adventure. However I feel that the re-write may be heading into the land of Enterprise Code, so I'm interested in feedback. I think there are still some opportunities for improving it but regardless, if there's no appetite for the re-write then I'm happy to smash support for split pages into the existing code.

Finally, I've tested the implementation with both the test suite and broadcast data, and also fuzzed the rewrite with AFL[1] at around 3hrs CPU time: no crashes were found and the hangs identified were spurious.

Hopefully it's an interesting contribution!

Cheers,

Andrew

[1] I can push the small patch creating a new executable to fuzz with if there's interest.

### CODE REVIEW

**Comment by jmcorgan** [comment]
It's really great that someone is working on this--I wrote the original demod code back in 1998 and ported it to GNU Radio in 2006.  There are many things about how the code works that can be improved, from the way the timing recovery works, to taking advantage of modern GNU Radio features like stream tags and messages.

That said, this whole component is being removed from GNU Radio in release 3.8, as it is better suited for reimplementation as an out-of-tree module.  Alas, I have not found the time to port the existing code into an OOT.

So, please stand by.  When I *do* get around to making the OOT, it will look rather different from the existing gr-pager.  I'll look through what you've done and see what I can incorporate.

Alternatively, if you wanted to take the initiative to do this yourself--create a new OOT module with gr_modtool, then migrate the existing code as-is into it--that would be an excellent learning experience and win you GNU Radio fortune and fame.  This would be with the existing, known-working code, so it would mostly be a mechanical exercise.

With that basis, then we could improve it in the ways I mentioned above and also with the contributions above.

**Comment by amboar** [comment]
Oh, interesting! I'll have a go at making it an OOT module and report back. It might be a day or so before I get to it.

**Comment by amboar** [comment]
@jmcorgan Okay, I've pushed up the code extracted from the tip of master:

https://github.com/amboar/gr-pager

It appears to build okay, but I haven't yet done any testing. I've also pushed a branch containing a `gr-pager.lwr` to my gr-etcetera fork:

https://github.com/amboar/gr-etcetera/commits/gr-pager

If that looks okay I'll apply my series to gr-pager in a separate branch and push it up. But that does leave the question of the best way to review the changes for this pull-request.

**Comment by jmcorgan** [comment]
gr-pager has already been removed from the next branch (which will become 3.8), so no need for that.  I'll get to testing the OOT fairly soon, but I expect that if it is all working, you'll become the new owner of this OOT, and *I'll* be send you pull requests.

**Comment by jmcorgan** [comment]
I'll go ahead and close this here, and we'll pick things up on the OOT repo.

**Comment by amboar** [comment]
No worries. My local testing suggests the OOT module is working as expected.

**Comment by amboar** [comment]
See also gnuradio/gr-etcetera#25

**Pull request closed without merging**
