### PR TITLE
Remove all examples depending on and references to message_s{ource,ink}

### LINKED ISSUE #1024: code refers to nonexisting message_sink/message_source block (branch: next)
See result of:

git grep message_sink
git grep message_source

affceted files: error_rate.py, tx_voice.py, packet.py, blocks_blocks.rst, index.rst

Those blocks/examples are unusable because of nonexisting message blocks.

### PR DESCRIPTION
**Pull request by marcusmueller**
Fixes #1024.

Note that this only removes non-functional code which should have been
removed when message_s{ink,ource} were removed.

This also means that we'll need new narrowband examples (#1958).

### CODE REVIEW

**Comment by marcusmueller** [comment]
Since this is a topic related to having demonstratable software, I'll need a review from someone advising students: @jdemel, would you take that chance?

**Comment by jdemel** [comment]
@marcusmueller I can do this. But it'll take some time. I'm still working on other 3.8 related issues at the moment.

**Comment by michaelld** [comment]
Looks like `gr-digital/python/digital/pkt.py` also has a `message_source` ...

**Comment by michaelld** [comment]
Otherwise LGTM, for what it's worth ;)

**Comment by marcusmueller** [comment]
Wow, good catch! Thanks, @michaelld !

**Comment by michaelld** [comment]
YW! L(really)GTM now!

**Pull request merged**
