### PR TITLE
modtool: Resubmit swapnils work rebased on current master

### PR DESCRIPTION
**Pull request by noc0lour**
Superseds #1873 . Comments most likely still apply.
@swap-nil7 i'll close the the old pullrequest and if you want you can submit commits on a personal branch of yours (just tell me the name) and I'll pull them in here.

### CODE REVIEW

**Comment by noc0lour** [comment]
I'm actually not so sure about the changes I had to do in the `wip` commit, it certainly needs a sane message.

**Comment by mbr0wn** [comment]
...that's a lot of commits. Do we want to squash them (or some of them)?

**Comment by noc0lour** [comment]
I actually don't know. Also I tried to keep your progress from the hackfest in the changes. But some might have been lost due to big refactoring in this PR.

**Comment by jdemel** [comment]
@noc0lour I suggest to merge this PR asap. I know this might introduce bugs but right now. Though, current modtool is basically useless because it creates outdated OOTs. The sooner people can use this new modtool version, the better. Also, this would move modtool to a kind of beta test stage. And 3.8 is in this stage too.
Or are there any issues that would prohibit this approach?

**Comment by noc0lour** [comment]
Hm, I don't see any obstacles aside from my `wip` commit message, which I will fix right now.

**Comment by noc0lour** [comment]
If @mbr0wn can live with that he can merge it once I changed the commit message.

**Comment by noc0lour** [comment]
@mbr0wn in this case I also would suggest creating a merge commit ;) since probably none of the commits are really bisectable.

**Comment by noc0lour** [comment]
I'll squash some of the commits and merge myself once I'm done.

**Comment by noc0lour** [comment]
With only one commit left I wil lrebase & merge (:

**Comment by noc0lour** [comment]
Ok, anything else will be fixed accordingly.

**Pull request merged**
