### PR TITLE
docs: Add markdown styling to README

### PR DESCRIPTION
**Pull request by mhostetter**
I took the liberty to add markdown to the GitHub README. I don't know exactly what you guys want, so I took a whack at it and will let you guys tell me what you want/don't want.

Some things I added/changed:

* GNU Radio logo (won't work until merged as I added the logo png to the docs/ folder)
* License and docs shields from http://shields.io (we can add a build passing/failing shield once continuous integration is added)
* Introduction (taken from gnuradio.org)
* PyBOMBS build instructions (I think this is the method we are recommending)
* Polished formatting and added markdown to manual source build instructions
* I kept the Known Incompatibilities and Notes sections, although they seem out of date (not sure what you guys want to do here)

Let me know your thoughts.

### CODE REVIEW

**Comment by mbr0wn** [comment]
Should probably rename to `.md`. The pure ASCII readmes are pretty standard for GNU projects though.

**Comment by jmcorgan** [comment]
It is renamed to .md, actually, but this creates another problem, in [GrPackage.cmake](https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GrPackage.cmake#L107), where it references the name of the README.

**Comment by mhostetter** [comment]
@jmcorgan I fixed the [GrPackage.cmake](https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GrPackage.cmake#L107) issue.

I welcome all other thoughts.

**Comment by skoslowski** [comment]
2 years ago there was another PR for this, #319.
I am still in favor of using markdown, as long as the ASCII view is readable.

**Comment by mhostetter** [comment]
I didn't realize the legacy/controversy of this issue. I'm fine with whatever direction the core devs want to take.

**Comment by jmcorgan** [comment]
I'm myself am okay with the idea of using markdown.  I'm hoping more people will chime in here about that, and as importantly, the content itself.

**Comment by jmcorgan** [comment]
I'm still looking for community comments on this, but given the age of the PR and the :+1: as the only thing heard so far, I'll be merging it soon.

**Comment by mhostetter** [comment]
Some things I think we (the community) should discuss before merging are:

* Do we want the PyBOMBS section? And is that our suggested installation method?
* What about the old Known Incompatibilities and Notes sections? Can we remove them or do they still provide value?

**Comment by mbr0wn** [comment]
Todos, notes, known issues, etc. should be kept separate. PyBOMBS section, I vote for we keep it here. We do endorse PyBOMBS, after all.

**Comment by mhostetter** [comment]
I fixed a few minor typos and removed the Known Incompatibilities and Notes sections.

**Comment by mhostetter** [comment]
I also changed the "docs" shield to point to the doxygen page, not the wiki.

**Comment by jmcorgan** [comment]
I think it would be more useful if the file maintained a column 72 margin, so that reading it as plaintext is easier.

**Comment by mhostetter** [comment]
@jmcorgan I did my best to limit the column size to 70-ish. Let me know if you think I can do more. (There were a couple links I couldn't reduce...)

**Comment by mhostetter** [comment]
@jmcorgan thanks! I think it looks good :smiley:

**Pull request merged**
