### PR TITLE
Windows audio sink refactor

### PR DESCRIPTION
**Pull request by gnieboer**
Refactored windows audio sink to use multiple buffers, eliminates skipping sounds when nperiods and period_time are set within reason.  
Default values should work fine for most.  Set verbose=true to see additional info. 
Output device can be set to either the ordinal number of the device to use, or the string name of the device.  Setting a string in verbose mode will also display a list of choices in the console on run

### CODE REVIEW

**Comment by jmcorgan** [comment]
A big issue with this is all the gratuitous white space changes--it is very hard to tell which is a change to actual code vs. it just showing up because of spacing.  We'd really prefer it if you could stick to the original coding style found in almost all GNU Radio code.

**Comment by gnieboer** [comment]
Mea Culpa.

Fixed, new commit added.

**Comment by jmcorgan** [comment]
Thanks for the cleanup.  Can you squash these three to a single commit?

**Comment by gnieboer** [comment]
Down to two... couldn't seem to convince github not to show the merge, but all the content is in 03669f5

**Comment by jmcorgan** [comment]
Ok, I'm merging this blind, as I have no means of testing it, but since the changes are limited to internal files that are Windows only, the risk is low.

**Pull request merged**
