### PR TITLE
digital/chunks to symbols: be less inefficient

### PR DESCRIPTION
**Pull request by marcusmueller**
The block formerly took the tags from `get_tags_in_range` (which are sorted),
gave them to `tag_checker`, which sorted them, and then went through every
input sample, checking its index against the next tag.

Removed the tag_checker; that saves us a sorting of a sorted vector per work call.

The other optimization is to not dispatch any tag encountered to the own
message handler; instead, the handler is called directly.

Found #4898 while doing this.

### CODE REVIEW

**Comment by marcusmueller** [comment]
hand-wavy Benchmarking:

benchmark_chunks_to_symbols

Vector source affinity `[1]`, C_t_S affinity `[0]`

State  |  Rate of indexes per second | Speedup over baseline
-------|--------------------------------------|--
Before| 9.28·10⁷ | 100%
After | 43.2·107 | 466%

**Comment by marcusmueller** [comment]
@willcode um, you added the backport tag, but a backport will require you to undo the public header changes (which boil down to using const and unsigned where applicable); I didn't think you'd want to backport this, sorry :(

**Comment by willcode** [comment]
Changing int to unsigned where the value already had to be unsigned should be compatible, right?

The const changes are private.

**Comment by willcode** [comment]
@marcusmueller Given that the only user of D() is probably Python, which doesn't care ... if you think someone will use -Wsign-conversion -Werror, then we can keep the API the same and cast internally. Or, if you really don't want this backported at all, that's also fine - let me know.

**Comment by marcusmueller** [comment]
> Changing int to unsigned where the value already had to be unsigned should be compatible, right?

It does change the function signature in a way that the mangling changes, so it's at least an ABI break. 

If anyone inherits from `chunk_to_symbol`, changing of signedness, at it means the function signatures aren't compatible anymore, would also be breach of API.

I don't mind this being backported, but I do think the signed->unsigned thing warrants me patching the commit.

**Comment by willcode** [comment]
I always thought of the mangled signature as ABI. Will have to read up on opinions. Practically, it's likely harmless here, but I agree we should try to do the "right thing".

**Comment by marcusmueller** [comment]
@willcode #4905 :)

**Comment by marcusmueller** [comment]
> I always thought of the mangled signature as ABI.

And I'd agree. 

But the thing is: in C++, you can't override a `unsigned int foobar(int)`  method with a `int foobar(unsigned int)` function, or use them in the same `std::function` type and so on; separate types!

**Review by mormj — APPROVED** [review]

**Pull request merged**
