### PR TITLE
analog: Change noise_source seed type to uint64_t

### PR DESCRIPTION
**Pull request by bgottula**
Type of `seed` in noise_source was inconsistent with fastnoise_source
and with the random number generator classes. This makes everything
consistent.

Signed-off-by: Brett Gottula <bgottula@gmail.com>

---
name: Pull Request Template
about: A template to help contributors submit clear pull-requests.
title: ''
labels: ''
assignees: ''

---

# Pull Request Details

## Description

Type of `seed` in noise_source was inconsistent with fastnoise_source
and with the random number generator classes. This makes everything
consistent.

## Related Issue

Addresses part of #5959

## Which blocks/areas does this affect?

analog/noise_source

## Testing Done

None, but willing to if the automated test coverage is not sufficient.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Review by marcusmueller — APPROVED** [review]

**Comment by marcusmueller** [comment]
OK, I think I fixed this issue! @bgottula: could you do something like, on your branch, 

```shell
git pull https://github.com/marcusmueller/gnuradio.git bgottula-fix-noisesource-seed-type
git push
```

to add my small fixes to your pull request?

**Comment by marcusmueller** [comment]
Went ahead and quickly squashed the two identical commits that I made you introduce, sorry!

**Comment by marcusmueller** [comment]
by the way, did someone already compliment you on this work? It's awesome to have you fix that long-standing issue, and in such a well-sorted-out manner! Thank you.

**Review by willcode — APPROVED** [review]
LGTM. Maybe someone else can do a quick check of the bindings.

**Pull request merged**
