### PR TITLE
Remove 'friend' from 'read_wavein' callback function

### PR DESCRIPTION
**Pull request by cozycactus**
## Description
Resolves build issue in MSYS2 MinGW64 environment

## Which blocks/areas does this affect?
gr-audio 

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
There's still an extra commit in there. See if you can squash and do a force push - no need to create a new PR for that. Otherwise, I'll squash when this merges.

@ryanvolz Tagging you because this touches Windows. Is there anyone else who might want to take a look?

**Review by ryanvolz — APPROVED** [review]
Evidently this still works with MSVC, so no issues from me for conda purposes. I can't comment from a C++ correctness standpoint, but being able to compile is a good indicator...

**Review by argilo — APPROVED** [review]
I'm not enough of a C++ expert to comment on the style, but I can confirm that the Audio Source still works correctly after this change. (I built in a Conda environment.)

**Comment by argilo** [comment]
> Resolves build issue in MSYS2 MinGW64 environment

Could you provide the details of the issue (e.g. the compiler error)?

**Comment by cozycactus** [comment]
> > Resolves build issue in MSYS2 MinGW64 environment
> 
> Could you provide the details of the issue (e.g. the compiler error)?

https://github.com/cozycactus/gqrx/actions/runs/6907732208/job/18795508774

**Pull request merged**
