### PR TITLE
audio: fix use of 'memcpy' in OSX impl.

### PR DESCRIPTION
**Pull request by michaelld**
subject says it all. From #1204 .

### CODE REVIEW

**Comment by jmcorgan** [comment]
Any reason this can't go on maint for 3.7.11.1?

**Comment by michaelld** [comment]
Nope. I can redo from maint if that's the right place. My GIT repo defaults to master, so "checkout -b" always uses it.

**Comment by michaelld** [comment]
Moved to maint & there are 69 commits WTF? & LOL!

I guess you can do this, or I can redo the actual branch to be off of maint. Let me know. NP either way.

**Comment by jmcorgan** [comment]
Yeah, you need to rebase the single commit off maint, then force push to your branch on github.

**Comment by michaelld** [comment]
OK. Try this version now.

**Comment by jmcorgan** [comment]
Worked, thanks.

**Pull request merged**
