### PR TITLE
updates to waterfall for suchsamples

### PR DESCRIPTION
**Pull request by namccart**
bit of cleanup to suchsamples commit

bugfixes

... Adding a message port to work with O'Shea's such samples tools...

### CODE REVIEW

**Comment by jmcorgan** [comment]
@trondeau this needs your review

**Comment by trondeau** [comment]
Two big issues and a couple small nits on this one.

First, this only changes the complex version of the widget. Any changes should work on both float and complex. Second, there's no example or QA for using it.

The style of spacing/indents is off in a lot of places, too. I'd also like to change it from "such_samples" to something like just "pdu" -- so the handle being called "handle_pdu".

**Comment by namccart** [comment]
Hopefully, I can do this next week.  Having an example requires having such
samples (not a part of gnuradio)... If I just have a grc flowgraph that
expects such samples blocks, is that good?

We can talk about spacing on Monday...

Cheers,
Nick M.

**Comment by trondeau** [comment]
Yeah, I think that the PDU handling should just take in PDUs of samples and plot them. Just take the message, apply the FFT of the given length on it, and add it to the plot. So we should be able to come up with a simplified example that just creates a PDU of samples for that purpose.

Regarding spacing, not much to talk about :)
http://gnuradio.org/redmine/projects/gnuradio/wiki/Coding_guide_impl

Honestly, this isn't a huge problem as I'll likely just "fix" it myself on my look through the code. There are some styles that I'll push back on; this was just a request.

**Pull request merged**
