### PR TITLE
runtime: Prefs cleanup (backport to maint-3.9)

### PR DESCRIPTION
**Pull request by willcode**
Cleanup of the code.
Actually using the mutex.
Safer preference writing using atomic rename.

Backport https://github.com/gnuradio/gnuradio/pull/4504

### CODE REVIEW

**Comment by willcode** [comment]
C++ 14 does not have filesystem::path. Make C++ 14 friendly.

**Comment by willcode** [comment]
@ThomasHabets - I can look at this later, but if you get to it first ...

**Comment by ThomasHabets** [comment]
Looks like a clean apply of same commit? Code looks good. I should try running it too, but LGTM.

**Comment by willcode** [comment]
Clean apply, but it didn't work. Something about push_back of filesystem::path to a vector of string (see CI runs).

**Comment by ThomasHabets** [comment]
Looks like boost has missing `operator string` on path.

**Comment by ThomasHabets** [comment]
… and needs member method `.string()` to push back.

**Comment by willcode** [comment]
The string for push_back is easy enough, but there is also something with boost::system for errors. Is this important enough to fiddle with deps for a backport, or should it be a 3.10 thing?

**Comment by willcode** [comment]
Closing, this will be a 3.10 change.

**Pull request closed without merging**
