### PR TITLE
GRC: Port templates to mako

### PR DESCRIPTION
**Pull request by stwunsch**
The gui part (grc/gui) is fully ported, but the flowgraph generation is still using cheetah. I try to port the rest of grc as well and keep the pull request updated.

### CODE REVIEW

**Comment by stwunsch** [comment]
Note: mako version needs to be adjusted to minimum possible version

**Comment by skoslowski** [comment]
Stefan, thanks for taking some initiative here. 

Unfortunately, this has already been taken care of as part of our current GUI port to GTK3 (which will be merged to next as soon as we deem it stable enough).

I do however welcome help with the generator template. If you want to work on this, please contact me beforehand. We already discussed some changes we want to make there.

(please issue GRC PRs againt the grc repo)

**Comment by stwunsch** [comment]
Volk is ported as well: [Volk PR 94](https://github.com/gnuradio/volk/pull/94) (I can't link it from here?)

**Comment by stwunsch** [comment]
ah ok, then I close this! wasn't much work, so not a problem.

**Comment by stwunsch** [comment]
@skoslowski So still what has to be done? Porting the template part (everything in grc/generator/)? There is a public discussion about this?

**Comment by skoslowski** [comment]
Well, looks like I never came around to add some notes to the GRC call...

**Pull request closed without merging**
