### PR TITLE
grc: make node states consistant

### LINKED ISSUE #5779: Adding node sets `state: true` disabling and enabling it sets `state: enabled`
### What happened?

When I add a node to my flowgraph, the `.grc` file will contain a line

```
state: true
```

If I disable that node, the line switches to

```
state: disabled
```

and if I re-enable the node, it switches to

```
state: enabled
```

I think the value `true` is incorrect and it should be `enabled` instead.

### System Information

OS: Arch Linux
GR Installation Method: Conda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1. Add a node. The file says `state: true`
2. Disable it. The file says `state:disabled`
3. Enable it. The file says `state:enabled`

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by haru-02**
## Description

Changed just a single line as pointed in issue #5779.
Just a good first issue.
## Related Issue

Fixes #5779 

## Testing Done

All previous tests pass. make test successful.
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by mormj** [comment]
Hi @haru-02 - thank you for your submission - happy to have a new contributor!  A couple of notes that make it easier for us to review and merge:
1) Please make the title of the github issue more descriptive - e.g. something like "grc: make node state value consistent"
2) Same goes for the commit - the commit log is not linked with github, so it is not necessary to indicate the github issue in the commit

Please update the git commit ( `git commit -s --amend`) and force push

**Comment by willcode** [comment]
@haru-02 Take a look at the new title. Formats like that (module: short description of change) make it easier to manage our list of PRs. Using the same title as the first line of the commit (with a blank line after) will do this automatically.

**Comment by haru-02** [comment]
@willcode @mormj thanks for the feedback, i will make the changes to the title now and push again. Will keep this in mind when i maek the next PR.

**Comment by willcode** [comment]
@haru-02 Would you still amend the commit with this new line? Git commits shouldn't usually mention Github commits or PRs, and the first line needs to be descriptive, e.g., same as the title of this PR.

**Comment by haru-02** [comment]
yes, will do it now.

**Comment by haru-02** [comment]
@willcode changed it, hope that helps :smile: . I will make sure to write the commit messages in a more descriptive format next time.

**Comment by haru-02** [comment]
closing this because I made a Pr from main branch of my fork, may get things mixed up, will make a PR again.

**Pull request closed without merging**
