### PR TITLE
cmake GSL cleanup

### PR DESCRIPTION
**Pull request by bastibl**
continuation of https://github.com/gnuradio/gnuradio/pull/1195

### CODE REVIEW

**Comment by jmcorgan** [comment]
@horvathp @michaelld

**Comment by bastibl** [comment]
Just to add one data point, I tested it with the next branch on macOS and a recent homebrew.

**Comment by horvathp** [comment]
It seems to work for me after upgrading to gsl-2.3.

Interestingly, it is still broken, as it used to be, with gsl1 (or gsl@1 as homebrew calls it nowadays). Homebrew people might have recently fixed something around gsl2, as gnuradio didn't seem to compile (for me) with gsl2 previously. But if gnuradio is happy, I'm happy, too :)
Peter

**Comment by bastibl** [comment]
@horvathp Thank you for testing! For me it also works with gsl@1, but good to have a build that fails :-) Any chances you don't use the bottled version of gsl@1 and the compiled version doesn't have the install_name set?

Would be great if you could do a
`otool -D /usr/local/opt/gsl@1/lib/*.dylib`
(with the folder where you have gsl@1 installed).

**Comment by horvathp** [comment]
I can't reproduce anymore the state which I had earlier, gsl-1 is keg-only now. One would have to fiddle with compiler flags anyway to be able to build with gsl-1.

As a side note, I'm still wondering why the -lgsl syntax instead of linking with the dylib, see below. I'm not sure if this is an issue, but nevertheless.

[100%] Linking CXX shared module _dtv_swig.so
cd /Users/hp/src/gnuradio/build/gr-dtv/swig && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_link_script CMakeFiles/_dtv_swig.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -std=c++98 -O3 -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o _dtv_swig.so CMakeFiles/_dtv_swig.dir/dtv_swigPYTHON_wrap.cxx.o -Wl,-rpath,/usr/local/lib -undefined dynamic_lookup ../lib/libgnuradio-dtv.3.8git.dylib -L/usr/local/Cellar/gsl/2.3/lib -lgsl -lgslcblas -lm ../../gr-analog/lib/libgnuradio-analog.3.8git.dylib ../../gr-filter/lib/libgnuradio-filter.3.8git.dylib ../../gr-fft/lib/libgnuradio-fft.3.8git.dylib /usr/local/Cellar/fftw/3.3.6-pl1/lib/libfftw3f.dylib /usr/local/Cellar/fftw/3.3.6-pl1/lib/libfftw3f_threads.dylib ../../gr-fec/lib/libgnuradio-fec.3.8git.dylib ../../gr-blocks/lib/libgnuradio-blocks.3.8git.dylib ../../gnuradio-runtime/lib/libgnuradio-runtime.3.8git.dylib ../../gnuradio-runtime/lib/pmt/libgnuradio-pmt.3.8git.dylib /usr/local/lib/liblog4cpp.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib -lgsl -lgslcblas -lm ../../volk/lib/libvolk.1.3.0git.dylib /usr/local/Cellar/orc/0.4.26/lib/liborc-0.4.dylib
[100%] Built target _dtv_swig

**Comment by bastibl** [comment]
You're right. One would have to manually add it to the `PKG_CONFIG_PATH` or `--force` link the keg.

I don't think that `-lgsl` is a problem. But note that the command that you posted seems to be from a compilation without the above patches. The `-lgsl -lgslcblas -lm` is  what was deleted.

**Comment by horvathp** [comment]
I'm on next, I've manually removed the ${GSL_LDFLAGS} thingy from gr-dtv.
Still, they are there when linking fec, wavelet AND dtv. 
But the main concern is, why does CMake find the -lgsl variant in the first place, instead of the .dylib?

./build/CMakeCache.txt:1193:GSL_LDFLAGS:INTERNAL=-L/usr/local/Cellar/gsl/2.3/lib;-lgsl;-lgslcblas;-lm
./gr-fec/swig/CMakeLists.txt:44:set(GR_SWIG_LIBRARIES gnuradio-fec ${GSL_LDFLAGS})
./gr-wavelet/swig/CMakeLists.txt:42:set(GR_SWIG_LIBRARIES gnuradio-wavelet ${GSL_LDFLAGS})

**Comment by bastibl** [comment]
Maybe you have to wipe you build directory.

These libs are not really "found", but are from pkg config
```
basti@tronn /usr >> cat /usr/local/opt/gsl@1/lib/pkgconfig/gsl.pc 
prefix=/usr/local/Cellar/gsl@1/1.16
exec_prefix=/usr/local/Cellar/gsl@1/1.16
libdir=/usr/local/Cellar/gsl@1/1.16/lib
includedir=/usr/local/Cellar/gsl@1/1.16/include
GSL_CBLAS_LIB=-lgslcblas

Name: GSL
Description: GNU Scientific Library
Version: 1.16
Libs: -L/usr/local/Cellar/gsl@1/1.16/lib -lgsl ${GSL_CBLAS_LIB}  -lm 
Cflags: -I/usr/local/Cellar/gsl@1/1.16/include
```

**Comment by horvathp** [comment]
I have wiped it. But anyway, it's working, so hey.

**Comment by michaelld** [comment]
I'll test later today. A quick "grep" off fec and dtv looks like this is appropriate.

**Pull request merged**
