### PR TITLE
Update license header to SPDX format

### PR DESCRIPTION
**Pull request by devnulling**
~~Submitting to run BB~~

This PR switches all files to use the standard SPDX header format: https://spdx.org/

All files retain their same license (some files are still GPLv2)

### CODE REVIEW

**Comment by michaelld** [comment]
(1) Is there a GREP for this?

(2) Can we get rid of the Copyright lines?

(3) If not (2), should they be updated to include 2020? Can they be abbreviated down to "X-2020"?

I honestly don't recall the rules for Copyright years. Not sure it matters, TBH. Just asking for the sake of it :)

**Comment by devnulling** [comment]
Fixed up the few missed GPLv2 files:

```
% grep -c "version 2" 04d850bb758e983583fd3276b00ec6b86b7359cc.patch 
88

% grep -c "SPDX-License-Identifier: GPL-2.0-or-later" 04d850bb758e983583fd3276b00ec6b86b7359cc.patch         
88

% grep -c "version 3" 04d850bb758e983583fd3276b00ec6b86b7359cc.patch                                
2609

% grep -c "SPDX-License-Identifier: GPL-3.0-or-later" 04d850bb758e983583fd3276b00ec6b86b7359cc.patch
2609
```

**Comment by devnulling** [comment]
Couple outstanding places where the full license header is at. Should these be changed as well?

Auto generated:

https://github.com/gnuradio/gnuradio/blob/master/gnuradio-runtime/include/pmt/pmt_serial_tags.h

Inline: 

https://github.com/gnuradio/gnuradio/blob/master/gnuradio-runtime/python/gnuradio/ctrlport/gr-ctrlport-monitor#L441-L445

https://github.com/gnuradio/gnuradio/blob/master/gnuradio-runtime/python/gnuradio/ctrlport/gr-perf-monitorx#L221-L225


Modtool template:

https://github.com/gnuradio/gnuradio/blob/master/gr-utils/python/modtool/templates/templates.py#L32-L49

https://github.com/gnuradio/gnuradio/blob/master/gr-utils/python/modtool/templates/templates.py#L51-L69

**Comment by mbr0wn** [comment]
Definitely the latter for consistency. The others, meh, let's move on.

**Comment by devnulling** [comment]
```
grep -c "version 2" 3a863de237813a5528bdadc340b702a97d1e00ad.patch                                
88

grep -c "SPDX-License-Identifier: GPL-2.0-or-later" 3a863de237813a5528bdadc340b702a97d1e00ad.patch 
88

grep -c "version 3" 3a863de237813a5528bdadc340b702a97d1e00ad.patch                                
2612

grep -c "SPDX-License-Identifier: GPL-3.0-or-later" 3a863de237813a5528bdadc340b702a97d1e00ad.patch
2612

```

**Pull request merged**
