### PR TITLE
gr-dtv: move init_pilots from work to init

### PR DESCRIPTION
**Pull request by reisub-de**
Instead of recomputing the pilots for each symbol, generate a list in the constructor and just read the pilots from this list

### CODE REVIEW

**Comment by noc0lour** [comment]
So, the first commit has my CLA on it, the second I don't know about, probably the work of @reisub-de there

**Comment by marcusmueller** [comment]
First commit is challenge-specific and not an appropriate specialization for upstreaming; so while we have CLA for the first commit, we don't have for the second, and thus, not for the overall PR.

**Comment by mbr0wn** [comment]
@reisub-de We're still very happy with the contribution and the code, but until the CLA situation is cleared we can't merge this (not because of technical, but because of legal reasons).

It would be great to see you (or other authors) resubmit this PR against the latest master, but we need to make sure that:
- All commits are attributed to the correct author, either by virtue of the commit author being the code author, or by using `Signed-Off-By` (`git commit -s`).
- All authors have submitted a CLA to GNU Radio.

Thanks again for your work, and I hope we can this merged in the future.

**Comment by mbr0wn** [comment]
@reisub-de My bad, I was cleaning up PRs, but we actually did have permission to merge this. I'll combine them into their own new PR for going through BBot again, then we can merge.

**Pull request closed without merging**
