### PR TITLE
Code reformat 3.7

### PR DESCRIPTION
**Pull request by marcusmueller**

### CODE REVIEW

**Comment by michaelld** [comment]
For my edification, how does one do clang-format / clang-tidy / whatever we're doing here?

**Comment by marcusmueller** [comment]
@michaelld one runs `tools/clang-format.py format` from the root of the source tree (it's on master, I should have checked it out onto maint-3.7).

When one wants to reformat a single file, it's just `clang-format -style=file -i filename.cc`.

**Comment by marcusmueller** [comment]
Maybe we should be documenting this in CONTRIBUTING?

**Comment by michaelld** [comment]
@marcusmueller Thx! I really had no idea. Yeah I'd encourage noting something about how the files are formatted, and how to do formatting for PRs ... CONTRIBUTING seems like a legit place for that.

**Comment by marcusmueller** [comment]
Squash before merge!

**Comment by mbr0wn** [comment]
@michaelld et al: I highly recommend using a git pre-commit hook to verify your patch is of valid formatting. I use this one (this is not an endorsement use at own risk etc.): https://github.com/barisione/clang-format-hooks/

**Comment by michaelld** [comment]
@mbr0wn cool; thx!

**Comment by mbr0wn** [comment]
@marcusmueller @michaelld We don't actually have a CONTRIBUTING file. We have README.hacking (which we might want to rename to CONTRIBUTING.md) and we have the GREP1, which I just modified and made you two reviewers for the PR.

**Comment by mbr0wn** [comment]
@marcusmueller Looks like we're down to the usual test failures right? Merge time?

**Pull request merged**
