### PR TITLE
gui: Update colors.py for better contrast in dark mode

### PR DESCRIPTION
**Pull request by kdriedger**
## Description
Properties dialog for modifying values was hard to see because of low contrast.

## Testing Done
Opened all the different types of properties (like string, int, bool).

## Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [ ] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
@kdriedger Thanks for the contribution.

Please read about the required DCO signoff under `Details` next to the DCO line above.

Could you add before/after screenshots so people can see what they think?

**Comment by kdriedger** [comment]
Signed the DCO.

Before Screenshot:
before-patch-Screenshot

After Screenshot:
after-patch-Screenshot

**Comment by kdriedger** [comment]
My algorithm for deciding on contrasting colors was to take #FFFFFF minus the <current value>.

Seems to be usable in dark mode now.  

Perhaps someone has an opinion on better colors.

**Comment by willcode** [comment]
@kdriedger Please squash the two commits and sign the result (all commits need to be signed, not just the latest).

We'll see what people think. In my opinion, the colors should still be darker an less vibrant, though it is more readable than the original.

**Comment by kdriedger** [comment]
@willcode , I believe that I've squashed the two commits and signed them.  Thanks for your feedback.

**Comment by willcode** [comment]
@kdriedger Now you have 3 commits, including one that's not yours.

**Comment by mbr0wn** [comment]
Can you please:
```
git checkout <your branch>
git rebase -i main
```

The latter will open an editor and let you squash your stuff. Just replace `pick` with `fixup` or `squash`.

**Comment by kdriedger** [comment]
> The latter will open an editor and let you squash your stuff. Just replace `pick` with `fixup` or `squash`.

Will do.  Thanks for the help!

**Comment by kdriedger** [comment]
I did the `rebase` and `drop`'ed the commits that were not pertinent to this PR.  

The 'Files changed' tab looks good but I still see 7 commits.

Is there more I need to do?

**Comment by kdriedger** [comment]
If this is still not working, I've redone the whole PR from scratch on another branch and another PR.  

I can reopen that one and we can proceed that way.

It's super clean and includes all the learning from this PR.

**Comment by willcode** [comment]
Close this one when you open the new one. Also add the screenshots to the new one so people can see them more easily.

**Comment by kdriedger** [comment]
@willcode , I closed this PR and opened the new one:
https://github.com/gnuradio/gnuradio/pull/6722

Hopefully you'll find it better.   

Thanks so much for your feedback!

**Pull request closed without merging**
