### PR TITLE
gr-video-sdl: Fix YUV formats.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Review by willcode — APPROVED** [review]
Removes an extra /2, changes incorrect enum to int, fixes comments. Looks OK to me. Did not try it.

**Comment by drmpeg** [comment]
@willcode If you want to try it, here's the test package. Beware, it's a large file - 662,396,510 bytes.

http://www.w6rz.net/sdltest.tar.gz

**Comment by willcode** [comment]
Tested all 3 modes using the provided files (byte input). Entire frame is now in color in 4:4:4 with this patch, as in 3.9.

**Review by mormj — APPROVED** [review]
LGTM

**Comment by mormj** [comment]
QA failures are unrelated to the PR.  Merging

**Pull request merged**
