### PR TITLE
qtgui: bugfix - display tags on the last sample

### LINKED ISSUE #2775: QT GUI Time Sink doesn't display tags on the very last sample
A tag on the very last sample is not displayed.  It works from the first sample to the next to last.

### PR DESCRIPTION
**Pull request by jasonuher**
fixes #2775

Signed-off-by: Jason Uher <jason.uher@jhuapl.edu>

### CODE REVIEW

**Review by mormj — APPROVED** [review]

**Comment by mormj** [comment]
@jasonuher - the logic here looks sound - is it still WIP, or is this all of them?

**Comment by willcode** [comment]
@jasonuher Is this still a WIP? If so, you can hit "convert to draft" under Reviewers, and remove "WIP" from the title. Same with the other PR with "WIP" in the title.

**Comment by jasonuher** [comment]
> @jasonuher Is this still a WIP? If so, you can hit "convert to draft" under Reviewers, and remove "WIP" from the title. Same with the other PR with "WIP" in the title.

Not really sure.  I need to figure out what's going on with the tests, but I'll do the 'draft' piece in the mean time.

**Comment by jasonuher** [comment]
@mormj  is this the same issue with the tests (but a different one?)  We can cherry pick just the first commit and I can mark this as ready if so

**Comment by willcode** [comment]
You can also just squash the commits (or they can be squashed in the merge). Don't worry about tests like packetheader that fail half the time.

**Review by willcode — APPROVED** [review]

**Pull request merged**
