### PR TITLE
digital: addresses issue #890.

### PR DESCRIPTION
**Pull request by trondeau**
The set_taps was redone a while ago to better handle the differential
taps as well as the normal ones, but this made externally resetting
them impossible. Adding a new update_taps function to properly handle
this case so as to not change the API. We should fix this in 3.8.

### CODE REVIEW

**Comment by trondeau** [comment]
I'd like Rich to check this out in his example to make see if he finds any other side effects before merging.

(see http://gnuradio.org/redmine/issues/890)

**Comment by which988** [comment]
I just tested the pfb change taps fix, but it doesn't seem to make a difference.

I pulled the latest from git, version 3.7.10git-75-g13b69807 and recompiled gnuradio. I then deleted the old pfb block from my grc just to make sure, regenerated the new top_block.py, instantiated it in a python script and tried to set the rolloff after instantiation. It failed with the same error:

Traceback (most recent call last):
File "radio_devel/scripts/multisim_python/pcodes_multi_sim.py", line 549, in <module>
main(radio_option)
File "radio_devel/scripts/multisim_python/pcodes_multi_sim.py", line 244, in main
tb.set_samp_symb(sample_per_symbol) # problem using this pfb_filter
File "/home/rbell/Documents/pcodes/radio_devel/scripts/multisim_python/pcodes_bpsk_stream_FEC_loopback_nogui.py", line 190, in set_samp_symb
self.set_pfb_filter(firdes.root_raised_cosine(self.nfilts_pfb, self.nfilts_pfb*self.samp_symb, 1, self.rolloff, self.nfilts_pfb*11*self.samp_symb+1))
File "/home/rbell/Documents/pcodes/radio_devel/scripts/multisim_python/pcodes_bpsk_stream_FEC_loopback_nogui.py", line 374, in set_pfb_filter
self.digital_pfb_clock_sync_xxx_0.set_taps((self.pfb_filter))
File "/usr/local/lib/python2.7/dist-packages/gnuradio/digital/digital_swig.py", line 25566, in set_taps
return _digital_swig.pfb_clock_sync_ccf_sptr_set_taps(self, *args, **kwargs)
TypeError: Required argument 'ourtaps' (pos 3) not found

Rich

**Comment by trondeau** [comment]
Added additional fix to this to update the .grc file to use the new update_taps for the callback.

Commit: 5c00c2d688bd95cde8550e75030e27a7ef4dc657

**Comment by which988** [comment]
This fix did it. Works now.

**Pull request merged**
