### PR TITLE
boost: qualify placeholders with their full namespace. (Backport to 3.8)

### PR DESCRIPTION
**Pull request by noc0lour**
This is needed with boost >= 1.73.0.

This is just a backport of #3489

### CODE REVIEW

**Comment by noc0lour** [comment]
failing Ubuntu 18.04 test is unrelated, message passing \o/

**Comment by jdemel** [comment]
I suggest to move to lambdas instead of fully qualified placeholders. @ThomasHabets benchmarked them and the result was basically: use lambdas.

**Comment by noc0lour** [comment]
Is there a separate path for master we can backport? I really don't mind which solution is chosen, I just want to compile it on my machine ;)

**Comment by jdemel** [comment]
You could use #3441 and just change those 2 lines in `basic_block` such that you use `boost::function` instead of `std::function` again.
Unfortunately, the development history of this PR was, I want `std::function` and then I fixed all the issues that arose. Instead of, let's just move to lambdas and then just do the trivial switch to `std::function`.

**Comment by noc0lour** [comment]
Will see that I can pull out the lambda commit and apply it on 3.8.

**Comment by mbr0wn** [comment]
Inactive, needs rebase, closing.

**Pull request closed without merging**
