### PR TITLE
Renamed doc to docs so it would render nicely on GitHub

### PR DESCRIPTION
**Pull request by bogdanr**
Also it makes it all consistent because some of these have the directory named docs.

### CODE REVIEW

**Comment by noc0lour** [comment]
@jmcorgan Yes, no? I'd recommend squashing the commits and force pushing on your branch, but it's a trivial improvement.

**Comment by jmcorgan** [comment]
I'm a little confused at the goal of this PR, can you elaborate?

**Comment by bogdanr** [comment]
This module has the dir named docs:
https://github.com/gnuradio/gnuradio/tree/master/gr-zeromq
and this one doc:
https://github.com/gnuradio/gnuradio/tree/master/gr-vocoder

The naming is not consistent and as you can see, in the first case github renders documentation out of the box, which makes it a bit more user-friendly.

**Comment by noc0lour** [comment]
And it would make naming consisten across all modules (:

**Comment by mbr0wn** [comment]
Manually merged.

**Pull request closed without merging**
