### PR TITLE
Add github Issue and PR templates

### LINKED ISSUE #2611: Add Issue and PR templates
The awesome folks over at Ettus Research have a fancy Issue and PR template. We should use one like it. 

https://raw.githubusercontent.com/EttusResearch/uhd/master/.github/ISSUE_TEMPLATE.md

https://raw.githubusercontent.com/EttusResearch/uhd/master/.github/pull_request_template.md

### PR DESCRIPTION
**Pull request by devnulling**
# Pull Request Details

## Description
This PR adds the special files for github Issue and Pull Request templates

## Related Issue
Fixes #2611

## Which areas does this affect?
github issues and PRs

## Testing Done
N/A

### CODE REVIEW

**Comment by noc0lour** [comment]
Second this. @marcusmueller wasn't in favour last time I raised this.

**Comment by marcusmueller** [comment]
@noc0lour, I was not not in favor of this.

I was not in favor of "just doing it without consideration and just based on loose anecdotal evidence it's good for a community", and I'm still not. 

What has changed is that people that are directly involved in GR have tested this for a year in a project. So, we're not flying blind here.

**Comment by marcusmueller** [comment]
@devnulling so, I like these!

Couple of questions:

* The pull request template is in a different folder than the issue template. Is that intentional?
* When I go into github's tree of uhd/.github/ISSUE_TEMPLATE.md, it says "You're using an old version of issue templates"; is this different?

**Comment by devnulling** [comment]
@marcusmueller 
>The pull request template is in a different folder than the issue template. Is that intentional?

That is an error, I'll submit a different PR with the changes below.

>When I go into github's tree of uhd/.github/ISSUE_TEMPLATE.md, it says "You're using an old version of issue templates"; is this different?

It looks like there is a new option to have a different template for Feature Requests and Bug Reports. I think this is a better format!

**Pull request closed without merging**
