### PR TITLE
grc: Move menu init debug log to MainWindow.py

### PR DESCRIPTION
**Pull request by mpentler**
This code belongs in MainWindow and not Application since the menu is
created in there. Additionally the commented-out code block below it
can also come out.

Signed-off-by: Mark Pentler <xxxxxx>

# Pull Request Details
A small one to get something in for October and get used to sending in PRs.

## Description
The menu is created in MainWindow.py and not Application.py, so I have moved the logging statement across and removed the commented-out code below it.

## Related Issue
#4628 is still an issue here, so the statement isn't actually run. If you do change the logging initialisation statement to reference `'grc'` instead of `(__name__)` then the statement does run as intended. I am interested in looking further into this issue.

## Which blocks/areas does this affect?
grc output logging

## Testing Done
As noted above, tested by somewhat hamfistedly getting logging to work from that source file, and seeing the output as intended in my console window. I haven't really changed anything major, so not sure how much work is required here.

## Checklist
You'll note I haven't filled all of these in, and I am wondering how important it is given what I've changed. Happy to do the extra work needed. My change only had one commit - do I need to squash?

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/master/CONTRIBUTING.md).
- [ ] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/master/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/master/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by mpentler** [comment]
Er - I thought it'd change emails. Sorry, very new to this and panicking a bit now.

**Comment by mpentler** [comment]
A little alarmed at having my email address in the commit - I stupidly put it in the message as I thought you had to do that, and now I am panicking about exposing it.

I am quite new to this kind of thing.

**Comment by willcode** [comment]
@mpentler Commits usually do contain a valid email address, though it's not a requirement. You can always create an email that you use for open source project work only. If you amend the commit, using a new address or no address at all, and then do a force push, your info will be replaced. Of course, everything that happens on the internet is forever :-)

**Comment by mpentler** [comment]
Sure - it may be worth doing tomorrow when I get a chance, won’t happen now. Thinking about it now I’ve probably exposed it in the past somewhere else so it’s not a huge deal if I don’t, I think…

**Comment by willcode** [comment]
@mpentler Not sure what you meant to do with that last commit, but you probably were trying to overwrite the first one and didn't. Also, any commits still need a Signed-off-by line.

**Comment by willcode** [comment]
@mpentler You can just rebase, shouldn't merge upstream commits into your PR. Best to rebase on the upstream master, squash to one commit (in this case at least) and force push.

**Comment by mpentler** [comment]
Just to confirm - are you looking for me to reset/revert the last merge commit? If I can get away with doing that and then a squash would that do it? It would leave behind one single signed commit. As you say, probably no need to rebase if I’m going nowhere newly-changed code.

I can get this done tomorrow and then hopefully that should be it ready.

**Comment by mpentler** [comment]
Your patience with me is admirable. I think at this rate I would just like to delete this PR, junk the branch, and make the changes again. I was scared off reverting those commits because it also leaves a commit, and I didn’t think that’d fly.

My other PR has gone much better, and I learned a lot from this process with you, so it hasn’t been a total loss.

**Pull request closed without merging**
