### PR TITLE
Explicitly set the size of the gengen templates

### PR DESCRIPTION
**Pull request by marcusmueller**
This leads to the following typemap:

s: int16_t
i: int32_t
f: float
c: gr_complex
b: uint8_t

### CODE REVIEW

**Comment by marcusmueller** [comment]
@noc0lour certainly, we can, but I'd actually find it cooler if your templates had types like `int32_t` instead of `int`, and `int8_t` instead of `char`. I find the explicit naming of signedness and size a desirable quality here. But yes, definitely, let's hold this off.

**Comment by noc0lour** [comment]
Oh, I'm totally with y'all on the type side. (In the gengen removal PR the gr-analog stuff has the "old" type definitions in it, but I'll update them as well).

**Comment by michaelld** [comment]
@marcusmueller For my knowledge / edification: what is the "swig vector<char> confusion" of which you write?

**Comment by marcusmueller** [comment]
Since @noc0lour's anti-gengen PR does this, closing.

**Pull request closed without merging**
