### PR TITLE
gr-qtgui: Use no_quotes function in some qtgui blocks

### PR DESCRIPTION
**Pull request by dl1ksv**
See #5016

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>

### CODE REVIEW

**Comment by mbr0wn** [comment]
@dl1ksv Where does `no_quotes` come from? Is it defined in Mako? If so, is it in 1.0.7?

**Comment by haakov** [comment]
no_quotes was introduced in https://github.com/gnuradio/gnuradio/pull/5016

**Comment by mbr0wn** [comment]
Ah thanks -- looks like I hadn't git pulled recently.

**Review by mormj — APPROVED** [review]

**Comment by mormj** [comment]
@haakov - does this look good to you?

**Comment by haakov** [comment]
Yes, looks good to me

**Review by haakov — APPROVED** [review]

**Pull request merged**
