### PR TITLE
soapy: added Python support for Soapy types needed for full API support

### PR DESCRIPTION
**Pull request by ncorgan**
* Fixed gr-soapy Python import
* Partially addresses https://github.com/gnuradio/gnuradio/issues/4571

Signed-off-by: Nicholas Corgan <n.corgan@gmail.com>

### CODE REVIEW

**Comment by willcode** [comment]
For arginfo bool, int, float ... can the correct type be returned instead of having the caller do a value_to_x? The type is known in the arginfo. Is the type fixed (per key) or should it be set based on the value setter?

**Comment by ncorgan** [comment]
Sounds good, I'll make that update.

**Comment by willcode** [comment]
Ubuntu 20.04 ship with 0.7.2, so that's what we have on CI. Centos and Debian ship with older versions, so we're using 0.8.0 from source. Did you include some 0.8.0 functionality?

**Comment by ncorgan** [comment]
Looks like some of Soapy's string conversion helper functions were post-0.7.2. Simple enough to work around.

**Comment by willcode** [comment]
* Where possible, we're trying to de-boostify the code. Is there an easy alternative to boost::lexical_cast()?
* Can you check that float is only used for Python? Should string_to_setting<float> should be a double? Others?

**Comment by ncorgan** [comment]
Ah, good catch on the float, that's a typo. Should be double.

And in theory, a stringstream could work. I'll see how the unit tests hold up.

**Comment by willcode** [comment]
Build, test, and a local run (did not try out args/ranges though) worked. Let me know when you're happy with it.

**Comment by ncorgan** [comment]
What's up there works for me. The unit tests work for me to confirm the fields work as expected.

**Comment by willcode** [comment]
And the maint-3.9 test worked, so all good.

**Pull request merged**
