### PR TITLE
updated doc for corr_est 'threshold'

### PR DESCRIPTION
**Pull request by Ipsit1234**
Updated the documentation of Correlation Estimator "Threshold"

### CODE REVIEW

**Comment by mormj** [comment]
With the small update in the doxygen, this is probably an improvement over the current incorrect description - would probably help to just be a bit more descriptive. 

Beyond this PR, and for the change to the documentation to be impactful, I think we need to follow more of @anastas guidance on https://github.com/gnuradio/gnuradio/issues/4273 - namely changing parameter names to match what the block does and a more in depth description of the calculation.  This is certainly more involved.

**Comment by mormj** [comment]
Also, when editing a header file , 2 things need to be done:
1) Update the binding hash for corr_est_cc.h in corr_est_cc_python.h
```
md5sum corr_est_cc.h 
```
Then take the hash value and put it in the _python.h file

2) Run clang-format
Usually I just run:
```
find ./ -iname *.h -o -iname *.cc | xargs clang-format -i
```
from the top of the source tree

**Comment by Ipsit1234** [comment]
> Also, when editing a header file , 2 things need to be done:
> 
> 1. Update the binding hash for corr_est_cc.h in corr_est_cc_python.h
> 
> ```
> md5sum corr_est_cc.h 
> ```
> 
> Then take the hash value and put it in the _python.h file
> 
> 1. Run clang-format
>    Usually I just run:
> 
> ```
> find ./ -iname *.h -o -iname *.cc | xargs clang-format -i
> ```
> 
> from the top of the source tree

Thanks for this info. I will follow these steps and also work as per the guidance given by @anastas in #4273

**Comment by anastas** [comment]
please see some new comments I posted on #4273

**Comment by Ipsit1234** [comment]
I updated the docstring and ran `clang-format` on the file `gnuradio/gr-digital/python/digital/bindings/corr_est_cc_python.cc` file. I had updated the hash too. But still the C++ Formatting test is failing.

**Comment by mormj** [comment]
@Ipsit1234  - try running it just on the file that has changed, and run it from the top dir of the source tree - i.e. the dir that the `.clang-format` file lives in:
```
josh@josh-m15:/share/gnuradio/gr310/src/gnuradio$ clang-format -i gr-digital/include/gnuradio/digital/corr_est_cc.h
```

**Comment by mormj** [comment]
@Ipsit1234 - any luck getting the clang-format to run?  If you are still not able I can push a commit here to do the formatting

**Comment by Ipsit1234** [comment]
> @Ipsit1234 - any luck getting the clang-format to run? If you are still not able I can push a commit here to do the formatting

Yes, the clang-format is running now. Initially I was running the command wrongly. Sorry for the delay. I have pushed a new commit and all the tests are running without any errors. Thanks a lot for the help!

**Comment by 777arc** [comment]
The wiki block doc has been updated, https://wiki.gnuradio.org/index.php/Correlation_Estimator

**Review by 777arc — APPROVED** [review]

**Comment by mbr0wn** [comment]
To close out the PR, I manually merged this and squashed the commits. @Ipsit1234 the formatting was also a bit off so I fixed that too.

**Comment by Ipsit1234** [comment]
> To close out the PR, I manually merged this and squashed the commits. @Ipsit1234 the formatting was also a bit off so I fixed that too.

Oh, sorry for the trouble. This is my first time and hence I too had faced some issues.  After running `clang-format -i`,  the docstring that I had written was formatted in such a way that it looked off. I do not know why that happened. I am using Manjaro Linux. Even the GRC icon looks different. It doesn't look like the original Orange Logo that we see on Ubuntu.

**Comment by mbr0wn** [comment]
> Oh, sorry for the trouble. This is my first time and hence I too had faced some issues. After running `clang-format -i`, the docstring that I had written was formatted in such a way that it looked off. I do not know why that happened. I am using Manjaro Linux. Even the GRC icon looks different. It doesn't look like the original Orange Logo that we see on Ubuntu.

That's OK. We appreciate your contribution!

**Comment by anastas** [comment]
Has this been propagated back to 3.7 maintenance, or is there a different route for that?

**Comment by mormj** [comment]
Not very much, if anything is going back to 3.7 at this point, unless someone wants to take up the work to backport things.

**Pull request closed without merging**
