### PR TITLE
Fix default parameters in Stream_Mux block

### PR DESCRIPTION
**Pull request by adriengit**
fix default parameter 'Length' in Stream Mux block. Cannot connect in the flowgraph otherwise. Stream mux block example is OK as it uses '[3, 2]'.

### CODE REVIEW

**Review by mbr0wn — CHANGES_REQUESTED** [review]
Please do the following:
- Sign off your commit (`git commit -s` or amend your commit message manually)
- Make a single commit on top of master

Otherwise, this is good. Many thanks!

**Comment by dave-pi** [comment]
I think Stream Demux also has the same problem.

**Comment by adriengit** [comment]
Default parameters in Stream Demux are OK

**Comment by dave-pi** [comment]
> Default parameters in Stream Demux are OK

No they're not:

https://github.com/gnuradio/gnuradio/blob/0f1ec604f758e28d788ad71283236928d2d82300/gr-blocks/grc/blocks_stream_demux.block.yml#L17

**Comment by adriengit** [comment]
> > Default parameters in Stream Demux are OK
> 
> No they're not:
> 
> https://github.com/gnuradio/gnuradio/blob/0f1ec604f758e28d788ad71283236928d2d82300/gr-blocks/grc/blocks_stream_demux.block.yml#L17

Change is also done in Demux Block. In 3.8 branch, this block does exist, I was refering to Streams to Stream Block, quite similar.

**Review by mbr0wn — APPROVED** [review]

**Pull request merged**
