### PR TITLE
gr-qtgui: Eye Sink remove unnecessary request for trigger value

### LINKED ISSUE #5487: QT GUI Eye Sink requires unnecessary value for trigger level
### What happened?

Upon execution of a flowgraph containing the https://wiki.gnuradio.org/index.php/QT_GUI_Eye_Sink a small pop-up window asks for the trigger level even though the trigger level is specified in the Parameters.

### System Information

OS: Ubuntu 20.04.3
GR Installation Method: Source

### GNU Radio Version

3.10-git (master)

### Specific Version

3.10.0.0-rc4

### Steps to Reproduce the Problem

A test for the QT_GUI_Eye_Sink is in https://pastebin.com/kU3ymmqa

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dl1ksv**
---

# Pull Request Details

Fixes #5487
## Description

Removes unneeded PopupMenu d_tr_level_act and tr_delay_act
and corresponding functions.

## Which blocks/areas does this affect?

gr-qtgui eye sink

## Testing Done

Ran the example in #5487
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
@dl1ksv Can you elaborate on "unnecessary" so we can think about backporting? This changes the API.

**Review by mormj — APPROVED** [review]
LGTM.  tested locally

**Comment by dl1ksv** [comment]
@willcode If you run a flowgraph using an eye sink you are requested to enter a value for the trigger level on startup even this value must be given in the block parameters. You can enter a useless value like the letter a, no error message, the flowgraph runs.
Once given the value, you can't change it. You have to restart your flowgraph.

**Review by duggabe — APPROVED** [review]
LGTM

**Comment by willcode** [comment]
Seems like an acceptable risk to backport. Sometimes OOTs use the "internal" GUI API. Probably not in this case.

**Review by drmpeg — APPROVED** [review]
Tested and works good.

**Comment by willcode** [comment]
Not backporting to 3.9, to be extra careful about the API change. Worth the risk for 3.10 (famous last words).

**Comment by dl1ksv** [comment]
@willcode , there is no API change. There is a gui change. The old one starts an extra dialog widget, the new one avoids this.

**Comment by willcode** [comment]
`setTriggerLevel()` and `setTriggerDelay()` are public slots. I know the probability is low, but last time I made a change in what I thought was an interternal-only class, someone external was using it.

**Pull request merged**
