### PR TITLE
runtime: expose set_log_level for blocks

### PR DESCRIPTION
**Pull request by n-west**
@skoslowski

Below is a snippet from an informal writeup of a nice-to-have-feature. It was way easier to expose this for blocks than it is for the top_block level. The top_block interface could use more discussion. I can see it either walking through connections and setting their log_level, or only affecting the top_block.

# Proposed Change

This proposal adds an API call to set `log_level` for a flowgraph or individual blocks. In python it looks like the following

    from gnuradio import gr, blocks
    tb = gr.top_block()
    tb.set_log_level(gr.log.LOG_FATAL)
    vsrc = blocks.vector_source_c([4,2])
    vsrc.set_log_level(gr.log.LOG_DEBUG)

This would be implemented in `block.h` by adding a

    void set_log_level(std::string level) { 

# Competing Solutions

## Setting log_level through prefs

The log level is controlled through the gr::prefs architecture which reads a
config file in ~/.gnuradio/config.conf. That file sets the `log_level`, or
directs log4cpp to read a more advanced logging-specific config file. The `log_level` can be changed inside either file, or in a flowgraph with the following
python

    from gnuradio import gr
    gr.prefs_singleton().set_string("log", "log_level", "warn")

This sets the logger to the specified `log_level` for the remainder of `gr`'s lifetime for all blocks and top_blocks.

## gr::log::set_level

There is a public function exposed in `gnuradio-runtime/include/gnuradio/logger.h.in` called set_level that can set the `log_level` for `d_logger` of the calling class.

### CODE REVIEW

**Comment by n-west** [comment]
I should point out that half of the written thing is implemented, the other half needs more discussion/isn't as critical to me. If top_block gets a set_log_level call, what should happen in it? Should it only affect d_logger in top_block, or should it walk the graph setting log_level as it goes?

**Comment by jmcorgan** [comment]
I think the intuitive expectation is that if you set it for a flowgraph top block (or a hierarchical block in general), it should affect everything in the hierarchy below it.  Hierarchical blocks appear as "one block" to the user; often times, they don't even know that it is hierarchical.  And, a top block is simply a hierarchical block with no outer input or output ports.

**Comment by n-west** [comment]
Added hier block interface, but haven't tested yet.

**Comment by n-west** [comment]
Rebased and tested. This should be ready for merge

**Comment by jmcorgan** [comment]
Have you tested this with nested hier blocks to make sure the recursion happens?  It would be useful to see this in the form of QA.

**Comment by n-west** [comment]
I tested with a top_block, but not with a hier_block2. I don't know of any blocks that deterministically log in tree. I could add a getter for log_level and then make QA to get log_level, set log_level, then get_log_level, but it doesn't really test that logging happens properly unless we redirect and test stdout with different levels.

**Comment by n-west** [comment]
Added the getter and some QA in gr-blocks, then rebased off master again.

**Comment by jmcorgan** [comment]
This code needs to be conditionalized so that it is only attempted to be compiled when HAVE_LOG4CPP is true.

**Comment by jmcorgan** [comment]
@n-west ping

**Comment by n-west** [comment]
:+1:

**Comment by jmcorgan** [comment]
This is still not compiling when ENABLE_GR_LOG is true but HAVE_LOG4CPP is false.

**Comment by jmcorgan** [comment]
Given the merge of #857 I recommend re-implementing this on the next branch, where there is no longer conditionalization.

**Pull request closed without merging**
