### PR TITLE
gr-video-sdl: Clean up sink

### LINKED ISSUE #4993: gr-video-sdl: clean up sink
In the SDL sinks:
- [ ] `d_format` is not used (video format is inferred from number of inputs). This could be removed from the API. The block yml always sets it to `0`.
- [ ] `if (1)` code can be removed, was probably an experiment 2+ years ago.

### PR DESCRIPTION
**Pull request by solomonbstoner**
Fixes #4993.

### CODE REVIEW

**Comment by solomonbstoner** [comment]
Couldnt find an example flowgraph on the wiki to test its performance. So I just made sure gnuradio could compile after the changes, and that `ctest -v -R video` passed.

**Comment by drmpeg** [comment]
Here's the test suite. Warning, it's a large file. 1,010,079,355 bytes.

https://www.w6rz.net/sdltest2.tar.gz

**Comment by solomonbstoner** [comment]
Rick and Morty! :D When the video started playing I wondered why it looks a little familiar. 
Anyways, the video plays, albeit with a little lag inbetween. There is no audio, but looking at the code, I dont see anywhere indicating an audio sink. So I guess all's good, I didnt break anything :)

**Comment by solomonbstoner** [comment]
Done. clang-formatted, and now the c++ formatting test passes.

**Review by drmpeg — APPROVED** [review]
Tested and works good.

**Pull request merged**
