### PR TITLE
digital: bug fixed in chunks_to_symbols that the callback functiion set_symbol_table didn't work

### PR DESCRIPTION
**Pull request by fengzhe29888**
Dear @jmcorgan ,

This is a bug fix. So I created this new branch based on maint and opened the pull request to maint.

Could you review and merge it?

Thanks!
Best,
Zhe

### CODE REVIEW

**Comment by jmcorgan** [comment]
Can you please resubmit with a QA test that exercises the new public function?

**Comment by fengzhe29888** [comment]
hi Johnathan,

Do you want me to edit the qa_chunks_to_symbols.py by adding one more test
that exercise this callback function?
I'll think about how to do that and submit it when I'm ready.

Best,
Zhe

**Comment by jmcorgan** [comment]
Yes.

**Comment by jmcorgan** [comment]
I'm going to close this for lack of activity.  If you decide to do this, please submit a new PR.  Thanks.

**Pull request closed without merging**
