### PR TITLE
grc: support QApplication command-line args

### PR DESCRIPTION
**Pull request by tjeng**
Signed-off-by: Janice Tjeng <janicetjeng@gmail.com>
Functionality has not been tested, working with Derek to test it.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Hi @tjeng! Great to have you around! Quick question: does Qt print a warning or do something similar if an argument was specified that wasn't recognized? 

Otherwise, there's a bit of a usability hazard here (i.e., me having a typo in something that I wanted to pass to my flowgraph, and then not noticing that I had that typo).

**Comment by mormj** [comment]
Hi @tjeng - any regarding Marcus's concern?

**Comment by tjeng** [comment]
I had some errors installing the latest version of GNU radio earlier and
did not manage to try the feature. I pushed the suggested code to the
Github branch without extensively testing it. I'm a bit caught up with
something else at the moment and will circle back once I get it working.

**Comment by willcode** [comment]
Closing, based on last comment. @tjeng please reopen or submit a new PR when you have time to work on this.

**Pull request closed without merging**
