### PR TITLE
zeromq: Backport to 3.8: Add ZMQ_LINGER value to prevent infinite block

### PR DESCRIPTION
**Pull request by MattMills**
Backport of #3866 to gr 3.8

### CODE REVIEW

**Comment by willcode** [comment]
This seems low risk. Does anyone have an existing application that depends on one ZMQ endpoint hanging indefinitely until the other end empties a queue?

**Comment by MattMills** [comment]
@willcode Should I just assume this is closed as wontfix?

**Comment by dkozel** [comment]
Hi @MattMills sorry for the long delay. This wasn't followed up on after willcode's question. I don't think anyone knows of an application that relies on this behavior, and I think this is pretty clearly a bug so changing the behavior on maint is justified.

This is a small change and it's been merged on master for a while now without any new bug reports, so merging now.

**Comment by MattMills** [comment]
Thanks!

**Comment by willcode** [comment]
Already backported to maint-3.8, removing tag.

**Pull request merged**
