### PR TITLE
Added FFT-based Low Pass Filter Convenience Wrapper

### PR DESCRIPTION
**Pull request by ghostop14**
Based on analyses such as Tom R's filter_timing.py and some advanced users preferring FFT-based LPF's over FIRs in some implementations, this convenience wrapper provides a drag-and-drop LPF option mirroring the FIR-based LPF rather than having to select an FFT Filter block and build the taps manually.  This block also provides significant performance improvements over the FIR-based filter for any meaningful tap lengths.

### CODE REVIEW

**Comment by drmpeg** [comment]
Why is the commit for Rotator-based Freq Shift Convenience Wrapper included here?

**Comment by ghostop14** [comment]
Hi drmpeg, guidance on the Slack coredevs channel was these minor items could be put in as a PR rather than a more complex grep.  Happy to shuffle it wherever the team agrees is the best place.

**Comment by drmpeg** [comment]
Yes, but it's also included in PR https://github.com/gnuradio/gnuradio/pull/3046

**Comment by ghostop14** [comment]
Hmmm, they were definitely separate PRs from different local isolated branches.  Can always close/redo the FFT one if it looks like something got banged up.

**Comment by drmpeg** [comment]
I'll guess you based your fft_lpf branch on the freqshift branch instead of master.

**Comment by ghostop14** [comment]
They should be separate PR's.  3047 should not include it, just 3046.  I'll close 3047 and re-submit just what was intended to be in 3047.

**Comment by ghostop14** [comment]
I was thinking that might've been what happened when I went in to create the new branch. :)

**Pull request closed without merging**
