### PR TITLE
gr-blocks: Fixed strncpy warning in tuntap_pdu_impl.cc

### PR DESCRIPTION
**Pull request by alekhgupta1441**
References #3349 
Trivial fix for strncpy.

### CODE REVIEW

**Comment by japm48** [comment]
I just realized that because of the `memset(...)`  line above, this can be rewritten as simply:
```c++
strncpy(ifr.ifr_name, dev, IFNAMSIZ-1);
```

Also, there is a similar problematic line (not detected by the compiler):

```c++
strncpy(dev_cstr, dev.c_str(), std::min(sizeof(dev_cstr), dev.size()));
```

This should become:

```c++
strncpy(dev_cstr, dev.c_str(), std::min(sizeof(dev_cstr) - 1, dev.size()));
```

But I don't know if this should be a separate PR.

**Comment by alekhgupta1441** [comment]
@japm48 Thanks for seeing this. Changes suggested are done.

**Comment by michaelld** [comment]
My meta-question is: why use a buffer of 1024 length in the first place? `IFNAMSIZ` is 16, and that limit is imposed both inside `tun_alloc` and in `struct ifreq`, so 1024 is silly and unnecessary. My proposal: (1) expand or truncate `d_dev` to `IFNAMSIZ` bytes, and set the last one to 0. Then just copy that whole string any time its needed. Nice and easy, and no need to worry about `strncpy` .. just use `IFNAMSIZ` for any copy and the copied string will always be NULL terminated.

**Comment by japm48** [comment]
@michaelld That's true. I didn't realize that those were the same string!

**Comment by alekhgupta1441** [comment]
@mormj @michaelld Sir, I will surely try to bring a PR soon with above mentioned approach.

**Comment by mormj** [comment]
It does indeed make the warning go away, so merging this fix, and save the larger changes to a different PR.

**Pull request merged**
