### PR TITLE
Fix more misc-typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
Sorry about the follow up PR. These were leftover. Note the modifications to the API in f863d03

**Comment by luzpaz** [comment]
Sorry, dyslexic moment. I need to revert f863d03

**Comment by marcusmueller** [comment]
closing this then. I'm in the process of releasing and can't take typo fixes for the next couple of days.

**Comment by luzpaz** [comment]
Actually it was correct. But I can resubmit after the release

**Pull request closed without merging**
