### PR TITLE
gr-dtv: Add common blocks for DVB-S2 and DVB-T2.

### PR DESCRIPTION
**Pull request by drmpeg**
Hopefully the directory structure is acceptable.

### CODE REVIEW

**Comment by jmcorgan** [comment]
Based on feedback in IRC we'll put this on hold pending your updates.

**Comment by drmpeg** [comment]
1) Change /lib/common to /lib/dvb
2) Document header files.
3) Move defines out of public headers.
4) Vector I/O NOT implemented, since input/output size is not fixed.

**Comment by jmcorgan** [comment]
I'll review over the weekend, but--you can still have vector I/O if the I/O sizes are configurable but fixed during length of the block.  The vector sizes just become a function of the config parameters.  I'll comment later after reviewing your changes.

**Comment by drmpeg** [comment]
Understood, but the vector sizes are not a power-of-two bytes. This causes a rash of allocate_buffer warnings. Not sure how to add variable length padding to a power-of-two structure.

**Comment by jmcorgan** [comment]
Basically, you don't add padding to the structure; you take its size and round up to the nearest power of two when setting itemsize in the io signature.  In work(), you treat the memory as chunks of the power of two itemsize, but you cast it to the original structure, which is shorter, and you just never write to the excess padding.  It's easier than it sounds.

**Comment by jmcorgan** [comment]
Otherwise, the updates look fine.

**Comment by drmpeg** [comment]
Unfortunately, I'm not seeing enough benefit to the vector I/O change. 1) The difference between padded vector sizes is greater than the difference between actual sizes. This means that the padded vector sizes do not prevent flow graph mis-configuration. 2) The LDPC and especially the BCH blocks are quite CPU intensive. It would seem that any scheduling performance advantage will be a very small percentage of the total block performance.

**Comment by jmcorgan** [comment]
After discussion, Tom and I have decided that we'll continue with the your current design for 3.7 API, but will consider this for change to either vector I/O or conversion to a tagged stream block for 3.8 API.  So I'll merge this as-is and you can continue the development of the rest.

**Pull request merged**
