### PR TITLE
replaced uniform_int_distribution with uniform_int

### LINKED ISSUE #1227: can't use boost::(random::)uniform_int_distribution: requires boost version >> minimal_boost_version
44ef5e1c240b7d5aeac7ca6537c4b07f3cf606c5  added new analog random generators, functionally based on `boost::random::uniform_int_distribution`.

Problem is that uniform_int_distribution only became available in a version `v`, 1.45.5 < v <= 1.48 . Since our current Boost version requirement is 1.35, and not overly likely to become 1.48 soon, we simply can't do that and must revert the aformentioned patch, lest we find a way around `uniform_int_distribution`.

There's a class `uniform_int` that is in 1.41¹, which is deprecated in modern boosts. Maybe it does the same. Haven't looked at it, because I'm not sure what the code does, calling @jdemel on that 👸 !

**effect**: at least a broken build on EPEL 6 / RedHat.

<hr>
¹ by the way, let's soon as possible bump the Boost requirement to at least that

### PR DESCRIPTION
**Pull request by jdemel**
This should fix #1227

### CODE REVIEW

**Comment by marcusmueller** [comment]
sadly, no:

<pre>
cd /builddir/build/BUILD/gnuradio-3.7.10.1/build/gnuradio-runtime/lib && /usr/bin/c++   -DALIGNED_MALLOC=0 -DENABLE_GR_LOG -DGR_PERFORMANCE_COUNTERS -DHAVE_ARPA_INET_H -DHAVE_BYTESWAP_H -DHAVE_COSF -DHAVE_GETPAGESIZE -DHAVE_GETTIMEOFDAY -DHAVE_LINUX_PPDEV_H -DHAVE_MALLOC_H -DHAVE_MMAP -DHAVE_NANOSLEEP -DHAVE_NETDB_H -DHAVE_NETINET_IN_H -DHAVE_POSIX_MEMALIGN -DHAVE_PTHREAD_SETSCHEDPARAM -DHAVE_PTHREAD_SIGMASK -DHAVE_SCHED_SETSCHEDULER -DHAVE_SELECT -DHAVE_SHM_OPEN -DHAVE_SIGACTION -DHAVE_SIGNAL_H -DHAVE_SINCOS -DHAVE_SINCOSF -DHAVE_SINF -DHAVE_SNPRINTF -DHAVE_SYSCONF -DHAVE_SYS_IPC_H -DHAVE_SYS_MMAN_H -DHAVE_SYS_RESOURCE_H -DHAVE_SYS_SELECT_H -DHAVE_SYS_SHM_H -DHAVE_SYS_SOCKET_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_VALLOC -DTRY_SHM_VMCIRCBUF -Dgnuradio_runtime_EXPORTS -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -std=c++98 -fvisibility=hidden -Wsign-compare -Wno-uninitialized -O3 -DNDEBUG -fPIC -I/builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/lib/math -I/builddir/build/BUILD/gnuradio-3.7.10.1/build -I/builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/include -I/builddir/build/BUILD/gnuradio-3.7.10.1/build/gnuradio-runtime/include -I/builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/lib -I/builddir/build/BUILD/gnuradio-3.7.10.1/build/gnuradio-runtime/lib/../include -I/builddir/build/BUILD/gnuradio-3.7.10.1/volk/include -I/builddir/build/BUILD/gnuradio-3.7.10.1/build/volk/include    -o CMakeFiles/gnuradio-runtime.dir/math/random.cc.o -c /builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/lib/math/random.cc
/builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/lib/math/random.cc: In member function 'void gr::random::set_integer_limits(int, int)':
/builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/lib/math/random.cc:89: error: 'param_type' is not a member of 'boost::uniform_int<int>'
/builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/lib/math/random.cc:89: error: expected ';' before 'dis_params'
/builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/lib/math/random.cc:90: error: 'class boost::uniform_int<int>' has no member named 'param'
/builddir/build/BUILD/gnuradio-3.7.10.1/gnuradio-runtime/lib/math/random.cc:90: error: 'dis_params' was not declared in this scope
</pre>

**Comment by jdemel** [comment]
I worked on my machine. But nevertheless. Your compile error should be fixed now too.

**Comment by marcusmueller** [comment]
I'm not at my compile machine right now, and internet's too flakey. What's your OS/distro? I can *enable* you to test stuff *locally*, if you want.

**Comment by jmcorgan** [comment]
Fixes #1227.  We'll handle the changes to the min version tests in a different pull request.

**Pull request merged**
