### PR TITLE
Extend dot graph output to show hierarchical structure of flowgraph

### PR DESCRIPTION
**Pull request by iohannez**

### CODE REVIEW

**Comment by jmcorgan** [comment]
This compiles and tests okay, but I'm immediately merging it as-is.

The dot-graph generator removes a publicly visibile API function in gnuradio/include/flowgraph.h.  Normally, this would constitute an API change that would force it the 3.8 branch.  It's at least debatable whether we really consider this function part of the API or not.  @trondeau?

Also, the block naming changes are in the same category, as these names are publicly visible and can be uses by users in the tagging and messaging APIs.  The UHD ones have already been corrected in the next branch for 3.8.  The sub_ff one will probably go in as a bug fix, but would be separate from this.

**Comment by trondeau** [comment]
First, yes, we cannot remove the publicly visible function in flowgraph.h. We'll have to deprecate it if it's to be removed.

I'm ok with the fix to the sub_ff name. As @jmcorgan says, submit that as a separate bug fix off maint. Also yes to what @jmcorgan says about the change to the UHD name.

I'm not a fan of the duplicated flatten_aux function. That's a lot of code duplicated between those calls just for the sake of writing to the stringstream. What if you extend the API of the current flatten_aux and use a "std::string&" instead that defaults to something like "None". In the function, if not "None", create a stringstream and assign the return value to the str() function to copy the results back out. This is a little extra overhead when you don't care about the dotgraph because of the string checking, and it's more overhead when you do care with the copies and all, but we're not really concerned with that kind of performance hit when asking for that result.

**Comment by jmcorgan** [comment]
@iohannez Can you let us know your plans for this?

**Comment by iohannez** [comment]
I am sorry for the delay, I was busy with other things.
I just tried to implement Tom's idea but having some trouble.
It seems I can only give a default argument to a const std::string
reference but then I can not use it to pass back the final string.
Am I missing something?

**Comment by iohannez** [comment]
My colleague had another idea. Just have a function flatten_aux with the old interface  that calls the new flatten_aux with a dummy stringstream. 
Otherwise I guess the only solution is to use a string or stringstream pointer and set it to Null by default to implement something in the direction of Tom's idea.

**Comment by iohannez** [comment]
> Part of my reasoning is that you're basically the only one (or team) that
> really wants this. So it's hard to justify this kind of intrusion into the
> core code to support it.

Personally I would suggest that this kind of argument could also be more like a
self-fulfilling prophecy. Maybe the absence of such sophisticated debugging
tools (I could name some others but that would lead to an off-topic discussion)
causes the people to believe that GNU Radio should be only used in conjunction
with the companion and is not meant for any other "serious" work.
Also how do you come to the conclusion that nobody other than us wants this, if
it didn't exist so far? No offense but that doesn't sound perfectly valid. Or
are you talking about the dot-graph features that we had until now?

I can find a discussion on the mailing list suggesting to extend the
dot-graph features:
https://lists.gnu.org/archive/html/discuss-gnuradio/2014-10/msg00015.html
I find this a good idea as well. Maybe that could be done in a next step.

Actually it's a fact that if you build a flowgraph from pure python and C++
code then there is no way to obtain the information about it's hierarchical
structure in an automatic way. This can become very bothersome as your
flowgraph grows bigger and bigger and you really need to introduce hierarchy.

Probably the fact that the dot-graph feature is badly documented is the actual
reason why not many people are using it. So we should maybe rather discuss
about extending the documentation (which I would be willing to do if you would
let me know where exactly you would like to have a page written about this)
than if this is a useful feature.

What could be further done is to enable GNU Radio itself to generate the final
PDF(, PNG, JPG) of the flowgraph using the graphviz library in order to make
the feature more accessible.  At the moment we are doing this manually from the
command-line.  I imagine there could also be a button in the companion that
generates the PDF with a single click. Wouldn't that be great for all kinds of
documentation tasks?

So I actually believe that what we are talking about here is a very basic
feature and not something totally obscure that nobody would ever like to use.
I would agree though that it's probably not enough integrated and exposed to 
the user.

I don't understand this one:

> It doesn't offer you the same subgraph grouping that you wanted, though.

Do you mean that we can not get the hier blocks drawn with what you suggest?

**Comment by jmcorgan** [comment]
Superseded by #394

**Pull request closed without merging**
