### PR TITLE
grc: fix duplicate All Files filter entry in save screenshot dialog

### LINKED ISSUE #6010: Duplicate "All files" filter entry in save screenshot dialog
### What happened?

I was saving several screenshots of a flowgraph using the Screen Capture (Ctrl + P) function. After saving a few screenshots I noticed the filter dropdown menu looking like this: 
2022-07-14-213147_1920x1080_scrot

I had expected to see only a single "All files" entry. 

### System Information

OS: Arch Linux
GR Installation Method: Source

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-185-g53dd57ca

### Steps to Reproduce the Problem

1. Open a flowgraph
2. Hit Ctrl+P, then Esc.
3. Repeat step 2 a couple times
4. Hit Ctrl+P, then open the filter dropdown menu ("PDF Files")

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by R-ohit-B-isht**
Signed-off-by: R-ohit-B-isht <rbtunes0@gmail.com>

## Description
Fixes invoking screen capture (crtl+p) multiple times duplicates "All Files" option in the file filter each time it is invoked.

## Related Issue
Fixes #6010 

## Which blocks/areas does this affect?
grc/gui/FileDialogs.py line no. 60-63

## Testing Done
Yes

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Review by mormj — APPROVED** [review]
does indeed fix the issue.  nice catch and fix!

**Comment by mormj** [comment]
@R-ohit-B-isht - It would be helpful for this and future commits to adjust the git commit message to be prefixed by the module, something like:
```
grc: Fix Duplicate All_files filter entry in save screenshot dialog
```
It should be easy enough with 
```
git commit --amend
git push --force ...
```

**Comment by R-ohit-B-isht** [comment]
> @R-ohit-B-isht - It would be helpful for this and future commits to adjust the git commit message to be prefixed by the module, something like:
> 
> ```
> grc: Fix Duplicate All_files filter entry in save screenshot dialog
> ```
> 
> It should be easy enough with
> 
> ```
> git commit --amend
> git push --force ...
> ```

👍🏻 I'll keep that in mind

**Comment by willcode** [comment]
Something like
```
        if filters is None:
            filters = [(self.filter_label, self.filter_ext)] if self.filter_label else []
            filters.append(('All Files', ''))
```
is just a touch simpler, and none of the callers explicitly add `All Files`. Do you think this does the same thing?

**Pull request merged**
