### PR TITLE
Remove deprecated blks2 blocks from next branch

### PR DESCRIPTION
**Pull request by jmcorgan**
This builds on top of #1067 but should merge cleanly after that is merged into master->next.

A couple broken old-style OFDM blocks still use blks2, but those will get removed in another PR.

### CODE REVIEW

**Comment by jmcorgan** [comment]
So, I missed a bunch of GRC-based examples in gr-trellis, will take care of in another PR.

**Comment by mbr0wn** [comment]
Yaaay... good riddance.

**Comment by jmcorgan** [comment]
A PR to deprecate the old-style OFDM blocks on master and another to remove them from next would be...nice.

**Comment by jmcorgan** [comment]
Deprecation meaning a warning print in the block constructor and changing the category to [Core]/Deprecated in the .grc file.

**Comment by mbr0wn** [comment]
On a side note, C++17 has a 'deprecated' keyword for this case. So, in 2025-ish, we might be able to just use that.

**Comment by skoslowski** [comment]
You can also add `<flags>deprecatedy</flags>` to the block wrapper. This triggers a message on generate much like the one for missing a throttling block.

**Pull request merged**
