### PR TITLE
grc: grc_setup_freedesktop is installed unconditionally

### LINKED ISSUE #6464: grc_setup_freedesktop created unconditionally (in the wrong location)
### What happened?

Hi! I'm currently improving the gnuradio package for Arch Linux.

I noticed that the file `usr/libexec/gnuradio/grc_setup_freedesktop` is created unconditionally and its location can not be changed.
On Arch we do not use or support /usr/libexec/ (everything is /usr/lib/).

I have tried `-DENABLE_POSTINSTALL=OFF`, `-DGR_LIBEXEC_DIR=lib` and `-DGR_PKG_LIBEXEC_DIR=lib/gnuradio/` but the file is always installed.

Since we already get the XDG integration in the correct location I believe the script serves no purpose and could be omitted altogether.

 Currently I revert to just removing the entirety of usr/libexec from the package contents.

### System Information

OS: Arch Linux
GR Installation Method: Source

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.5.0

### Steps to Reproduce the Problem

```
  local cmake_options=(
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_BUILD_TYPE=None
    -D ENABLE_GR_ANALOG=ON
    -D ENABLE_GR_AUDIO=ON
    -D ENABLE_GR_BLOCKS=ON
    -D ENABLE_GR_BLOCKTOOL=ON
    -D ENABLE_GR_CHANNELS=ON
    -D ENABLE_GR_CTRLPORT=ON
    -D ENABLE_GR_DIGITAL=ON
    -D ENABLE_GR_DTV=ON
    -D ENABLE_GR_FEC=ON
    -D ENABLE_GR_FFT=ON
    -D ENABLE_GR_FILTER=ON
    -D ENABLE_GR_IIO=ON
    -D ENABLE_GR_MODTOOL=ON
    -D ENABLE_GR_NETWORK=ON
    -D ENABLE_GR_PDU=ON
    -D ENABLE_GR_QTGUI=ON
    -D ENABLE_GR_SOAPY=ON
    -D ENABLE_GR_TRELLIS=ON
    -D ENABLE_GR_UHD=ON
    -D ENABLE_GR_UTILS=ON
    -D ENABLE_GR_VIDEO_SDL=ON
    -D ENABLE_GR_VOCODER=ON
    -D ENABLE_GR_WAVELET=ON
    -D ENABLE_GR_ZEROMQ=ON
    -D ENABLE_GRC=ON
    -D ENABLE_POSTINSTALL=OFF  # we distribute freedesktop integration directly
    -W no-dev
    -B build
    -S $pkgbase-$pkgver
  )

  cmake "${cmake_options[@]}"
  cmake --build build --verbose
  DESTDIR="$pkgdir" cmake --install build
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dl1ksv**
## Description

grc_setup_freedesktop should only be installed if -DENABLE_POSTINSTALL=ON
## Related Issue

Fixes #6464

## Testing Done

Doing a fresh install with -DENABLE_POSTINSTALL=ON and a second one with -DENABLE_POSTINSTALL=OFF
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Review by marcusmueller — APPROVED** [review]

**Review by willcode — APPROVED** [review]

**Comment by dl1ksv** [comment]
Meanwhile I found out that the installation process can be further simplified, without moving grc_setup_freedesktop to the installation path.

I'll put an additional fix here.

**Comment by willcode** [comment]
@marcusmueller could you give this another look since it changed after your approval?

**Comment by antonio-rojas** [comment]
This breaks building the application for distro packaging. By removing the code that installs the icons, desktop files, etc from CMakeLists.txt, those files are now installed for the user which is building the package instead of the path given in DESTDIR.

**Comment by willcode** [comment]
@dl1ksv @marcusmueller could you comment on this? I don't understand how all this interacts well enough. How are packagers meant to pick up the icons for an install script?

**Comment by antonio-rojas** [comment]
gnuradio uses cmake, and cmake honors the DESTDIR env variable at install time.
The cmake code to install the icons was removed in commit 868a5a070c584bb551b40055518c09810217ca33 as far as I can see, and unconditionally replaced by the custom grc_setup_freedesktop script, which is not usable in packaging because it doesn't honor DESTDIR.

**Pull request merged**
