### PR TITLE
Refactor threads.cc

### PR DESCRIPTION
**Pull request by marcusmueller**
## Description

#7553 showed that the current, very coarse "we copy all code for 1. Linux, 2. Windows, 3. Mac OS (and all the BSDs, they're the same, right?)" doesn't reflect reality well.

Windows is different between MINGW and MSVC, and not all BSDs are MacOS. So, instead of large redundant blocks, pull the platform decision into the functions, and decide as necessary.

Also, add logging. If the user tried to pin a thread to a CPU and we couldn't do that, we might as well tell them…

## Which blocks/areas does this affect?

Hopefully none functionally; I hope that future porting efforts become easier that way (pretty sure MacOS does support a lot of the functionality that we don't implement on that platform, for example).

## Testing Done

ran test suite on Linux. 

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
@landryb this incorporates your OpenBSD fix, but it would be very appreciated if you could test this, and give feedback.

**Comment by marcusmueller** [comment]
in fact, added setting of thread names on MacOS; just don't have a device to test whether it makes user life better.

**Comment by landryb** [comment]
> @landryb this incorporates your OpenBSD fix, but it would be very appreciated if you could test this, and give feedback.

i can mostly only build-test things by backporting them on 3.10.11 release (which builds within our ports infra, and sets up the configure args/dependencies/etc), so if that's enough for you.. unless ofc you point me at an unit test that would exercise this codepath.

**Comment by landryb** [comment]
fwiw, i had mostly forgot about it, but the PR manually backported on top of 3.10.11 builds fine on OpenBSD.

**Pull request merged**
