### PR TITLE
Enable GRC example tests

### LINKED ISSUE #1740: Adding automatic unit testing for .grc grcc compilation
grcc compilability could be a "collatoral" unit test that we could have for every single .grc added to the tree. 

* CMake needs to automagically find all the .grc
* … and to add them to a list of files to be pushed through `grcc` during a unit test
* … and to check the resulting's Python syntax

This would allow us to detect f'ups caused by GRC changes in non-GRC code.

### PR DESCRIPTION
**Pull request by marcusmueller**
## Description

In #4208, the necessary infrastructure was introduced, but promptly disabled – 100% test failure at the time being.

With #6632, the last failing GRC example flow graph (on my machine) gets fixed. Time to enable these

Downsides:

- 85 s additional test time on my machine

Upsides:

- Test coverage for all GRC examples
- Unearth GRC code generation regressions much earlier
- Potentially a free pony for everyone
- Integrate the Block YAMLs into testing by writing an example: good for our example stockpile, good for our block files

## Related Issue

Fixes #1740

## Which blocks/areas does this affect?

- Testing: All of the modules
- GRC

## Testing Done

Is itself a mere enabling of unit tests

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Interesting! I get neither the failures in fecapi nor in gr-uhd; now the question is, what's different on my machine vs the consistency with which the CI machines detect a problem with these flow graphs?

**Comment by ryanvolz** [comment]
For the conda builds at least, grc_tests is timing out at 120 seconds because that's the timout specified in the build scripts when the tests are run! That will have to be increased and it's probably fine to go pretty high since I don't think hanging tests have ever really been a problem.

**Comment by marcusmueller** [comment]
> I don't think hanging tests have ever really been a problem.

They've been before, especially on gr-digital tests that expect some messages to come in and that nondeterministically might not always happen. But I think argilo got these under control.

**Comment by willcode** [comment]
@marcusmueller @ryanvolz Is this one ready for main, or is it going to make conda fail every time?

**Comment by ryanvolz** [comment]
Raising/eliminating the timeout on the tests in the conda build scripts is still something that should happen before merge, but besides that I don't know about the pass/fail reliability in general.

**Pull request closed without merging**
