### PR TITLE
gr-pdu: fix pdu_lambda block and examples

### PR DESCRIPTION
**Pull request by jacobagilbert**
Several flowgraphs had errors in them due to a name change during development.

Thanks @drmpeg!

### CODE REVIEW

**Review by mormj — APPROVED** [review]

**Comment by drmpeg** [comment]
The pdu_lambda_chirp_demo.grc flow graph still seems very broken. I've left my findings on Matrix GNU Radio Development room.

**Comment by drmpeg** [comment]
Both "lambda" flow graphs fail with:
```
<<< Welcome to GNU Radio Companion 3.7.10git-4390-g134a7d19 >>>

Block paths:
	/opt/gnuradio-3.10.0git/share/gnuradio/grc/blocks

Loading: "/home/re/xfer/gnuradio/gr-pdu/examples/pdu_lambda_chirp_demo.grc"
>>> Done

Generating: '/home/re/xfer/gnuradio/gr-pdu/examples/pdu_lambda_chirp_demo.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python3 -u /home/re/xfer/gnuradio/gr-pdu/examples/pdu_lambda_chirp_demo.py

Traceback (most recent call last):
  File "/home/re/xfer/gnuradio/gr-pdu/examples/pdu_lambda_chirp_demo.py", line 40, in <module>
    import pmt, numpy as np, pylambda
ModuleNotFoundError: No module named 'pylambda'

>>> Done (return code 1)
```

**Review by drmpeg — APPROVED** [review]
Tested all six flow graphs. Looks good!

**Comment by jacobagilbert** [comment]
Thanks for the review @drmpeg - who would have thought there would be so much facepalm involved in moving blocks in tree..

**Pull request merged**
