### PR TITLE
audio: raise nperiods for alsa source/sink

### PR DESCRIPTION
**Pull request by duggabe**
raise nperiods to 32
resolves https://github.com/gnuradio/gnuradio/issues/3798

### CODE REVIEW

**Comment by argilo** [comment]
I think this is a good change. Audio underruns caused by the ALSA sink's very short default buffer size have been a common source of frustration for me. The only downside is that the default audio latency will increase by 140 milliseconds, but anyone who wants low latency can override this in their `~/.gnuradio/config.conf` file.

If this change is made, we should probably also update these defaults:

https://github.com/gnuradio/gnuradio/blob/4675ce0579ba99b9ebe2fce9ac37e5420f325ee6/gr-audio/lib/alsa/alsa_sink.cc#L56-L59

https://github.com/gnuradio/gnuradio/blob/4675ce0579ba99b9ebe2fce9ac37e5420f325ee6/gr-audio/lib/alsa/alsa_source.cc#L55-L58

**Comment by duggabe** [comment]
I changed the source and sink files, but now I'm curious. How does the value in gr-audio-alsa.conf get used, when these are hard-coded in the .cc files?

**Comment by argilo** [comment]
> How does the value in gr-audio-alsa.conf get used, when these are hard-coded in the .cc files?

`prefs::singleton()->get_long("audio_alsa", "nperiods", 32)` reads from the config file, and falls back to 32 if `nperiods` is not present in the `audio_alsa` section of the config file.

**Comment by duggabe** [comment]
Thank you. Is this ready to go now?

**Review by noc0lour — APPROVED** [review]

**Pull request merged**
