### PR TITLE
qtgui: fix QT GUI Histogram Sink produces implausible results #6494

### LINKED ISSUE #6494: QT GUI Histogram Sink produces implausible results
### What happened?

A sequence of 10 equidistant values should produce an even histogram (10 bins, 10 values) => 1 value per bin.

### System Information

OS: Ubuntu 22.04
GR Installation Method: native distro packages

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1. Create flow graph:

test

10 different source values of same distance (0..9), 10 bins, number of points: 10.

2. Expected behaviour:

All 10 bins should have 1 as count. Distance between bins should be exactly 1.

3. Observed behaviour:

Some bins have more values, some have no values inside. Distribution not even. Distance between bins is not 1:
[0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, ??]

Screenshot_20230129_150941

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by R-ohit-B-isht**
## Description
when the data range is very small, the leftmost bin can be too narrow, which can cause some data points to fall outside of the histogram.

## Related Issue
Fixes #6494 

## Which blocks/areas does this affect?
gr-qtgui/lib/HistogramDisplayPlot.cc: line no. 192-198

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
What does the plot look like with this change? Curious what [0,10] looks like. Does it plot the x axis as 0.5, 1.5, ..., 9.5?

**Comment by R-ohit-B-isht** [comment]
> lot look like with this change? Curious what [0,10] looks like. Does it plot the x axis as 0.5, 1.5, ..., 9.5?

image

**Comment by willcode** [comment]
Thanks. Would you also try an example with [-10,10] to how `lround()` in `plotNewData()` works with this change?

**Comment by R-ohit-B-isht** [comment]
> 



> Thanks. Would you also try an example with [-10,10] to how `lround()` in `plotNewData()` works with this change?
like this?
image

**Review by willcode — APPROVED** [review]

**Review by mormj — APPROVED** [review]

**Pull request merged**
