### PR TITLE
grc: make node states consistant

### LINKED ISSUE #5779: Adding node sets `state: true` disabling and enabling it sets `state: enabled`
### What happened?

When I add a node to my flowgraph, the `.grc` file will contain a line

```
state: true
```

If I disable that node, the line switches to

```
state: disabled
```

and if I re-enable the node, it switches to

```
state: enabled
```

I think the value `true` is incorrect and it should be `enabled` instead.

### System Information

OS: Arch Linux
GR Installation Method: Conda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1. Add a node. The file says `state: true`
2. Disable it. The file says `state:disabled`
3. Enable it. The file says `state:enabled`

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by haru-02**
just a one line change to make sure node state is consistant
## Related Issue

Fixes #5779

## Testing Done

make test runs successfully.
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Hi @haru-02, thanks for resubmitting. PRs should contain a single commit, unless there is a good reason to have multiple. In this case, there is a stray merge commit. Would you please squash (`git rebase -i main`) and the do a force push? Thanks.

**Comment by haru-02** [comment]
@willcode i have made the changes. Hope it's all good this time

**Review by willcode — APPROVED** [review]

**Review by mbr0wn — APPROVED** [review]

**Comment by mbr0wn** [comment]
@haru-02 Thanks for contributing to GNU Radio, and welcome as part of the contributor base!

FYI, I edited your initial comment. See this (not the dotted underlines):
image

This will auto-close the bug/issue when this PR is merged. You need to prefix the issue number with "Closes" or "Fixes" or something like that ("Resolves" may work).

**Comment by haru-02** [comment]
> @haru-02 Thanks for contributing to GNU Radio, and welcome as part of the contributor base!
> 
> FYI, I edited your initial comment. See this (not the dotted underlines): image
> 
> This will auto-close the bug/issue when this PR is merged. You need to prefix the issue number with "Closes" or "Fixes" or something like that ("Resolves" may work).

Thank you ! I will add the prefix next time i make a pr 😄

**Pull request merged**
