### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`

### CODE REVIEW

**Comment by noc0lour** [comment]
To be honest, I don't think this is the right way to fix typos. We might want to integrate that into buildbot and hold off new pull requests if typos are in there. But manually fixing stuff to create merge conflicts doesn't help a lot.

**Comment by mbr0wn** [comment]
@noc0lour For new PRs, I agree -- for the existing codebase, I think this a fine way to go ahead.

**Comment by mbr0wn** [comment]
And also, I *hate* typos.

**Comment by marcusmueller** [comment]
@mbr0wn while I hate topys as mcuh as yuo do, and while suggesting this now after having merged the first of @luzpaz' PRs at FOSDEM, really, this makes the `master`/`next`/`python3` merge way more work intense. Let's put off such automated mass fixes after we've got `python3` being mainline, OK?

**Pull request closed without merging**
