### PR TITLE
gr-audio: update comments in wavfile_sink and wavfile_source and add list of supported audio files

### LINKED ISSUE #5971: Wavfile Sink: Header docstring still only mentions PCM, but we do all of libsnd
### What happened?

[A bug happened!](https://github.com/gnuradio/gnuradio/blob/v3.10.3.0/gr-blocks/include/gnuradio/blocks/wavfile_sink.h) still says 
https://github.com/gnuradio/gnuradio/blob/v3.10.3.0/gr-blocks/include/gnuradio/blocks/wavfile_sink.h#L22

Also, [`Check gr_make_wavfile_source() for extra info.`](https://github.com/gnuradio/gnuradio/blob/main/gr-blocks/include/gnuradio/blocks/wavfile_source.h#L26) is utterly meaningless (and would not be much better if this was still GNU Radio 3.6, where such a function might have still existed.

same for `…_source.h`

Now, starting since 3.9.0.0, we do all the formats that libsndfile can handle.

# Fix

* Remove https://github.com/gnuradio/gnuradio/blob/main/gr-blocks/include/gnuradio/blocks/wavfile_source.h#L26 
* replace the `\brief …` sentence with "Write samples to an Audio file"
* Add the list of supported audio containers from [the wiki page](https://wiki.gnuradio.org/index.php?title=Wav_File_Sink#Source_Files) to the `\details` section
* Replace all occurences of "wav file header" in the comments with "audio file metadata" or similar
* Apply the above to `wavfile_sink.h` as well

### System Information

OS: –
GR Installation Method: –

### GNU Radio Version

3.11-git (main)

### Specific Version

3.9.0.0 and later

### Steps to Reproduce the Problem

reading the docstrings

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by harshiiiit**
Made changes to comments in wavfile_sink and wavfile_source and added list of supported audio files.

Signed-off-by: Harshit Singh [singhh198@gmail.com](mailto:singhh198@gmail.com)

## Description
- [x] Removed https://github.com/gnuradio/gnuradio/blob/main/gr-blocks/include/gnuradio/blocks/wavfile_source.h#L26
- [x] Replaced the \brief … sentence with "Write samples to an audio file (uncompressed or compressed)"
- [x] Added the list of supported audio containers from [libsndfile](https://libsndfile.github.io/libsndfile/api.html) to the \details section
- [x] Replaced all occurences of "wav file header" in the comments with "audio file metadata".

## Related Issue
Fixes #5971 

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
The list of audio containers/format might just want to be "all supported by libsndfile". That way we don't have to keep the comment up to date. Please amend the commit message so it's like the PR title - that makes it clearer what module it applies to. Thanks.

**Comment by willcode** [comment]
Please squash the commits. Also run `clang-format -i` on files that were changed to make sure the format check passes. Make sure that each commit (there will be only one) contains your `Signed-off-by:` so the DCO check passes. I know this seems like a lot of work for a simple comment change, but you'll be familiar with the process for bigger changes later!

**Comment by willcode** [comment]
I went back and checked in the code (`wavfile.h`) and here are the actual supported formats:
```
enum wavfile_format_t {
    FORMAT_WAV = 0x010000,
    FORMAT_FLAC = 0x170000,
    FORMAT_OGG = 0x200000,
    FORMAT_RF64 = 0x220000,
};
```
In the grc yml file it's expressed as:
```
-   id: format
    label: Output Format
    dtype: enum
    options: [FORMAT_WAV, FORMAT_FLAC, FORMAT_OGG, FORMAT_RF64]
    option_labels: [WAV, FLAC, Ogg Vorbis, 64-bit WAV]
```
So, neither of us had the right list!

**Comment by harshiiiit** [comment]
Okay, I will make these changes. But I couldn't understand the part `clang-format -i`. Can you help me out with how to do that?

**Comment by willcode** [comment]
If you changed `gr-blocks/include/gnuradio/blocks/wavfile_sink.h`, run
`clang-format -i gr-blocks/include/gnuradio/blocks/wavfile_sink.h`

**Comment by drmpeg** [comment]
Just a note that the Opus format was added. See this commit for changes:

https://github.com/gnuradio/gnuradio/commit/eaeb3789401137fa3d7f3a30fdf782f07b331cb1

**Comment by drmpeg** [comment]
Format support is asymmetrical. The source block will try to read all of the libsndfile supported formats, but the sink block only selects a subset.

Also, mp3 support is only in libsndfile version 1.1.0, which has not made it into most distros (will be in Ubuntu 23.04).

In addition, the comment in wavfile_source.h about only supporting 8 or 16 bits is no longer true.

**Comment by harshiiiit** [comment]
I am sorry I made a mistake. Going to solve it.

**Pull request closed without merging**
