### PR TITLE
Qt freq sink 2407

### LINKED ISSUE #2407: heap-buffer-overflow in gr-qtgui/lib/freq_sink_c_impl.cc
https://github.com/gnuradio/gnuradio/blob/d5e0b4b82aa2f08030d391cc878698295e525b4a/gr-qtgui/lib/freq_sink_c_impl.cc#L509

I guess it should be `sizeof(float)*(d_tmpbuflen)` instead of `sizeof(float)*(d_tmpbuflen + 1)`? Can anyone confirm?

Below is the trace from address sanitizer for GNURadio 3.7.12 but the offending line of code has not changed since.

The heap-buffer-overflow can be triggered with this simple flow graph: [bug.grc.txt](https://github.com/gnuradio/gnuradio/files/2973819/bug.grc.txt)

```
=================================================================
==22939==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000d59500 at pc 0x7f455ac7077a bp 0x7f452eee78b0 sp 0x7f452eee7058
WRITE of size 2052 at 0x621000d59500 thread T6 (freq_sink_c1)
    #0 0x7f455ac70779  (/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so+0x79779)
    #1 0x7f45344fc7b0 in memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
    #2 0x7f45344fc7b0 in gr::qtgui::freq_sink_c_impl::fft(float*, std::complex<float> const*, int) /home/hcab14/gnuradio/gr-qtgui/lib/freq_sink_c_impl.cc:500
    #3 0x7f453450040d in gr::qtgui::freq_sink_c_impl::work(int, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) /home/hcab14/gnuradio/gr-qtgui/lib/freq_sink_c_impl.cc:701
    #4 0x7f4549d6a760 in gr::sync_block::general_work(int, std::vector<int, std::allocator<int> >&, std::vector<void const*, std::allocator<void const*> >&, std::vector<void*, std::allocator<void*> >&) /home/hcab14/gnuradio/gnuradio-runtime/lib/sync_block.cc:66
    #5 0x7f4549c46ffc in gr::block_executor::run_one_iteration() /home/hcab14/gnuradio/gnuradio-runtime/lib/block_executor.cc:500
    #6 0x7f4549d8da04 in gr::tpb_thread_body::tpb_thread_body(boost::shared_ptr<gr::block>, boost::shared_ptr<boost::barrier>, int) /home/hcab14/gnuradio/gnuradio-runtime/lib/tpb_thread_body.cc:123
    #7 0x7f4549d5863a in gr::tpb_container::operator()() /home/hcab14/gnuradio/gnuradio-runtime/lib/scheduler_tpb.cc:46
    #8 0x7f4549d5863a in gr::thread::thread_body_wrapper<gr::tpb_container>::operator()() /home/hcab14/gnuradio/gnuradio-runtime/include/gnuradio/thread/thread_body_wrapper.h:51
    #9 0x7f4549d5863a in boost::detail::function::void_function_obj_invoker0<gr::thread::thread_body_wrapper<gr::tpb_container>, void>::invoke(boost::detail::function::function_buffer&) /usr/include/boost/function/function_template.hpp:159
    #10 0x7f4549bdf914 in boost::function0<void>::operator()() const /usr/include/boost/function/function_template.hpp:759
    #11 0x7f4549bdf914 in boost::detail::thread_data<boost::function0<void> >::run() /usr/include/boost/thread/detail/thread.hpp:116
    #12 0x7f4548f93bcc  (/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1+0x11bcc)
    #13 0x7f455a5ee6da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #14 0x7f455a92788e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12188e)

0x621000d59500 is located 0 bytes to the right of 4096-byte region [0x621000d58500,0x621000d59500)
allocated by thread T0 here:
    #0 0x7f455acd67a0 in posix_memalign (/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so+0xdf7a0)
    #1 0x7f454920ea0b in volk_malloc /home/hcab14/gnuradio/volk/lib/volk_malloc.c:49

Thread T6 (freq_sink_c1) created by T0 here:
    #0 0x7f455ac2ed2f in __interceptor_pthread_create (/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so+0x37d2f)
    #1 0x7f4548f92b09 in boost::thread::start_thread_noexcept() (/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1+0x10b09)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so+0x79779) 
Shadow bytes around the buggy address:
  0x0c42801a3250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42801a3260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42801a3270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42801a3280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42801a3290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c42801a32a0:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42801a32b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42801a32c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42801a32d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42801a32e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c42801a32f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==22939==ABORTING
```

### PR DESCRIPTION
**Pull request by mormj**
memcpy copying one too many elements
applied fix also for freq_sink_f_impl.cc

fixes #2407

### CODE REVIEW

**Comment by marcusmueller** [comment]
That is pure awesomeness!

Only thing I'd ask you to change: The second commit message refers to a bug number but should probably "work" standing alone. I think simply 

> qtgui: heap-buffer-overflow in freq_sink_f 

would do just as well. Makes it easier to skim the commit history later!

**Comment by mormj** [comment]
Marcus - thanks for the feedback.  Updated now with single commit and more straightforward message.

**Comment by mormj** [comment]
@mbr0wn you are right - nice catch! - will fix this shortly

**Comment by mbr0wn** [comment]
My suggestion: We add an fft_shift() function somewhere. This can have unit tests, and it could come in usefully in other pieces of code.  This function can take a buffer as a third param, so it wouldn't incur performance penalties.

**Comment by hcab14** [comment]
One way of doing this to have a separate object which manages the  buffer needed for the cyclic shift, see 
https://github.com/gnuradio/gnuradio/pull/2497/commits/b2fca466c6aa26d87f603a4f14d36a752edc6091

**Comment by mormj** [comment]
Agree on the fft shift object.  Fixed the odd/even issue in the manner it was presently coded with more intuitive variable names for the fft shift to clear the current issue.  

Will apply the fft shift as a separate function in a way that is consistent for all qt blocks that do fft shift per @hcab14 .

**Comment by hcab14** [comment]
I have already done that, see the last commit in https://github.com/gnuradio/gnuradio/pull/2497. And I would not use a _function_ for the fft shift but an object which properly encapsulates the temporary buffer.

In case you are going to repeat what I have done, I will adapt PR https://github.com/gnuradio/gnuradio/pull/2497 accordingly.

**Comment by mbr0wn** [comment]
Superseded with 6996d1b7ee20fb7611068906bb64886eb5b514ef

**Pull request closed without merging**
