### PR TITLE
Add some documentation to squelch blocks

### PR DESCRIPTION
**Pull request by jmendeth**
Explain `ramp` parameter better, and add GRC documentation to the Power Squelch block.

### CODE REVIEW

**Comment by Notou** [comment]
While you wait for the PR to be reviewed, may I suggest you add your documentation to the block pages on the [wiki](https://wiki.gnuradio.org/index.php?search=squelch&title=Special%3ASearch&fulltext=1)?

**Comment by 777arc** [comment]
@Notou That's why Marcus assigned me to review it, to make sure the change also gets updated on the wiki.  Moving forward, any PRs that change the usage of blocks, or the block's documentation itself (unless its purely developer-centric) will have to be reflected in the wiki.  These kind of changes don't happen much so this is perfectly fine with me.  It's just a small price to pay in order to have our User Documentation live in the wiki and be really easy for people to read and edit.

**Comment by 777arc** [comment]
@marcusmueller I've updated the wiki, feel free to merge.

**Comment by jmendeth** [comment]
I wasn't aware of the wiki, thanks @777arc for updating it :)

**Comment by jmendeth** [comment]
Hmm, today I noticed a little inconsistency. The documentation says `gate` is false by default.
This was copied straight from the C++ docs, and it is true:

https://github.com/gnuradio/gnuradio/blob/c57004b61d8dac8958995b535a225b81d2b12a3d/gr-analog/include/gnuradio/analog/pwr_squelch_cc.h#L61-L62

But when you create the block in GRC, it sets `gate` to Yes by default.
This is odd, most people would expect `gate = false` behaviour by default, could this be changed?

**Comment by 777arc** [comment]
Yeah, weird.  I would say don't change the functionality, just update the docs.

**Comment by jmendeth** [comment]
Done!

**Comment by 777arc** [comment]
I've updated it on the wiki as well, feel free to merge @marcusmueller

**Comment by mbr0wn** [comment]
We let this get a bit stale -- merged and resolved manually.

**Pull request closed without merging**
