### PR TITLE
runtime: fix OpenBSD doesn't have prctl()

### PR DESCRIPTION
**Pull request by landryb**
## Description

working on updating our aging gnuradio port from 3.8.2 to 3.10.11, upstreaming the patches we have that make sense..

## Which blocks/areas does this affect?
gnuradio-runtime
## Testing Done

zero runtime testing, patch builds in the context of the 3.10.11 release.

i've called out SDR users on OpenBSD to test the port update.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ ] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
looks sensible to me. I don't have an OpenBSD machine myself to test it. @landryb any vagrant (or other standard VM format) machines you use for testing?

**Comment by marcusmueller** [comment]
stoopid question, @landryb: does the "default" code work if you comment out `#include <sys/prctl.h>` and the actual call to `prctl`? It feels like *generally*, OpenBSD should be relatively close to Linux there, just that instead of the Linux-specific `prctl(PR_SET_NAME,…` one should use `pthread_set_name_np` (on OpenBSD-typical libpthreads) or `pthread_setname_np` (on Linux; don't ask me why the names differ by a single `_`).

**Comment by landryb** [comment]
if i try to adapt the linux codepath, it also fails on `cpu_set_t` type:
```
/usr/obj/ports/gnuradio-3.10.11.0/gnuradio-3.10.11.0/gnuradio-runtime/lib/thread/thread.cc:242:5: error: unknown type name 'cpu_set_t'
    cpu_set_t set;
```
im not sure its worth pursuing that effort. Or rather implement the `set_thread_name` method in the non-linux/non-windows codepath ?

**Comment by landryb** [comment]
[d7ad0b8](https://github.com/gnuradio/gnuradio/pull/7553/commits/d7ad0b8dad4b66c73c9b5199b53b49c220df64f0) fixed the DCO hell, hopefully

**Review by marcusmueller — APPROVED** [review]
nice, thanks!

**Pull request merged**
