### PR TITLE
grc: add xfce4-terminal to the grc auto-detector for XTERM_EXE

### PR DESCRIPTION
**Pull request by ZeroChaos-**
xfce4-terminal is the terminal emulator for xfce users.  Support for
gnome and kde specific terminal emulators are already here, so please
accept this as well.

Signed-off-by: Rick Farina (Zero_Chaos) <zerochaos@gentoo.org>
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Review by Yamakaja — APPROVED** [review]

**Comment by ZeroChaos-** [comment]
Give me just a few to add urxvt (by request) and squash/push.

**Comment by ZeroChaos-** [comment]
PR has been updated (with a force push due to squash).  Feedback from irc addressed.  Tested both xfce4-terminal and urxvt with "-e blah" and they both run and execute "blah" as expected.

**Review by mormj — APPROVED** [review]

**Comment by willcode** [comment]
We should be able to get this into the maint releases coming out in a couple weeks.

**Comment by ZeroChaos-** [comment]
Yes please, I was going to ask for cherry pick to the maint branches.  Do I need to open PRs or ?

**Comment by ZeroChaos-** [comment]
Thanks for the merge!

**Comment by willcode** [comment]
No, I'll backport to 3.10 and 3.9.

**Comment by ZeroChaos-** [comment]
thanks @willcode ! :-)

**Pull request merged**
