### PR TITLE
Bumped SWIG minimal SWIG version to 2.0.4

### PR DESCRIPTION
**Pull request by marcusmueller**
This is the pull for next, see #1222

### CODE REVIEW

**Comment by mbr0wn** [comment]
There is some overlap with #1215.

**Comment by marcusmueller** [comment]
@mbr0wn indeed, and #1215 does the right thing by removing old versions and making the minimal SWIG version a CMake variable and so on.

We should just also do it for the 3.7.X line, as I presume it won't disappear overly soon, and as community, we won't be rid of the "support burden" the next two years; bumping dependencies on master (and also, maint) will make our lives easier. Frankly, we've not been doing a terrible good job at testing our fixes against the versions we "promise" things should work on – I've been guilty of that several times myself, but if you want a recent example, #1227. I'd rather actually spell out what we **need** on maint than not touching the dependencies. In fact, with our dependency list, GR should build cleanly on RH 6.8, according to the RPMs I've been trying to build yesterday. It does not.

Problem is that testing this kind of thing is pretty intense, and to make matters worse, you basically have to work yourself through about 5 different versions of the Boost docs if you use a single boost function to make sure it works on 1.35 – 1.63; SWIG is worse, by far, in that most of the things where it behaves erratically are not covered by documentation, and oh, SWIG documentation.

I think the approach of taking each of the dependencies individually, looking specifically at it, filling in a table of what we perceive are distros we need to support over the next years might be an easier thing (and easier to test) than to bump all "core" dependencies at once.

**Comment by jmcorgan** [comment]
@marcusmueller I'm pretty sure that the merge up from master in #1224 covers this on next, making this PR redundant.  Can you verify?

**Comment by mbr0wn** [comment]
@jmcorgan Yep you're right. I'll abuse my powers and close this.

**Pull request closed without merging**
