### PR TITLE
New random number generator using boost.random

### PR DESCRIPTION
**Pull request by stwunsch**
Changes:
- Remove number generator from 'Numerical Recipes in C' and add boost.random implementation
- Default seed is set with system time (before the seed was always the same) -> ctime include!
- Fixed wrong laplacian transformation
- Added random class to swig -> can use it in python (especially test-cases)
- Added qa_random with test-cases for the different distributions
- Some test-cases in gr-filter and gr-atsc used a weird combination of std::random and a global in gr::random for uniform random numbers. Fixed this using the new implementation. -> Removed RANDOM_MAX global

Concerning processing load and memory use, see mailing list (New random number generator).

### CODE REVIEW

**Comment by jmcorgan** [comment]
I won't be able to fully review and test this for a couple days, but there are a few issues with the QA code. First, the code should be testing a condition and succeeding or failing; this code is doing calculations and printing to stdout for human inspection.  Secondly, QA code shouldn't output anything except upon failure.  Finally, our QA code should not depend on any optional packages like scipy in order to function.

Overall, though, on cursory inspection this looks good.

**Comment by stwunsch** [comment]
I think the QA has to check the distribution of the generator output. Now there is the problem: A check with an assert function can fail at any time because you can't do a hard decisions on random numbers. Besides the output range (and that only for the uniform generator) and the seeding, I don't see a way to write any QA code which satisfies your restrictions. Obviously you can use a lot of realisations to check the distributions and make failing very unlikely, but this would increase the run-time of the test-case excessively.

What about a stand-alone test-case for the distributions, which is not included in ctest? I could do such a test including scipy and some nice graphics. The file could be added to examples or somewhere else.

**Comment by stwunsch** [comment]
I have redone the qa test without print statements and added such a evaluation script in gnuradio-runtime/apps.

**Comment by jmcorgan** [comment]
This is a good approach, thanks for the quick update.  I'll review this further soon.

**Pull request closed without merging**
