### PR TITLE
fec: install TPC header files

### PR DESCRIPTION
**Pull request by nowls**

### CODE REVIEW

**Comment by nowls** [comment]
Not sure why I closed this.

**Comment by nowls** [comment]
@jmcorgan is it too late for this to make the next maint release?

**Comment by jmcorgan** [comment]
No, I can get this in.  Was trying to figure out how I overlooked it until I saw that you had just reopened it.

**Comment by nowls** [comment]
Thanks. My theory is that in messing with 'git push --mirror' to my gnuradio fork, I accidentally closed the PR when I deleted a branch.

**Pull request merged**
