### PR TITLE
Updated OFDM tx_ofdm.grc example for more occupied carrier flexibility

### PR DESCRIPTION
**Pull request by tim-huggins**
The OFDM tx_ofdm.grc example appears to only work when the occupied carriers are in multiple of 8 however the OFDM Loopback example and the Receiver example work with greater occupied carrier flexibility. 

I examined the ofdm_txrx.py file an noted that it did not utilize the Protocol Formatter Block but instead utilized the Packet Header Generator block (ofdm_txrx.py also did not include the Repack Bits block on the header chain). After modifying tx_ofdm.grc to utilize the Packet Header Generator I was able to change the occupied_carrier variable to (list(range(-24, -21)) + list(range(-20, -7)) + list(range(-6, 0)) + list(range(1, 7)) + list(range(8, 21)) + list(range(22, 25)),) and still properly decode values after the receiver with a QT GUI Time Sink which did not work with the Protocol Formatter Block.

### CODE REVIEW

**Comment by mormj** [comment]
Hi @tim-huggins .  Thank you for the contribution.  Would you mind squashing your commits into 1 and also giving it a name that identifies the gr module. For this example would be something like: `digital: Modified OFDM example to utilize the Packet Header Generator`.  This helps when searching/scraping the git logs.  Since this is a change to an example, it might fly under the requirements for a CLA but will find out.

**Comment by tim-huggins** [comment]
@mormj I think I have made the changes that you requested, please let me know if you need any additional changes and thank you for looking at the change.

**Comment by mbr0wn** [comment]
@tim-huggins thanks for the contribution. Can you please rebase this, and sign it off?
```
git rebase master
git commit --amend -s
```

**Review by mbr0wn — APPROVED** [review]

**Comment by tim-huggins** [comment]
> 
> 
> @tim-huggins thanks for the contribution. Can you please rebase this, and sign it off?
> 
> ```
> git rebase master
> git commit --amend -s
> ```

Welcome, and this should be done.

**Comment by mbr0wn** [comment]
@tim-huggins The rebase worked, but the sign-off did not. Try
```
git commit --amend -s
git push -f
```

**Comment by tim-huggins** [comment]
> 
> 
> @tim-huggins The rebase worked, but the sign-off did not. Try
> 
> ```
> git commit --amend -s
> git push -f
> ```

Done

**Comment by mbr0wn** [comment]
Merged manually (had to squash and rebase).

**Pull request closed without merging**
