### PR TITLE
Readme to markdown

### PR DESCRIPTION
**Pull request by dud3**
I thought making the the readme in markdown would be useful.

### CODE REVIEW

**Comment by alexbirkett** [comment]
+1 for markdown
[atom](http://atom.io) is also a good markdown editor

**Comment by jmcorgan** [comment]
Need to come to some sort of consensus on this.

**Comment by trondeau** [comment]
I've thought about this and am voting against the idea of using markdown. I find the minor improvement in readability on github to be of lesser importance than the lack of readability when opening a README file in any text editor. And I really don't want to ask people to install a program just for the sake of parsing a bit of markdown text.

**Comment by skoslowski** [comment]
I think we should try to find a middle ground here. There are a couple of minor changes that would work for both use-cases:

Markdown compatible section headers won't hurt raw readability at all. Also, using a HTML comment instead of a Python-like comment for the legal disclaimer won't make much difference either.

Although it would be nice to show the logo on GitHub, that, and the syntax highlighting stuff could be omitted.

**Comment by trondeau** [comment]
Sorry for those of you liking this feature, but I'm going to nix it. I don't see the real benefit of the formatting over how we currently have the README file. I find that it's perfectly readable.

It would be nice to see the logo, but I'd rather see that done through Github at the top of the page or something. Again, seems like such a minor thing to make a change like this over.

**Pull request closed without merging**
