### PR TITLE
cherry-pick corr_est_cc and constellation onto main-3.7

### PR DESCRIPTION
**Pull request by hcab14**
Do I understand correctly that 3.7.x tags are made from the main-3.7 branch?

If yes, can the two commits be added to the maint-3.7 branch? They are quite old and I need them in 3.7x.

Thanks

### CODE REVIEW

**Comment by mormj** [comment]
@hcab14 Yes, the 3.7.x tags are made from the maint-3.7 branch - these changes look reasonable to include as they shouldn't affect any legacy behavior since the default parameter value keeps the original normalization

**Comment by btashton** [comment]
Make sure to also pull this commit if you do e1053e44c2ed76c94c33187c44f1562e43a5fc1d

**Comment by hcab14** [comment]
@mormj : Thanks for your feedback.

@btashton: I agree. According to GitHub it is ok, but I wonder how git will handle the changes to a YAML file in https://github.com/gnuradio/gnuradio/commit/e1053e44c2ed76c94c33187c44f1562e43a5fc1d when merging onto maint-3.7.

**Comment by michaelld** [comment]
@hcab14 Would you please tag the GR38 PR to which you're referring, for completeness if nothing more?

**Comment by hcab14** [comment]
> @hcab14 Would you please tag the GR38 PR to which you're referring, for completeness if nothing more?

These are the two pull requests:
https://github.com/gnuradio/gnuradio/pull/1725
https://github.com/gnuradio/gnuradio/pull/2169

**Comment by michaelld** [comment]
@hcab14 there are conflicts to be resolved ... can you please do that & then this can be merged.

**Comment by btashton** [comment]
This is still missing the important commit I mentioned, merging without it will not expose the needed enums.

**Comment by michaelld** [comment]
Yes ... that makes sense! @hcab14 also please bring in the commit @btashton mentions.

**Comment by hcab14** [comment]
The merge conflicts are there because of clang reformatting of maint-3.7. Do I need to follow the new coding style when resolving the conflicts or will this be taken care of automatically?

**Comment by hcab14** [comment]
> The merge conflicts are there because of clang reformatting of maint-3.7. Do I need to follow the new coding style when resolving the conflicts or will this be taken care of automatically?

I have manage to resolve the commits by re-committing after clang-format. @btashton your commit is included; please check. I have noticed that the flowgraphs `gr-digital/examples/packet/example_corr_est*.grc` and `gr-digital/examples/packet/packet_rx.grc` do not work.

**Comment by hcab14** [comment]
> Failures are unrelated to this PR. I'm good to merge this. Anyone else agree or disagree?

Fine with me. 

@btashton: did you verify that the flowgraphs gr-digital/examples/packet/example_corr_est*.grc and gr-digital/examples/packet/packet_rx.grc work with your changes?

**Comment by mbr0wn** [comment]
Merged manually.

**Comment by hcab14** [comment]
Thanks for merging. However I am not convinced that `corr_est_cc` + the flowgraphs using `corr_est_cc` work as they should. It would also good to add tests for `corr_est_cc` if they do not already exist.

> @btashton: did you verify that the flowgraphs gr-digital/examples/packet/example_corr_est*.grc and gr-digital/examples/packet/packet_rx.grc work with your changes?

**Comment by btashton** [comment]
The changes that I made restored the original behavior and left the undocumented behavior as an option. No one seems to know what the magic values are in the dynamic method. Multiple people confirmed my fix restored functionality in OOT modules that before had to carry the old version. 

See #1207 for some history. That said the examples might be using the wrong mode/be broken.

**Pull request closed without merging**
