### PR TITLE
dtv: Remove superfluous set_relative_rate() in DVB-T inner coder.

### PR DESCRIPTION
**Pull request by drmpeg**
Also remove assert that was failing for 7/8 rate on debug builds.

### CODE REVIEW

**Comment by marcusmueller** [comment]
hm, seems like the right thing given this thing is `block`, but: doesn't that processing step actually *have* a fixed relative rate?

**Comment by drmpeg** [comment]
Yes, the block is using set_output_multiple(), so the number of input/output bytes (or rate) is already cast in concrete.

**Comment by mbr0wn** [comment]
set_output_multiple() will only make sure that noutput_items is a multiple of 4, in this case. The default rate is still 1 if this is removed. Which means there's a theoretical performance hit if we remove this, since the scheduler will schedule less data for this block than it has available.

The other problem with removing the rate is tag propagation. This block has no tag propagation policy, which means it'll rely on the relative rate.

If the assert is a problem maybe we can just drop that? Or maybe the assert can be fixed. Obviously, we defer to your specific expertise on the behaviour of the block itself, @drmpeg.

**Comment by drmpeg** [comment]
The block output is actually a vector of size 1512 or 6048 bytes. So the minimum output is 1512 * 4 = 6048 bytes. The scheduler does essentially the same allocations whether the set_relative_rate() is present or not. Here's the instrumented dump:

With set_relative_rate():
```
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 12, bytes = 18144, consumed = 11907
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 24, bytes = 36288, consumed = 23814
noutput_items = 4, bytes = 6048, consumed = 3969           <------ 71st iteration
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
always 4 after this point.
```

Without set_relative_rate():
```
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 12, bytes = 18144, consumed = 11907
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 40, bytes = 60480, consumed = 39690
noutput_items = 20, bytes = 30240, consumed = 19845
noutput_items = 32, bytes = 48384, consumed = 31752
noutput_items = 8, bytes = 12096, consumed = 7938
noutput_items = 4, bytes = 6048, consumed = 3969       <------- 70th iteration
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
noutput_items = 4, bytes = 6048, consumed = 3969
always 4 after this point.
```

As for tag propagation, the DVB-T transmitter flow doesn't use tags. And it's unlikely this block would be used anywhere else since it's hard wired to the number of DVB-T active ODFM carriers.

**Comment by mbr0wn** [comment]
Thou hast convinced me.

**Pull request merged**
