### PR TITLE
Add custom buffer infrastructure to runtime, defaults to NOP, maintains 3.7 API

### PR DESCRIPTION
**Pull request by jmcorgan**
This is a rebased version of #689.

### CODE REVIEW

**Comment by jmcorgan** [comment]
@sdh11 I've inserted your fix and rebased this on current master.

**Comment by sdh11** [comment]
I think the class structure needs to be reworked a bit. Currently, gr::buffer maintains internal references to vmcircbuf, which actually allocates memory. This seems a bit backwards for custom buffers, because a custom implementation inheriting from gr::buffer still holds those internal objects even though a vmcircbuf will never get allocated.

If gr::buffer were changed to an base class with vmcircbuf inheriting from it, this would clean up the class hierarchy for custom buffers without changing the API much, if at all.  Another possibility is implementing Gr::buffer as an abstract class, with generic double-mapped and single-mapped subclasses used for the actual inheritance (gr::vmcircbuf : gr::dm_buffer : gr::buffer). Since the runtime uses gr::make_buffer to allocate new buffers, it could use gr::vmcircbuf as the default.

**Comment by sdh11** [comment]
Also, with the current implementation, no information is passed to the custom allocator regarding the expected size of the buffer. This should be an easy fix by moving those calls under allocate_buffer rather than allocate_block_detail and changing the signature of the custom allocators.

**Comment by douggeiger** [comment]
@sdh11 For the second comment, the size is passed into the ctor via nitems/sizeof_item (i.e. same as before), and hence into allocate_buffer() via the d_bufsize member variable - so this behavior is unchanged from master.
 As for the first comment - I don't disagree that the use of a private vmcircbuf could be dropped - especially via re-working the class hierarchy. In my mind that was one of the next steps (and would allow addressing [issue 731](http://gnuradio.org/redmine/issues/731)). However my goal was to get a resolution to [issue 730](http://gnuradio.org/redmine/issues/730) in the meantime, and to build from there.

**Comment by sdh11** [comment]
Oh, I didn't explain my second comment very well.

In flat_flowgraph::allocate_block_detail, custom buffers are created by grblock->allocate_output_buffer(). Normal buffers are then allocated through flat_flowgraph::allocate_buffer, which has several checks in place for calculating what the size should be. What I was suggesting is that grblock->allocate_output_buffer should be moved into flat_flowgraph::allocate_buffer so that the same size checks can be applied and passed to allocate_output_buffer for the block to create a buffer of the expected size.

**Comment by jmcorgan** [comment]
Given your comments, and that we don't have a pressing use-case driving this, I'm happy to hold off on merging this to let you implement these ideas.  You could either start off with this branch if you think your changes would be incremental, or do something new.  I only ask that you keep d6a09ea.

**Comment by jmcorgan** [comment]
@sdh11 How are things with your reimplementation?

**Comment by sdh11** [comment]
I haven't been able to spend a ton of time on this due to a project ending. I did get an example single-mapped buffer working, but it required additional changes with both the buffer and buffer_readers that I don't like.  There are also issues for blocks with multiple custom input buffers that I haven't tracked down yet.

I have an idea for the direction I want to go with this, but I just need to sit down and write it up.

**Comment by jmcorgan** [comment]
Needs rebase.

**Comment by jmcorgan** [comment]
@sdh11 I'd like to see what you've changed on this for your presentation at GRCON16.  If it is substantially different then I'd like to close this and have you open a new PR; otherwise, I'd like to get your changes on top of this.

**Comment by jmcorgan** [comment]
I'm going to close this one out due to inactivity.

**Pull request closed without merging**
