### PR TITLE
Hier msg fix

### PR DESCRIPTION
**Pull request by osh**

### CODE REVIEW

**Comment by osh** [comment]
Resolves issue http://gnuradio.org/redmine/issues/862

**Comment by jmcorgan** [comment]
@skoslowski please look at the grc commit here, i'd like to merge this in directly

**Comment by skoslowski** [comment]
@jmcorgan, good to go.

**Comment by jmcorgan** [comment]
This was cherry-picked onto the maint branch as a bug fix.

**Comment by jmcorgan** [comment]
Still getting failure (hang) in qa_hier_block2

**Comment by osh** [comment]
@jmcorgan qa est fixed, now passes

**Comment by jmcorgan** [comment]
This series of commits has been squashed to a single commit, then applied to the maint branch as a bug fix.

**Pull request closed without merging**
