### PR TITLE
gr_filter_design: conditionally enable save

### PR DESCRIPTION
**Pull request by dl1ksv**
File->save fails with key error, if no filter was calculated.
So disable 'save' up to a filter was calculated.

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>

### CODE REVIEW

**Comment by willcode** [comment]
It should really also be disabled any time you change anything, and before "design". Otherwise you get old data.

**Comment by mormj** [comment]
> It should really also be disabled any time you change anything, and before "design". Otherwise you get old data.

If this is relatively simple to fix, that would be another good check to add here.  Otherwise this change alone makes some improvement.

**Review by mormj — APPROVED** [review]

**Comment by dl1ksv** [comment]
Of course, this is doable, but not quite easy. And it needs a deeper discussion. What does it mean 'outdated'.
Example:

You start gr_filter_design
switch to IIR
design           now you have a valid calculated filter

go back to FIR. Is the IIR filter now outdated ?
go back to IIR  . Is the filter now again valid ?

To be consequent, you had to clean up each 'result window' like Magnitude response, Pole plot etc.  at once, if you just change one parameter entry. Is this intended ?

**Comment by willcode** [comment]
Would it work to make Save a one-shot, e.g., enable Save after Design, then disable it after Save.

**Comment by dl1ksv** [comment]
Disableing 'Save' after saving is no big deal. I'll look if I can clear the results of 'Design' after saving in addition. I think, this would be perfect.

**Comment by dl1ksv** [comment]
Now 'Save' will be disabled after saving of a designed filter has been applied and the plotted are deleted, to make clear that you have to design a new filter before saving again.

**Review by willcode — APPROVED** [review]
Tried it out, looks good.

**Pull request merged**
