### PR TITLE
doxygen: update license to GPL v3

### PR DESCRIPTION
**Pull request by duggabe**
## Description

Update GPL software license information in doxygen docs from 1.3 to 3.0
## Which blocks/areas does this affect?

"GNU Radio Manual and C++ API Reference"

## Testing Done

Built modified files in a separate fork and verified the changes.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Do we want the docs under GPL vs FDL? I'm not up on documentation licenses. Much of the documentation is scraped from the code, so does that require GPL?

**Comment by duggabe** [comment]
Since the license citation in https://github.com/gnuradio/gnuradio is GPL, I thought it should be consistent.

**Comment by duggabe** [comment]
Looking at the rendered page https://www.gnuradio.org/doc/doxygen/index.html we talk about the free and open software, but then the FDL says "However, we do not grant such permission for the program code in our release"

That is not only contradictory but not our intent!

@willcode: My other planned PR will affect [docs/doxygen/other/main_page.dox](https://github.com/gnuradio/gnuradio/blob/main/docs/doxygen/other/main_page.dox) as well. Should it be combined with this one? If separated, they could not both be merged without conflict.

**Comment by duggabe** [comment]
Could we just delete the "Documentation License" section on that page, thus side-stepping the apparent conflict? If so, I will close this PR and generate a new one for the content of https://github.com/gnuradio/gnuradio/blob/main/docs/doxygen/other/main_page.dox only.

**Comment by willcode** [comment]
Let's keep any changes that affect licensing (including deleting that confusing paragraph) in separate PRs. Or better yet, let's not have any PRs at all that affect licensing, and we'll have a separate discussion on what should be done first.

**Comment by willcode** [comment]
Close this one.

**Comment by duggabe** [comment]
Closing as requested.

**Pull request closed without merging**
