### PR TITLE
modtool: update python docstring generation

### PR DESCRIPTION
**Pull request by sbmueller**
I noticed docstrings are created differently for in-tree and out-of-tree modules. Since the docstrings for in-tree modules are more extensive, It would be nice to also have the same structure for OOTs.

NOTE: The changed files are just copied from the global docs folder. @skoslowski stated it could be sensible to use symlinks here. Would this work or potentionally break anything?

### CODE REVIEW

**Comment by jmcorgan** [comment]
Symlinks in a repository can sometimes create issues if they are not properly handled (relative only), and it's not clear if there is a net benefit.

However, we do duplicate many files in the OOT template, and they can go stale if they are not updated when the canonical files change. Complicating it more is that some of the duplicated CMake files actually do have some changes in order to work in the OOT environment vs. in-tree.

I'd suggest keeping the duplication issue separate and evaluate this PR within the existing way of doing it.

@skoslowski @mbr0wn Let me know what you decide.

**Comment by skoslowski** [comment]
Fine with me. If this concerns more files, I rather see gr-newmod get updating during the gr build rather than using symlinks.

**Comment by mbr0wn** [comment]
I would also prefer not to have symlinks. If we can automatically update gr-newmod, that would be my preferred solution.

**Comment by jmcorgan** [comment]
Ok, I'll merge this one as-is, let me know if you plan to update how we synchronize gr-newmod files.

**Comment by mbr0wn** [comment]
:+1:

**Pull request merged**
