### PR TITLE
modtool: Run all generated C++ code through clang-format

### PR DESCRIPTION
**Pull request by ThomasHabets**
Forked off of https://github.com/gnuradio/gnuradio/pull/3377 since that was left unreviewed to the point where it could not be salvaged.

### CODE REVIEW

**Comment by drmpeg** [comment]
This should be optional. I find the current .clang-format rules to be hideous and would much rather not use them in my OOT.

**Comment by ThomasHabets** [comment]
> This should be optional. I find the current .clang-format rules to be hideous and would much rather not use them in my OOT.

It is inevitable that the generated code will have *some* style (the only code that doesn't have a style is a 0 byte file). Currently it's a mess with *no* style. It's not like this PR forces you to keep the same style in your OOT module.

**Comment by ThomasHabets** [comment]
@drmpeg fixed!

**Comment by mormj** [comment]
Approvals.  Merging.

**Pull request merged**
