### PR TITLE
Added controls for importing, exporting, and sharing LOs

### PR DESCRIPTION
**Pull request by dkozel**
This commit adds additional controls and functionality to gr-uhd.

### CODE REVIEW

**Comment by jmcorgan** [comment]
@mbr0wn ping

**Comment by mbr0wn** [comment]
:+1:

**Comment by n-west** [comment]
This breaks a new PB build

```
In file included from /home/nathan/gnuradio/v3.7.10-dev/src/gnuradio/gr-uhd/lib/usrp_block_impl.cc:23:0:
/home/nathan/gnuradio/v3.7.10-dev/src/gnuradio/gr-uhd/lib/usrp_block_impl.h:46:42: error: ‘ALL_LOS’ is not a member of ‘uhd::usrp::multi_usrp’
       static const std::string ALL_LOS = ::uhd::usrp::multi_usrp::ALL_LOS;
                                          ^
gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/build.make:54: recipe for target 'gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/usrp_block_impl.cc.o' failed
make[2]: *** [gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/usrp_block_impl.cc.o] Error 1
CMakeFiles/Makefile2:10969: recipe for target 'gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/all' failed
make[1]: *** [gr-uhd/lib/CMakeFiles/gnuradio-uhd.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
```

My UHD head is 9e0861e1b05fa88d2b6567b153a31759545e3a82 which matches latest I see on github and `grep ALL_LOS -R *` returns nothing. Can you guys confirm this works with a current/released UHD?

**Comment by jmcorgan** [comment]
This PR was reverted; please make a new one when this is corrected.

**Comment by mbr0wn** [comment]
@dkozel Looks like you forgot some ifdefs (and I missed that in the review).

**Pull request merged**
