### PR TITLE
pmt: remove extra, mis-named pmt::pmt_ functions

### PR DESCRIPTION
**Pull request by willcode**
Signed-off-by: Jeff Long <willcode4@gmail.com>

Fixes https://github.com/gnuradio/gnuradio/issues/4619

### CODE REVIEW

**Review by mormj — APPROVED** [review]

**Comment by marcusmueller** [comment]
Isn't this a non-backportable ABI break, removing symbols?

**Comment by jacobagilbert** [comment]
I don't think this should be backported, it appears to be removing cruft, not really fixing an issue.

**Comment by willcode** [comment]
It's an API break (the ABI is already broken), but apparently anyone using the API would get a link error. Not super important to take it out, so I'll let it sit here for now.

**Comment by willcode** [comment]
Even though this looks like an API change, I'm going to call it a bug and backport so no one tries to use these functions.

**Pull request merged**
