### PR TITLE
blocks: add blocks_stream_align to support acquiring alignment to TSB fr...

### PR DESCRIPTION
**Pull request by osh**
...om an unaligned TSB stream

### CODE REVIEW

**Comment by jmcorgan** [comment]
Why does the constructor create an input iostream with 1, -1 ?  The block only works on one stream, so this should be 1,1, correct?

**Comment by jmcorgan** [comment]
Tim--can you reply to the above question?  This looks good for merging, other than the above.

**Comment by osh** [comment]
Yep, will make that change - it should be 1,1 - good catch

**Comment by jmcorgan** [comment]
ping

**Comment by jmcorgan** [comment]
This could be a one line change for commit.  But I need you to let me know if that's the case.

**Comment by osh** [comment]
wow, very fixed

**Pull request merged**
