### PR TITLE
gr-blocks: Add example flowgraphs for Stream Mux/Demux blocks.

### PR DESCRIPTION
**Pull request by dave-pi**
Add a couple of example flowgraphs for these blocks. Usage is demonstrated in the wiki page of each block.

### CODE REVIEW

**Comment by mormj** [comment]
Getting a missing block error in the stream_demux_demo.

image

If I replace it with the stream demux block that is in tree, everything works great:

image

Is your example reference a block from an OOT?

**Comment by dave-pi** [comment]
> Getting a missing block error in the stream_demux_demo.
> 
> image
> 
> If I replace it with the stream demux block that is in tree, everything works great:
> 
> image
> 
> Is your example reference a block from an OOT?

oh shoot, yes. I'll replace it...

**Comment by dave-pi** [comment]
I've fixed the flowgraph, if you could test that would be great. I'm having trouble with grc 3.9 segfaulting so haven't been able to test.

**Review by mormj — APPROVED** [review]
Tested and the example look good. Thanks!

**Pull request merged**
