### PR TITLE
C++14: Use std::make_unique instead of boost::make_unique

### PR DESCRIPTION
**Pull request by marcusmueller**
Also, clean up includes

### CODE REVIEW

**Comment by marcusmueller** [comment]
Note that this PR changes no public API and thus can be merged into maint-3.9 as well as master at this point.

**Review by ThomasHabets — APPROVED** [review]
Just watched the Dec call. You beat me to it. :-P

**Review by mbr0wn — APPROVED** [review]

**Comment by mbr0wn** [comment]
@marcusmueller You really want to merge this into maint-3.9? It doesn't exactly fix a bug there.

**Comment by willcode** [comment]
Several other PRs had conflicts on maint-3.9 without this. All internal changes, so backporting.

**Pull request merged**
