### PR TITLE
blocks: callback function additions for repack_bits , stream_mux and stream_to_tagged_stream;  blocks: smoother added for throttle; digital: callback function added for packet_headergenerator; digital: naturally mapped 8psk and 16qam constellation objects added;  trellis: corrected a missing callback function

### PR DESCRIPTION
**Pull request by fengzhe29888**
Hi all,

The changes are the following:
For gr-blocks: 
1) I added callback functions to both bits per input and output bytes of repack_bits in gr-blocks to make it able to be changed dynamically. 
2) Similarly, I added callback functions to stream_to_tagged_stream and stream_mux to enable dynamical change of parameters.

3) @anastas found there exists huge delay in a system we are working on due to some buffer in the queue. He modified the throttle to decrease the delay by decreasing the samples throttle process at a time. 
So the throttle was modified by adding an optional parameter max_noutput_items.

For gr-digital:
4) I also added callback function set_header_formatter to packet_headergenerator to make the header able to be chaned dynamically.

5) I've also added two constellations objects in the constellation of gr-digital. One of the constellation object is the natural mapped 8psk and the other is a 16qam. These two constellations are both used in trellis coded modulations based on the paper by G. Ungerboeck "Channel coding with multilevel/phase signals", IEEE Trans. Info Theory, vol. IT-28, pp. 55–67, 1982.

6) I found the chunks_to_symbols has callback function set_symbol_table, but it wasn't working! I found it missed the set_symbol_table in chunks_to_symbols.grc and chunks_to_symbols.h, and added const to std::vector@O_TYPE &symbol_table to make it work.

For gr-trellis:
7) I found the trellis_encoder.grc missed the callback function set_K, so I added it to make it work.

I'm sorry that I wasn't making a clean commits history last time to cause the delay in merge. So I made everything clean and request this pull again. 
Could you check the updated changes and merge them to the gnuradio if possible.

Thanks!
Best,
Zhe

### CODE REVIEW

**Comment by jmcorgan** [comment]
Gentlemen, I'd to suggest an different approach to getting this set of things merged.

Can I work with either of you (or both) one very small commit at a time, iteratively?  This would give me an opportunity to provide immediate guidance on any issues before a lot gets built on top of things.  Then, we can build on this one by one and start making the commits larger.

**Comment by anastas** [comment]
This is a great idea.
Please let us know what would you like us to work on first.

**Comment by anastas** [comment]
May I suggest that the "trellis" commit and the "natural_8psk/16QAM" commit are merged immediately.
I really do not see any issues with those straightforward  changes.

**Comment by fengzhe29888** [comment]
Dear @jmcorgan,

Do you mind merge the "trellis" commit and the "digital: constellations" commit to the gnuradio first and then we can discuss the remaining commits and merge them step by step?

I think from your previous comments and Tom's comment, you agreed these two commits are good. 

Thanks!

**Comment by jmcorgan** [comment]
What I'd like you to do is to start a new branch off current master, with just the constellation commit on it, and submit a pull request.  We'll go from there.

**Comment by fengzhe29888** [comment]
Hi Johnathan,

I see. I'll do that and let you know.
Thanks!
Zhe

**Comment by fengzhe29888** [comment]
Hi Johnathan,

I've done a clean new pull request. Could you check it?

Thanks!

**Comment by jmcorgan** [comment]
Looking at it now.  I'll close this pull request and we can iterate on that one.

**Pull request closed without merging**
