### PR TITLE
gnuradio-companion: Exit if no X server available.

### PR DESCRIPTION
**Pull request by balister**
Signed-off-by: Philip Balister <philip@balister.org>

### CODE REVIEW

**Comment by marcusmueller** [comment]
Isn't that a bit misleading, potentially? The X server being absent is not the only source of problems when importing gtk, and if any other exception is raised (or warning is converted to exception, but I don't find many other warnings) everything shown to the user will be "you're using SSH incorrectly". 

Being in the support business, I think this is the most likely cause for GRC to fail starting (aside from wrong paths), but it might bite us later, if some distro decides to ship a GTK that somehow throws upon import.

It shouldn't be hard to figure out the actual type of Exception that the warning is converted to, so can't we just except against that?

**Comment by balister** [comment]
On 06/29/2015 08:02 AM, Marcus Müller wrote:
> Isn't that a bit misleading, potentially? The X server being absent is not the only source of problems when importing gtk, and if any other exception is raised (or warning is converted to exception, but I don't find many other warnings) everything shown to the user will be "you're using SSH incorrectly". 
> 
> Being in the support business, I think this is the most likely cause for GRC to fail starting (aside from wrong paths), but it might bite us later, if some distro decides to ship a GTK that somehow throws upon import.
> 
> It shouldn't be hard to figure out the actual type of Exception that the warning is converted to, so can't we just except against that?

You are correct, I am a gtk n00b.

**Comment by marcusmueller** [comment]
For ref: [this](http://pastebin.com/SsqrdMH9) is the people might be getting, to illustrate the intensity of @balister 's desire to solve this.

**Comment by jmcorgan** [comment]
I think it could just say "Failed to import Python GTK module, unable to continue...<possible reasons>"

**Comment by skoslowski** [comment]
I agree. Please change the message, send it to stderr instead and reissue this against maint_grcwg

**Comment by balister** [comment]
I updated the branch and rebased against the grcwg maint branch. I don't have a fork of that repo so no pull request.

https://github.com/balister/GNU-Radio/commit/5946806c62e8a04f4b348455ce8aa762749ee59d

Should have a better message and uses sys.exit to print to stderr and exit.

**Comment by jmcorgan** [comment]
@skoslowski You can just cherry-pick this commit to your maint branch.  Let me know when you do and I'll close this one out.  It will all get rolled up when you're ready to PR your maint branch.

**Comment by skoslowski** [comment]
Done. Thanks, Phil.

**Pull request merged**
