### PR TITLE
filter: continue transition to pyqtgraph and pyqt5

### PR DESCRIPTION
**Pull request by mormj**
continue the work of @ekigwana to get a stable version of filter_design_tool on 3.8 branch

Still missing functionality and issues

### CODE REVIEW

**Comment by 777arc** [comment]
The IIR option doesn't seem to be doing anything for me, no errors, but no updates in the output either.

**Comment by mormj** [comment]
@777arc Interesting - this was working at some point - no trick I know to get it working.  Will debug on my end

**Comment by mormj** [comment]
@777arc - should be good to go now.  Looks like the text in the box was changed from IIR(numpy) to IIR(scipy) which it was keying off of.

**Comment by mbr0wn** [comment]
This seems to a big improvement.

**Pull request merged**
