### PR TITLE
Fix compilation under mingw-w64

### PR DESCRIPTION
**Pull request by pcercuei**
This set of patches fix a few issues reported when compiling GNU Radio using mingw-w64 under Linux.

### CODE REVIEW

**Comment by jmcorgan** [comment]
This will get reviewed by @ncorgan for overlap and incorporation into his mingw work.

**Comment by jmcorgan** [comment]
@pcercuei Per the email thread I had started a while back, I want to consolidate all the windows bugfixes under one pull request/branch.  Can you confirm these are still valid?  I will be starting a new branch and will cherry-pick these into place once you confirm, then close this PR.

**Comment by pcercuei** [comment]
Honestly, I don't build it under mingw anymore - you can close this PR for now.
I will prepare a 'msvc' branch that contains fixes for Windows.

**Comment by jmcorgan** [comment]
Refer to #822 for continuation of this work.

**Pull request closed without merging**
