### PR TITLE
grcqt: add missing xterm_executable to qsettings

### PR DESCRIPTION
**Pull request by dl1ksv**
The xterm_executable variable was part of Config.py and was removed with #https://github.com/gnuradio/gnuradio/commit/e10de5c71d473a29cb296348165eab2edf3c9c1e.

### CODE REVIEW

**Review by haakov — APPROVED** [review]
Merging once the PR has been rebased :)

**Comment by dl1ksv** [comment]
Rebased

**Comment by haakov** [comment]
Looks like the rebase didn't quite do the trick. The feature-grc-qt branch was also rebased recently, maybe you created the xterm branch before that?

In that case, it might be easier to create a new branch from origin/feature-grc-qt and just cherry-pick https://github.com/gnuradio/gnuradio/pull/7142/commits/d86f8f109c98b29b59e7c6621c7cc7d65d048652 on top of that (and force push that branch to the xterm branch)

**Comment by dl1ksv** [comment]
Sorry, seems, that I screwed up my feature-grc-qt branch.
So I close this pr and fix this issue in #7148

**Pull request closed without merging**
