### PR TITLE
Small C++ modernization

### PR DESCRIPTION
**Pull request by gerstrong**
## Description
Just a small change that avoids running into initialization order problems when constructor init lists is used for default values

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ ] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Was there a problem changing the order of the initializers?

**Comment by gerstrong** [comment]
No, but whenever you change them you get a warning about initialization order. By removing init variables that get default values anyways you reduce that risk. Usually such warnings arise, when you decide to add another member somewhere in the class declaration and in the constructor init list you put it somewhere, messing up the order.

Why are order in init list important? https://www.geeksforgeeks.org/order-of-execution-in-initializer-list-in-c/

**Comment by willcode** [comment]
Best I can tell, using initializer lists is the "modern" way, initializing in declaration order is important, and that's what the warning is for. For trivial values, there's not much advantaage to initializer lists, but if an expression is used for an initial value, then in-constructor initialization is required and use of an initializer list helps check the order. This is also the way we (try to) do things throughout the code.

If someone else has opinions on this, let me know. Otherwise, we'll stick with constructor lists and fix any broken ordering turned up by warnings.

**Comment by gerstrong** [comment]
Similar discussion already here: https://stackoverflow.com/questions/36600187/whats-the-differences-between-member-initializer-list-and-default-member-initia

I have a preference for default member initialization and keeping constructors as slim as possible, especially if you have to declare different constructors and repeat defining the init lists with the same default variables. Anyway, it is up to you how to decide on this. It still would be nice though to use nullptr instead of NULL, but same here; up to you...

**Comment by mbr0wn** [comment]
I have a tendency towards default member initialization because they tend to keep the code shorter, and the core guidelines recommend it: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c48-prefer-default-member-initializers-to-member-initializers-in-constructors-for-constant-initializers

...but not a strong one, and it does get tricky when you mix both styles (one attribute gets initialized up there, another down there).

@gerstrong If you wanted this PR merged, you should fix the commit message according to our guidelines (assuming @willcode  even wants to merge this).

**Comment by willcode** [comment]
Given that the majority of GR uses initializaiton in the constructor (including gr-uhd), I don't really want to start making this change without the intent to update the codebase (huge undertaking). It would be too confusing. Even after this PR, the initialization of this class would have a mix of initialization based on the args to the constructor. This is practical for this particular (the only) constructor, but doesn't help with any kind of code goodness goal.

The nullptr changes are welcome. We're trying to gradually get rid of NULL.

**Comment by gerstrong** [comment]
Well, I will make a new PR then. Feel free to reject this one.Von meinem iPhone gesendetAm 16.07.2024 um 13:15 schrieb Jeff Long ***@***.***>:﻿
Given that the majority of GR uses initializaiton in the constructor (including gr-uhd), I don't really want to start making this change without the intent to update the codebase (huge undertaking). It would be too confusing. Even after this PR, the initialization of this class would have a mix of initialization based on the args to the constructor. This is practical for this particular (the only) constructor, but doesn't help with any kind of code goodness goal.
The nullptr changes are welcome. We're trying to gradually get rid of NULL.

**Comment by mbr0wn** [comment]
> Given that the majority of GR uses initializaiton in the constructor (including gr-uhd), I don't really want to start making this change without the intent to update the codebase (huge undertaking). It would be too confusing. Even after this PR, the initialization of this class would have a mix of initialization based on the args to the constructor. This is practical for this particular (the only) constructor, but doesn't help with any kind of code goodness goal.

Yeah, I agree with that. Thanks for pushing back on cosmetic changes 😄

**Comment by mbr0wn** [comment]
> Well, I will make a new PR then. Feel free to reject this one

@gerstrong Many thanks for your contribution! I'll close this PR to keep the PR queue tidy.

**Pull request closed without merging**
