### PR TITLE
cmake: Use -undefined dynamic_lookup linkage for python (swig) on macos

### PR DESCRIPTION
**Pull request by kolen**
Second try of #604.

Use of ``-undefined dynamic_lookup`` to link against python in mac os is recommended by many people ([github search](https://github.com/search?l=CMake&q=undefined+dynamic_lookup&type=Code&utf8=%E2%9C%93)) and seems python's distutils uses it too (I can't confirm). And it is [requirement for package to be included in homebrew core](https://github.com/Homebrew/brew/blob/c9c7f462d37500549127efba96c7a25e5c70de4a/Library/Homebrew/extend/os/mac/formula_cellar_checks.rb#L45) — currently homebrew has gnuradio without python.

Tried to build with it and without (by swapping blocks inside `if`), it produces differently linked binaries. Not yet tried to build on other systems, however.

### CODE REVIEW

**Comment by jmcorgan** [comment]
I've set this to the 3.7.10.2 milestone, which would require it to be changed to branch off maint.  If we merge this I'll probably just cherry-pick it, however.

**Comment by michaelld** [comment]
Cool. I like this change better than the prior one. Let me test it out & see what comes of it. Solving the Python linkage / runtime problem would be nice. Simultaneously I would prefer that non-Python undefined symbols be caught & error out at linking. Not sure if we can do both. One step at a time ...

**Comment by michaelld** [comment]
OK. This version builds for me & passes "make test". Good first step.

It is a total PITA to get this working with Apple's Python, but it does work!

@jmcorgan : I think this is a reasonable way to address the issue Mac OS X users have where Python ABI and runtime are mixed. I'm approving it. We also need to get it added to modtool's GrSwig cmake file.

**Comment by tdsmith** [comment]
> Simultaneously I would prefer that non-Python undefined symbols be caught & error out at linking. Not sure if we can do both.

You may be able to get this behavior by passing `-bundle_loader` to ld:

```
     -bundle_loader executable
                 This specifies the executable that will be loading the bundle output
                 file being linked.  Undefined symbols from the bundle are checked
                 against the specified executable like it was one of the dynamic
                 libraries the bundle was linked with.
```

but I've never done this in anger.

**Comment by michaelld** [comment]
Oh! I've never heard of that. Testing right now ...

**Comment by michaelld** [comment]
@jmcorgan : Looks like "bundle_loader" actually adds the "executable" to the DYLD linkage, which is what we're trying to avoid. Who would have known? Could be that this flag is -supposed- to work like "-undefined ...", but its actual implementation is not working as such. Either way, seems like we're better sticking with the "-undefined" fix. It does work, but when using it it'll be more difficult to diagnose linking issues related to undefined symbols ... that's a reasonable trade-off, IMHO.

**Comment by jmcorgan** [comment]
@michaelld Ok, let me know (via the github review and approval process) once this branch implements your preferred change *and* it is also done for the OOT module in gr-utils.

**Comment by tdsmith** [comment]
Sorry for the misdirection!

**Comment by michaelld** [comment]
NP Tim. It was worth a try! It sounded so promising! I really do wish GCC & Clang provided this feature (and, it worked). Thanks for offering it up!

**Comment by jmcorgan** [comment]
Was there ever a conclusion on whether this PR should be merged?

**Comment by michaelld** [comment]
Yes, merging is OK if you want to; not quite complete since modtool should also have the same change added to it's cmake Modules file. You asked me to get my preferred changes in place ... just not enough time to do that yet. I've got in on my queue for next week, if you can wait that long.

**Comment by jmcorgan** [comment]
Yes, that would helpful.  We're aiming for a 3.7.10.2 and 3.7.11 release shortly; this would be good to get in.

**Comment by michaelld** [comment]
OK. I'll bump it up in my queue to ASAP then. Probably still next week though. Too many Q4'16 items to get finished still.

**Comment by kolen** [comment]
Applied these changes to `GrSwig.cmake` in `gr-newmod` too (not tested).

**Comment by michaelld** [comment]
Thanks for getting that change pushed. @jmcorgan : this PR is now ready for merging.

**Comment by jmcorgan** [comment]
This was cherry-picked onto the maint branch for release as 3.7.10.2

**Pull request closed without merging**
