### PR TITLE
gr::blocks::repeat: add runtime interpolation adjustment

### PR DESCRIPTION
**Pull request by marcusmueller**
* Addition by Kevin McQuiggin: Repeat now can be reconfigured at runtime
* Thread safety by me: reconfiguration moved to msg handler

### CODE REVIEW

**Comment by jmcorgan** [comment]
@marcusmueller  do we have copyright assignment from @mcquiggi ?

**Comment by mcquiggi** [comment]
Certainly, do I have to do anything formally?

Kevin

**Comment by marcusmueller** [comment]
@jmcorgan didn't consider that; does the FSF make a difference for "small" changesets? This one's about 5 LOC...

**Comment by mcquiggi** [comment]
Small in volume of code but big in terms of figuring out Gnuradio and c++ !!

**Comment by marcusmueller** [comment]
> Small in volume of code but big in terms of figuring out Gnuradio and c++ !!

Exactly, and that's why I am liking this so much :)

**Comment by jmcorgan** [comment]
Well, it's an edge case and I'd rather get an assignment that would cover this and future contributions.  @trondeau handles these.

**Comment by mcquiggi** [comment]
Hi Jonathan and Marcus:

I’m happy to contribute and thus will assign rights, give up copyright, or otherwise just give the code away to the project.  If there are forms or something then that’s fine but hopefully it needn’t be that formal!

Please take the block as a donation or suggestion and incorporate it if you would like to.  As i said to Marcus, it may be small in terms of lines of code, but the real value for me was starting down the path of learning to write blocks, and learning C++.  I am an experienced developer but didn’t know anything much about C++, and zero of gnuradio internals, until this little task.

Thanks to Marcus for the great background information and support as I figured it out!  Hopefully somebody else can use the block.

Kevin

**Comment by jmcorgan** [comment]
@mcquiggi Thanks for your contribution; we really appreciate it.  Part of the motivation for requesting the copyright assignment is that I'm expecting more good stuff and we might as well stay ahead of the curve.

**Comment by mcquiggi** [comment]
Hi Johnathan:

Thank you, and glad to help.

You have my agreement, is there anything else required?

Kevin

**Comment by trondeau** [comment]
@mcquiggi Can you send me an email? I can't find your email address.

Unfortunately, just saying you give us your agreement isn't actually what we need. We have a full legal agreement structure set up with the Free Software Foundation that we need to go through to actually get this sorted. But we do it once and we'll set it up so you never have to do it again to contribute.

Thanks!

**Comment by mcquiggi** [comment]
Hi Tom:

Sure!  It’s mcquiggi@sfu.ca <mailto:mcquiggi@sfu.ca>.  Please send me the docs.

I got swamped at work so no time to write any docs for those undocumented blocks.  It is still on my plan!

Kevin

**Comment by jmcorgan** [comment]
@mcquiggi @trondeau Did assignment ever happen here?

**Comment by trondeau** [comment]
@jmcorgan yes, @mcquiggi is all set on the copyright assignment.

**Comment by mcquiggi** [comment]
Thanks!  It is nice to be able to contribute to the project in a minuscule way!

Kevin

**Pull request closed without merging**
