### PR TITLE
digital: added callback function set_header_formatter to packet_headergenerator_bb

### PR DESCRIPTION
**Pull request by fengzhe29888**
Hi @jmcorgan 

I've created another new branch with the updates on packet_headergenerator of gr-digital. Could you check it?

Thanks!
Best,
Zhe

### CODE REVIEW

**Comment by jmcorgan** [comment]
I don't think the the header formatter object shared pointer should be passed as a reference, but need to think about it.

**Comment by fengzhe29888** [comment]
Hi Johnathan,

We made a new packet_header class in our OOT module which includes the
modulation/coding type. In our adaptive modulation/coding system, once the
modulation/coding type is changed, the header_formatter should also be
changed. That's why we want to add callback function for header_formatter
in packet_headergenerator.

Thanks!
Best,
Zhe

**Comment by jmcorgan** [comment]
Can you please resubmit this with a change that passes the header formatter object shared pointer by value, not reference.

**Comment by fengzhe29888** [comment]
Hi Johnathan,

Could you check it again now?

Thanks!
Best,
Zhe

**Comment by jmcorgan** [comment]
There is no need for either const or pass by reference for shared pointers, they are explicitly designed to be passed by value.  Can you remove the const as well?  It would be best if the commits were squashed as well.

**Comment by fengzhe29888** [comment]
Sure. I've removed the const, and I'll squash the commits now.

Thanks!

**Comment by fengzhe29888** [comment]
Hi Johnathan,

I squashed the commits into one. Could you check it?

Thanks!
Zhe

**Pull request merged**
