### PR TITLE
qtgui: allow axis labels on/off modes

### PR DESCRIPTION
**Pull request by osh**

### CODE REVIEW

**Comment by trondeau** [comment]
@osh: setting the axis labels off on the waterfall sinks doesn't do anything. Also, we should probably add this to the Constellation Sink and Time Raster Sink blocks. It causes an error if you have the Time Raster Sink in a flowgraph, so that needs to be fixed, anyways.

I would also argue that the setting belongs under the Config tab.

Awesome that you added it to the menu for runtime control.

**Comment by osh** [comment]
All of these issues are now addressed

**Comment by trondeau** [comment]
Almost there. It looks like you forgot to add the "self.$(id).enable_axis_labels($axislabels)" line to the constellation and histogram sink xml files. I think everything works as expected after that.

**Comment by osh** [comment]
ah good catch

**Comment by osh** [comment]
changes pushed, i wish we could consolidate a lot of the duplicitous code some day around these parts

**Comment by trondeau** [comment]
Looks good now!

**Pull request merged**
