### PR TITLE
digital: constellation_receiver_cb rework

### PR DESCRIPTION
**Pull request by marcusmueller**
Removes `tag_checker`

Improves performance

### CODE REVIEW

**Review by mormj — APPROVED** [review]

**Review by ThomasHabets — APPROVED** [review]

**Review by jdemel — APPROVED** [review]
LGTM.

Is this a deprecated block?

**Comment by marcusmueller** [comment]
@jdemel no, not that I'd be aware of. Why?

**Comment by jdemel** [comment]
Because I thought the modulator is deprecated. Also, this block performs a few distinct things. demodulation with hard decision and computes error margins. I'd argue these are several processing steps. Beginners would have a hard time figuring out how such a block works. Since this block computes symbol-wise results, it is not the best solution to in terms of performance for people who know exactly what they do. It is somewhere in between.

**Comment by marcusmueller** [comment]
> Because I thought the modulator is deprecated. 

You've got me confused there! *Which* modulator?

> Also, this block performs a few distinct things. demodulation with hard decision and computes error margins. I'd argue these are several processing steps. 

I must admit I don't really see how – this is decision feedback phase sync. You need to directly feed back the error margins: 

        sym_value = d_constellation->decision_maker_pe(&sample, &phase_error);
        phase_error_tracking(phase_error); // corrects phase and frequency offsets

Here, the phase error occurs "naturally" inside the demod. It's a Costas loop! Of sorts at least, because Mr. Costas made that for PSKs only, and this works for any constellation.

> Since this block computes symbol-wise results, it is not the best solution to in terms of performance for people who know exactly what they do. It is somewhere in between.

Well, but it *is* a Costas loop. So, the error performance should be the same as for our costas loop block (for PSKs). A fair question would be "why is there two Costas Loops", but I argued to myself that the BPSK/QPSK Costas loop was such a special case that the optimizable implementation we have in `costas_loop_cc` deserved its own block; this indeed is a bit of an unusual use case, but I see why I'd want to use it – especially to calculate mean phase noise variance on QAM-style modulations, which is a nice metric in nonlinear channels.

**Pull request merged**
