### PR TITLE
cmake: FindQwt: Allow pkg-config to set the library name

### PR DESCRIPTION
**Pull request by mbr0wn**
Currently, the library name is hard-coded to qwt-qt5 to force
disambiguation from the Qt4 version. However, when pkg-config is
invoked, other package names (e.g. qwt) are also permissable, since we
trust pkg-config to not point us to a Qt4 version of Qwt.

This will let @balister build on OE.

### CODE REVIEW

**Comment by marcusmueller** [comment]
That sounds right! But shouldn't this imply that we use the pkgconfig-found results with highest priority?

**Comment by noc0lour** [comment]
Are results in `NAMES` priority sorted?

**Comment by mbr0wn** [comment]
Good question. I think they are.

**Comment by mbr0wn** [comment]
Actually, the CMake docs say nothing about this. However, I'll still put them front, even if it's just to document the intention.

**Comment by mbr0wn** [comment]
I changed the order to use the PC vars first, and tested on a system without the PC file to make sure the empty var doesn't screw things up.

**Comment by michaelld** [comment]
CMake should search in the order provided. So listing the PC provided library name first is the correct way to go here.

**Pull request merged**
