### PR TITLE
grc: A generated python hier_block is written to the wrong directory

### LINKED ISSUE #5531: Hier Blocks are not installed to ~/.grc_gnuradio
### What happened?

If you create Hier blocks in GRC and run them the generated python and block description file are generated int he same folder as the .grc file. They are not copied to ~/.grc_gnuradio .

### System Information

OS: Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

GR Installation Method: Source

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.10.0.0-5-g3349d483

### Steps to Reproduce the Problem

1. Create Hier block in GRC
2. Run it to install
3. Reload Block list
4. Hier block is not available because it was not copied to ~/.grc_gnuradio . Generated files are in the same folder as the .grc file of the Hier block and cannot be found by GRC.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dl1ksv**
---

# Pull Request Details

The generated code is written to the directory of the generating grc file
instead to the 'hier_block_lib_dir' directory.

cpp generated code ends up in the correct directory.

This error was introduced with commit af3fbe432fe16efb05f26c24a0fa9724680dc8dd

## Description

Take the directory from the config settings ( as before)

## Related Issue

Fixes #5531

## Testing Done

Tested with different hier blocks

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Does this still work with grcc? #4871 makes it seem like this change was intended. Should the correct directory be passed in from above instead of ignored?

**Comment by dl1ksv** [comment]
Good point. 

Without my patch
In case test.grc is a hier block with output langage python
grcc -o /tmp/test test.grc
is written to /tmp/test
but if the output language is c++ the code is written ~/.grc_gnuradio/
which is not intended.

After my patch in both cases the code is written ~/.grc_gnuradio.

All other combinations of generation option and output language are not affected by my patch.
To write hier block code to the specified output directory this should be fixed in grcc.
This is done by the following commit.

**Comment by mormj** [comment]
> After my patch in both cases the code is written ~/.grc_gnuradio.

Shouldn't the output given `grcc -o /tmp/test` be to /tmp/test in both cases?

**Comment by dl1ksv** [comment]
Yes, but I wanted to point out, that this was not the case without any patch. After my first commit the code for the hier block is written to ~/.grc_gnuradio  , independently of the the output language. For other types the code is written to the correct directory.
The second commit forces grcc -o /tmp/test to write to  /tmp/test for hier blocks , too.

**Comment by mormj** [comment]
Ah ok - I didn't get the distinction between the two commits. Thanks!

**Comment by mormj** [comment]
Tested and working - sorry for the delay and thank you for the fix.

**Review by mormj — APPROVED** [review]

**Pull request merged**
