### PR TITLE
Enable parameter block for BokehGUI

### PR DESCRIPTION
**Pull request by kartikp1995**
Solves kartikp1995/gr-bokehgui#9

### CODE REVIEW

**Comment by mbr0wn** [comment]
@skoslowski needs to review this.

**Comment by marcusmueller** [comment]
Calling @skoslowski on this, I know your time is sparse, but I'd really love to merge Kartik's code.

**Comment by mbr0wn** [comment]
Hm that's too bad. Well we'll close this PR for now. @kartikp1995 can you please rebase it?

**Comment by kartikp1995** [comment]
Sure. I will look into porting gr-bokehGUI to GR 3.8 sometime this semester. Thanks.

**Pull request closed without merging**
