### PR TITLE
spdlog: include spdlog system settings header before including spdlog/fmt/

### LINKED ISSUE #6927: 3.10.8.0 build failure
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  /opt/homebrew/include/spdlog/fmt/fmt.h:27:14: fatal error: 'spdlog/fmt/bundled/core.h' file not found
  #    include <spdlog/fmt/bundled/core.h>
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6589047383/job/17902765159
relates to Homebrew/homebrew-core#151928

### PR DESCRIPTION
**Pull request by marcusmueller**
Otherwise, spdlog/fmt/anything.h might include the internal
fmt/anything.h, although spdlog is set up to use an external fmt.

This is addressed upstream in
https://github.com/gabime/spdlog/issues/2922 .

## Description

Just an `#include <spdlog/tweakme.h>` with an explanatory comment on why reordering the include would be a bad idea.

## Related Issue

Hopefully:

Fixes #6927

## Which blocks/areas does this affect?

a couple, sadly including public runtime headers

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by marcusmueller** [comment]
> Including tweakme in any code that uses spdlog just doesn't seem right.

it's only that code which uses spdlog/fmt without using spdlog beforehand!
The alternative would have either adding another layer of redirective header, or to include spdlog – something I actively don't want to do in io_signature.h

**Comment by marcusmueller** [comment]
> I'd rather avoid github links in the code.

Sure, I can include a short explanation in place

**Comment by willcode** [comment]
Another level of header would be better than tweakme. That really looks like an internal spdlog/packager thing. Even including spdlog would be better - you don't like that one due to compile performance?

BTW, spdlog headers use `#pragma once`, mostly without `#ifdef` guards, so we're already requiring the compiler to support it!

**Comment by willcode** [comment]
Does this fail on anything other than homebrew, and will homebrew pull the latest fmt with the fix?

**Comment by chenrui333** [comment]
yeah, homebrew just always build whatever latest dependency.

**Pull request merged**
