### PR TITLE
gr-filter: Add complex band rejection filter design helpers

### PR DESCRIPTION
**Pull request by Yamakaja**
Adds three new helper functions that allow for easier creation of complex band rejection filters.

### CODE REVIEW

**Comment by drmpeg** [comment]
Works great!

image

**Comment by Yamakaja** [comment]
> 1. Change all occurrences of `lptaps` to `hptaps`.
> 2. Add the YAML to instantiate the new filters. I've done the dirty work for you as part of testing.
> 
> http://www.w6rz.net/filter_band_reject_filter.block.yml
> 
> http://www.w6rz.net/variable_band_reject_filter_taps.block.yml

Alright, i've corrected the variable naming (:blush:) and integrated your updated grc ymls - is there a way i can credit you for those in the commit?

**Comment by drmpeg** [comment]
Don't worry about the credit. Happy to help out with this sweet new feature.

**Review by mormj — APPROVED** [review]
Thanks for the new feature - looks great!

**Pull request merged**
