### PR TITLE
grc: prevent Generate/Run silent fails for unsaved GRC flowgraphs

### LINKED ISSUE #6185: Generate/Run fails silently if the GRC flowgraph has not yet been saved
### What happened?

Clicking the Generate or Run buttons has no effect and prints/displays no error message if the flowgraph has not been saved yet.

Possible fixes from best to easiest:
* Display a pop-up dialog saying that the flowgraph needs to be saved before Generating and include a button to "Save Flowgraph" and "Cancel". Launch the regular save dialog box and then return to Generating after a successful save.
* Display a pop-up dialog saying that the flowgraph needs to be saved before Generating and have an "OK" button to close.
* Print a console message saying the file needs to be saved before generating.

### System Information

OS: Ubuntu 20.04
GNU Radio 3.10 installed from the releases PPA on September 1st.

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Create a blank/new flowgraph. Press the Generate or Run buttons.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by haru-02**
## Description

Before change : Generate/Run button when clicked on a new flow-graph fails silently with no warning or error message.
After change : Clicking Generate/Run button on an unsaved GRC flow-graph prompts you to save the file.
## Related Issue

Fixes #6185 
## Testing Done

Make test ran successfully with no errors.
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
On the right track, but this causes ALL flowgraphs to be marked as unsaved when opened. If a flowgraph is not modified, it should not need to be saved.

**Comment by haru-02** [comment]
okay, i will try and correct it. Thanks for the feedback  :+1:

**Comment by haru-02** [comment]
@willcode It does not mark ALL flow-graphs as unsaved now. please just try once on your end and let me know if there are any more bugs. :+1:

**Comment by willcode** [comment]
That looks right. I'll give it a try when I get a chance.

**Comment by willcode** [comment]
@haru-02 Don't worry about OSX at the moment. I re-ran the Ubuntu 22.04, which is probably unrelated.

**Review by mbr0wn — APPROVED** [review]

**Pull request merged**
