### PR TITLE
grc: add middle mouse button panning

### LINKED ISSUE #7178: grc: Panning Canvas using Middle-Mouse button
### Feature Description

While drawing flowgraphs, panning the canvas is possible only by using the scrollbars. 
The trackpad panning is there, but not using the mouse.
Hence, having the middle mouse button to pan would be great.

### Feature Urgency

medium (would be nice to have in the near future)

### More Information

_No response_

### PR DESCRIPTION
**Pull request by vnydv**
## Description

While drawing flowgraphs, panning the canvas is possible only by using the scrollbars.
The trackpad panning is there, but not using the mouse.
Hence, implementing the middle mouse button pan here.

## Related Issue

Fixes #7178

## Which blocks/areas does this affect?

DrawingArea

## Testing Done

Did UI test
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Thanks. We're going to try to keep feature parity between the current (Gtk) and new (Qt) GRC GUIs. The Qt version will become an option soon. If you can, take a look at the feature-grc-qt branch and see what it would take to add this feature to the Qt version too. Eventually, the Qt version will become the default.

**Comment by vnydv21** [comment]
Sure @willcode , I will try looking into the feature-grc-qt branch also.

**Comment by haakov** [comment]
@vnydv21 I've got some links to get you started :)

https://github.com/gnuradio/gnuradio/blob/8c8368774eadbff68e0450125cbbd82d7a05c216/grc/gui_qt/components/flowgraph_view.py#L159

https://stackoverflow.com/questions/4753681/how-to-pan-images-in-qgraphicsview

PS: For the record, you can pan up/down using the mouse wheel, and left/right with the mouse wheel while holding Shift. This is implemented in both GRC Gtk and GRC Qt.

**Comment by vnydv21** [comment]
@haakov :sweat_smile: 
tbh, after when _willcode_ mentioned that, I found that this feature is already implemented in the upcoming GUI. 
Still, thanks for the resources.

**Comment by vnydv21** [comment]
@willcode, it seems like we can close this issue now. As @haakov mentioned, and I also checked, this feature is available in the Qt version.
The other things related to pan related _key combos_ you mentioned can be looked for.

**Comment by willcode** [comment]
I see the standard mouse wheel pan in Gtk and Qt, but no middle button pan (the subject of this PR).

**Comment by vnydv21** [comment]
Yeah, that's true. 
And having a middle mouse one (without holding shift) is good, less key presses. :)
So, will add that.
Hope, it's fine.

**Comment by willcode** [comment]
I'm hoping we get the Qt version merged soon. For now, make a separate PR against feature-grc-qt.

**Comment by vnydv21** [comment]
@willcode, shall I make a PR in the main for GRC QT, given it's also in the main now?

@haakov, there is an issue with the flowgraph's block dragging; they can be dragged in the negative axis ;P, 
with no scrollbar adjustments.

**Pull request merged**
