### PR TITLE
grc: pluggable workflow

### PR DESCRIPTION
**Pull request by ZakyHermawan**
## Description

Modularize options block by converting it to python file
Let people to define their own workflow

## How to add workflow ?
1. go to grc/workflows
2. make your own workflow module
3. Make the code generator class
4. Declare your codegen class in __init__,.py of your workflow module
5. Make your own template for code generation
6. make your workflow YAML file with extension .workflow.yml

The workflow YML file should consist of:

id: your workflow id
description: description of your workflow
output_language: id of your output language
output_language_label: output language label to show in PropsDialog
generator_module: location of your generator module, ex: gnuradio.grc.workflows.cpp_hb_qt_gui
generator_class: class name of your code generator class, ex: CppQtHierBlockGenerator
generate_options: generate options that will be used to select how to generate the code
generate_options_label: generate options label to show in PropsDialog
parameters: list of parameters of your workflow (the format each params if following previous format on options.block.yml) 
asserts: (optional) assertion for options block
See workflow definition on: grc/core/workflow.py

## Related Issue

https://github.com/gnuradio/gnuradio/issues/5315

## Which blocks/areas does this affect?

options block, tests, code generations

## Testing Done

Make workflows, add flow graph for each workflow for test and run them (generate and execute), make tests

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by ZakyHermawan** [comment]
image

I passed the test on my local, the error on CI is coming from No module named gnuradio.grc on grc_test:
```
    from gnuradio.grc.core.blocks._flags import Flags
E   ModuleNotFoundError: No module named 'gnuradio.grc'
```
But I think my import statements are correct since I'm importing from gnuradio directly instead of referencing the grc directory (for ex: from grc.core.blocks)

**Comment by mbr0wn** [comment]
Hey @ZakyHermawan, @haakov: I was going to give this branch a spin, but ignoring the need for a rebase I noticed:

- It's broken. I'm still trying to get this to run (I've done a rebase, and fixed some more obvious issues).
- Even if it will work, it will break gr-bokegui (which will need its own updates). Personally, I think that's fine. Us dragging around bokeh support was not good design anyway, but is there an accompanying gr-bokehgui update?

As for the failures, the first thing I got was a circular import error, which I may or may not have a fix for. Right now I'm looking at an exception around a missing method `insert_grc_parameters()`.

**Comment by mbr0wn** [comment]
Also, it's tough to review this with all the changes mangled into one big commit. I tried splitting up the changes by random fixes and the actual change.

**Comment by mbr0wn** [comment]
>     * Even if it will work, it will break gr-bokegui (which will need its own updates). Personally, I think that's fine. Us dragging around bokeh support was not good design anyway, but is there an accompanying gr-bokehgui update?

OK that was also wrong, but was also masked by trying to get this branch to run. I see there is a workflow for gr-bokeh_gui in-tree even after this patch.

**Comment by mbr0wn** [comment]
Something else: I think the Executor class should also be pluggable, so we don't have to hard-code the "run cmake for C++" and so on.

**Comment by ZakyHermawan** [comment]
@mbr0wn Thanks for trying out this PR and providing feedback. I stopped working on this pull request because the code was moved to this [repository](https://github.com/ZakyHermawan/grc/tree/gsoc). Nonetheless, I will resume work on this PR as soon as I have free time

**Comment by mbr0wn** [comment]
@ZakyHermawan I have reached out to @haakov and @skoslowski and I'll pick up the slack on this PR. I'll move this a new PR with less tangled changesets (i.e., better commit splits) and I already have made significant changes on my local branch.

Adding to the list of issues: I think this breaks the grcc compiler, too.

**Pull request closed without merging**
