### PR TITLE
Reference added for turbo product code

### PR DESCRIPTION
**Pull request by fkvd**
## Description
Reference for turbo product code is added to make code more clear.

## Related Issue
This PR doesn't related to any issue.

## Which blocks/areas does this affect?
Since the only contribution is comment, no block is affected.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Was the code written based on this presentation, or is that a presentation on the same subject?

**Comment by fkvd** [comment]
> Was the code written based on this presentation, or is that a presentation on the same subject?

Hello, I believe the code is written based on the presentation. Because, I couldn't find any other reference which name the related variables as in the code. Also it took me a long time to find this reference. So, I thought it could be helpful to add reference directly to the code. Also this link can be accessed via web archive.

**Comment by willcode** [comment]
The wiki would be a good place. You could edit
https://wiki.gnuradio.org/index.php?title=TPC_Encoder_Definition
and
https://wiki.gnuradio.org/index.php?title=TPC_Decoder_Definition
adding a link to the presentation at the end of the intro (before Parameters) on each page.

I don't think we want to put a reference in code unless the code author (apparently @osh) says that the code is based on that reference.

**Comment by fkvd** [comment]
Okay, thank you for your interest and guidance. I will edit wiki as soon as I have free time.

**Pull request closed without merging**
