### PR TITLE
QA test for complex sinusoid

### PR DESCRIPTION
**Pull request by gregjesl**
There were no unit tests for sig_source_c for the sinusoidal case.  This pull request adds a unit test for a complex sinusoid. 

The original motivation was that I had incorrectly assumed that setting the waveform of a complex signal to GR_COS_WAVE and GR_SIN_WAVE would yield different results.  I had assumed that setting the waveform to GR_SIN_WAVE would have created a complex signal that was 3pi/2 radians phase shifted.  I reviewed the unit tests because I thought that there was something wrong; I think there should be at least a runtime note that GR_COS_WAVE and GR_SIN_WAVE produce the same behaviour in the complex case.  

My goal was to have two complex signals that were out of phase.  I may open up an issue (and potentially send a pull request) regarding setting the phase of a signal source.

### CODE REVIEW

**Comment by marcusmueller** [comment]
@gregjesl this is AWESOME! Thanks!

**Comment by bhilburn** [comment]
Hey @gregjesl - this is indeed awesome! We'll need a CLA to get this merged. If you shoot me an e-mail, `bhilburn@gnuradio.org`, we'll get things rolling `=)`

**Comment by gregjesl** [comment]
@bhilburn CLA request has been sent.

**Comment by marcusmueller** [comment]
@bhilburn @gregjesl any news on the CLA?

**Comment by marcusmueller** [comment]
The fsf finally handed over the cla confirmation.

**Pull request merged**
