### PR TITLE
grc: fails to evaluate a block parameter that references another parameter of the block

### LINKED ISSUE #5627: gr-qtgui /gr-fec gnuradio/gr-fec/examples/ber_curve_gen.grc fails to build
### What happened?

Trying to build the gnuradio/gr-fec/examples/ber_curve_gen.grc fails as the qtgui_ber_sink fails to evaluate.

The error message is:

Param - Bus_Structure_Sink(bus_structure_sink):
	Value "list(map(lambda b:list(map(lambda a:b * len(esno) * 2 + a, range(len(esno)*2))), range(num_curves)))" cannot be evaluated:
	name 'num_curves' is not defined

but num_curves is set to 1 in the example.

### System Information

OS: Fedora 35 , build from scratch

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

Just open [ber_curve_gen flowgraph ](https://github.com/gnuradio/gnuradio/blob/main/gr-fec/examples/ber_curve_gen.grc) in grc

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dl1ksv**
# Pull Request Details

## Description

If you have a block with

param1: 3
param2: 3 * param1

the evaluation of param2 fails, as only variables of the flowgraph are used during evaluation.
This pr stores previous evaluated paramters of the block and uses them during evaluation,
so param2 will be correctly evaluated.

## Related Issue

Fixes #5627

## Testing Done

Run
[ber_curve_gen](https://github.com/gnuradio/gnuradio/blob/main/gr-fec/examples/ber_curve_gen.grc)
in grc.
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by haakov** [comment]
This topic has been briefly discussed in an earlier issue: https://github.com/gnuradio/gnuradio/issues/5198

What happens if you have a "global" (flowgraph-wide) variable with the same name as a block parameter?

**Review by skoslowski — CHANGES_REQUESTED** [review]
This is not bug! In my opinion, the parameters of a block should not depend on each other. Parameters are not variables. I recommend not to merge this.

Sorry, @dl1ksv for shooting down your idea (again). Here's my reasoning:
- The mental model here is that a block is like a (python) class (because is usually is) and the parameters end up as (kw)args of the init-function. Parameters do not reference each other. If they depend on each other, this is expressed by a variable (to be fair, or explicitly with an inline assigment). 
- How would a user know what the internal names of these Variables are? 
- What about shadowing, eval order, recursive evals?

Maybe I am missing some really compelling use-cases here.

**Comment by dl1ksv** [comment]
@skoslowski I'm a bit surprised, that this should not be a bug, as in an earlier version of gnuradio ( 3.7,3.8, may be even 3.9) this flowgraph could be build, but maybe I'm wrong, as the screenshot does not show the running flowgraph.

See [ber_curve_usage_example](https://wiki.gnuradio.org/index.php?title=File:Ber_curve_gen_fg.png)

You are right, parameter should not depend on each other. I think I used a wrong example.

 The problematic code part is
https://github.com/gnuradio/gnuradio/blob/f44384ae1f061f257603b02288aef4db1b74d4be/gr-qtgui/grc/qtgui_ber_sink_b.block.yml#L314-L318

As bus_structure_sink is hiden, the user can't change the assignment.
In this case:  is bus_structure_sink a parameter or a ( block ) local variable ?

You can make the flowgraph work by adding two variables num_curves and esno. But how would you handle a flowgraph with two  ber_curve sinks with different parameter settings? Modifying the ber_curve sink , to be able to modify the bus_structure_sink parameter?

May be it's a useless discussion, as only ber_curve_sink is malformed

**Comment by skoslowski** [comment]
If GRC really did allow resolving other parameters at some point, I would consider that a bug. Anyway, glad that is not the case anymore.

The bus ports code has always been problematic to say the least. I can see why it would benefit from accessing other parameters. I someone really wanted to refactor (rewrite) the bus ports implementation I would still suggest not to generally allow parameters to depend on each other. I'd make a special (bus ports specific, internal) dtype that behaves as desired (probably by delaying the eval until the ports are (re-)formed)

**Comment by mormj** [comment]
Closing based on discussion so as to not affect general GRC behavior in order to patch bus ports

**Pull request closed without merging**
