### PR TITLE
Merge cumulative MSVC/mingw patches for compatibility

### PR DESCRIPTION
**Pull request by jmcorgan**
This is a new branch I've started for collecting together an ongoing set of patches for MSVC and mingw compatibility.  I've started off by cherry-picking from @gnieboer and @pcercuei branches they have published.

I'm doing this so we have one place we can review these changes, one branch that others can test, and one branch to merge in when we deem them ready.

Right now, the emphasis is on bug fixes that have minimal impact on non-Windows code.  That is, code that corrects incompatibilities with the Windows platform, but that presents minimal risk to our main Unix-like user base.

My plan is to maintain this as a branch off maint and only accept bug-fixes and compiler compatibility fixes at this time.  Later, once we are confident our code base is properly multi-platform compatible, we can shift towards changes that help implement things like Windows packaging and new Windows-specific features.

I encourage others to post their fixes as individual branches off this branch, on their own repo, making sure that the commits are independent of each other and can be individually cherry-picked as needed to the tip of this one.

### CODE REVIEW

**Comment by jmcorgan** [comment]
@gnieboer I believe this covers your patches 2, 3, and 4. 

For 1, I'm not sure using (!MSVC) is the proper conditional, and for 5, I'm not sure I understand the changed logic.

**Comment by gnieboer** [comment]
Does CMake not support "!" ?  I can change it to (NOT MSVC).  I didn't get any errors though.

On patch 5...  not() is not supported in MSVC (it's a GCC extension), so the obvious change would simply be instead of `not(s<1.0)` have `s>=1.0`

However, when I looked up exactly what this routine was, I found the `s != 0` in there too. See https://en.wikipedia.org/wiki/Marsaglia_polar_method, and I found a couple other examples too.  Turns out if s==0 happens and it's not caught, then you'll get a div/zero at line 132.  So that's actually a bug fix in addition to the compiler notation change, as the current version will crash if s computes to exactly zero (unlikely but possible).

**Comment by jmcorgan** [comment]
The question about the conditional was whether it should be MSVC or something else--I don't know if that line impacts mingw or not.

**Comment by jmcorgan** [comment]
Regarding the Marsaglia algorithm, could you make it more explicit by making the 1 and 0 into 1.0 and 0.0?

**Comment by pcercuei** [comment]
About patch 1, I think 'NOT MSVC' is correct - mingw uses GCC, which does not understand the /RTC1 flag.

**Comment by gnieboer** [comment]
Yes, the first patch is correct... it fixes two MSVC-related issues, first
is that MSVC uses a different syntax for compiler command line options, so
-msse2 becomes /arch:SSE2.
The second issue is that when compiling for 64-bit, the detection of
compiler support won't work because that flag won't show up as supported
because it's not necessary... all 64-bit x64 CPU's support SSE2, so all
coded is compiled with that support, no flag required or supported.

And I've changed the constants from patch-5 to be specified as floats.

Geof

**Comment by jmcorgan** [comment]
Ok, this has been updated; please continue suggesting commits for inclusion here.

**Comment by pcercuei** [comment]
https://github.com/gnuradio/gnuradio/commit/3c96e1121ae4fc1a796f01652dd975a4c5915aa2 is definitely required.
https://github.com/gnuradio/gnuradio/commit/c71055a8f0e0c5f8b2d38dfa012cd86b0b09df0a will fix tons of 'macro already defined' warnings.
https://github.com/gnuradio/gnuradio/commit/61f1149f3a28cdab14a5fc9121d75d9cec68b87e allows me to build Volk and GNU Radio separately on AppVeyor, and keep the build time below 1h.
https://github.com/gnuradio/gnuradio/commit/1791a0357de05b5d2160953ab1d7a3060d5793e0 allows out-of-tree modules to properly find the headers and libraries of GNU Radio.

**Comment by jmcorgan** [comment]
3c96e11 is a bug fix for GNU Radio not specific to windows--you can make a pull request separately off maint if you want credit, or, I can just do that myself.

**Comment by pcercuei** [comment]
My credit is my signed-off line, you can merge it ;)

**Comment by jmcorgan** [comment]
3c96e11 was cherry-picked onto the current maint branch as a bug fix; c71055a was added to the end of the maint-windows branch and the entire branch was rebased off current maint.

**Comment by jmcorgan** [comment]
@pcercuei can you elaborate on 61f1149, why it is needed?  Also, for 1791a03, aren't hardcoded paths like that a problem?  Could it ever be different?

**Comment by pcercuei** [comment]
@jmcorgan: Ok, you can ignore https://github.com/gnuradio/gnuradio/commit/61f1149f3a28cdab14a5fc9121d75d9cec68b87e - I found the correct way of doing it on Windows (set Volk_DIR + https://github.com/analogdevicesinc/volk/commit/b602cd6).

About https://github.com/gnuradio/gnuradio/commit/1791a0357de05b5d2160953ab1d7a3060d5793e0: those are just the default search paths. Adding one default search path doesn't mean that GNU Radio has to be there. But if it is, the installation will be automatically found and the user won't have to specify the paths manually. However, I have to admit that this commit has a problem - it assumes that GNU Radio was installed in "c:/Program Files/gnuradio". So ignore that commit as well, and I'll submit a new one.

**Comment by pcercuei** [comment]
About @558b4f0 - the 'thread' Boost module is still listed a few lines before, so it ends up twice on the Boost modules list. Sorry for not seeing it before.

**Comment by pcercuei** [comment]
I added two commits, in a separate pull request (https://github.com/gnuradio/gnuradio/pull/826), to fix the search paths of GnuradioConfig.cmake without hardcoding paths in the source files. This is required for GNU-Radio out-of-tree modules to properly detect the GNU Radio installation, especially on Windows.

**Comment by gnieboer** [comment]
Added patches 6,7,8,9, and 10 in my repo.  
Patch 10 adds VLA declaration macros to attributes.h (__GR_VLA & __GR_VLA2).  
Let me know if you want them named something else or put somewhere else.  attributes.h obviously is mostly __attribute definitions, but a couple other non-attribute definitions were in there and it seemed the best place I could find.

**Comment by gnieboer** [comment]
Also submitting patch 11, which eliminates setting SO_LINGER for udp_source as SO_LINGER is not relevant to a UDP socket.  Linux ignores the setting, but windows throws an exception.

**Comment by jmcorgan** [comment]
@gnieboer In your patch-8, I get the below when compiling with gcc:

In file included from /usr/include/math.h:69:0,
                 from /opt/gnuradio/src/gr-vocoder/lib/codec2/fdmdv.c:42:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:309:15: error: two or more data types in declaration specifiers
 __MATHCALLX (round,, (_Mdouble_ __x), (__const__));
               ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:309:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before '<' token
 __MATHCALLX (round,, (_Mdouble_ __x), (__const__));
                          ^
make[2]: *** [gr-vocoder/lib/CMakeFiles/gnuradio-vocoder.dir/codec2/fdmdv.c.o] Error 1
make[1]: *** [gr-vocoder/lib/CMakeFiles/gnuradio-vocoder.dir/all] Error 2

**Comment by jmcorgan** [comment]
@gnieboer Ok, I've added your patches 6, 7, 9, 10, and 11 and rebased.

**Comment by gnieboer** [comment]
Ah, I see the problem with patch-8, I need to test not only that it's <1800, I also need to test that it exists at all as an undefined _MSC_VER will pass the < 1800 test.  I'll fix.

**Comment by gnieboer** [comment]
patch-8 updated to add "defined(_MSC_VER)" test.

**Comment by jmcorgan** [comment]
Btw, could you make your commit messages conform to our convention of having a module prefix and then description, less than 72 char total?  We use this to sort on component; just look through the commit history to see how it looks.

**Comment by gnieboer** [comment]
OK, can do.

**Comment by jmcorgan** [comment]
This branch has been consolidated into three commits and merged into the maint branch.

**Pull request closed without merging**
