### PR TITLE
expanded quadrature_demod_cf docs; added .grc <doc>

### PR DESCRIPTION
**Pull request by marcusmueller**
Having explained the workings of quadrature demod one too many times, here's some documentation.

### CODE REVIEW

**Comment by trondeau** [comment]
This is great. We shouldn't have to duplicate comments in the .h and .grc files, though. It should just go into the .h file and get compiled into the GRC block. If that's not working, we should try and fix that.

**Comment by marcusmueller** [comment]
Problem: Compiling TeX into the plain text doc field basically can't
work 100% automatedly, hence the manual <doc> tag. Also, I couldn't
figure out why that doesn't work.

**Comment by trondeau** [comment]
Hmm, I see. Then this is ok for now. I'd like to fix this issue, but we can put it aside for now. Could mean integrating a reinterpreter into GRC to handle it... sounds ugly.

Thanks.

**Comment by skoslowski** [comment]
I'd rather have GRC display TeX directly, if that's even possible without adding bulky deps.

**Comment by marcusmueller** [comment]
This sounds like the easiest approach to get that would be including
some kind of HTML view, and really just tell GRC to find the
doxygen-generated content, instead of having a <doc> tag that gets
loaded into a gtk.TextView.

**Comment by skoslowski** [comment]
Right. The job is yours.

**Comment by marcusmueller** [comment]
I can't claim I didn't see that coming.

Am 6. November 2015 17:30:22 MEZ, schrieb Sebastian Koslowski <notifications@github.com>:
>Right. The job is yours. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gnuradio/gnuradio/pull/676#issuecomment-154460589

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jmcorgan** [comment]
Is there a specific reason this is requested for maint?

**Pull request closed without merging**
