### PR TITLE
tools: Add .zenodo.json to support Zenodo DOI citations

### LINKED ISSUE #3155: DOI for releases
Add documentation how and which DOI to use if citing gnuradio in published documents.

### PR DESCRIPTION
**Pull request by jdemel**
Zenodo already generates a new release entry with a [DOI for every GR release](https://zenodo.org/record/6433546). However, the presented info is incomplete and would benefit from some formatting.

This PR adopts the VOLK implementation to support Zenodo.

## Description
The new `.zenodo.json` file provides info about every contributor. This file is used to generate new entries on zenodo.org. `.zenodo.json` must be a top-level file to be picked up by the automated workflow.

Besides, the list of authors needs updates constantly. Before a release run:
```bash
./tools/update_citations.sh
```
This commands extracts all contributors according to git and calls a Python script `run_citations_update.py` to update `.zenodo.json`. Only names that are missing in `.zenodo.json` are added. One can add ORCIDs and affiliations to their name. All in all, this might be an interesting addition for people in academia. At least I intend to use it.

## Related Issue
#3155 

## Which blocks/areas does this affect?
Release tools in `tools/` as discussed in #3155 

## Testing Done
The generated list is a combination of automatic checks and quite a bit of manual work to fix typos, relate github handles to names, etc.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

Fix #3155

### CODE REVIEW

**Comment by 777arc** [comment]
Nice util.  Is there a list of things we do each release that we can add to?

**Comment by jdemel** [comment]
I added @willcode and @mormj for reviews because this PR mostly affects their work.

**Comment by willcode** [comment]
If it was just an authors list that would be fine. But I don't really want to start managing contact infomation and other stuff people will want changed as PRs. Is there a way we can manage this outside the code base?

**Comment by jdemel** [comment]
I tried to automate it as much as possible. However, at some point the generated list for Zenodo needs to be updated with all the authors according to git.
Personally, I'd like my ORCID to show up as well.
The git user list is a mess because mistakes happen and people have typos in their names. Also, Github tends to add the GH nick to commits that are committed through the webinterface.

I tried to fix as many naming issues as possible. Thus, this list should not change much or at all from release to release.

**Comment by willcode** [comment]
@jdemel New repo: https://github.com/gnuradio/gnuradio-metadata. A zenodo dir would be a good place for the tools and user map. There could be one `zenodo.json` for each branch, e.g., `zenodo-maint-3.10.json`, or separate directories per branch, or ... ??? TBD: procedures to perform at release time.

**Comment by willcode** [comment]
@jdemel Content of the PR is checked in at https://github.com/gnuradio/gnuradio-metadata, so this PR can be closed.

**Pull request closed without merging**
