### PR TITLE
Pull request for issue #1952 (adding bandwidth message port to qtgui freq / waterfall sink)

### PR DESCRIPTION
**Pull request by jjhein**
Added support to qtgui frequency and waterfall sink for a bandwidth message port so a user can change the display bandwidth programatically from another block.

### CODE REVIEW

**Comment by marcusmueller** [comment]
This is very nice! Did you have contact with @bhilburn about a CLA yet?

Only thing I wish for is that we have some documentation (in the include/qtgui/*.h) that tells users to use these message ports, or what they do. Simply extend the classes' doxygen comments!

**Comment by jjhein** [comment]
Thanks.  No, I don’t have a CLA yet.  Just let me know what to do for that.  Also, I’ll take a look at the documentation this weekend.

Jason

**Comment by mbr0wn** [comment]
@jjhein If you haven't done so yet, please email bhilburn@gnuradio.org and request a CLA. All you need to do is fill out a form.

**Comment by marcusmueller** [comment]
CLA issue has been resolved. I'm in the process of rebasing (#2244) and am doing a test build.

**Pull request closed without merging**
