### PR TITLE
grc,blocks,fft,filter: assigned categories to all blocks without any;

### PR DESCRIPTION
**Pull request by donludovico**
Hi,

As requested in http://lists.gnu.org/archive/html/discuss-gnuradio/2014-12/msg00133.html, I submit a pull request, which assignes categories tu blocks, which previously had no assigned category.

A final check in GRC shows no remaining (apart from the intended ones) category-orphans.

The change log in detail (pattern: <block> -> <new assigned category> - <reason>):
* Missing Block -> no category, on purpose

gr/grc
* Options -> Misc; grc/options - like import, note,
* Bus Sink -> Misc; bus_sink - like pad sink, virtual sink
* Bus Source -> Misc; bus_source - dto.
* Bus Sink Structure	-> Misc; bus_structure_sink
* Bus Source Structure -> Misc; bus_structure_source
* IChar To Complex	-> Type Converters; gr-blocks::blocks_interleaved_char_to_complex - like all other converters

gr-blocks
blocks_message_debug,blocks_random_pdu,blocks_message_strobe appear three times: [Debug Tools], [Measurement Tools], and [Message Tools] (only first ist shown in GRC)
=> is this on purpose (e.g. if at a later stage of dev the tree wil show [repeated] entries in each category)?

* Message Strobe Randome-Delay	-> Debug Tools; blocks_message_strobe_random - like blocks_message_strobe
* Min -> Math Operators; blocks_min_xx - like blocks_max_xx
* PDU Remove -> Message Tools; blocks_pdu_remove - like blocks_pdu_filter
* PDU Set	-> Message Tools; blocks_pdu_set - dto.
* VCO (Complex) -> Modulators/Waveform Generators; blocks_vco_c - like blocks_vco_f

gr-fft
* Ctrlport Probe PSD -> Control Port; fft_ctrlport_probe_psd - like the other *_ctrlport_* blocks

gr-filter
* Fractional Interpolator	-> Resampler; fractional_interpolator_xx - like fractional_resampler_xx
* filter_low_pass_xlating_filter.xml does not appear at all?

For the sake of completeness, I further checked all other gr-* modules of gnuradio for further orphans.
checked, but not changes required:
gr-analog
gr-atsc => no GRC blocks!
gr-audio (no audio_block_tree.xml, but <category>)
gr-channel
gr-comedi -> no GRC blocks!
gr-digital
gr-dtv
gr-fcd (no fcd_block_tree.xml, but <category>)
gr-fec
gr-noaa (no noaa_block_tree.xml, but <category>)
gr-pager (no pager_block_tree.xml, but <category>)
gr-qtgui
gr-trellis (no trellis_block_tree.xml, but <category>)
gr-uhd
gr-utils (obviously no GRC blocks)
gr-video-sdl -> no GRC blocks!
gr-vocoder
gr-wavelet -> no GRC blocks!
gr-wxgui (no wxgui_block_tree.xml, but <category>)
gr-zeromq (not installed)

/Stephan

### CODE REVIEW

**Comment by donludovico** [comment]
in above's request, angular brackets are not displayed correctly.
The line should read:
The change log in detail (pattern: block name -> file name; new category - reason):

**Comment by skoslowski** [comment]
Thanks. I personally think the Options block should remain category-less. For the sake of completes, however, I am fine with your choice. Before merging, the tabs must be converted to spaces.

**Comment by trondeau** [comment]
I agree that Options should not be included in the block tree. There can be only one options block for a GRC file and it's there by default. I see no reason to make it look like it's another normal block.

**Comment by donludovico** [comment]
Thanks for your comments. I do not mind making Options category-free. White spaces are prettified in the new commit. /Stephan

**Pull request merged**
