### PR TITLE
Backports 3.7

### PR DESCRIPTION
**Pull request by rear1019**
Backports of the following pull-requests to maint-3.7
* #3103 (fix-up for formatting included)
* #2969

### CODE REVIEW

**Comment by marcusmueller** [comment]
The patches you're backporting here contain C++11 (`constexpr`, from a cursory glance) and hence _can't_ be applied to maint-3.7, sadly.

Since that only affects https://github.com/gnuradio/gnuradio/pull/3183/commits/e838708915aa5000f919a3e7659ba6c76407f3b4 , could you please  simply remove the `constexpr` there (L. 35), and use the hardcoded number in the array size in the line below (36)? It's not as beautiful, but with these two instances of the same number so close to each other, the intent is clear.

**Comment by rear1019** [comment]
Should be fixed now. I also fixed a ``-Wsign-compare`` warning.

**Comment by michaelld** [comment]
Do we not have CI beyond formatting going for this branch?

**Comment by marcusmueller** [comment]
@michaelld I thought we had, but it seems we don't. @noc0lour did we turn of CI for maint-3.7?

**Comment by noc0lour** [comment]
Will be built soon, had to clear some errors & resent the webhooks.

**Comment by marcusmueller** [comment]
Tested build on Ubuntu 14.04, seems fine

**Pull request merged**
