### PR TITLE
Fix the gnu-ism in terminite_handler

### PR DESCRIPTION
**Pull request by gvanem**
* `<cxxabi.h>` is for GCC only
* Fix the `dllexport` decoration. Ref. https://github.com/gnuradio/gnuradio/pull/4013 for this. I didn't manage to create 2 changes in one PR in the GitHub's editor.

### CODE REVIEW

**Review by nickoe — APPROVED** [review]

**Review by mbr0wn — APPROVED** [review]

**Comment by mbr0wn** [comment]
@gvanem We'll need your Signed-off-by line though. Please amend the commit message.

**Comment by gvanem** [comment]
> @gvanem We'll need your Signed-off-by line though. Please amend the commit message.

What?

**Comment by nickoe** [comment]
@gvanem Look at the DCO check. https://github.com/gnuradio/gnuradio/pull/4012/checks?check_run_id=1583830681

**Comment by gvanem** [comment]
@nickoe This DCO failed:
```
c:\temp\gr> git push --force-with-lease origin patch-1
error: src refspec patch-1 does not match any.
error: failed to push some refs to 'https://github.com/gvanem/gnuradio.git'
```

**Comment by nickoe** [comment]
@gvanem I don't think you should push to origin. I asume that remote is gnuradio upstream where you probably don't have write permissioms. You should push to your own fork.

**Comment by gvanem** [comment]
@nickoe Seems it worked now via SSH:
```
c:\tmp\gr> git push --force-with-lease origin patch-1
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
Total 0 (delta 0), reused 0 (delta 0)
To github.com:gvanem/gnuradio.git
 + 1a46af7a9...5ed1177ed patch-1 -> patch-1 (forced update)
```

But oh man! Why should it be so hard to contribute to FOSS nowadays?

**Comment by nickoe** [comment]
@gvanem Well, requiring the signed off message in the commit is a billion times easier than the request you needed to make earlier. The signed off thing is standard git workflow and as the origin from the linux kernel workflow.

Anyway, it looks to me like you pushed to wrong branch. The current commits seem to be related to logging and not cxxabi.h and the export.

In case you "lost" some commites. Git "reflog" is your friend.

**Comment by mbr0wn** [comment]
I *think* this was fixed by https://github.com/gnuradio/gnuradio/pull/4056. @gvanem, if that's untrue, sorry, and please reopen this.

**Pull request closed without merging**
