### PR TITLE
modtool: move OOTs equal to components for 3.10

### PR DESCRIPTION
**Pull request by mormj**
Signed-off-by: Josh Morman <jmorman@gnuradio.org>

# Pull Request Details

## Description
It is desired to make OOT modules equivalent to in-tree modules, both from a packaging perspective, and semantically by ensuring that GR OOT modules are associated with gnuradio in naming convention, package import, etc.

This PR updates modtool for 3.10 to do the following
1. `include/gnuradio/howto`
2. `python/gnuradio/howto`
3. Rename the cmake target gnuradio-howto

The usage of OOTs then will slightly change to be
1. from gnuradio import myoot
2. #include <gnuradio/myoot/myblock.h>

When including an OOT in another OOT, right now this should look like:
`find_package(gnuradio-myoot)`
but going forward it would be desirable to have
`find_package(gnuradio COMPONENTS runtime blocks myoot)`
-- just not sure how to do this yet

## Related Issue
Partially addresses #3006 

## Which blocks/areas does this affect?
Modtool - so all OOTs past and present (back to 3.7).  When creating a new module it will be 3.10 modtool compatible (can't use an old prefix to update the blocks), and older OOTs created with 3.9, 3.8, 3.7 should function the same and be updated with this modtool accordingly

## Testing Done
So far, have only created new OOTs

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/master/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/master/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/master/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by 777arc** [comment]
> `find_package(gnuradio COMPONENTS runtime blocks myoot)`
> -- just not sure how to do this yet

Any progress with this one?

**Comment by mormj** [comment]
Nope I have no idea how to do the components part. I think gnuradio-oot will suffice unless someone adept at cmake can figure it out.

**Comment by mormj** [comment]
This should be at a point now where we can have gnuradio installation and oot installation in different prefixes, as long as LD_LIBRARY_PATH and PYTHONPATH include both

Here is the testing that I have done:
1) install gnuradio in /usr/
2) install oot in /usr/local
3) python import from both gnuradio and oot
4) c++ include headers and link to both gnuradio and oot using find_package(gnuradio-myoot)

So I think this should be ready to go at this point pending review

**Comment by 777arc** [comment]
When trying this out I got the error `Unknown CMake command "configure_package_config_file"`, I've got cmake version 3.16.3, does the new scheme require a newer version?

**Comment by mormj** [comment]
Hmm - not sure what the dependency was there.  I have cmake 3.16.3 as well.  Must be something in my cmake module path - but I added the include and it doesn't cause any issues here.  Thanks for catching that.

**Comment by mormj** [comment]
Added some changes found from people on chat who had tried it out.  Going ahead and merging this to expedite the RC.

**Pull request merged**
