### PR TITLE
gr-dtv: Make the gr-dtv component easily cross-compiled.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Comment by jmcorgan** [comment]
In general I like the idea of making things easier, of course, but what was the problem before?

**Comment by balister** [comment]
Eliminating the nee d to create an executable during build is fine, but I am curious what failed with the existing approach? Although the cmake removed doesn't look quite right to me (for cross compiling)

**Comment by drmpeg** [comment]
Doesn't the line "if(NOT CMAKE_CROSSCOMPILING)" in gr-dtv/lib/CMakeLists.txt break the cross-compile build?

**Comment by balister** [comment]
That is the part that looks funny. There should be something to build it to run on the host, but your approach is fine also.

**Pull request merged**
