### PR TITLE
gr-blocks: fix tag propagation policy for stream mux block

### PR DESCRIPTION
**Pull request by noc0lour**
Referring to:  http://lists.gnu.org/archive/html/discuss-gnuradio/2016-04/msg00357.html 
Tags from different input streams propagate with their absolute value. I adjusted tag propagation so tags stay with its original sample. 

Is this a desired behaviour? Should I write a test case? I'm not quite sure if this matches the expectations for tag propagation.

### CODE REVIEW

**Comment by jmcorgan** [comment]
@trondeau ping

**Comment by trondeau** [comment]
I'd definitely like to see some test code for this. Also an example of using this block with multiple stream tags.

I think the concept is correct, but I'd want to verify that the calculations done to adjust the tag placement are correct via QA tests.

**Comment by noc0lour** [comment]
Added a qa_test for tag propagation. Thanks for providing an initial flowgraph @mrlnc.

**Comment by trondeau** [comment]
This looks good. Thanks for doing the QA.

I also created a simple GRC example that I think we should add to gr-blocks/examples:
https://gist.github.com/trondeau/798c0ee5166042683204ccd3fb205885

**Comment by jmcorgan** [comment]
@noc0lour Can you add the above grc example (make sure it installs, too)?  Also, as a bug fix, we put these into the maint branch and merge up.  I'll cherry-pick the commits there this time, but in the future, please submit against the maint branch.

Thanks!

**Comment by noc0lour** [comment]
@jmcorgan Should be fine for now. Sorry for picking the wrong branch. I'll keep it in mind.

**Comment by jmcorgan** [comment]
This was rebased on maint branch and merged.

**Pull request closed without merging**
