### PR TITLE
v3.8.3.1-rc1

### PR DESCRIPTION
**Pull request by willcode**
Signed-off-by: Jeff Long <willcode4@gmail.com>

### CODE REVIEW

**Comment by velichkov** [comment]
Hi Jeff,

> The volk submodule has not been checked out in the github-generated tar and zip files. Use
git submodule update --init

Would it be possible to release a tarball that contains the `volk` sub-module? A few weeks ago I've requested upgrade of gnuradio to 3.8.3-0 in Fedora 33 and one of the problems that prevent/delay the update is that volk is not included in the tarball. 

See https://bugzilla.redhat.com/show_bug.cgi?id=1956356#c3 and https://bugzilla.redhat.com/show_bug.cgi?id=1956356#c6

**Comment by willcode** [comment]
Yes, I'll definitely post v3.8.3.1 with a `-with-volk` variant, as I did (retroactively) for v3.8.3.0. Will that work with your release procedures?

**Comment by velichkov** [comment]
> Will that work with your release procedures? 

I hope so. 

@yarda  Do you have any other requirments?

> This will be out next week.

OK.

> Do you need this for the rc too?

No.

**Comment by yarda** [comment]
> @yarda Do you have any other requirments?
> 
Thanks, at the moment I am not aware of anything else.

**Comment by willcode** [comment]
@velichkov @yarda the volk submodule has been set to v2.0.0 for the last couple of years, so that's what you've been getting in the tar files. It is reported that the latest versions of volk work with gnuradio 3.8, are required for some architectures (armv7). I ran the QA tests with gnuradio 3.8 and volk 2.4.1 with no problems, using
`-DENABLE_VOLK=ON -DENABLE_INTERNAL_VOLK=OFF`
as part of the gnuradio cmake.

I don't know of any reason you need to use an upgraded/external volk. There are probably performance improvements and bugfixes.

**Comment by willcode** [comment]
Johannes Demel advises that the submodule was left at v2.0.0 on purpose, at the time at least.

**Comment by velichkov** [comment]
Hi Jeff,

I agree that it will be good `volk` to be upgraded to its latest stable version as well. `volk` has some problems on `s390x` and `ppc64le` architectures that are still not resolved but the very same problems exists in the version that's currently included in Fedora 33.

**Comment by willcode** [comment]
I'll make a gnuradio-with-volk-2.5.0.tar.gz and gnuradio-with-volk-2.0.0.tar.gz so it's obvious. Then people can take their pick. I don't know how to decide for them. My own quick tests show that volk 2.5.0 should be fine, at least for gnuradio in-tree stuff. If I forget - remind me!

It could be useful for packagers to do the volk checkout themselves in the future, since they have to do this already for newer versions of gnuradio. But I don't mind adding a couple files to the releases if it helps people.

**Comment by willcode** [comment]
Done.

**Pull request merged**
