### PR TITLE
Update dependency versions on next

### PR DESCRIPTION
**Pull request by mbr0wn**
This PR will probably linger a bit until we've figured out the actual versions we want.

### CODE REVIEW

**Comment by jmcorgan** [comment]
Yeah, I'd like to expand the list as well, to clearly identify all the items we're tracking in the spreadsheet.

**Comment by jmcorgan** [comment]
Needs rebase.

**Comment by mbr0wn** [comment]
...rebased.

**Comment by mbr0wn** [comment]
Cross-referenced with the spreadsheet, added some more versions, put them all in a central location in CMakeLists.txt. I'd say this is ready to go.

**Comment by jmcorgan** [comment]
This isn't just a bump in version requirements, it's a quite nice improvement on how these are documented and tested for. It would be useful to have this as a master branch merge (with the version numbers changed as appropriate), then merge up to next with these version numbers here.  It would help keep divergence between the branches down and reduce the chances of merge conflicts in the future.

Also, I anticipate a conflict with merging up to the python3 branch as some of the python-related CMake checks have changed.

**Comment by skoslowski** [comment]
Looking at the changed files, it merge cleanly, but we'll have make use of the vars. 

And add one for min python3

**Comment by mbr0wn** [comment]
This is now based on #1252.

**Comment by mbr0wn** [comment]
@skoslowski @jmcorgan Based on the spreadsheet, it seems Python 3.4 would be a suitable minimum?

**Comment by jmcorgan** [comment]
Yes, 3.4.

**Pull request merged**
