### PR TITLE
Making gr_modtool start faster by avoiding to iterate over all globals

### PR DESCRIPTION
**Pull request by marcusmueller**
All subclasses of object have a __subclasses__ method, which gives the
subclasses. That's a lot fewer objects than what's in globals().

### CODE REVIEW

**Comment by noc0lour** [comment]
lol'd at the branch name

**Comment by marcusmueller** [comment]
for reference: [Python 2.7 docs](https://docs.python.org/2.7/library/stdtypes.html?highlight=__subclasses__#class.__subclasses__)

**Comment by skoslowski** [comment]
...better yet, use explicit registration via a decorator =)

**Comment by marcusmueller** [comment]
@skoslowski without having thought about that, I guess that `object` having a `subclasshook` that... registers subclasses is kind of the same. I'm daily reminded that "explicit is better than implicit" is a Pythonic mantra (someone put up a poster),  but I feel that inheritance is explicit in itself!

**Pull request merged**
