### PR TITLE
wavelet: check for correct malloc pointer

### PR DESCRIPTION
**Pull request by ValZapod**
Copy-paste mistake

### CODE REVIEW

**Comment by michaelld** [comment]
simple tweak & a no brainer! 2 approvals, CI passes. Merging!

**Comment by michaelld** [comment]
Do we need this on maint-3.7 and maint-3.8 too? guessing so ... can you make PRs for those if/as necessary, please?

**Comment by ValZapod** [comment]
It is still not automated? Sigh. There is also this (another 2 out of 17563 warnings, ha), can you fix it yourself, maybe with throw?
https://github.com/gnuradio/gnuradio/blob/4f53ac5a76e3ab05960a81905a570cd74d2708d7/gr-wavelet/lib/squash_ff_impl.cc#L51-L53

**Comment by michaelld** [comment]
Not automated yet; nope! Wishing it were that easy.

**Comment by michaelld** [comment]
The first 3 should just use `std::vector` ... so much easier. The last 2 IDK; have to check out the GSL API as to what it does and doesn't do for alloc.

**Comment by ValZapod** [comment]
@michaelld 
> The last 2 IDK
It is done properly in that file I patched here.

**Comment by michaelld** [comment]
17563 warnings? how crap ... there isn't enough time to deal with those! GR ain't perfect in many ways ... hopefully you can sort through & target PRs and/or issues for the critical ones? Thanks for your work on GR!

**Comment by ValZapod** [comment]
Yep, and most of them are valid, not like with those cppcheck, lgtm, coverity, gcc/clang and what not...

**Comment by michaelld** [comment]
> @michaelld
> 
> > The last 2 IDK
> > It is done properly in that file I patched here.

I don't understand. Please clarify!

**Comment by ValZapod** [comment]
https://github.com/ValZapod/gnuradio/blob/86e1aa4fa82e29f8e2fd0ac44fd9e74765490ce0/gr-wavelet/lib/wavelet_ff_impl.cc#L52-L57 Here.
Please look and doxygen issue.

**Comment by michaelld** [comment]
Gotcha. That looks solid to me; nice work!

**Comment by michaelld** [comment]
Sorry if I've asked you this already: Do you have a CLA with GR?

**Comment by michaelld** [comment]
For this PR, it's such a small change we don't require a CLA ... but, we will given how much work you're submitting ... which is awesome BTW!

**Comment by ValZapod** [comment]
I will sign it when you say I had to sign it)) There is second pull comming))

**Comment by michaelld** [comment]
I'll send an email to get the process moving, using the email on this GitHub account.

**Comment by ValZapod** [comment]
Okay, but it is not a legal problem?

**Comment by michaelld** [comment]
Not up to me to decide.

**Pull request merged**
