### PR TITLE
QTGui: make sure the number of connections is passed as ints

### LINKED ISSUE #1941: grc next ! qtgui time sink fails for inputs >= 3
Trying to generate a qtgui time sink with 3 inputs fails with

Param - Line 3 Label(label3):
	Failed to eval '('part' if ((int(nconnections) >= 3 or (type == "complex" and int(nconnections) >= 2)) and not type.t == "message") else 'all')': 'str' object has no attribute 't'

Param - Line 3 Width(width3):
	Failed to eval '('part' if ((int(nconnections) >= 3 or (type == "complex" and int(nconnections) >= 2)) and not type.t == "message") else 'all')': 'str' object has no attribute 't'

Param - Line 3 Color(color3):
	Failed to eval '('part' if ((int(nconnections) >= 3 or (type == "complex" and int(nconnections) >= 2)) and not type.t == "message") else 'all')': 'str' object has no attribute 't'

Param - Line 3 Style(style3):
	Failed to eval '('part' if ((int(nconnections) >= 3 or (type == "complex" and int(nconnections) >= 2)) and not type.t == "message") else 'all')': 'str' object has no attribute 't'

Param - Line 3 Marker(marker3):
	Failed to eval '('part' if ((int(nconnections) >= 3 or (type == "complex" and int(nconnections) >= 2)) and not type.t == "message") else 'all')': 'str' object has no attribute 't'

Param - Line 3 Alpha(alpha3):
	Failed to eval '('part' if ((int(nconnections) >= 3 or (type == "complex" and int(nconnections) >= 2)) and not type.t == "message") else 'all')': 'str' object has no attribute 't'

This may depend on the use of 'subtypes'. 
Solution ?? Also see the discussion in
[https://github.com/gnuradio/gnuradio/pull/1925#pullrequestreview-141317403](url)

### PR DESCRIPTION
**Pull request by marcusmueller**
fixes #1941.

### CODE REVIEW

**Comment by marcusmueller** [comment]
I'll need a review from either @haakov or @dl1ksv, please :)

**Comment by haakov** [comment]
Looks good! This might be a problem with other blocks as well though, but I can't verify that at the moment. I can check tomorrow.

**Comment by marcusmueller** [comment]
@haakov thanks for the review! Yes, if you could check, that'd be really awesome!

**Comment by dl1ksv** [comment]
I‘m just on the Road. I‘ll try tomorrow

**Comment by haakov** [comment]
Okay I checked, it doesn't look like this problem exists in any of the other blocks.

**Comment by dl1ksv** [comment]
@haakov Did you already find a solution for the handling of option_attributes ?

These attributes provoke some inconsistencies in different blocks. See [#1991](https://github.com/gnuradio/gnuradio/issues/1991)

**Comment by haakov** [comment]
@dl1ksv I haven't fixed it yet, still working on it.

**Pull request merged**
