### PR TITLE
Splitting Transcendental block into separate ones.

### PR DESCRIPTION
**Pull request by aiicore**
- Removed blocks under Math Operations:
   - blocks_transcendental

- New blocks under Math Operations:
   - blocks_math_functions_cos
   - blocks_math_functions_cosh
   - blocks_math_functions_exp
   - blocks_math_functions_log
   - blocks_math_functions_sin
   - blocks_math_functions_sin
   - blocks_math_functions_sqrt
   - blocks_math_functions_tan
   - blocks_math_functions_tanh
   - blocks_math_functions_acos
   - blocks_math_functions_acosh
   - blocks_math_functions_asin
   - blocks_math_functions_asinh
   - blocks_math_functions_atan
   - blocks_math_functions_atanh
- Blocks are configured for std::complex<float> and float operations.

Signed-off-by: Igor Podoski <igor.podoski@gmail.com>

### CODE REVIEW

**Comment by aiicore** [comment]
Resolves #2852

Introducing VOLK functions as a parameter to templates was not possible (correct me if I'm wrong) due to the fact that they are not recognized as types at compilation time.

Added all related functions from cmath/complex, that use only one argument.

Few questions:
1. Should I also introduce double and std::complex<double> here? Those types were defined, but were not used.
2. Should I introduce `std::complex<T> (*func)(T)` and `T (*func)(std::complex<T>)` if possible?

Still tests need to be written.

Please let me know if I'm going in the right direction.

**Comment by mrjacobagilbert** [comment]
Seems like a great idea but gr-blocks doesn't need more...blocks. Maybe a good time to create gr-math per #1230 and [GREP #26](https://github.com/gnuradio/greps/pull/26)?

**Comment by aiicore** [comment]
@mrjacobagilbert Yeah, I wasn't happy with putting everything into gr-blocks, but this is the easiest part to change. I'm more curious if those changes are 'valid' in matter of general approach to the topic. I'm just starting with gnuradio dev.

I will spend some time for writing tests, then will adjust blocs positions according to suggestions in this PR.

Thanks for the hints!

**Comment by devnulling** [comment]
@aiicore Please reach out to bhilburn at gnuradio dot org for a CLA.

**Comment by aiicore** [comment]
@devnulling already in progress

**Comment by aiicore** [comment]
Can't get CLA.

**Pull request closed without merging**
