### PR TITLE
fcd: Update hidapi to latest HEAD.

### PR DESCRIPTION
**Pull request by csete**
This contains necessary fixes for Mac OS X.

### CODE REVIEW

**Comment by csete** [comment]
I should note that I have not tested it using the maint branch, but I have tested on Linux and Mac OS X using 3.7.10 and 3.7.10.1.

**Comment by jmcorgan** [comment]
Does the OOT gr-fcdproplus also support the hardware the our in-tree gr-fcd does?

**Comment by csete** [comment]
Sadly, no. gr-fcd supports only the original Funcube Dongle Pro (96k kHz, 50 - 2200 MHz) whereas gr-fcdproplus only works with the Funcube Dongle Pro+ (192 kHz, DC - 2 GHz).

**Comment by jmcorgan** [comment]
The reason I ask, is, gr-fcd has been removed from 3.8/next branch.  I'm happy to update it here for 3.7, but it looks like an OOT module for the original hardware will be needed.

**Comment by csete** [comment]
I think it would be a good idea to update it for 3.7 and we will make an OOT for 3.8 or make it available in another way through gr-osmosdr.

**Comment by jmcorgan** [comment]
Excellent, will do.

**Pull request merged**
