### PR TITLE
Add functions to USRP Sink block

### PR DESCRIPTION
**Pull request by dkozel**
This adds the LO functions from the Source block to the Sink block.

### CODE REVIEW

**Comment by marcusmueller** [comment]
Doesn't compile!

<pre>
/data/src/pull/1813/master/gr-uhd/lib/usrp_sink_impl.cc: In member function 'virtual std::vector<std::__cxx11::basic_string<char> > gr::uhd::usrp_sink_impl::get_lo_names(size_t)':
/data/src/pull/1813/master/gr-uhd/lib/usrp_sink_impl.cc:294:22: error: 'class uhd::usrp::multi_usrp' has no member named 'get_tx_lo_names'; did you mean 'get_rx_lo_names'?
         return _dev->get_tx_lo_names(chan);
</pre>

**Comment by mbr0wn** [comment]
Uh-oh: I see what happened. In https://github.com/EttusResearch/uhd/commit/77adcffe0689f120fee71854ec0f627a32991f79#diff-7cacf248dd2f15443c5c956403b2cc40, we added the symmetrical TX calls (before, there were only RX calls) but didn't also add a `#define` to advertise their existence. In this PR, we're using `UHD_USRP_MULTI_USRP_LO_CONFIG_API` to detect both -- but there's a wide range of commits that don't support both.

@dkozel, can you please update this PR to use `UHD_USRP_MULTI_USRP_TX_LO_CONFIG_API` for detecting the TX capabilities. I will update UHD to include said macro.

**Comment by dkozel** [comment]
@marcusmueller This has been updated with the improved ifdef guards. No other changes have been made.

**Comment by marcusmueller** [comment]
Test running through, code well-reviewed.. merging.

Thanks, everybody!

**Comment by marcusmueller** [comment]
(memo to myself)
Since this is on master, and next replaces the XML grc files with YAML conversions of the XML files at a point prior to this change: this will lead to a merge conflict.

**Pull request merged**
