### PR TITLE
Chooser default value change in example flowgraphs

### LINKED ISSUE #3027: Multiply Matrix example flowgraph throws exception
Looks to be QT related, not necessarily related to the matrix multiply example itself.

```
Executing: /usr/bin/python3.6 -u /share/gnuradio/grdev/src/gnuradio/gr-blocks/examples/matrix_multiply_demo.py

Traceback (most recent call last):
  File "/share/gnuradio/grdev/src/gnuradio/gr-blocks/examples/matrix_multiply_demo.py", line 264, in <module>
    main()
  File "/share/gnuradio/grdev/src/gnuradio/gr-blocks/examples/matrix_multiply_demo.py", line 242, in main
    tb = top_block_cls()
  File "/share/gnuradio/grdev/src/gnuradio/gr-blocks/examples/matrix_multiply_demo.py", line 94, in __init__
    self._new_A_callback(self.new_A)
  File "/share/gnuradio/grdev/src/gnuradio/gr-blocks/examples/matrix_multiply_demo.py", line 93, in <lambda>
    self._new_A_callback = lambda i: Qt.QMetaObject.invokeMethod(self._new_A_combo_box, "setCurrentIndex", Qt.Q_ARG("int", self._new_A_options.index(i)))
ValueError: tuple.index(x): x not in tuple
```

### PR DESCRIPTION
**Pull request by mormj**
After the way the default value was configured for QT GUI Chooser, this did not propagate correctly in flowgraphs that use it.  

The new "default" value was set to whatever open 0 was set to, then option 0 was set to "0"

This fixes the example flowgraphs only, not the underlying problem that made the new behavior not update automatically

Fixes #3027

### CODE REVIEW

**Comment by michaelld** [comment]
@mormj To get these changes, did you basically have the latest GRC "compile" them & then push those changes here? Thinking these weren't done by hand ... mostly just curious. I'm OK with them either way.

**Comment by mormj** [comment]
The process that got me here was - 
- opened up the Matrix Multiply example and it hit an exception 
- figured out it was the change in default value #2778 that caused the change in behavior
- tested all the flowgraphs that use the chooser, and found 3 from that set that were adversely affected by the change in default value

I don't think more grc example flowgraphs need to be updated - unless we want to do a flush so they all have stored the current state variables that are stored in the grc rather than take the default values when they are first opened.  This would require a lot of manual testing (which we should probably do ahead of any release date)

**Comment by michaelld** [comment]
@mormj does this PR need a backport to maint-3.8 (if not done already)?

**Comment by mormj** [comment]
Yes - added into #3391

**Pull request merged**
