### PR TITLE
network: Fix various bugs

### PR DESCRIPTION
**Pull request by argilo**
## Description
This fixes the following bugs:

* `udp_sink_impl::stop` leaks `d_udpsocket` (80 bytes on my system)
* `udp_sink_impl::stop` reads uninitialized `d_udpsocket` (and often crashes) if the block was not previously started
* `udp_source_impl::stop` leaks `d_udpsocket` (80 bytes on my system)
* `udp_source_impl::stop` reads uninitialized `d_udpsocket` (and often crashes) if the block was not previously started
* `tcp_sink_impl::connect` reads uninitialized `d_is_ipv6` if the block is in server mode
* `tcp_sink_impl::stop` crashes in server mode because it fails to join `d_listener_thread`

## Which blocks/areas does this affect?
* UDP Sink
* UDP Source
* TCP Sink

## Testing Done
To test the blocks, I used valgrind (`valgrind --leak-check=full --show-leak-kinds=definite python3`), and ran the following Python code:
```python
from gnuradio import network

u_sink = network.udp_sink(1, 1, "localhost", 1234, 0, 1448, True)
del u_sink

u_sink = network.udp_sink(1, 1, "localhost", 1234, 0, 1448, True)
u_sink.start()
u_sink.stop()
del u_sink

u_source = network.udp_source(1, 1, 1234, 0, 1448, True, True, False)
del u_source

u_source = network.udp_source(1, 1, 1234, 0, 1448, True, True, False)
u_source.start()
u_source.stop()
del u_source

t_sink = network.tcp_sink(1, 1, "localhost", 1234, 2)
t_sink.start()
t_sink.stop()
del t_sink
```

## Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] ~~I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.~~
- [x] ~~I have added tests to cover my changes~~, and all previous tests pass.

### CODE REVIEW

**Review by willcode — APPROVED** [review]
Very minor: nullptr instead of NULL?

**Comment by argilo** [comment]
I went with NULL because it's used across gr-network, but I guess it would make sense to switch over to nullptr.

**Comment by argilo** [comment]
Done.

**Comment by willcode** [comment]
I could only see the diffs on my phone. Not a big priority to change existing NULLs.

**Pull request merged**
