### PR TITLE
Switch from boost pointers to std C++11 pointers

### PR DESCRIPTION
**Pull request by ThomasHabets**
This is a recreate of https://github.com/gnuradio/gnuradio/pull/2974 now that [greps-18](https://github.com/gnuradio/greps/blob/master/grep-0018-modernize-c%2B%2B.md) is committed.

Commit message duplicated here:

--

Most of this code is automated code changes:

```
#!/usr/bin/env bash
set -e
SUB="s/dummy/dummy/"
for i in shared_ptr make_shared dynamic_pointer_cast weak_ptr enable_shared_from_this get_deleter; do
  SUB="$SUB;s/boost::$i/std::$i/g"
done
SUB="$SUB;s^#include <boost/shared_ptr.hpp>^#include <memory>^g"
SUB="$SUB;s^namespace boost^namespace std^g"

find . \( -name "*.cc" -o -name "*.h" -o -name "*.i" -o -name "*.cxx" -o -name "*.py" \) -print0 | xargs -0 sed -i "$SUB"
```

Only one manual change. In `./gr-fec/lib/fec_mtrx_impl.cc`, add
`#include <algorithm>`.

### CODE REVIEW

**Comment by ThomasHabets** [comment]
Oops, tests found missing `#include <cassert>` in one place. Fixed now. PTAL.

**Comment by ThomasHabets** [comment]
Hey @marcusmueller, this is actually taking a bit of effort rebasing and fixing, as other code comes in and adds boost pointers.

And now it seems that HEAD is broken, so now that I push my new rebased commit it'll probably fail for unrelated reasons.

Could you see if you could merge this?

**Comment by ThomasHabets** [comment]
Ok, the tests are passing, so I guess the failures are just local to me. So should be all good and ready to be merged! :-)

**Comment by michaelld** [comment]
We have a GREP for this change now; all CI passes; local testing shows this PR works. I'm going to go ahead and merge before this gets stale!

**Comment by ThomasHabets** [comment]
Thanks!

**Comment by michaelld** [comment]
YW! Thank you for all of your work moving GR into better C++ usage ... here and other PRs & the GREP! We will eventually catch up with you ...

**Pull request merged**
