### PR TITLE
gr-modtool: Don't copy source permissions

### PR DESCRIPTION
**Pull request by doronbehar**
# Pull Request Details

This is needed for systems such as NixOS, where the build tree isn't writable and the files copied should be. 

## Description

See the difference between `shutil.copy` and `shutil.copy2` (the default `copy_function`).

https://docs.python.org/3/library/shutil.html#shutil.copytree

## Related Issue

https://github.com/NixOS/nixpkgs/issues/142428

## Which blocks/areas does this affect?

None probably.

## Testing Done

Tested that `gr_modtool newmod` works with this patch on NixOS.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/master/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/master/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/master/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by doronbehar** [comment]
> I understand the design aspect, but that means NixOS is taking away file system features that work well and that we rely on, for us to then reimplement and maintain something less general within our own code base. Wouldn't the right solution be to tell `nix-daemon` to exclude the gr-newmod directory?

Nix will never do that. What other file system features does GR rely on? Even on a non-NixOS system, what is the reason you'd want to keep the permissions of the source directory? They have no meaning. The default permissions of the user creating the destination directory should be used.

**Comment by marcusmueller** [comment]
> Nix will never do that. What other file system features does GR rely on? 

I don't think a maintainer would want to start worrying about the file permissions set during the installation process being changed afterwards. So, the FS feature would be "persistent permissions".

**Comment by willcode** [comment]
Looked at this closer - no monkey-patching a Python library.

**Comment by doronbehar** [comment]
> So, how do we proceed from here? I'm not the maintainer, but I don't think they'd want to merge something that is nixos-specific and Stackoverflow describes it as "hotfix, not recommended in the general case," which also monkeypatches shutil with unforeseeable side effect bugs in the future, but I do want to help GNU Radio install and run well on NixOS.
> 
> Isn't there a more general solution from the NixOS world, where we can keep the permissions as installed somehow and reconstruct on copying? Like a map for setting `umask` before copying each file, based on what the permissions / attributes used to be before nix-daemon replaced them?

Unfortunately, there is no way we can affect the way Nix makes the files readonly. Worse case we'll maintain this patch on our own, or, we can copy the code of `shutil.copytree` while removing conditionals and other logic not needed.

**Comment by mormj** [comment]
Going to go ahead and close this one as we are pushing closer to 3.10 release and not ready to make this type of change that would have a lot of impact across the board.  I do appreciate you bringing this forward and educating us on the file system feature philosophy.  It should perhaps be revisited again after 3.10 release.  Thanks!

**Comment by jpsimas** [comment]
This same issue also happens when using Guix System.

**Pull request closed without merging**
