### PR TITLE
Virtual connection with multiple upstream connections (messages) and Wildcard pad

### LINKED ISSUE #1166: grc: Virtual sink ignores multiple message connections
I discovered a bug with a virtual sink with multiple message input connections from blocks with the same output port name.  GRC will only connect one message port and ignore the rest.

Here's an example flowgraph:
screenshot from 2017-01-13 11-54-13

The output is:
screenshot from 2017-01-13 11-56-02

The .grc and .py files are attached in the zip.  You can see in the GRC-generated .py file only the first message strobe is connected to the debug print.

[test.zip](https://github.com/gnuradio/gnuradio/files/704847/test.zip)

### PR DESCRIPTION
**Pull request by skoslowski**
This fixes #1166. I went ahead and did a rewrite of the type/vlen resolution code, that was planned for 3.8. Additional/new features like resolving through bypassed ports will be continued on next.

Along the way I found that the "Wildcard" setting for pad block didn't work and fixed that, too.

### CODE REVIEW

**Comment by jmcorgan** [comment]
If I can get a review from @sdh11 quickly this can make it into 3.7.10.2 and 3.7.11. Need to tag release during week of 23rd.

**Comment by sdh11** [comment]
This does fix the initial multiple connection issue, but I found otherbugs when stress testing.  It is such an obscure use case that I'm ok with merging this and fixing it on next.

This should never be a real use case, but connecting a chain of several virtual sources and sinks without stream ids (or other blocks in between) causes the drawing code to crash (doesn't in master). It can also cause the properties window to not close correctly. As soon as the mouse moves the drawing is refreshed, so this really just makes editing the flow-graph more difficult. 

virtual-connections-stress-test

**Comment by skoslowski** [comment]
Thanks for checking this closely. Seems I was a bit to easy on catching exceptions for such cases. 
I put some changes on top, that fixes the GUI glitches you were described.

Also, now, loop errors get reported to the user

**Comment by skoslowski** [comment]
clean-ed up commit history

**Comment by jmcorgan** [comment]
This has a large conflict with next branch when merging up.  You'll need to do the usual dance to get two PRs, one for maint, one for next.

**Pull request merged**
