### PR TITLE
modtool: Instead of installing test_modtool, run it as test when testing

### PR DESCRIPTION
**Pull request by marcusmueller**

### CODE REVIEW

**Comment by swap-nil7** [comment]
@marcusmueller: I think we should comment out the section of `Pylint tests`. They will take unnecessarily 8-10 seconds.

**Comment by mbr0wn** [comment]
@swap-nil7 I think 8-10 seconds of testing for static code errors is worth it.

**Comment by noc0lour** [comment]
Do we need to test for more python modules in CMake?
```
Traceback (most recent call last):
  File "/cache/workdir/Ubuntu_18_04_64_0/build_Ubuntu_18_04_64/src/gr-utils/python/modtool/tests/test_modtool.py", line 32, in <module>
    from pylint.epylint import py_run
ImportError: No module named pylint.epylint
```

**Comment by swap-nil7** [comment]
I think we should make the pylint test conditional since `pylint` module is an added dependency for this test.

**Comment by noc0lour** [comment]
I'll update the CI docker containers to contain pylint then we rerun the tests here.

**Comment by marcusmueller** [comment]
Superseeded by #2431

**Comment by marcusmueller** [comment]
@noc0lour you can still add pylint if you want.

**Pull request closed without merging**
