### PR TITLE
Added interactive language selection, renamed "code type" to "block type" to be more descriptive.

### PR DESCRIPTION
**Pull request by tkuester**

### CODE REVIEW

**Comment by jmcorgan** [comment]
@mbr0wn ping

**Comment by mbr0wn** [comment]
I discussed this with @tkuester (and suggested he submit this PR). It changes behaviour of gr_modtool; if you don't specify -l it will now ask you for the preferred language. For me, this will mean typing -l cpp a lot, but before, it screwed over everyone who used Python blocks a lot.

So, this is fine but it can't go onto maint and I will probably revisit this some day with a config.conf settings.

**Comment by jmcorgan** [comment]
Got it.

**Comment by jmcorgan** [comment]
Merging this, but in the future, please create branches for your feature requests separate from master or maint branches.

**Pull request merged**
