### PR TITLE
Added new menu option under 'Help' for Keyboard-Shortcuts.

### LINKED ISSUE #3148: GRC: `Help` Menu should be extended
Pressing `F1` shows a short usability help, but suggests:
> see the menu for other keyboard shortcuts 

It might be worth to extend this menu to show the shortcuts as well (github- or trello-like behavior when pressing with `?`)

### PR DESCRIPTION
**Pull request by alekhgupta1441**
Fixes #3148 
Screenshot from 2020-02-07 01-18-05
Included keyboard shortcuts in 'Help' menu.

### CODE REVIEW

**Comment by devnulling** [comment]
@alekhgupta1441 thanks for the PR. 

A few things:

1) we will need a CLA from you. 

https://github.com/gnuradio/gnuradio/blob/master/CONTRIBUTING.md
https://wiki.gnuradio.org/index.php/Development#What.27s_this_Copyright_Assignment.3F

In order to get the process rolling, please email "bhilburn AT gnuradio.org" for a form to start the copyright process. 

2) You should only have a single commit for this change, you will need to squash the multiple commits into one.

3) This change adds a little bit too much text to that display, so on smaller screens, like what you have a screen shot of, the "close" menu will not be displayed.

i think it would be better to add a new menu option under "Help" such as "Keyboard Shortcuts" that would open up a different alert/popup window, where this info would be at.

**Comment by devnulling** [comment]
One more request, the commit message should prefix the section of code that it changes for example:

grc: Extend the help menu

**Comment by alekhgupta1441** [comment]
I have mailed for CLA prcoess.
And i will soon update this pr with requested changes.

**Comment by 777arc** [comment]
Sounds like @alekhgupta1441 wants to update it to address the small screen size issue, and we're also waiting on the CLA, but should be good to go after that.

**Comment by alekhgupta1441** [comment]
Sorry, for being quite late.
I have updated the PR with requested changes.
And get CLA processed.

**Comment by alekhgupta1441** [comment]
New menu screenshot.
Screenshot from 2020-03-04 23-33-23
CLA is signed.

**Comment by alekhgupta1441** [comment]
@michaelld,@marcusmueller,@devnulling, @777arc can you please review this?

**Comment by 777arc** [comment]
@alekhgupta1441 I don't see the keyboard shortcuts menu, is it supposed to be listed under Help?  Control-K doesn't do anything for me either.

-Marc

**Comment by alekhgupta1441** [comment]
@777arc Yes, Keys menu option is under 'Help' and CTRL +K opens Keyboard Shortcuts menu.I checked it again by building gnuradio from branch alekh_gr.

**Comment by alekhgupta1441** [comment]
WhatsApp Image 2020-03-09 at 3 56 15 PM
*Keys menu.*

**Comment by 777arc** [comment]
Oops had PYTHONPATH issues.  Yeah looks good!

**Comment by michaelld** [comment]
All looks good here: CLA; multiple approvals; relatively simple And useful addition. Merging.

**Comment by alekhgupta1441** [comment]
@777arc , @michaelld, @nickoe Thanks for Reviewing and Merging PR.

**Comment by nickoe** [comment]
@michaelld @alekhgupta1441 @marcusmueller  Do we want this on maint-3.8 as well, or should we ignore that?

**Comment by nickoe** [comment]
I just tested this as a cherry-pick on maint-3.8 and it seem to work well. But this is only testing with python3.

**Pull request merged**
