### PR TITLE
docs: updated usage manual export from wiki

### PR DESCRIPTION
**Pull request by 777arc**
(these changes were automatically generated using the export script)

### CODE REVIEW

**Comment by mbr0wn** [comment]
Do these files get pulled into something somewhere?

**Comment by 777arc** [comment]
Maybe every 6 months, or when there are big wiki improvements of these pages.  These pages live on the wiki, so this export is meant purely as a way of having an offline copy of the usage manual for people without internet.  Not 100% sure what you mean by the 2nd question.

**Comment by mbr0wn** [comment]
I meant, do these txt files get consumed by Doxygen or something else. I think you've answered that -- it's just an offline copy.

**Comment by 777arc** [comment]
Ah, yeah these exported files are just wikimedia's format which is pretty readable and looks kind of like markup.  If you only look at the lines that changed, it doesn't look very readable, but that's just because most of the changes were in the tags.

**Pull request merged**
