### PR TITLE
gr-blocks: Reformat file_source_impl.cc for readability.

### PR DESCRIPTION
**Pull request by LaughingCabbage**
Repull of #1364 to base off maint. Fix inconsistent whitespace to make this file readable.

### CODE REVIEW

**Comment by LaughingCabbage** [comment]
Build failed.

**Comment by jmcorgan** [comment]
It's better to fix things on your submitted branch and repush (with -f if needed) than to close and reopen a PR.

**Comment by LaughingCabbage** [comment]
Thanks @jmcorgan . Bear with me here. I'm unable to reopen this pull request because it was force pushed. Any idea what's going on here?

**Comment by jmcorgan** [comment]
I can't really say, it looks like you deleted the branch first which would close it out. At this point, just open another.

**Comment by LaughingCabbage** [comment]
Thank you for your time. I'm still familiarizing myself with open source contributions and I appreciate the guidance.

**Pull request closed without merging**
