### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell v2.1.dev0`  
`codespell -q 3 -L ans,fo,hist,inout,ist,ith,nd,sinc,uint -S ./volk`

### CODE REVIEW

**Comment by mormj** [comment]
@luzpaz - thank you for the fixes here.  Please squash and sign your commits.  Looks like the python binding hashes need to be updated.  Fortunately Marcus added a utility to make this easier (since these are not changing any of the function signatures) - check out gr-utils/bindtool/scripts/binding-hash-hotfixer.zsh

**Comment by jacobagilbert** [comment]
As someone responsible for more than one of these... thank you!

**Comment by mbr0wn** [comment]
Closing due to lack of action (we need to de-clutter the PR queue). Please reopen if you can update the PR. Thanks for your contribution!

**Comment by luzpaz** [comment]
The .zsh script didn't work for me so i needed to de-prioritize this task. I can still do it but not till later this week? Anyone care to cherrypick and commit?

**Comment by mormj** [comment]
@luzpaz - if you go back and sign your commits, I can push the python binding updates onto your branch and merge.  But the DCO check has to pass.

**Comment by jacobagilbert** [comment]
It'll take you two seconds: https://wiki.gnuradio.org/index.php/Development#What.27s_this_Developer_Certificate_of_Origin_.28DCO.29.3F

`git rebase --exec 'git commit --amend --no-edit -n -s' -i COMMIT_HASH`

**Comment by luzpaz** [comment]
Thanks @mormj and @jacobagilbert I've signed the commits.

**Pull request closed without merging**
