### PR TITLE
CI: add 32 bit debian builder

### PR DESCRIPTION
**Pull request by marcusmueller**
Add a debian 11 i386 builder

In recognition of #5973, depends on https://github.com/gnuradio/gnuradio-docker/pull/28

Signed-off-by: Marcus Müller <mmueller@gnuradio.org>

# Pull Request Details

## Description

Just a temporary thing; don't actually merge.

## Related Issue

Issue #5973 triggered my interest

## Which blocks/areas does this affect?

all and none; this should be just as successful as debian's own build.

## Testing Done

None, that's the point of this PR.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by mormj** [comment]
Closing as we are not yet ready to add the 32 bit builder until fixes are made

**Comment by argilo** [comment]
As noted in https://github.com/gnuradio/gnuradio/issues/5973#issuecomment-1292382602, all necessary fixes have been merged into `main`, and tests pass on my 32-bit Debian VM. Shall we take another crack at this now?

**Comment by argilo** [comment]
Next steps:

* merge https://github.com/gnuradio/gnuradio-docker/pull/28
* rebase this PR on `main`

**Comment by argilo** [comment]
It looks like this should all work. I built the `ci-debian-i386-11-3.10` container on my laptop, built GNU Radio's `main` branch and ran the test suite without issue.

**Comment by argilo** [comment]
It should be possible to backport this to 3.10 as well, since all the necessary bug fixes are on tap to be backported.

**Comment by mormj** [comment]
Closing as included now in #6329

**Pull request closed without merging**
