### PR TITLE
qtgui: Remove the command line plot tools

### PR DESCRIPTION
**Pull request by mbr0wn**
Note: In gr-utils, we have a version of these tools that don't have Qt4
dependencies (note: they have matplotlib dependencies, though).

None of these tools work with Qt5.

### CODE REVIEW

**Comment by mbr0wn** [comment]
@marcusmueller I'm usually the guy that warns about removing stuff, but these are mostly duplicate.

**Comment by noc0lour** [comment]
You have to remove the files from the appropriate `CMakeLists.txt` as well.

**Comment by marcusmueller** [comment]
So, I discussed that in coredevs a while ago, sorry for the long silence.

So, sorry, I'm not 100% OK with this :(

So, we need to get rid of the matplotlib plot thingies. These are typically unusably slow and a pain to use.

We should be sticking to the applications that are nice and fast and use our own plot widgets. That would make sense, as a) higher usability value, b) illustration of how to use the widgets, c) actually our software. 

And we should be moving these to `gr-qtgui/apps`, as that's the module they'd "logically" belong too (also, that'd ensure their dependencies are met when they are installed).

**Comment by noc0lour** [comment]
I'd rather have the applications (we don't have that many) all in examples/apps in the root folder instead of hiding them in `apps/` folders of our libraries. 
This would enable us to have sensible applications depending on a lot of our "sublibraries".

**Pull request merged**
