### PR TITLE
boost: qualify placeholders with their full namespace.

### PR DESCRIPTION
**Pull request by Ponce**
This is needed with boost >= 1.73.0.

### CODE REVIEW

**Comment by jacobgilbert-snl** [comment]
any reason to do this over lambda functions (e.g.: #3441)?

**Comment by Ponce** [comment]
nope, it's just that ATM [master](https://github.com/gnuradio/gnuradio/tree/master/) won't build at all against boost-1.73.0 so it's either moving to lambda functions (if the work is complete) or qualify the existing placeholders.

**Comment by mbr0wn** [comment]
Man I hate Boost.

**Comment by mbr0wn** [comment]
Well hate is a strong word. But this is getting ugly.

**Comment by mbr0wn** [comment]
I'm going to declare this a change of the trivial variety. @Ponce, for other, bigger changesets we'll need a CLA from you.

**Comment by mormj** [comment]
There is another PR #3441 that will make its way onto master once the pybind11 branch is merged, that replaces all the msg_handlers with lambda functions, which will override this PR

**Comment by jdemel** [comment]
I suggest to close this issue. All `set_msg_handler` calls should be converted to lambdas on master now.

**Comment by mormj** [comment]
Closing as lambdas were added on master branch - 3.8 version of this is on #3566

**Pull request closed without merging**
