### PR TITLE
blocks/wavfile_source: fix case where we'll loop producing zero forever

### LINKED ISSUE #6435: Wav file source with libsndfile does not always terminate when done
### What happened?

When using a bunch of .ogg files when processing with gr_satellites using the --wavfile sometimes it is stalls at the end and never exiting properly. This is reproducible with a Wav File Source connected to a Null Sink. 

One [example ogg](https://archive.org/download/satnogs-observations-006850001-006860000/satnogs-observations-006857001-006858000.zip/satnogs_6857031_2022-12-10T09-43-12.ogg) from a SatNOGS observation [6857031](https://network.satnogs.org/observations/6857031/) is available.

Library version `libsndfile1:amd64     1.1.0-3+b1`.
More info in the issue I first posted at [gr_satellites#428](https://github.com/daniestevez/gr-satellites/issues/428)

### System Information

OS: Linux Debian bookworm amd64
GR Installation Method: official debian repos

### GNU Radio Version

4.0-git (dev-4.0)

### Specific Version

3.10.4.0

### Steps to Reproduce the Problem

Run the flowgraph with the offending ogg, does not exit when finished.

The Wav file source never returns WORK_DONE.

bild

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by marcusmueller**
This required checking for actual return amount in-loop; also, do not assume that length of a file fits in an int; there's files longer than 2³¹.

Be clear about ignored sndfile errors.

Signed-off-by: Marcus Müller <mmueller@gnuradio.org>

## Related Issue

Fixes #6435

## Which blocks/areas does this affect?

wavfile source

## Testing Done

tests continue to pass, and the supplied example ogg that used to fail now finishes

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by drmpeg** [comment]
You have to update the pybind11 bindings for wavfile.h.

Also, since you're in here, maybe address #5971 ?

**Comment by willcode** [comment]
PyBind11 hash needs updating.

Looks good. The name `s_items_size` confused me for a minute, but that's not your code.

**Comment by marcusmueller** [comment]
huh unit test failures I didn't see. wat.

**Review by drmpeg — COMMENTED** [review]
Completely broken. Plays for a second with garbled audio, then silence.

Test flow graph is just the wavfile source connected to the audio sink.

**Pull request closed without merging**
