### PR TITLE
Adding LDPC functionality to gr-fec

### PR DESCRIPTION
**Pull request by tracierenea**
This pull request is to add LDPC functionality to gr-fec. This is the effort that I started back in GSoC 2013. I do not think there is really any overlap with the code that Tim just added to gr-fec (which was based on Manu's work from GSoC 2013) because we store and handle the data in very different ways. I can elaborate more on that if needed.

The main functions of these new classes are: 

1) A reduced complexity encoder, as described by Richardson and Urbanke
2) A simple generator matrix encoder
3) A hard decision bit flip decoder
4) Associated blocks for blocks for GRC
5) Classes for handling parity check matrices using GSL
6) Classes for reading/writing alist-format files
7) A new LDPC-specific BER curve example GRC file, which compares 2 different LDPC methods using provided matrices
8) Pre-processing python scripts to generate LDPC matrices (just optional if anyone wants to create their own, but very time consuming)
9) A small library of matrices ready to be used, including some specifically formatted for the Richardson-Urbanke encoding method

I've tried to implement flexibility such that someone could use these LDPC classes by providing one of the following:

1) a parity check matrix in the standard H=[P' I] form
2) a generator matrix in the standard G=[I P] form
3) a parity check matrix in the format defined by Richardson & Urbanke (where the parity part comes first in the codeword instead of last)

And finally, I'm sorry but I accidentally borked the volk submodule. When I did an upstream fetch and merge, I mistook the empty volk directory for something to clean up (delete), not recognizing what it was. I could not find a way to “pull” the submodule again from upstream, so I just recreated the volk submodule in my fork. The head is different, I think. I hope you can just ignore that.

### CODE REVIEW

**Comment by trondeau** [comment]
Tracie,

This is a great start. Just a few things that I'd like to work on.

1. You've done a good job commenting the code. All I ask is that the public header files use Doxygen tags (/*! docs */ or //!) so that the documentation appears in the manual.

2. I don't think that the alist files should be installed under the Python directory. I think we should install these somewhere more global -- I feel like having a set of known alist files out there in the code is, by itself, a benefit to the community. Let's maybe put them under $prefix/share/gnuradio/fec/ldpc. In CMakeLists.txt file, the install line's destination would then be ${GR_PKG_DATA_DIR}/fec/ldpc.

I wouldn't even install the alist and gen file into the examples directory. We can use "gr.prefix()/share/gnuradio/fec/ldpc" in the example itself to point directly at them since GNU Radio knows its own prefix.

3. We like to merge in what we call 'feature branches,' which basically means that it just has a distinctive name. You've just called this 'master' here, which looks confusing in the logs to merge master into master. Instead, just rename this something like 'fec/ldpc_ru' (or whatever looks good to you).

**Comment by tracierenea** [comment]
Thanks so much for the helpful feedback - that all makes sense. I've got final exams right now, so I'll address these things next week.

**Comment by tracierenea** [comment]
Regarding the third item Tom mentioned: I confirmed with github help support that if you rename a branch (i.e. git branch -m newname), that change is not reflected in the pull request as other new commits would be. I need to close this this pull request, push the new/renamed branch to GitHub, and then create a new pull request from the renamed branch. Please let me know if I've misunderstood something, otherwise I'll be closing this pull request today. I will be applying the other 2 requested changes on the new branch as well.

**Comment by trondeau** [comment]
Tracie, that's fine. Close this out and issue a new pull request with the updated commits. Thanks!

**Pull request closed without merging**
