### PR TITLE
codec2: development (master) branch support

### PR DESCRIPTION
**Pull request by ra1nb0w**
add support for the development branch (master) of codec2 still
maintaining compatibility with versions 0.8.1 and earlier.

codec2 version < 0.8 doesn't provide codec2/version.h header
therefore cmake discovers if it is available. Needed by ubuntu < 19.04
and debian < 10 for example.

NOTE:
from 0.9.1 codec2 works fine without `extern "C"`.
from 0.8.1 to 0.9.1 the build fails (not public release exists).

### CODE REVIEW

**Comment by ra1nb0w** [comment]
CIs should install
```
-- Could NOT find LIBCODEC2 (missing: LIBCODEC2_LIBRARIES LIBCODEC2_INCLUDE_DIRS) 
-- Could NOT find LIBGSM (missing: LIBGSM_LIBRARIES LIBGSM_INCLUDE_DIRS) 
```

**Comment by michaelld** [comment]
So CI have codec2 installed, some don't. CI errrors are in "make test" and have nothing to do with this PR. This PR matches the prior 2 PRs on master, so I'm merging without need for further comment.

**Comment by michaelld** [comment]
Did @bhilburn ever get back to you about a CLA? These changes aren't really enough to warrant it, but I'd rather have it in place than not ...

**Comment by ra1nb0w** [comment]
> Did @bhilburn ever get back to you about a CLA? These changes aren't really enough to warrant it, but I'd rather have it in place than not ...

Yes, I sent today the CLA.
Thank you!

**Comment by michaelld** [comment]
Excellent! :+1:

**Pull request merged**
