### PR TITLE
grc: Remove param field colorings by type and replace with labels

### PR DESCRIPTION
**Pull request by cafeclimber**
## Description
Many folks have complained about the garish color scheme used to denote types of parameters in the block parameters dialog. The meaning is not especially clear, and the colors do not adapt to different color schemes well. Instead, this PR adds the field's datatype as a label at the end of the parameter (see below) and removes coloring.

(apologies for the change count...I will try to remember to turn off Black when working on PRs in the future 😖)

grc_params
grc_params_dark

## Related Issue
#2687 

## Which blocks/areas does this affect?
GRC

## Testing Done
pytest was run in `grc/` and all tests passed

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
I like this idea. I always have to hover over the field to find out what type the color means anyway.

Could you remove the unnecessary changes?

**Comment by cafeclimber** [comment]
K fixed those changes. I do want to revisit an switching to Black if possible. There's so many odd inconsistencies both across and within files. If not that, then adding a pyproject.toml to define autopep8 settings to be consistent across the project.

**Comment by marcusmueller** [comment]
the code is clean (ok, there's still four empty line fixes), and it seems all good to me.

**Comment by willcode** [comment]
Type field should be suppressed for
- `enum` - no point in telling the user that
- `id` - not a type
- `file_save` - not a type
- see if there are any others like this?

Vector types could have the `_` removed. That's the internal type and not relevant for the user.

**Comment by cafeclimber** [comment]
I think I saw `_multiline_python` as well. And this is why I added the ignored types list :D simple fix. 

I could also make a dictionary of type-label if we think that would be better the `int`, `list` etc

**Comment by cafeclimber** [comment]
Ack! I hadn't pushed the commit with the updated label ignore list. Was waiting to see folks thoughts on a dict of labels by the vs just a list of ignored types.

Should I just push the latest code to this branch?

**Comment by willcode** [comment]
Sorry! Just make another PR with the updated list. Thanks.

**Pull request merged**
