### PR TITLE
cmake: cmake should get native thrift binary when cross compiling.

### PR DESCRIPTION
**Pull request by trondeau**
Using the same logic we do for finding the native python binary.

### CODE REVIEW

**Comment by douggeiger** [comment]
Perhaps `/usr/bin/env thrift` would be better (i.e. assume it's in $PATH, but not in any particular absolute location)

**Comment by trondeau** [comment]
Force pushed an update. @balister checked this on OE to confirm it finds the right native binary in the sysroot and confirmed by me to work on Android NDK builds.

**Comment by balister** [comment]
I ran a test and it still finds the sysroot copy of thrift.

**Comment by jmcorgan** [comment]
Need some sort of resolution on this.

**Comment by trondeau** [comment]
I thought we did resolve it, unless I misunderstood what @balister was saying on IRC.

@balister can you please clear up what you mean. Is finding the sysroot copy of thrift the right thing that should happen? Not sure if you mean the native build or the target build in the sysroot.

**Comment by balister** [comment]
Tom, your last patch looked OK on an OE build. Corgan merge it.

**Comment by jmcorgan** [comment]
Got it, thanks.

**Pull request merged**
