### PR TITLE
runtime: remove single-threaded scheduler

### PR DESCRIPTION
**Pull request by jmcorgan**
This branch removes the single-threaded scheduler, which has been unmaintained and broken for a couple of years.

### CODE REVIEW

**Comment by pinkavaj** [comment]
Single thread scheduler is in some situations very useful (eg. on Raspberry -pi cannot be used threaded scheduler without some tweaking because for some block creates crazy amount of threads causing process to die).

**Comment by jmcorgan** [comment]
The solution here would be to identify what is causing the failure in the thread-per-block scheduler and address that

**Comment by pinkavaj** [comment]
Thread-per-block is the problem. We are using some flowgraphs where signal is first channelizet into 72 channels and then selected channels are demodulated and processed (~5 blocks per channel). This forks something like 1200 Threads. The solution was to increase ulimit for number of processes per user and increase value in /proc/sys/kernel/shmmni. But with STS we were able to decode two times more channels.

Until there is scheduler which use sane amount of threads (corelating with number of CPUs for example) STS is in my opinion ireplacable.

STS is also usefull in some cases for debuging.

**Comment by mbr0wn** [comment]
STS doesn't do a whole bunch of things (tags, messages) and fails in a non-obvious way if you try and do that. It would require at least some amount of work to get that to work.

TPB definitely needs some attention, too. I'm not sure why it's spawning 1200 threads, for example. Clearly that's BS. As @jmcorgan says, if we fix that issue, this should leave us with a single scheduler (i.e. less code to maintain) which hopefully works better.

**Pull request merged**
