### PR TITLE
grc: fix debug logging and GTK import order

### PR DESCRIPTION
**Pull request by sdh11**
## Description
Replacement PR for #5220.

This fixes the logger prefix which can change depending on how GRC is launched. This also fixes an issue with importing GTK if multiple versions are installed.

## Related Issue
Fixes the logger prefix in grc (#4628)

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
I haven't tested, but it looks like this would fix a `ValueError: Namespace Gtk is already loaded with version 4.0` seen when trying to run `grc` from a source directory, in addition to the logger name change.

**Review by willcode — APPROVED** [review]
Just for clarity, something other than `__name__[:-5]` would be good. Otherwise, LGTM.

**Review by mormj — APPROVED** [review]

**Comment by willcode** [comment]
@sdh11 did you want to implement `rindex` or something similar? `replace` would almost work, but someone could have a submodule that matches `.main`. Regex would be overkill, so `rindex` and a comment would be good enough.

**Comment by sdh11** [comment]
Yes, I will. I haven't had a chance to do that yet.

**Comment by sdh11** [comment]
@willcode: I've pushed the new commit with the fix

**Pull request merged**
