### PR TITLE
qtgui : add eye sink widget

### PR DESCRIPTION
**Pull request by ChristopheSeguinot**
Third attempt to get a clean PR.

### CODE REVIEW

**Comment by mbr0wn** [comment]
I'm really not sure a change of this magnitude should go into maint-3.8. I don't think there's anything wrong with the sink by itself, and thanks again for writing that!
But the purpose of maint-3.8 is for bugfixes, not new features, which this is.

**Comment by dkozel** [comment]
@ChristopheSeguinot Sorry this has been idle for so many months. I'm going to build and test this on 3.8 to give some feedback (if needed) on the feature. Then it'd be great to get this merged into the master branch and included in the 3.9 release.

**Comment by duggabe** [comment]
Why pick out this one new GUI widget when there about 15 others which are also new for 3.9? It doesn't seem appropriate for maint-3.8

**Comment by mormj** [comment]
This widget is already merged on 3.9 so I think the backport here can be safely closed

**Comment by nickoe** [comment]
Are there any plans on when 3.9 will be released?
I think a decision need to be made about this, but note that it seems as if the debian packager already do include this patch...

**Comment by mbr0wn** [comment]
Looks like we have this on maint-3.9, and there's good reasons (see above) not to merge it into maint-3.8. 3.9 is in RC1, so looks like it's OK to close.

**Pull request closed without merging**
