### PR TITLE
GRC: Fix color for input box in parameter widget with dtype raw

### PR DESCRIPTION
**Pull request by aru31**
Fix for issue #2374 
Changed the input color from `#FFFFFF` (white)  to `#A9A9A9` (dark grey)

### CODE REVIEW

**Comment by skoslowski** [comment]
I'd prefer a solution were we use the default color of the current theme for this.

**Comment by aru31** [comment]
@skoslowski color code now  changed to #23272A

**Comment by skoslowski** [comment]
I was actually proposing not to alter the background-color at all for this dtype. That way the default is kept which then works for both light and dark themes. The current color, white, was meant represent that - before themes were supported, that is

**Comment by aru31** [comment]
`

**Comment by aru31** [comment]
I am sorry for accidentally closing the pull request

**Comment by aru31** [comment]
@skoslowski just to be clear, you mean that the color should change according to the default theme, Right?

**Comment by nickoe** [comment]
I think some care must be taken to make sure there is a good contrast between the background color and the text color.

I guess in my dark theme the default text is light grey or white as seen on my screenshot. I would assume that gtk had a way to handle this a bit more nicely, but I am not familiar with framework.

**Comment by noc0lour** [comment]
I think what @skoslowski wants to outline: The color scheme should be fully defined by the theme and not be hardcoded at all.

**Comment by aru31** [comment]
@noc0lour: would this be feasible, I mean there are a lot of gtk-themes currently and it would really be a tedious job in order to explicitly define colour scheme for all of them.

**Comment by marcusmueller** [comment]
@aru31 the matter is not whether it's feasible – any change we do needs to be for the better. We won't just pick a random color that works better with your dark theme and not really bad with your light theme, if it breaks an equal amount of people's readability with other color schemes. That's not progress!

So, yeah, I've played around with this myself, as my dark colorscheme doesn't allow for easy readability. My intuition is that coloring the background to give type information was a sub-optimal UX decision to begin with – input boxes should have the recognizable default input box coloring. We could work with colored borders, or with a separate color button, or simply a textual / symbolic hint.

**Comment by nickoe** [comment]
I guess the coloring is ok, but it should be constrained to contrasting colors for the background and the foreground (text), and not let the foreground be chosen by the theme.

**Comment by aru31** [comment]
@marcusmueller thank you for the insight. but what I was trying to say has been clearly stated by @nickoe, that it would be a much better solution if the font text and the background colour are chosen by colour matching both of them and not let the colours be decided by theme.

**Comment by noc0lour** [comment]
I don't know how the Gtk theming engine works, but probably we can get information about the type of theme (dark, light).

**Comment by aru31** [comment]
@noc0lour, you are absolutely right that we can classify Gtk themes as light or dark, but there is no particular or to say official categorization for them, a lot of different software (like tweak tools) have their own themes and have categorized them as dark or light accordingly.
Taking your point in the account, what instead can be done is that we can make our own list of dark or light themes and change the background colour accordingly, and the list can be updated time to time. For all other themes that are initially not present in the list, the default background colour can be used.

**Pull request closed without merging**
