### PR TITLE
Pull in volk rotator fixes

### PR DESCRIPTION
**Pull request by argilo**
Fixes https://github.com/gnuradio/gnuradio/issues/2748.

https://github.com/gnuradio/volk/pull/278 was recently merged into volk to fix the broken AVX FMA rotator kernel. This PR pulls the fix into GNU Radio so the rotator block will work properly on recent Intel CPUs.

### CODE REVIEW

**Comment by michaelld** [comment]
@argilo I can't figure out which GIT commit this corresponds to ... can you confirm that it is https://github.com/gnuradio/volk/commit/f04a46f18308771b5ebf46292bf0fe6918578b35 ?

**Comment by michaelld** [comment]
Also: does this need to be applied to `maint-3.7` and `master` too?

**Comment by argilo** [comment]
@michaelld Yes, this updates volk to https://github.com/gnuradio/volk/commit/f04a46f18308771b5ebf46292bf0fe6918578b35. The full list of differences is here: https://github.com/gnuradio/volk/compare/1299d72c396a88fd2679adfd7a919ac00d2cf678...f04a46f18308771b5ebf46292bf0fe6918578b35

This change should also be applied to the `master` branch, but not `maint-3.7` as it uses a version of volk that predates the broken rotator kernel.

**Comment by michaelld** [comment]
@argilo OK thx & that makes sense to me.

**Comment by michaelld** [comment]
Tagging @marcusmueller for another review, just for confirmation.

**Comment by mbr0wn** [comment]
Merged manually (fixed commit message).

**Pull request closed without merging**
