### PR TITLE
dtv: Make SSE2 check clang compatible.

### PR DESCRIPTION
**Pull request by drmpeg**

### CODE REVIEW

**Comment by drmpeg** [comment]
It's a problem for ARM architecture. Read the referenced issue. https://github.com/gnuradio/gnuradio/issues/2262

**Comment by michaelld** [comment]
My preference would be to check for the flag first & if found then try the actual compile. My reasoning is that some Clang will pass the former but not the latter because the compiler has flaws in how it does pre-processing; this issue is mostly with older clang, but I like the general two-pronged approach.

This said, I'm not sure if this approach would solve whatever the actual issue is. Hopefully @drmpeg will comment more specifically.

**Comment by drmpeg** [comment]
Just to reiterate, the issue manifests itself on ARM architecture. If you pass the compiler flag -msse2 to clang on ARM, it doesn't give an error, it just gives a warning. SSE2_SUPPORTED gets set to true, and the build fails.

**Comment by michaelld** [comment]
!@#$ Clang ... just has some issues here and there with compiler flags. Hence trying both the flag and compile.

**Comment by mbr0wn** [comment]
Yeah I see your point (and I didn't realize this was specific to ARM). For me (and maybe also for @michaelld) there's just a hesitation here because `check_c_compiler_flag()` is what you're "supposed" to do, vs. check_compile which is considered hacky.

However, none of that matters if the former solution (aka the "clean solution") doesn't work. Non-working solutions are never better than working ones.
We should, however, add a comment in the CMake which explains why we're deviating from what is considered better CMake code. @michaelld, would that work for you?

Also, we should ask @balister if there's any issues with this solution.

**Comment by mbr0wn** [comment]
@balister approves from the coaching box.

**Comment by mbr0wn** [comment]
Merging manually.

**Comment by mbr0wn** [comment]
I squashed the commits and added some verbage. 83c0b7c0651a1959ac118c67154fce50541755df

**Pull request closed without merging**
