### PR TITLE
gr-pager: Added implementation of BCH(31,21) error correcting code that was missing in gr-pager

### PR DESCRIPTION
**Pull request by broglek**
The current implementation of the FLEX demodulator in gr-pager is missing the implementation of the BCH(31,21) error correcting code. When using gr-pager to demodulate FLEX messages, the lack of ECC results in the occasional garbled message.

This patch implements a baseline implementation of BCH(31,21) encoding.  Verified with FLEX transmitter that messages are being decoded correctly, and that any 32 bit block with 2 bit errors or less is successfully corrected.

Fixes https://github.com/gnuradio/gnuradio/issues/1512

### CODE REVIEW

**Comment by mbr0wn** [comment]
If you have already submitted a CLA, please apologize, we're still in the process of transitioning the tech ownership. If you have *not* submitted a CLA, I would suggest you get that going until this is reviewed -- this is quite a bit of code and needs some careful reviewing.

Thanks for the submission! At first glance, this looks pretty cool.

**Comment by marcusmueller** [comment]
Dear @broglek, are you still up for this?

**Comment by noc0lour** [comment]
@marcusmueller since `gr-pager` is gone now the PR does not apply anymore.

**Comment by mbr0wn** [comment]
@broglek We're very happy with the contribution and the code, but until the CLA situation is cleared we can't merge this (not because of technical, but because of legal reasons).

See also the issues that @marcusmueller pointed out. They're pretty minor.

It would be great to see you (or other authors) resubmit this PR against the latest master, but we need to make sure that:

- All commits are attributed to the correct author, either by virtue of the commit author being the code author, or by using Signed-Off-By (git commit -s).
- All authors have submitted a CLA to GNU Radio.

Thanks again for your work, and I hope we can this merged in the future. Even with this being gone from master, we can merge it into maint-3.7. Or maybe gr-pager gets adopted as an OOT.

**Pull request closed without merging**
