### PR TITLE
modtool: Added feature to prevent creation of multiple blocks with same name (Backport for maint-3.8)

### PR DESCRIPTION
**Pull request by alekhgupta1441**
Backport of PR #3340 for maint-3.8.

### CODE REVIEW

**Comment by swap-nil7** [comment]
To be honest, I am shocked how we forgot to add this check! Thanks a lot for bringing it out. Clean and nice work. :)
I just want to point out two things:
- Please use imperative style present tense in the commit message.
- Secondly, we'll need a similar check for the API version in the `core/add.py` file, so you can either add the feature in both the files or just move it to `core/add.py`. The issue with it being only in `core/add.py` (although I would prefer it) is that the user won't be notified as soon as the blockname is entered through the CLI. So, you can update the `core/add.py` file as well.

**Comment by alekhgupta1441** [comment]
@swap-nil7 Thanks for suggesting changes. I have pushed the changes.

**Comment by swap-nil7** [comment]
@alekhgupta1441 : Surely, the CLI will block on the call to `core/add.py` if we are invoking it using the CLI, but if someone invokes it directly using the API, the CLI check will be bypassed.

**Comment by swap-nil7** [comment]
We'll have to fix this in the `master` as well then.

**Comment by mormj** [comment]
Tested and works well - seems to be general improvement and feedback taken into account. Merging.  
I'll also make a forward port PR with these changes for master for consistency

**Review by mormj — APPROVED** [review]

**Pull request merged**
