### PR TITLE
gr-channels: Fixing the formula behind the IQ_imbal block

### PR DESCRIPTION
**Pull request by SaikWolf**
Fixing the formula behind the IQ_imbal block to be true mathematically.
X' = (1+mag_lin)·cos(theta)·real(X) + j·((1+mag_lin)·sin(theta)·real(X) + imag(X))
is the proper equation for handling the IQ imblance purely within the Inphase component.

Previously it was:
X' = (1+mag_lin)·real(X) + j·(sin(theta)·real(X) + imag(X))

### CODE REVIEW

**Comment by SaikWolf** [comment]
Double checking the formula.

**Comment by marcusmueller** [comment]
:) thanks! I just didn't get around doing that myself. If you have trouble, I hear `#gnuradio` on [Freenode](https://webchat.freenode.net/) or the [mailing list](https://lists.gnu.org/mailman/listinfo/discuss-gnuradio) is full of people to discuss with :)

**Comment by SaikWolf** [comment]
So the change I made makes it a transmitter IQ imbalance model. I'll edit it a little more and add a toggle for Transmitter/Receiver and make the adjustments needed for receiver IQ imbalance, and then reopen.

**Comment by SaikWolf** [comment]
Ok, the changes now reflect the origin of the IQ Imbalance while assuming a single component error.
Logic provided below for ease in analyzing.

Transmitter Effects:
X = Xi + j*Xq
X' @ w = Real{(Xi+j*Xq)*(mag_lin*cos(w*t + theta) + j*sin(w*t))}
X' @ w = (mag_lin*cos(theta)*Xi)*cos(w*t) - (mag_lin*sin(theta)*Xi + Xq)*sin(w*t)
X' @ w = Xi'*cos(w*t) - Xq'*sin(w*t)
X' @ baseband = Xi' + j*Xq'
Xi' = mag_lin*cos(theta)*Xi
Xq' = mag_lin*sin(theta)*Xi + Xq

Receiver Effects:
X = Xi*cos(w*t) - Xq*sin(w*t)
Xi' @ baseband = Filtered{ X*2*mag_lin*cos(w*t+theta) }
Xi' = mag_lin*(cos(theta)*Xi + sin(theta)*Xq)
Xq' @ baseband = Filtered{ X*-2*sin(w*t) }
Xq' = Xq
X' = Xi'+ j*Xq'
X' = mag_lin*(cos(theta)*Xi + sin(theta)*Xq) + j*Xq

**Comment by awalls-cx18** [comment]
Hi @SaikWolf and @marcusmueller,

I've taken a look at the receiver model and the math and implementation match.  The math is correct.  But it seems like there some arbitrary choices:
a. The incoming signal had a negative sign on the modulated quadrature component (i.e. -Xq sin(wt))
b. The receiver quadrature mixer mixes in -2sin(wt) vs. +2sin(wt)
c. The gain imbalance is manifested (wholly) after the mixing and filtering vs. before.

The above choices make the math nice in that everything comes out with a positive sign and you only need one multiply block to handle the gain imbalance.

I guess a. and b. are OK, as long as one understands the transmitter modulator is behaving in a complementary manner so that -Xq sin(wt) is the quadrature component going over the air.
However, an uninformed user who didn't read the block code or work through the math might not understand that about the model.

Regarding c., in my limited experience, I've usually seen gain imbalance modeled before the mixing.  I haven't seen it modeled afterward.  It's still valid, just not what I assumed was going on before reading through the math.

This block could really use a block diagram in the comments and/or documentation to document the receiver model pictorially. (This could likely be said for many blocks in gr-channel.)  Something as simple what's in figure 3.4 here  [http://www.eit.lth.se/sprapport.php?uid=764] would be nice.

I'll check the transmitter model next.  I'm guessing @SaikWolf's math will be correct, the model won't match my going in assumptions, and I'll suggest a block diagram would be nice. :)

-Andy

**Comment by noc0lour** [comment]
@SaikWolf probably GRC is not the best choice for creating ASCII arts if you don't use a monospace font. Using my editor (which uses monospace font) I can't see the ASCII art.

**Comment by awalls-cx18** [comment]
If the block diagram doesn't work out, I'm good with a reference.

@SaikWolf is your reference the Springer Brief by Li and Yabo?

**Comment by noc0lour** [comment]
I didn't test with GRC here, just looking at the xml in my editor. GRC might work out for everyone (but I doubt that due to font rendering issues).

**Comment by SaikWolf** [comment]
@noc0lour I've added the monospace version of the block diagram to the Python script. Should hopefully work for all now.

@awalls-cx18 Yes, the Springer brief is what was used. Although that focuses on the balanced approach rather than the single branch approach. I simply adapted what was needed following their explanation.

**Comment by noc0lour** [comment]
@SaikWolf Thanks a lot for fixing the documentation w.r.t to ASCII art :+1:

**Comment by marcusmueller** [comment]
So, albeit it's taken me far too long to follow up on this: 

@SaikWolf, this is grade-A exquisite nice work! Thank you and: Keep that up :) 

@awalls-cx18 Thank you so much for doing the in-depth math analysis. I simply wouldn't be able to put as much math rigor into this, and I'm really thankful for having you on board :)
 
@noc0lour thanks for handling the tagging, and the doc feedback; always great to have you help the project, too!

**Pull request merged**
