### PR TITLE
Fix documentation typo in frequency_modulator_fc

### PR DESCRIPTION
**Pull request by rajb245**
Pretty self explanatory, the descriptor of the variable is "sensivity".

### CODE REVIEW

**Comment by jmcorgan** [comment]
Hey, thanks for your contribution. However, as a bug fix, can you rebase this patch off the maint branch, push to your repo, then edit this PR for merge into maint?

**Comment by rajb245** [comment]
You're welcome! No, I don't plan on submitting this against maint. It's a few characters, so I hope this typo is fixed by the maintainers outside of this pull request.

**Comment by jmcorgan** [comment]
This was cherry-picked on to the maint branch.

**Comment by rajb245** [comment]
@jmcorgan Apologies for making you do the hard work of rebasing and applying to maint, but it just wasn't that important to me to be credited for a typo fix. That said, I appreciate that you applied the patch in a way that maintains the authorship (if you can call fixing a typo that). I'll make sure to base off maint in the future if what I have is a bug fix.

**Pull request closed without merging**
