### PR TITLE
Qtgui matplotlib dependency

### PR DESCRIPTION
**Pull request by sidkapoor97**
Typo in azeplot references #3281

### CODE REVIEW

**Comment by marcusmueller** [comment]
This needs to be rebased against master manually. Can you do that? There should be _no_ "merge master into" commit.

A squashing of commits into one also seems sensible, since this seems to boil down to a single changed line of code.

Considering all this boils down to a single line of changed code, I think there might be some mistake that happened here. I'm sorry, I'm not quite sure how to proceed here.

**Comment by drmpeg** [comment]
@sidkapoor97 In the future, the correct procedure would be to not reuse a branch that's already been merged. Instead, follow these steps.

1) Go back to the master branch.
 git checkout master

2) Update the master branch.
git fetch upstream
get merge upstream/master

3) Create a new branch.
git checkout -b new-branch-name

4) Make changes, commit, push, etc.

**Comment by marcusmueller** [comment]
@sidkapoor97 yes, I think @drmpeg  is right: it's probably easiest if you make a new branch, `git cherry-pick` the commits you want onto that branch, and then simply open a new pull request :)

Thanks!

**Comment by sidkapoor97** [comment]
Sure I'm sorry @marcusmueller , I'm fairly new to contributing , really sorry for the mistake and thanks @drmpeg for clarification, will definitely keep that in mind.

**Comment by sidkapoor97** [comment]
@drmpeg I have created a new branch in a new PR #3343 I hope that makes thing clear, I am sorry for the mistake

**Pull request closed without merging**
