### PR TITLE
gr-qtgui: Switch to Qt5

### PR DESCRIPTION
**Pull request by pcercuei**
This pull request switches the gr-qtgui blocks to use Qt5 instead of Qt4.

### CODE REVIEW

**Comment by pcercuei** [comment]
A small note: The Qt5 version of the 'uic' compiler generates incorrect code right now, so the build of gr-qtgui will not succeed until Qt5 is fixed upstream.
The bug has been reported (https://bugreports.qt.io/browse/QTBUG-48492) and is pending review.

A workaround I used is to add a file ```/usr/local/include/QtWidgets/QRegExpValidator``` that contains the following: ```#include <QtGui/QRegExpValidator>```

**Comment by trondeau** [comment]
@pcercuei, this is awesome, thanks! Unfortunately, we can't take this onto the master branch as-is. On master -- for the 3.7 series of GNU Radio -- we have to maintain API consistency and dependency versions of things.

There are two possible ways to go here. First, we could just put this onto the next branch instead of master. That would mean it would be part of the 3.8.0 release (release date yet to be determined). Or we could try to do something on master where we do a lot more checks and fallbacks. Basically, look to see if the versions of cmake, QT, QWT, PyQT, etc. all meet the requirements for this. If so, use QT5. If not, fall back and check QT4 support and use that if things meet there. Otherwise, disable gr-qtgui like we already do in that case.

From one perspective, I'd love to see this in there sooner than later. But that'll be a lot of duplication of code for the different versions, and so a lot more testing required if we change anything on either side. There also possible issues of some of the dependencies for QT5 being met but not all, and different systems have different install paths with QT, etc, etc. The route to just do this on next is a lot safer and less prone to these kinds of issues and errors. But it will slow down the introduction of this capability.

**Comment by pcercuei** [comment]
Well I think it would make sense to have it on next then.

**Comment by jmcorgan** [comment]
Agree on this being next/3.8.  The release time frame for that has not been set, but I could see it sometime in the early spring.

Please rebase this off the next branch, thanks!

**Pull request closed without merging**
